### ISSUE TITLE
Style sheet external editor not available causes Ipe to get stuck

### ISSUE THREAD

**Issue by ocastany** [otfried/ipe#10]
When I do: Edit > Style sheets > Edit, a window opens and displays "Waiting for external editor".
This puts Ipe to hang. The only way to get out of the situation is to kill Ipe.
It seems that Ipe doesn't find my editor. How is it requesting the editor? Where is it documented?

Expected behavior: if an editor is not available, it should be possible to go back to the software without having to kill Ipe.

Olivier, with Ipe 7.1.4 on Debian Linux

**Comment by otfried** [comment]
How did you set prefs.external_editor?   The default is "nil", and you would get an error message, but it could pick up the environment variable "EDITOR".

What does Ipe -> Help -> Show Configuration -> External editor say?

**Comment by ocastany** [comment]
Note: my $EDITOR is "/usr/bin/vim"

**Comment by ocastany** [comment]
"Ipe > Help > Show Configuration" does not show an external editor.

**Comment by otfried** [comment]
I cannot reproduce the problem, and you are running a very old version of Ipe (from March 2013) - I guess the problem was somehow fixed since then.

**Comment by ocastany** [comment]
It's the most recent version on Debian testing. When it will be upgraded on Debian, I will test again.

**Comment by revher** [comment]
I have had the same problem on OSX. I opened a second Ipe and found that the external editor was "open -W -n -e %s"; therefore I opened  a Terminal
`$ ps uaxw | grep open `
and found
`  30381   0,0  0,1 34251664  10612   ??  S     3:43     0:00.07 open -W -n -e /tmp/lua_KOIxXr`
and then killed the process 
`$ kill -KILL 30381`
and I have been able to get the original ipe and I saved my work.

**Comment by ocastany** [comment]
I tested again with Ipe 7.2.28 from the command line in a terminal (Linux):
- If I run "ipe", then it will open my $EDITOR in the terminal and wait until the editor closes ==> OK.
- If I run "ipe &", then it will launch a shell session hosting my $EDITOR, but this shell is not connected to anything and it is thus invisible and unreachable ==> problem.

I was wondering : under linux, is there an environment variable pointing to a default _GUI_ editor ?

Anyway, what I did for avoiding Ipe freezing was : 
- Create a file: ".ipe/ipelets/customization.lua"
- with the line: prefs.external_editor = "/usr/bin/gvim %s"
