### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by A6669** [otfried/ipe#100]
Hello,I am a user of ipe, I hope ipe can have some feature in future.
first, export pdf, now ipe does not have this option, so when I save ipe as pdf, I have to use save as..
second, import ipe file, some ipe picture I use very frequently, when I use it again I hope I can import it directly rather than draw it again.
thank you.

**Comment by otfried** [comment]
1.  Export and "save as" are two different operations.  Export does not save any Ipe markup, an exported file cannot be read again by Ipe.   Is that what you would like to have added to the menu? "Export to PDF"?
2. You can just copy and paste.  Open the figure you want to reuse, copy it, then go to your new figure and paste.

**Comment by A6669** [comment]
thank you for your reply, I am no sure whether it is possible that latex refer ipe file directly, it is using command   \includegraphicx[scale=1.7]{birds.ipe}, I think it is more convenient.

**Comment by otfried** [comment]
This already works in Ipe 7.2.6, if you include the PDF file birds.pdf
