### ISSUE TITLE
textstretch not available from lua

### ISSUE THREAD

**Issue by QBobWatson** [otfried/ipe#101]
From what I can tell, the only object property not available to ipelets is "textstretch".  I wrote a [TikZ exporter ipelet](https://github.com/QBobWatson/ipe2tikz) which is unable to scale the exported text correctly because of this.

**Comment by otfried** [comment]
You should be able to access the textstretch definitions in the style sheet using sheet:allNames("textstretch") and sheet:find("textstretch").

What exactly doesn't work for you?

**Comment by QBobWatson** [comment]
Yes, and that's what the exporter does, when exporting the stylesheet.  But obj:get("textstretch") throws an error, so the value used for individual objects is unavailable.

**Comment by otfried** [comment]
This is a misunderstanding:  Objects have **no** "textstretch" property.   

What happens is the following:  Text objects have a "textsize" property.  This could either be absolute (in which case a \fontsize{}{}\selectfont command is used with the given size), or symbolic.

If it is symbolic, Ipe uses the symbolic name as a key for **both** "textsize" and "textstretch".  The value of "textsize" is a Latex command to set the font size.   The value of "textstretch" (if it is defined) is used to scale the text object **after** typesetting.

This mechanism is used in presentations, where you want the natural appearance of the smaller font sizes, for instance in math subscripts, but they need to be much bigger to be readable on a big screen.

**Comment by QBobWatson** [comment]
I see, thank you.  I've updated the exporter to behave like that.  At least I think so -- if the text size is numeric, does Ipe use a textstretch of 1 or of "normal"?  I'm assuming the latter.

**Comment by otfried** [comment]
If the text size is numeric, no stretch is applied - the fontsize is applied as is.

**Comment by QBobWatson** [comment]
Ok, I've fixed it again, thanks.
