### ISSUE TITLE
Auto Export to eps?

### ISSUE THREAD

**Issue by bstrdb** [otfried/ipe#103]
Hey otfried,
I just updated from ipe 7.1.7 to 7.2.6
I noticed, that the auto-export settings were changed.
In addition to:
`prefs.auto_export_to_pdf = true`
I tried 
`prefs.auto_export_to_eps = true`
but it doesnt work. Is there an option to to have auto-export to eps like in 7.1.7?
Best regards
Daniel

**Comment by otfried** [comment]
Auto-export to eps is no longer supported, because not everything can be exported to EPS.

**Comment by bstrdb** [comment]
Thanks for the quick reply! Closed.
