### ISSUE TITLE
"Move graph nodes" with custom symbols sometimes fails

### ISSUE THREAD

**Issue by moritzbeck** [otfried/ipe#107]
Using Ipe 7.2.6 (Windows 7) when I move a node (custom symbol) multiple times sometimes it fails.
Then it will fail each time when I try to move the graph node.
Here failing means: The node is moved but not the incident lines.

It should always move the node along with the incident lines.

Workarounds I've found (so it works again _temporary_):
- Deleting the incident lines and creating new ones.
  This is annoying and (partly) defeats the point of the "move graph nodes" feature.
- Undoing the last graph node move on that node.
  This might be infeasible (because undo history is gone or too many actions in between).

**Comment by otfried** [comment]
This happens when the edges have a non-trivial transformation matrix.  I've already fixed it for 7.2.7.

**Comment by otfried** [comment]
Here is the (very simple) patch for `tools.lua`:

[tools.lua-patch.txt](https://github.com/otfried/ipe-issues/files/551705/tools.lua-patch.txt)
