### ISSUE TITLE
add shadow plugin

### ISSUE THREAD

**Issue by gasagna** [otfried/ipe#108]
Hi, 

I love IPE and have used it to make my presentations for years now. 

This issue is not really a bug, but rather a feature request. It would be a super killer feature to be able to add shadows to objects, and being able to adjust position, blur, ... This would make presentation much nicer. At the moment, I insert custom pngs figure with shadows, but this is rather limited.

Thanks!

**Comment by pierreganty** [comment]
I have not tested but since 7.2.6 creating shadows using tikz should work flawlessly.
http://tex.stackexchange.com/questions/11272/faded-drop-shadow-using-tikz-based-rounded-rectangle

**Comment by otfried** [comment]
Using tikz to add shadows will only work for tikz objects (e.g. tikz nodes containing some text) - and that does indeed work in Ipe now.

It seems the original suggestion was to allow shadows on arbitrary Ipe objects.  I'm not so sure what they need to look like in this case.   It would be quite easy to make an Ipelet that adds a copy of a polygon with some offset and gives it a gray color, but once you want blur it's much less clear what it should look like, or how to achieve this using Ipe objects (or PDF in general).   The pgf-blur solution seems to be a hack that redraws the shape many times with increasing transparency.

If you only need shadows on rectangles, by the way, you can also achieve this now with decorations.  Add the `decorations.isy` style sheet to your document, select the object, group it (even if it's just one object), and then right-click on the group object.  Now try changing the decoration of the object, e.g. to `rounded-box-large`.

Currently there is no `shadow` decoration, but it should be easy to define one.
