### ISSUE TITLE
Ipe 7.1.10 wont install on 10.6.8.

### ISSUE THREAD

**Issue by jlsvds** [otfried/ipe#109]
Hi,

I want to install ipe on Mac OS 10.6.8 but when i install Ipe with Macports or by the installer on the web it doesn't work. In the main log error i see Ipe doesn't install 7.0.14 but 7.2.2. Even when i give this command:

sudo port install ipe @7.0.14 

Macports still tried to install 7.2.2

Is there anyone to give some help?

Thanks,
Jasper

**Comment by otfried** [comment]
Why don't you simply use the binary package for 7.1.10 at

https://dl.bintray.com/otfried/generic/ipe/7.1/ipe-7.1.10-mac.dmg?

I don't know much about macports - if you insist on installing  through macports, you better ask through their channels.

**Comment by jlsvds** [comment]
I want but the binary package doesn't work... When i double click on the icon the program won't start up...

**Comment by otfried** [comment]
I'll need to have another look at this.

What you can also try is installing 7.2.2 but with the Qt UI - this should work in OSX 10.6, I believe. 
You should select the `qt4` variant in the `port install` command - I don't know what the exact syntax is.

**Comment by otfried** [comment]
It seems to be `port install ipe +qt4`

**Comment by jlsvds** [comment]
I can't install qt4. I've got this error:

Error: Insufficient privileges to write to MacPorts install prefix.

**Comment by jlsvds** [comment]
And when I want to install ipe i've got this error:

sudo port install ipe @7.0.14
--->  Computing dependencies for ipe
--->  Building ipe
Error: org.macports.build for port ipe returned: command execution failed
Please see the log file for port ipe for details:
    /opt/local/var/macports/logs/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_graphics_ipe/ipe/main.log
To report a bug, follow the instructions in the guide:
    http://guide.macports.org/#project.tickets
Error: Processing of port ipe failed

When I start reading the main log I see that Macports is installing ipe 7.2.2 instead of ipe 7.0.14

**Comment by otfried** [comment]
As I said, I know nothing about the macports version of Ipe.

Apparently you need to go to http://guide.macports.org/#project.tickets as the error messages says to report the problem.

**Comment by m7thon** [comment]
The current and only version of ipe on MacPorts is 7.2.2 (yes, this should be updated, and it is currently preferred to just use the provided binary of ipe).

Do:

```
sudo port uninstall ipe
sudo port clean --all ipe
sudo port selfupdate
sudo port install ipe
```

This should clean any remnants of a previous MacPorts ipe install and install the latest MacPorts version. If you installed ipe manually at some point (e.g., into `/usr/local`, as used to be the default), you need to clean this up manually as well.

If you also want to update your other ports, do

```
sudo port upgrade outdated
```

after the `selfupdate`

Hope this helps. I am not sure, however, if a recent version of ipe can run on OSX 10.6.8 at all (that's ancient). You can also try to install the qt variant as Otfried suggested: `sudo port install ipe +qt4` (you obviously need sudo).

**Comment by otfried** [comment]
The cocoa version of Ipe requires at least OSX 10.9. (In theory 10.8 should be okay, but i was told it's unbearably slow there.)

10.6 simple doesn't have the needed APIs, so you must build the qt version.

**Comment by otfried** [comment]
I checked the binary of Ipe 7.1.10 again:

https://dl.bintray.com/otfried/generic/ipe/7.1/ipe-7.1.10-mac.dmg

It works fine for me.  Did you install it by moving the Ipe icon to another directory - say your desktop?

If it doesn't start by clicking on the installed Ipe.app, try running it from the command line, with debugging enabled:

```
$ export IPEDEBUG=1
$ ~/Desktop/Ipe.app/Contents/MacOS/ipe
```

(assuming you dragged the application to the desktop)

**Comment by jlsvds** [comment]
Hoi Otfried,

Sorry for the late replay.

Now I use Ipe 7.0.14. I had a TimeCapsule backup and i overwrite all the files in the local/opt folder. Now it works again. So now I don't dare to update Ipe or to install the Ipe app from the internet.

I guess there are not significant updates since 7.0.14.

Regards,
Jasper

Op 17 nov 2016 , om 15:18 heeft Otfried Cheong het volgende geschreven:
