### ISSUE TITLE
Feature request: optional snap to objects that don't appear in this view 

### ISSUE THREAD

**Issue by joehrlein** [otfried/ipe#112]
A feature working like "disable snapping for a layer" but the other way round would be nice. Snapping to inactive layers would allow to generate auxiliary layers.

Thank you!

**Comment by joehrlein** [comment]
The way I use ipe, it would also be reasonable to combine this feature with an "always on top"-option. 
This could result in a layer class "auxiliary" with the following properties:
- it is always possible to snap to its objects no matter whether they are visible
- its objects are "always on top", i.e. above all objects of regular/non-auxiliary layers
- the layer is only visible in ipe no matter whether its active or inactive (maybe)
- the layer is availabe on every page (maybe; if this is possible; and maybe optional...)

**Comment by otfried** [comment]
In 7.2.15 layers can enable snapping even when they are invisible.
