### ISSUE TITLE
gridsize fractional value crashes Ipe 7.2.6

### ISSUE THREAD

**Issue by ghali** [otfried/ipe#115]
Evidently using fractions for a gridsize value is not supported. Still, a guard may be warranted.

    <?xml version="1.0"?>
    <!DOCTYPE ipestyle SYSTEM "ipe.dtd">
    <ipestyle name="inch-friendly-gridsizes">
        <gridsize name="4.5 pts (1/16 inch)" value="4.5"/>
        <gridsize name="9 pts (1/8 inch)" value="9"/>
        <gridsize name="18 pts (1/4 inch)" value="18"/>
        <gridsize name="36 pts (1/2 inch)" value="36"/>
        <gridsize name="72 pts (1 inch)" value="72"/>
    </ipestyle>

Selecting 4.5 from the ones above crashes Ipe 7.2.6.

**Comment by otfried** [comment]
Fixed in 7.2.7
