### ISSUE TITLE
Packages transparent and tcolorbox used together cause Ipe to be very slow

### ISSUE THREAD

**Issue by Growling-Bear** [otfried/ipe#117]
When including an image with the following code, transparency does not apply.
I checked that the same code applied it properly in a standard Latex document (TexMaker).
(System : Windows 64 + Miktex)

Preamble : 
```
\usepackage[pdftex]{graphicx} 
\DeclareGraphicsExtensions{.pdf,.jpg,.png}
\usepackage{transparent} 
```

Text : 
`{\transparent{0.5} \includegraphics[width=8pt]{"my_image"}}`

**Comment by otfried** [comment]
It seems to work correctly in the PDF output.  It's only on the screen that the transparency is not displayed.  Do you see the same effect?

**Comment by otfried** [comment]
Actually, now it works for me on the screen as well.  It seems that the `transparent` package needs **two** Latex runs.

**Comment by Growling-Bear** [comment]
Indeed I tried it in an empty file and it worked (in the pdf, not inside IPE).

I found that the problem comes from the rest of my Preamble. When I put these lines (from your facebook post I think), it makes IPE malfunction (become very slow and not show transparent objects) when I add an image with transparency.

So it's no longer a problem for me but people may want to use both tcolorbox as well as transparency.
```
\usepackage{tcolorbox}
\tcbuselibrary{skins}
\newtcolorbox{block}[1]{enhanced,width=\textwidth,colbacktitle=blue!25!black,colback={blue!50},title={#1},drop fuzzy shadow,opacityfill=.5,colupper=white}

```

**Comment by otfried** [comment]
I noticed when investigating a different problem (#150) that the packages `tcolorbox` and `transparent`, when used together in the same Latex document, cause illegal PDF to be created.   

So I'm not sure I want to put much effort into this.

Can't you simply set transparency on the text object containing the \includegraphics part?
