### ISSUE TITLE
cannot change object colours in mac os - ice 7.2.7

### ISSUE THREAD

**Issue by gasagna** [otfried/ipe#119]
it seems that with the latest update (from homebrew) i cannot change objects color with the default mac os color picker. It seems that the "OK" and "Cancel" buttons have disappeared, so one cannot actually set the chosen color. See below screenshot.

<img width="1105" alt="screen shot 2017-01-06 at 11 12 41" src="https://cloud.githubusercontent.com/assets/744738/21716260/5e6733bc-d401-11e6-9439-9ee9c43e32bd.png">

My version is 

<img width="385" alt="screen shot 2017-01-06 at 11 12 18" src="https://cloud.githubusercontent.com/assets/744738/21716279/84f84f5c-d401-11e6-97b6-20907adeffc5.png">

Thanks

**Comment by otfried** [comment]
See #38.

**Comment by gasagna** [comment]
Sorry for the noise. surprisingly a search did not produce anything!

Thanks.
