### ISSUE TITLE
Panning during creation of objects

### ISSUE THREAD

**Issue by pglira** [otfried/ipe#12]
Panning (with the middle mouse button) is currently not possible during the creation of objects (e.g. lines, circle, ...), as a click with the middle mouse button creates the object and don't moves the canvas. This problem arises for example if the end of a line is outside the actual visible area. Sometimes it can be helpful to zoom out and in again with the mouse wheel, but this is not really practical.

**Comment by otfried** [comment]
Ipe users currently pan during the drawing or editing of objects using the "x" key.   It allows you to move to the region of interest and zoom in there.

I'm not sure if it's a good idea to allow the mouse for panning, as it might be confusing having too many different actions available with the mouse.

**Comment by pglira** [comment]
Ok, great news. I didn't know that... Works really fine!
