### ISSUE TITLE
PDF parser cannot read documents where /length is a reference

### ISSUE THREAD

**Issue by gasagna** [otfried/ipe#120]
Hi, 

It seems there is an issue in importing with `\includegraphics` *some* pdf plots generated with matplotib, i.e. those generated by the commands `matshow` and `imshow`. The minimal working example is attached here (you might need to change the absolute path to the pdf file in the ipe text element).

The latex compilation reports
<img width="424" alt="screen shot 2017-01-08 at 07 47 36" src="https://cloud.githubusercontent.com/assets/744738/21751136/c50f5c7c-d576-11e6-825f-f8ef612262eb.png">

and the interesting lines in the `latexrun` log are

````
(grfext)             [.png,.pdf,.jpg,.mps,.jpeg,.jbig2,.jb2,.PNG,.PDF,.JPG,.JPE
G,.JBIG2,.JB2,.eps]
(grfext)             \AppendGraphicsExtensions on input line 456.

(/usr/local/texlive/2016/texmf-dist/tex/latex/latexconfig/epstopdf-sys.cfg
File: epstopdf-sys.cfg 2010/07/13 v1.3 Configuration of (r)epstopdf for TeX Liv
e
))
</Users/davide/example.pdf, id=1, 433.62pt x 433.62pt>
File: /Users/davide/example.pdf Graphic file (type pdf)

<use /Users/davide/example.pdf>
Package pdftex.def Info: /Users/davide/example.pdf used on input line 51.
(pdftex.def)             Requested size: 433.61894pt x 433.61894pt.

Overfull \hbox (170.0pt too wide) in paragraph at lines 55--56
[][] 
 []

[1

 </Users/davide/example.pdf{/usr/local/texlive/2016/texmf-var/fonts/map/pdftex/
updmap/pdftex.map}>] (./ipetemp.aux) ) 
Here is how much of TeX's memory you used
````

Thanks!

[Archive.zip](https://github.com/otfried/ipe-issues/files/692216/Archive.zip)

**Comment by otfried** [comment]
Have you considered using the Ipe matplotlib backend?

https://github.com/otfried/ipe-tools/tree/master/matplotlib

(Has nothing to do with this bug, though.)

**Comment by gasagna** [comment]
No, have not tried. I guess the problem lies on the matplotlib side rather then here. I know there have been some updates in the imshow/matshow code with the new matplotlib version. I will try again.

**Comment by otfried** [comment]
Finally improved the PDF parser to handle this case in 7.2.15.
