### ISSUE TITLE
Pen width is lost when reopening

### ISSUE THREAD

**Issue by ordend** [otfried/ipe#121]
Dear Otfried.
When using a style to specify pen width and opacity, it seems that reopening the file keeps the prescribed opacity, but loses the pen width. 
It shows this
![image](https://cloud.githubusercontent.com/assets/25029345/21802582/a248b808-d726-11e6-8855-c9ed0f74a2eb.png)
instead of this
![image](https://cloud.githubusercontent.com/assets/25029345/21802602/b2e73856-d726-11e6-9ec5-1f4577b264ba.png)

Here is a minimal example, run in Windows with Ipe 7.2.7 (and also some previous versions). It seems that there is some problem with .zip files, so the .ipe and .sty are uploaded as .txt instead.

[Ipe pen width test.txt](https://github.com/otfried/ipe-issues/files/695775/Ipe.pen.width.test.txt)
[opacitypercentage.txt](https://github.com/otfried/ipe-issues/files/695778/opacitypercentage.txt)
[penwidth.txt](https://github.com/otfried/ipe-issues/files/695777/penwidth.txt)

I have not found references to this issue before, please forgive me if it has been already mentioned.

Many thanks for this useful program,

David.

**Comment by otfried** [comment]
You used "27" as the *symbolic* name of a pen width.   But when reading the file, "27" is interpreted as an absolute value.

Symbolic attribute names must start with a letter (or at least not a digit).
