### ISSUE TITLE
ipe crashes when I try to include text

### ISSUE THREAD

**Issue by goytadam** [otfried/ipe#123]
When I open up either the Text Labels window or the Mathematical Symbols Window, type text and press enter, ipe crashes.

**Comment by otfried** [comment]
What Ipe version?  Which operating system?   Does it work if you turn off "Automatically run Latex" in the File menu?

**Comment by goytadam** [comment]
I’m running Ipe 7.2.7 on Windows 7.  It still crashes if I turn off “Automatically run Latex” in the File menu.

Thanks.

**Comment by ydelomier** [comment]
Hi there,

I have the same problem here. I am running Ipe 7.2.7 on Windows 7. When I try to add a Text Label, Ipe crashes then an error appears indicating: "! LaTeX Error: File `xcolor.sty' not found."

I am missing something?

![error_ipe](https://cloud.githubusercontent.com/assets/26903942/24665674/67c242d8-195e-11e7-8afc-d413456e4941.PNG)

**Comment by otfried** [comment]
Well, Ipe shows you an error message, telling you exactly what went wrong - so it certainly did not crash.

As the error message says, your Latex installation is missing the file "xcolor.sty" - so install that and this problem will disappear.

**Comment by otfried** [comment]
As for the original bug, there is too little information to do anything about it.  I would at least need a crash log.

So if you start Ipe, select label mode by pressing "L", then click somewhere on the canvas - the Label dialog appears.  You type "abc" and press the "Ok" button (pressing Enter does not close the dialog) - and then Ipe crashes?   Do you have any customization of Ipe in a .lua file?
