### ISSUE TITLE
Mark and unmark pages/views from the sorter

### ISSUE THREAD

**Issue by pierreganty** [otfried/ipe#128]
1. For the sake of uniformity, it would be great to have a 'view sorter' in addition to the page sorter.

2. It would be also great to be able to mark / unmark views or pages from the sorter with a pinned icon on the thumbnail or something similar.

**Comment by pierreganty** [comment]
Recently, I did a 20 minutes presentation out of a 50 minutes one by marking pages and views and then relying on `ipetoipe --markedview ...`. First I was surprised to discover that marking a page would not automatically mark all the views inside of it. Second I did a lot of clicking to mark all the views inside all the marked pages. May I suggest in the top menu for `views` to have like with layers a `mark view onwards` and `unmark view onwards`.

**Comment by otfried** [comment]
The "mark" property was really created to make it possible to print or publish handouts.    Typically, you want the last view of a page, where all the incremental updates have been made.  That's why marking a page works as it does.

When I make a shorter version of a talk, I just make a copy of the presentation, and delete the pages and views I don't want.

I see that it might be possible use the mark feature to actually *maintain* a shorter version of a talk inside a larger one, so I can add the functions you ask for - but perhaps there's a better way to implement this functionality?

**Comment by pierreganty** [comment]
The reason I try to avoid copy the document and delete pages is that inevitably I will find some things to improve here and there. These improvements won't make it back to the long presentation unless I port the changes myself (e.g. by cut&paste the improved slides). 

While I do follow your explanations the behavior that is implemented assumes some context related to printing handouts. As you wrote "Typically you want the last view of a page, where all the incremental updates have been made". Neither the GUI nor `ipetoipe` does inform you about that context and, if you don't have it in mind, you are up for some "surprise" when you mark a page.

Whatever you decide I think it would be great that the --help output of running `ipetoipe` adds some context as you did in the manual.

<img width="1111" alt="image" src="https://user-images.githubusercontent.com/2111160/79633305-dcd6d180-8164-11ea-9b93-a2050af5e743.png">

Right now it only says:
<img width="843" alt="image" src="https://user-images.githubusercontent.com/2111160/79633398-8b7b1200-8165-11ea-8ca5-5443d7d160ff.png">

Finally, while researching I went back to the wiki about [Presentations](https://github.com/otfried/ipe-wiki/wiki/Presentations#printing-notes) where you mention that ipetoipe has some lastview option
<img width="753" alt="image" src="https://user-images.githubusercontent.com/2111160/79633359-422ac280-8165-11ea-9e15-32e7a686dc75.png">

This option is either absent or hidden from `ipetoipe --help` output.

**Comment by otfried** [comment]
The Wiki contents is written by Ipe users and contents can get outdated:  the `-last-view` option no longer exists (it was replaced by `-markedview`).  (Also the `ipe-weed` script there should be modified to run through ipescript, as the Lua ipe module is not installed on most user's systems...)

**Comment by otfried** [comment]
I've added "mark view onwards" and "unmark view onwards" and more help output in `ipetoipe` in 7.2.14.

View sorter is still on to-do list...

**Comment by otfried** [comment]
There will be a view sorter in 7.2.14, but not yet a possibility to mark/unmark pages/views from the sorter (the bitmaps are computed only once at the beginning, I'll have to see how I can easily mark items).

**Comment by otfried** [comment]
Marking and unmarking available from the sorter in 7.2.15.
