### ISSUE TITLE
iperender - svg option

### ISSUE THREAD

**Issue by PedroARamos** [otfried/ipe#130]
I was trying to convert ipe to svg but although the option is mentioned in the manual it seems it has disapeared from the options of the program iperender (at least, in version 7.2.7, windows). 

Is that a temporal problem?

Thanks!

**Comment by otfried** [comment]
Yes, apparently I did not compile in SVG support in the cairo library that comes with the Windows binaries.  It'll be fixed when I have time to recompile this.

**Comment by Caster** [comment]
Are there any updates on this? Is there support for this option in previous Ipe binaries for Windows? Thanks in advance.

*edit:* I found that the option exists in Ipe [7.1.9](https://dl.bintray.com/otfried/generic/ipe/7.1/:ipe-7.1.9-win.zip).

**Comment by otfried** [comment]
7.2.8 will again have the -svg option on Windows.
