### ISSUE TITLE
Feature request: Paste with layers

### ISSUE THREAD

**Issue by unruhschuh** [otfried/ipe#131]
If I select multiple objects which are on different layers, copy and paste them, the pasted objects are all in the current layer. It would be nice to have the option to retain the layers while pasting.

This would raise the question of what to do if I paste to another document / page. There you could simply add the layers if layers of the same names do not exist.

**Comment by mrzv** [comment]
If there was a way to vote for features, I'd vote for this one with both arms. Having the ability to preserve layers when pasting would be amazing.

**Comment by otfried** [comment]
Implemented in 7.2.15.
