### ISSUE TITLE
Portable Version

### ISSUE THREAD

**Issue by RoyiAvital** [otfried/ipe#133]
Hello,

Could you offer a Portable Version?
A collaboration with [PortableApps](https://portableapps.com) will be perfect.

It will increase exposure significantly to this great project.

Thank You.

**Comment by otfried** [comment]
Ipe is already completely portable - you can unzip the zip file anywhere you want.

The harder part is to make sure you have a portable TeX installation.  Here are some instructions:

http://ipe.otfried.org/manual/manual_41.html

**Comment by RoyiAvital** [comment]
Hi,

This is the nice thing about PortableApps.
There is a complete eco system and hence there is already Portable TeX.
It will also take care of updates, etc...

I think if you contact them (The site owner) they will do it if you wish.

It will increase exposure for IPE.

**Comment by 2wayne** [comment]
@otfried It's almost completely portable just one thing isn't. The autosave directory can't be adjusted so it'll always save in the user documents directory. If you could add an env variable to adjust it would be nice.
You can download a Development Test here: https://portableapps.com/node/56085

**Comment by otfried** [comment]
Actually, the autosave filename is determined by the preference `prefs.autosave_filename`. 

You can change it by modifying `prefs.lua`, or by adding an additional file (e.g. `portableapps.lua`) in any Ipelet directory.

**Comment by otfried** [comment]
See http://ipe.otfried.org/manual/manual_39.html for the standard way(s) of changing preference settings.

**Comment by RoyiAvital** [comment]
It seems someone has done it:

https://portableapps.com/node/56085

I really think if it will be official on PortableApps the exposure of the great application will increase.

**Comment by 2wayne** [comment]
Got it. Thanks!
