### ISSUE TITLE
Page and view naming

### ISSUE THREAD

**Issue by make-github-pseudonymous-again** [otfried/ipe#136]
Allow to give names to pages and views.

**Comment by make-github-pseudonymous-again** [comment]
This would allow, for example, to reference pages and views via those names in `iperender` or `ipetoipe` as well as more easily switch (dropdown menu) between views on pages with lots of views or switch (page sorter) between pages in documents with lots of pages. I use a `Makefile` to compile figures from a single `figure.ipe` file. This `Makefile` contains lots of `iperender` commands with cryptic page and view numbers that need to be updated when the order/position of pages/views changes. Page and view names would not suffer the same inconveniences.

**Comment by otfried** [comment]
In Ipe 6 it was possible to name pages, and I had even submitted a patch for pdflatex to make it possible to include pages by name (together with some other pdflatex patches that I wrote).  I wonder if this is still possible - that would be a nice feature.

Supporting named pages in ipetoipe and iperender would be very easy - we can just use the section title to name the page (these are already shown in the page sorter).

**Comment by otfried** [comment]
In 7.2.8,  pages can be referred to by name in `ipetoipe` and in `iperender`.
The name of a page is set as the "Section" in the "Edit page title & sections" dialog.

View names will be implemented in 7.2.9.

I'll need to look into the pdftex sources to check if symbolic page includes are still possible.

**Comment by otfried** [comment]
View names are implemented in 7.2.13.

What is still needed:

- [x] Allow view names to be used to refer to them in iperender (and ipetoipe -export?).
- [x] Generate labels in `page-labels` script.
- [ ] Implement view sorter?
