### ISSUE TITLE
Rotate does not work on Ubuntu?

### ISSUE THREAD

**Issue by hhuisman** [otfried/ipe#138]
Hi,

just installed IPE 7.2.7 both on a Windows and an Ubuntu (2016) machine. On the latter, rotating objects does not work, while on the Windows machine it does. Is this a known issue?

**Comment by otfried** [comment]
It seems to work for everybody else.

How are you trying to rotate objects?

**Comment by hhuisman** [comment]
Hi Otfried,

Today I tested again on a blank drawing and there it works, and now also in the drawing I was working on. Is it possible to lock this feature? If so, maybe I managed to do that by accident.

So, I don't know what went wrong, but there is no bug.

Have a nice weekend!

----------------------------------------------------
dr. ir. Henk Huisman
Associate Professor in Power Electronics
TU Eindhoven -- Electrical Engineering
Electromechanics & Power Electronics
Visiting address: Flux 2.132
Snailmail: P.O. Box 513
5600 MB -- Eindhoven -- The Netherlands
T: +31 40 247 8750  F: +31 40 243 4364
www.tue.nl/epe
----------------------------------------------------
________________________________
