### ISSUE TITLE
Manual mistake

### ISSUE THREAD

**Issue by domotorp** [otfried/ipe#139]
Not really a bug, just a mistake in the Manual. On http://ipe.otfried.org/manual/manual_13.html (3.10 Layers) it says that you have to left-click to change the active layer, but you need to double-click. It took me 10 mins to figure this out...

**Comment by otfried** [comment]
It's a bit more complicated:  the description is correct for the Qt and Cocoa interface.  But on Windows, I couldn't override the left-click event, so I used a double-click event - thanks for finding the missing information in the manual!

**Comment by domotorp** [comment]
I see, thanks!
