### ISSUE TITLE
Major grid spacing

### ISSUE THREAD

**Issue by mkraska** [otfried/ipe#14]
Is there a way to specify the major grid spacing? There is a thick grid line every four spacings. I managed to specify 1mm and 2mm grids but would like to have a cm major grid.
<gridsize name="1 mm" value="2.8346"/>
<gridsize name="2 mm" value="5.6693"/>

**Comment by otfried** [comment]
The grid is defined using prefs.canvas_style.

You can customize that as described under http://ipe.otfried.org/manual/manual_39.html

But be aware that the gridsize has to be an integer, so an exact mm/cm grid is impossible.  

It's on my todo-list to allow coordinates in other units than Postscript points (1/72 inch), for instance 1/10 mm. 

For the moment, all you can do is make a grid that's approximately mm/cm, and then rescale the figure when you use it to make it exact.
