### ISSUE TITLE
Transparency in PNG files is replaced by black background

### ISSUE THREAD

**Issue by tinloaf** [otfried/ipe#142]
Hi,

I'm trying to include a PNG file with transparent parts ( as an example, use http://i11www.iti.kit.edu/~barth/ipe.png ) in ipe 7.2.6. However, when I do that, I get a black background for the PNG instead of a transparent one. This also remains if I render the file to PDF. It also persists if I include the PNG via \includegraphics{} instead of Ctrl-Shift-O.

Am I doing something wrong or is this a bug?

Thanks a lot,

Lukas

**Comment by otfried** [comment]
Ipe doesn't support mask transparency - only colorkey transparency (which is detected automatically when the image is imported).  Adding mask transparency (from the alpha channel in the PNG) is on my todo list.

I thought it should work with \includegraphics - that needs to be investigated.  Make sure not to apply any opacity value to the text object that contains the \includegraphics call.

**Comment by make-github-pseudonymous-again** [comment]
I don't know what you mean by "colorkey transparency is automatically detected on import". Often it is not. I work around it by adding ColorKey="6letterhexadecimalcolorcode" to each bitmap object in the ipe file.

**Comment by otfried** [comment]
Can you attach a bitmap where automatic detection doesn't work so that I can investigate?

**Comment by make-github-pseudonymous-again** [comment]
Maybe I just don't know how to add ColorKey transparency directly to the png file. What tool can do that?

In GIMP, I remove the alpha channel then I export to png and check the "keep background color" option. The background comes up white. If I don't check that option then the background is black. I am probably doing something wrong. 

I could attach an example image once I get on a computer.

**Comment by otfried** [comment]
Maybe the easiest would be to add a field for a colorkey to the import dialog...

Ipe uses the png_get_tRNS function of libpng to determine a color key.  This will only work if either the image is in palette mode, with a single fully-transparent palette entry (and all other entries fully opaque), or if it's an RGBA image where one specific color is always fully transparent, and no other color having any transparency.   I suppose that when you draw on a transparent background, then the boundary will have many partially transparent pixels, and so this will fail.

It would be good to see an example so I can investigate what exactly happens.   In the near future I will add mask-transparency, so then you can simply keep your alpha-channel.

**Comment by make-github-pseudonymous-again** [comment]
It would also be easy with an entry in the contextual menu of image objects.

**Comment by otfried** [comment]
Images with alpha channel are fully supported in 7.2.11.

Also, detection of a color key now also works on Unix with non-paletted images.

**Comment by brunolnetto** [comment]
I resurrect this issue by question: Is it possible to: add the option 0% for objects opacity?

**Comment by otfried** [comment]
The opacity values offered to you are the symbolic values from your style sheet.  So you need to add a style sheet defining a 0% option, e.g. like this:

```
<opacity name="fully-transparent" value="0"/>
```

**Comment by brunolnetto** [comment]
I clicked on stylesheet option inon the upper menu Edit. A box pops out. What should I do next? Or: where I should add this code line?

I want to remove the circle around this organization symbol: https://github.com/dot-quiver . The library might suit you as well. :-P

**Comment by otfried** [comment]
The manual explains how to make and add a style sheet:

https://ipe.otfried.org/manual/manual_makestyle.html

**Comment by brunolnetto** [comment]
Great! Thank you very much. :)
