### ISSUE TITLE
Parts of Tikz images are cut off

### ISSUE THREAD

**Issue by tinloaf** [otfried/ipe#143]
Hi,

I'm using ipe 7.2.6. I'm using tikz to draw text on a circular arc, like so:

```
\begin{tikzpicture}

\path[postaction={decorate},decoration={text along path,
text={Algorithms},text align=left}]
(0,0) arc [start angle=170,end angle=0,radius=25mm, line width=0pt];
\end{tikzpicture}
```

Now, a certain part of that drawing is "outside" the text box, and I can't make it go back in. Also, when I export this to PDF, that part of the text is being cut off.

As an example, consider 
http://i11www.iti.kit.edu/~barth/ipe/algo-cut.ipe
http://i11www.iti.kit.edu/~barth/ipe/algo-cut.pdf 

Kind regards,

Lukas

**Comment by otfried** [comment]
I don't think there is a way to fix this problem, if the tikzpicture environment does not return the actual bounding box.

You may have to force a larger bounding box for Ipe by drawing a rectangle around your drawing.  If you put this rectangle into a layer called BBOX, it will be used even if the layer is not visible (http://ipe.otfried.org/manual/manual_30.html).

**Comment by tinloaf** [comment]
Thanks for the answer. That's unfortunate. :( Enforcing the larger bounding box does not work, however: It seems like there is not just a bounding box for the whole page, but also for the individual text elements. See 

http://i11www.iti.kit.edu/~barth/ipe/algo-cut2.ipe
http://i11www.iti.kit.edu/~barth/ipe/algo-cut2.pdf
(one is a text label, the other one a paragraph)

I'll try to work around by drawing something invisible left of the text in tikz. Maybe that increases the bounding box.

**Edit**: Yep, that works. I added something like

```
\draw[white] (-1,-1) -- (-1,0);
```

to the picture, thereby extending the bounding box to the left. One could possibly even use opacity instead of using white as color, but that works for me.

**Comment by otfried** [comment]
Ah yes, that's true since recently each text object is in its own XForm object in PDF.   You can enlarge the padding for text objects with <textpad> in the style sheet (http://ipe.otfried.org/manual/manual_48.html), but this will apply to all text objects in the drawing.

It may be necessary to work with Tikz to make sure it forms a larger bounding box.

**Comment by tinloaf** [comment]
Yes, see my comment above. :+1: Thanks for the help. I'm closing this, since it looks like there is nothing ipe can do in this case…
