### ISSUE TITLE
Improving UX for text editing

### ISSUE THREAD

**Issue by horasio** [otfried/ipe#144]
Two suggestions for the text-editing window:

1. Using XeLaTeX with a System Font is relatively slow (at least on my old mac),
so if I click "Apply" to have a preview of the rendered text, and then click
"OK" immediately, without changing the text, I'm frustrated to see the rendered text disappear
(Auto-latex disabled because slow).
If I click "Cancel" I have the desired behavior since the "Apply"-ed text stays.
I think it would be nice if the rendered text also would stay when clicking OK
if no change was made since the last "Apply".

2. Would be very cool if the edit window can remember its size and position.

And thank you for this great software!

**Comment by otfried** [comment]
1. is fixed in 7.2.11.

2. You can set your preferred edit window size by setting

```
prefs.editor_size = { 800, 600 }
```
Is this good enough?   I can look into remembering and storing the dialog sizes, but since I have to implement it on three different platforms, it's a bit of work.
