### ISSUE TITLE
Feature request: crop images

### ISSUE THREAD

**Issue by boileaum** [otfried/ipe#145]
Cropping images (as in Xfig) would be very useful to build a multi-figure layout from bitmap images (by typically removing redundant sub-figures axes legend or titles).

**Comment by otfried** [comment]
You can already clip any Ipe figure, including bitmaps.  

Select the image, and press Ctrl+G to group it (into a group of one).  
Draw a rectangle on top of the image.
Select both the image group and the rectangle, right click, and select "Add clipping path".

This doesn't actually crop the bitmap, it only hides the non-interesting part.  On the other hand, it also works with non-rectangular shapes.

**Comment by boileaum** [comment]
Thanks for the answer!

**Comment by simonvw95** [comment]
> You can already clip any Ipe figure, including bitmaps.
> 
> Select the image, and press Ctrl+G to group it (into a group of one). Draw a rectangle on top of the image. Select both the image group and the rectangle, right click, and select "Add clipping path".
> 
> This doesn't actually crop the bitmap, it only hides the non-interesting part. On the other hand, it also works with non-rectangular shapes.

I have tried this and it works exceptionally well. The main issue I have with this is that after clicking on "Add clipping path" I can no longer select the image group nor the rectangle to move them to other locations or even group them to other groups.
