### ISSUE TITLE
Problems with Symbols

### ISSUE THREAD

**Issue by Dmetzler91** [otfried/ipe#146]
Symbols are not shown in IPE. But if I transfer it to a PDF document,
we can see the symbols.

We use Windows 10.

Can U help us with this problem?
![screenshot_dennis](https://user-images.githubusercontent.com/29429471/27130804-0edc11da-5108-11e7-8441-7f129f88a18e.jpg)

**Comment by otfried** [comment]
Most likely you use a bitmapped font - that is not supported by Ipe.

If you open the PDF file and check the font properties, what font type does it show?

**Comment by Dmetzler91** [comment]
Thank you for your mail.

It shows the font type "Type 3" (PDF is attached)

Thank You so much!
________________________________
Von: Otfried Cheong [notifications@github.com]
Gesendet: Mittwoch, 14. Juni 2017 15:36
An: otfried/ipe-issues
Cc: Metzler, Dennis Renee; Author
Betreff: Re: [otfried/ipe-issues] Problems with Symbols (#146)


Most likely you use a bitmapped font - that is not supported by Ipe.

If you open the PDF file and check the font properties, what font type does it show?

**Comment by otfried** [comment]
A Type3 font is a bitmapped font - Ipe does not support them, because it wants to write genuine vector graphics.

Which fonts are you using (can you show the font selecting commands in your Ipe file, or attach the Ipe file)?   Note that it seems you have to attach files through the github UI, it doesn't seem to work when you reply by email.

**Comment by Dmetzler91** [comment]
Hello otfried,

thank You for your answer.

The files are attached now. I hope we will find an answer for that problem.

Best
Dennis
[Archiv.zip](https://github.com/otfried/ipe-issues/files/1104938/Archiv.zip)

**Comment by otfried** [comment]
I had thought until now you were using some non-standard fonts.  Now I see you get this problem even with the default Latex fonts.   

This implies that your pdflatex is misconfigured.   It should always use scalable fonts. 

My guess is that you simply did not install the necessary fonts, so it falls back on Metafont fonts from TeX.

This is really not an Ipe problem.   If you make simple test file, e.g. test.tex
as follows:

```
\documentclass{article}
\begin{document}
$\alpha$
\end{document}
```
Then run `pdflatex test.tex`.   Check what fonts are being used in the log file (`test.log`), and zoom into the pdf file:  you will also see a bitmapped alpha.

**Comment by Dmetzler91** [comment]
Thank you for your useful answer. 

and do you know how to install the necessary fonts? 

Best 

Dennis 

Am 2017-06-28 06:57, schrieb Otfried Cheong:

> I had thought until now you were using some non-standard fonts. Now I see you get this problem even with the default Latex fonts. 
> 
> This implies that your pdflatex is misconfigured. It should always use scalable fonts. 
> 
> My guess is that you simply did not install the necessary fonts, so it falls back on Metafont fonts from TeX. 
> 
> This is really not an Ipe problem. If you make simple test file, e.g. test.tex
> as follows:
> 
> \documentclass{article}
> \begin{document}
> $\alpha$
> \end{document}
> 
> Then run pdflatex test.tex. Check what fonts are being used in the log file (test.log), and zoom into the pdf file: you will also see a bitmapped alpha. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].

  

Links:
------
[1]
https://github.com/otfried/ipe-issues/issues/146#issuecomment-311556561
[2]

**Comment by otfried** [comment]
How could I?  I don't even know what Latex installation you have installed.

This is a quite unusual problem - the scalable fonts should be part of even the most basic TeX setup.
