### ISSUE TITLE
IpeletData->iSnap containing no data 

### ISSUE THREAD

**Issue by ghost** [otfried/ipe#148]
I am writing an Ipelet using C++. IpeletData->iSnap.iWithAxes is not returning true when the span axes are shown while calling the Ipelet, and IpeletData->iSnap.iDir does not seem to be updated with the direction of the snap axes. I am using Ipe 7.2.7 on arch Linux

**Comment by otfried** [comment]
Sorry about that.   Fixed in 7.2.8.
