### ISSUE TITLE
Transparency not applied to path's arrows

### ISSUE THREAD

**Issue by tinloaf** [otfried/ipe#149]
Hi,

it looks like the 'opacity' setting does not affect the arrows for paths. When I set the opacity of a path that has an arrow, the path itself becomes transparent, but the arrow remains opaque.

As an example, consider http://i11www.iti.kit.edu/~barth/ipe_transparency.ipe

I'm using ipe 7.2.6.

Thanks for any help,

Lukas

**Comment by otfried** [comment]
Duplicate of #84.
