### ISSUE TITLE
undocumented feature

### ISSUE THREAD

**Issue by pierreganty** [otfried/ipe#15]
If the latex code you include contains some TikZ code then it is likely not to be display correctly in `ipe`, `ipeview` or `ipePresenter` **but** if you export your ipe document as a PDF (using `save as` in `ipe` or `ipetoipe -pdf`) the TikZ code will be rendered perfectly in the generated PDF. So if you want to save precious time and not have to redraw in ipe some TikZ figure that option exists. It should also work for PSTricks etc.

**Comment by otfried** [comment]
Many Ipe users use this feature, judging from the discussions on ipe-discuss.  

It is hard to document in any case, as it's hard to predict what will work and what doesn't.  As long as you use rather basic TikZ, it usually works - but as soon as you use any TikZ feature that interrupts the linear generation of PDF, it will break.

It certainly does not work for PSTricks, which uses Postscript, and relies on the standard Latex -> DVI -> PS chain. 

Simple PGF commands can be used, as they generate PDF instructions without interrupting the linear flow of PDF.  

Handling TikZ figures in Ipe more completely is on my todo-list.  Ideally, Ipe should be able to display TikZ on screen and generate correct PDF output, even when features are used that rely on PDF side effects.
