### ISSUE TITLE
<textpad> not working with XeTeX

### ISSUE THREAD

**Issue by Willem3141** [otfried/ipe#151]
I was having an issue with text being cut off. As suggested in #105 I added `<textpad>` to my style file. While this works on PDFLaTeX, it turns out that this option does not work when using XeTeX.

I attached two testcases: [one with PDFLaTeX](https://github.com/otfried/ipe-issues/files/1222805/test-pdflatex.pdf) and [one with XeLaTeX](https://github.com/otfried/ipe-issues/files/1222804/test-xelatex.pdf). Both have `<textpad left="20" right="20" top="20" bottom="20"/>`. Note that the tail of the *f* is cut off in the XeLaTeX version, and not in the PDFLaTeX version.

I am using Ipe 7.2.7 on Linux.

**Comment by otfried** [comment]
When Ipe writes out the PDF resources, it recognizes the ones corresponding 1:1 to text objects by the presence of the /IpeId key.   When the PDF data comes from xetex, this doesn't work, and Ipe doesn't know which XForm objects to treat specially.

**Comment by otfried** [comment]
Finally fixed in 7.2.17.
