### ISSUE TITLE
Beep for key presses while drawing

### ISSUE THREAD

**Issue by ghali** [otfried/ipe#152]
Ipe generates a strange beep, suggesting an error:

1. Select "Polygons" (shift-P).
2. Mouse-click at first location.
3. Mouse-click at second location.
4. Mouse-move to third location, and press 'a'. Ipe draws an (elastic) circular arc.
5. Mouse-click at third location.

On Step 4, OS X beeps. It's not a big deal. One can mute the volume to avoid the distraction. The feature works fine.

But still, it makes the user wonder whether the 'a'/circular arc feature is possibly deprecated or if it has been superseded.

Running Ipe from the binary package ipe-7.2.7-mac.dmg on El Capitan (10.11.6)

**Comment by otfried** [comment]
It seems that OSX makes this "beep"  (on my old Macbook it's more a deep ping sound) whenever the user presses a key that is not understood by the system (i.e. a key that is not a shortcut for something).   It's strange that the sound happens even when the key is actually interpreted by the code - I'll need to investigate.   
The Ipe architecture is quite different from the standard Cocoa application architecture, and apparently Ipe's way of handling keys is confusing Cocoa.

**Comment by otfried** [comment]
Simply a missing return statement in the LINESTOOL:key handler...

Fixed in 7.2.8.
