### ISSUE TITLE
Lua error when deleting page with page sorter while e.g. on last page

### ISSUE THREAD

**Issue by d85iDE** [otfried/ipe#153]
**Ipe version tested:**
7.2.7 on Windows 10

**Steps to reproduce:**
- Create new ipe file
- Add 2 new pages (ctrl+i, ctrl+i)
- Open Page Sorter, delete 2 arbitrary pages, click Ok.

After doing so ipe says it is on Page 3/3, even so only one page exists. Ipe may unexpectedly close afterwards.

**Comment by otfried** [comment]
Fixed in 7.2.8.
