### ISSUE TITLE
ptarc/fptarc displayed incorrect for circular arcs

### ISSUE THREAD

**Issue by joklawitter** [otfried/ipe#154]
For circular arcs (by center, right and left point)/(3 points) the forward arrow shape `ptarc` and `fptarc` are displayed as `arc`  and `farc`, respectively. Works correctly for circular arcs (by center, left and right point).

For all three types of circular arcs the reverse arrow shape  `ptarc` and `fptarc` are not tilted along the arc.

**Comment by otfried** [comment]
Fixed in 7.2.8.
