### ISSUE TITLE
pdftoipe producing broken .ipe files using scientific notation for colors

### ISSUE THREAD

**Issue by pcaday** [otfried/ipe#156]
Hi,
     First and most importantly, thanks for such a great drawing editor!

I recently had a PDF file that, when converted by pdftoipe, produces an .ipe file that crashes ipe (assertion isColor in Painter::setStroke fails.) After looking at the produced .ipe file, it appears the problem is that some near-zero components of colors are output in scientific notation, e.g.

<path stroke="3.05176e-05 0 0" ...>

Further testing seems to indicate that Ipe isn't parsing this correctly. I'm not sure if this should be correct syntax. If not, the format specification on line 614 in pdftoipe/xmloutputdev.cpp could be changed to e.g. "%f %f %f" (and probably other %g specifiers in pdftoipe should be changed to %f). 

If scientific notation should be correct, I suppose that Lex::getFixed would need to be updated to handle scientific notation.

Peter

**Comment by pcaday** [comment]
(Also, patching pdftoipe/xmloutputdev.cpp as above does produce a working ipe file for this example.)

**Comment by otfried** [comment]
Thanks for the patch!

**Comment by otfried** [comment]
But next time please report it on the ipe-tools bug tracker:

https://github.com/otfried/ipe-tools/issues

pdftoipe is unsupported and not part of Ipe.
