### ISSUE TITLE
Order of loading ipelets in 7.1.8

### ISSUE THREAD

**Issue by nzeh** [otfried/ipe#16]
If no IPELETPATH is set, then the ipelets in the system ipelet dir and the user ipelet dirs are loaded in the wrong order, or at least in an order that causes problems with some ipelets.  Here's the problem:  config.ipeletDirs is populated first with the system directory and then the user directories are prepended to this list.  This means that user ipelets, including preferences and shortcuts are loaded before the system ipelets.  Now, align.lua sets some shortcuts (should it do that at all?).  The effect is that whatever shortcuts I set in my .ipe/ipelets/shortcuts.lua for these actions are overriden by the system settings.  Here's the simple fix that seems to work:

Replace the following lines in main.lua:

``` lua
  config.ipeletDirs = { config.system_ipelets }
  if config.platform == "win" then
    local userdir = os.getenv("USERPROFILE")
    if userdir then
      table.insert(config.ipeletDirs, 1, userdir .. "\\Ipelets")
    end
  else
    table.insert(config.ipeletDirs, 1, home .. "/.ipe/ipelets")
    if config.platform == "apple" then
      table.insert(config.ipeletDirs, 2, home .. "/Library/Ipe/Ipelets")
    end
  end
```

with

``` lua
  config.ipeletDirs = { config.system_ipelets }
  if config.platform == "win" then                           
    local userdir = os.getenv("USERPROFILE")
    if userdir then
      config.ipeletDirs[#config.ipeletDirs + 1] = userdir .. "\\Ipelets"
    end
  else
    config.ipeletDirs[#config.ipeletDirs + 1] = home .. "/.ipe/ipelets"
    if config.platform == "apple" then
      config.ipeletDirs[#config.ipeletDirs + 1] = home .. "/Library/Ipe/Ipelets"
    end
  end
```

**Comment by otfried** [comment]
Will be in 7.1.9
