### ISSUE TITLE
Jump to page dialog doesn't close on OSX 10.13

### ISSUE THREAD

**Issue by Timmmm** [otfried/ipe#160]
On OSX 10.12, (with the fix in #147) when you click a page in the "Jump to page" dialog, it goes to that page and then closes the dialog.

In OSX 10.13 it goes to the page, but then the dialog stays open. Further clicking on pages doesn't do any navigation.

**Comment by otfried** [comment]
Is this issue still present in OSX 10.14?   (I'm hoping to get a new Mac soon and just want to know if I need to install a specific version of OSX to reproduce the problem).

**Comment by otfried** [comment]
Fixed in 7.2.8.

**Comment by Timmmm** [comment]
Yeah I'm pretty sure this works now, thanks.
