### ISSUE TITLE
Possibly suboptimal PDF generated

### ISSUE THREAD

**Issue by pierreganty** [otfried/ipe#162]
I did a bunch of slides with a black background following the wiki recommendations on adding a background.
After generating the PDF (using `ipetoipe -pdf`) the generated PDF has a little but annoying problem on OSX: with both PDF viewers I've tried (Skim and Preview) the pdf flashes when switching pages (white flash before displaying black slide). 
The problem is transient: it flashes only the first time the page is displayed.
The same PDF on Linux is displayed fine with evince and okular (no white flash).
The OSX and Linux machine used were different.

**Comment by otfried** [comment]
Why do you think the PDF is suboptimal?   My guess that each page simply draws a black rectangle as the first thing it does.   Is there a better way?  What makes you think this is an Ipe problem rather than a feature of the OSX viewers?

**Comment by pierreganty** [comment]
My report suggests it is probably an OSX or OSX viewer problem. I am closing it.
