### ISSUE TITLE
Right-click not working with tablet buttons

### ISSUE THREAD

**Issue by bwinkler** [otfried/ipe#164]
I'm on Linux (so using QT) and I have a Wacom tablet with the side button on the stylus mapped to right-click (button 2 mapped to button 3).

Adding vertices using the tip works just fine but trying to add the final vertex using right-click does not work. It just adds another vertex.

I commented out the parts of the qt_canvas.h/qt_canvas.cpp regarding the tablet events (per another related issue) so that Ipe would only use QT mouse events. This seemed to make everything work properly but I'm guessing that I'm missing some fancy tablet features now, though.

Does it make sense  to make a configuration option to choose whether to treat events as mouse or tablet events?

**Comment by otfried** [comment]
You do know that you can use double-click to place the last vertex?

Such an option is certainly possible - what you lose is subpixel precision on pen input (which is quite important when using the ink mode, otherwise it's hardly noticeable).

I would like to figure out what the problem is, though.   Can you perhaps insert a single debug print statement and see what you get when you press the pen with and without the side button?
```
diff --git a/src/ipecanvas/ipecanvas_qt.cpp b/src/ipecanvas/ipecanvas_qt.cpp
index 4cdc68a..28ef570 100644
--- a/src/ipecanvas/ipecanvas_qt.cpp
+++ b/src/ipecanvas/ipecanvas_qt.cpp
@@ -227,6 +227,7 @@ void Canvas::tabletEvent(QTabletEvent *ev)
 
   switch (ev->type()) {
   case QEvent::TabletPress:
+    ipeDebug("TabletPress: %d %d", ev->button(), ev->pointerType());
     iGlobalPos = globalPos;
     computeFifi(hiPos.x(), hiPos.y());
     if (ev->pointerType() == QTabletEvent::Eraser) {
```
You need to set the environment variable IPEDEBUG to see debug output.

**Comment by bwinkler** [comment]
I think it is likely a [bug in QT](https://bugreports.qt.io/browse/QTBUG-57487). The debug messages show button 2 (middle-click) events even though that button is mapped to button 3 (right-click) using the Wacom configuration. 

Here is the output of 3 consecutive stylus taps (1st: no button, 2nd: button 2 pressed, 3rd: eraser button pressed):

```
TabletPress: 1 1
TabletPress: 2 1
TabletPress: 1 3
```

Here is what xev reports for the same 3 taps:

```
ButtonPress event, serial 25, synthetic NO, window 0x4600001,
    root 0xf6, subw 0x0, time 56633253, (416,366), root:(1996,1102),
    state 0x0, button 1, same_screen YES

ButtonRelease event, serial 25, synthetic NO, window 0x4600001,
    root 0xf6, subw 0x0, time 56633348, (417,361), root:(1997,1097),
    state 0x100, button 1, same_screen YES

ButtonPress event, serial 25, synthetic NO, window 0x4600001,
    root 0xf6, subw 0x0, time 56637920, (410,402), root:(1990,1138),
    state 0x0, button 3, same_screen YES

ButtonRelease event, serial 25, synthetic NO, window 0x4600001,
    root 0xf6, subw 0x0, time 56638105, (411,394), root:(1991,1130),
    state 0x400, button 3, same_screen YES

ButtonPress event, serial 25, synthetic NO, window 0x4600001,
    root 0xf6, subw 0x0, time 56640721, (463,400), root:(2043,1136),
    state 0x0, button 1, same_screen YES

ButtonRelease event, serial 25, synthetic NO, window 0x4600001,
    root 0xf6, subw 0x0, time 56640890, (459,398), root:(2039,1134),
    state 0x100, button 1, same_screen YES
```

I'm trying to get QT 5.9 installed now to see if that fixes it. I'll close the issue since it's definitely not a problem with Ipe.

Thanks!

**Comment by otfried** [comment]
But this is perfect - we get all the information we need to distinguish the different events.

And it does obey your button mapping:  Button #2 is the right mouse button (the middle button is button #4) - see http://doc.qt.io/qt-5/qt.html#MouseButton-enum

So here is a simple patch that should make the side button work correctly as the right mouse button;

```
diff --git a/src/ipecanvas/ipecanvas_qt.cpp b/src/ipecanvas/ipecanvas_qt.cpp
index 4cdc68a..130c7f3 100644
--- a/src/ipecanvas/ipecanvas_qt.cpp
+++ b/src/ipecanvas/ipecanvas_qt.cpp
@@ -227,6 +227,7 @@ void Canvas::tabletEvent(QTabletEvent *ev)
 
   switch (ev->type()) {
   case QEvent::TabletPress:
+    ipeDebug("TabletPress: %d %d", ev->button(), ev->pointerType());
     iGlobalPos = globalPos;
     computeFifi(hiPos.x(), hiPos.y());
     if (ev->pointerType() == QTabletEvent::Eraser) {
@@ -234,9 +235,9 @@ void Canvas::tabletEvent(QTabletEvent *ev)
        iObserver->canvasObserverMouseAction(Qt::XButton1 |
                                             iAdditionalModifiers);
     } else if (iTool)
-      iTool->mouseButton(Qt::LeftButton | iAdditionalModifiers, true);
+      iTool->mouseButton(ev->button() | iAdditionalModifiers, true);
     else if (iObserver)
-      iObserver->canvasObserverMouseAction(Qt::LeftButton | 
+      iObserver->canvasObserverMouseAction(ev->button() | 
                                           iAdditionalModifiers);
     break;
   case QEvent::TabletMove:
```

You should also be able to use the eraser to delete objects.   You can also reprogram the function of the eraser by changing the definition of mouse.button8 (see mouse.lua - the default definition is "shredder" to delete objects).

**Comment by bwinkler** [comment]
Thanks for the info and the patch. The stylus button works with right-clicks to finalize paths and the eraser does delete paths. That's great!

However, right-clicking to bring up a menu with the stylus button crashed Ipe. The problem seemed to be that the tablet event was giving floating point positions but the function for placing the menu was checking for an integer position.

I made the following change and it seemed to work but I'm not sure if this is the safest/best way to handle this.

```
diff --git a/src/ipeui/ipeui_qt.cpp b/src/ipeui/ipeui_qt.cpp
index 91bdd39..2dde017 100644
--- a/src/ipeui/ipeui_qt.cpp
+++ b/src/ipeui/ipeui_qt.cpp
@@ -463,8 +463,8 @@ PMenu::~PMenu()
 
 int PMenu::execute(lua_State *L)
 {
-  int vx = (int)luaL_checkinteger(L, 2);
-  int vy = (int)luaL_checkinteger(L, 3);
+  int vx = (int)luaL_checknumber(L, 2);
+  int vy = (int)luaL_checknumber(L, 3);
   QAction *a = iMenu->exec(QPoint(vx, vy));
   MenuAction *ma = qobject_cast<MenuAction *>(a);
   if (ma) {
```

**Comment by otfried** [comment]
The fix looks good to me - I'll add it for the next release.
