### ISSUE TITLE
PNG and transparency

### ISSUE THREAD

**Issue by pierreganty** [otfried/ipe#166]
By default `ipe` seems to assign transparent layers to white.
Is that imaginable for `ipe` to handle transparent background?
Else, could it, at least, pick the color of the background symbol (if any) and fall back to white otherwise? Would that make sense?  
Otherwise, one can always manipulate the png to have the right background,  for instance with ImageMagick that would be something like:
`convert input.png -background black -alpha remove input-black.png`

**Comment by otfried** [comment]
I'm not sure what you mean by "transparent layers" - there is no such thing in Ipe.

To generate a PNG file, Ipe simply draws the Ipe drawing onto a bitmap.   By default, this bitmap will be white, but using the -transparent option of iperender, you can also have it transparent.

**Comment by pierreganty** [comment]
I am referring to the transparent layers in the PNG format not in ipe.
When importing a PNG with transparent background ipe does not display the background on the PNG as transparent but with the white color instead.

**Comment by otfried** [comment]
So you are talking about importing PNG files using "Insert image"?   

Is this the same as feature request #142?

**Comment by pierreganty** [comment]
yes, it is a duplicate of #142. I thus let you close it.
