### ISSUE TITLE
IPE does not start if address of IPE Folder contains special symbols

### ISSUE THREAD

**Issue by DaLundi** [otfried/ipe#17]
IPE does not start if address of IPE Folder contains special symbols as "C:\Sö\ipe"

**Comment by otfried** [comment]
The Ipe installation instructions clearly say that you should not do this:

> You can unzip this binary distribution whereever you like, but please
> use a directory whose path contains neither spaces nor non-ASCII
> characters.  You can then find (and start) the Ipe executable in the
> "bin" subdirectory.

**Comment by DaLundi** [comment]
Oh you are right. Than this is an improvement suggestions :-)

**Comment by otfried** [comment]
If you want to suggest this as an improvement, you shouldn't close the issue...

**Comment by otfried** [comment]
Implemented in 7.1.10.
