### ISSUE TITLE
Non-roman characters in directory name cause EPS export to fail

### ISSUE THREAD

**Issue by DexKim** [otfried/ipe#170]
I tried to export in eps format but no files were created. Trying to run ipe in admin mode doesn't seem to fix the problem.

Current version: ipe 7.2.7
OS: Windows 10 Pro

**Comment by otfried** [comment]
Can you attach an Ipe document where exporting didn't work?

**Comment by DexKim** [comment]
[heat_pump_pic.zip](https://github.com/otfried/ipe-issues/files/2387316/heat_pump_pic.zip)
Exporting to png or pdf seems to work fine. Somehow eps export for other files I created works normally, but for this one it just doesn't work.

**Comment by otfried** [comment]
I have just tried it, and exporting to eps works fine for me, using the original Ipe 7.2.7.
Perhaps the eps file was written to another directory where you didn't look for it?

**Comment by DexKim** [comment]
I think it was a different issue; the eps exportation does not work when there are non roman characters in the directory. I tried exporting to a different directory with purely roman characters and the exportation worked fine.

**Comment by otfried** [comment]
If that is the case, it is also a bug.  

Strange, it seems I'm converting the filename correctly to wide characters...

**Comment by otfried** [comment]
Aha, cairo_ps_surface_create does not handle wide characters.

**Comment by otfried** [comment]
Fixed in 7.2.8.
