### ISSUE TITLE
The changes in a style sheet are not reflected immediately

### ISSUE THREAD

**Issue by pengdlzn** [otfried/ipe#171]
I am using some extra style sheets when making slides in Ipe 7.2.7.1 on Windows 7.

I sometimes change some settings in the style sheets, but the changes are not reflected immediately in the slides after I have run latex in Ipe.

Suppose that I have edited style sheet 'mystyle.isy'. In order to see the changes in my slides, I have to open 'Stype sheets' in menu 'Edit', remove ('Del') style sheet 'mystyle.isy', and then add this sheet again.

**Comment by otfried** [comment]
This is exactly what the function "Update style sheets" (Shift+Ctrl+U) is for.
