### ISSUE TITLE
"Background" symbols seem to be included separately on every page

### ISSUE THREAD

**Issue by guenterrote** [otfried/ipe#174]
putting a large Logo as part of the "background", to be repeated on every page, seems to blow up the PDF-file size, since it is apparently included separately on every page, instead of being included only once. (I recall that this was a bug in some previous ipe version, and was apparently fixed.)

[Congruence-Ippages.pdf](https://github.com/otfried/ipe-issues/files/1572849/Congruence-Ippages.pdf)
In this example file, adding or removing and empty page (or adding a new view) changes the PDF-filesize by 50k bytes

**Comment by otfried** [comment]
You need to set the **xform** attribute of the background symbol, like this:
```
<symbol name="Background" xform="yes">
```

See http://ipe.otfried.org/manual/manual_48.html for the explanation.
