### ISSUE TITLE
Please add release tags to Ipe

### ISSUE THREAD

**Issue by tillea** [otfried/ipe#175]
Hi,
for the Debian packaging of ipe it would help if you would use release tags.  This would enable automatic detection of new releases.
Thanks for considering, Andreas.

**Comment by otfried** [comment]
Can you be more specific?   What are "release tags"?

Ipe is released on bintray, I'm not aware of a tagging system other than the versioning I'm already using.

**Comment by tillea** [comment]
On Sat, Jan 27, 2018 at 04:37:31PM +0000, Otfried Cheong wrote:
> Can you be more specific?   What are "release tags"?

Just do `git tag VERSIONNUMBER` on Github.
 
> Ipe is released on bintray, I'm not aware of a tagging system other than the versioning I'm already using.

Github will create an additional download option under "Releases" tab
and this would enable automatic scanning of new versions.  Bintray has
quite an ugly format which causes trouble to scan for new versions.

Kind regards, Andreas.

**Comment by otfried** [comment]
I don't understand.  How would Github create an additional download option under "Releases"?   The Ipe sources are not on Github.

**Comment by tillea** [comment]
On Sat, Jan 27, 2018 at 12:32:58PM -0800, Otfried Cheong wrote:
> I don't understand.  How would Github create an additional download option under "Releases"?   The Ipe sources are not on Github.
Uhmmm, now I understand.  Well, what we need are versioned tarballs on a web site.  Its easy on Github but you seem to have reasons to use something else.

**Comment by Hirse** [comment]
fyi, the sources don't have to be on GitHub in order to use the Releases-feature. One can manually create new releases and attach uploaded binaries. (See https://help.github.com/articles/creating-releases)

**Comment by otfried** [comment]
There are versioned tarballs in https://dl.bintray.com/otfried/generic/ipe/7.2/
That's not good enough?

**Comment by tillea** [comment]
Hi Otfried,
On Sun, Sep 16, 2018 at 10:17:26AM -0700, Otfried Cheong wrote:
> There are versioned tarballs in https://dl.bintray.com/otfried/generic/ipe/7.2/
> That's not good enough?
It works somehow but is not really straightforward for users who just stumble upon Github.  So why not just adding those tags?
Kind regards, Andreas.

**Comment by otfried** [comment]
I thought this was about debian packaging, not about users who stumble upon Github?

Ipe uses github only for hosting the website and for the issue tracker.   Both the  "ipe" and the "ipe-issues" repositories have no commits, so it's not possible to tag commits (the "ipe" repository hosts the website, but that's on a different branch).

**Comment by tillea** [comment]
On Sun, Sep 16, 2018 at 12:09:34PM -0700, Otfried Cheong wrote:
> I thought this was about debian packaging, not about users who stumble upon Github?
For Debian packaging its possible to deal with versioned dirs (you are using 7.1 and 7.2 dirs - formerly this was an issue), but tags on Github are more convenient.
 
> Ipe uses github only for hosting the website and for the issue tracker.   Both the  "ipe" and the "ipe-issues" repositories have no commits, so it's not possible to tag commits (the "ipe" repository hosts the website, but that's on a different branch).
You probably have your reasons to do this - feel free to close the issue then ...
