### ISSUE TITLE
Double click doesn't work on osx 10.11.6

### ISSUE THREAD

**Issue by geomblog** [otfried/ipe#176]
Hi, I'm running ipe 7.2.7 on OSX 10.11.6 (El Capitan). Whenever I try to draw any object, using double-click to end the drawing causes the object to disappear. The only things I can draw are marks. This problem appears with lines, polylines, shapes, etc.

**Comment by otfried** [comment]
Are you using a mouse or a trackpad?

**Comment by geomblog** [comment]
I'm using a track pad.

**Comment by geomblog** [comment]
Follow up: based on your question, I also tried operating with an external mouse. It worked. So the problem appears to be with the double click signal coming from the trackpad.

**Comment by otfried** [comment]
I finally got to reviving my old Macbook.  It runs 10.11.6 as well, and double-clicks with the trackpad work just fine with my current Ipe development version.   I hope this means that the problem got fixed by one of the changes I made.   

Please try again once 7.2.8 is out (hopefully quite soon).
