### ISSUE TITLE
Latex symbol compilation

### ISSUE THREAD

**Issue by francoisdp** [otfried/ipe#177]
Hallo Otfried.  Thanks for the effort you are putting into a great program.  I recently moved over to a new workstation running Windows 7 and installed the latest version of Miktex (2.9) and IPE (7.2.7), but could not get IPE to compile Greek letters.  I finally dropped back to an earlier version of IPE (I tried 7.2.1) and it worked, so I did not try a later version.  So the issue that I am reporting is that it seems that this combo of Miktax 2.9, IPE 7.2.7 and Windows 7 64 bit has an issue in compiling Latex code.  I did not get any compilation errors.

**Comment by otfried** [comment]
Please attach an Ipe file that doesn't compile, and the latex log.

**Comment by francoisdp** [comment]
Hallo
I subsequently found the problem again.  There seems to be not problem with
the combo I mentioned.  It was one of the stylesheet files I used that was
breaking it.  I have not been able to detect which one it was.  I found the
styles from this site:  https://www.sthu.org/misc/ipe.html  The big sheet
is working

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
