### ISSUE TITLE
Document that it is required to call initLib()

### ISSUE THREAD

**Issue by Willem3141** [otfried/ipe#179]
I'm currently using Ipelib from my C++ program to write Ipe files. I was getting a strange crash from just calling the `Document()` constructor. After debugging and going through the documentation, I found the method `Platform::initLib()`. I included a call to that method, and the problem was solved (the crash apparently happened because the locale was not set).

The documentation for `Platform::initLib()` indeed states that it is required to call this method before doing anything with Ipelib, but (as far as I found) there is no indication of this elsewhere. Because omitting this method call leads to a seemingly unrelated crash, this is quite hard to debug. Therefore I think it makes sense to mention this on the [documentation main page](http://ipe.otfried.org/manual/index.html), for example something like

> Before using Ipelib, make sure to initialize the library by calling `Platform::initLib()`. See the [documentation](http://ipe.otfried.org/manual/classipe_1_1_platform.html#aaee52c13d75a741ce59d10f25ec61fcd) for that method for more details.

**Comment by otfried** [comment]
Added to documentation in 7.2.8.
