### ISSUE TITLE
OSX El Capitain pdflatex error

### ISSUE THREAD

**Issue by RobTrifiletti** [otfried/ipe#18]
Hi,
Just installed OSX El Capitain and when I try to run latex from Ipe I now get "An error occurred during the Pdflatex run"

This issue is probably related to https://tug.org/mactex/UpdatingForElCapitan.pdf. To fix my general latex setup I reinstalled mactex so that it fixed the new locations. Now that I tried running Ipe I get the above error. Could it be that Ipe is looking for pdflatex in the wrong place? I can however confirm that from my terminal running "pdflatex" work fine so it is in my system path. I am unsure how Ipe locates pdflatex and I am unable to find any settings so that I could point it to the right location..
I'm using the newest Ipe 7.1.8 and downloaded the precompiled .dmg file from your site.

**Comment by otfried** [comment]
You probably just need to add /Library/TeX/texbin to the path in the small shell script that starts Ipe (inside the Ipe bundle in Ipe.app/Contents/MacOS/ipe, I believe).

If that doesn't work, please start Ipe from the **command line** with debugging turned on:

```
export IPEDEBUG=1
ipe
```

(you may have to give the full path to the script, i.e. something/Ipe.app/Contents/MacOS/ipe).

**Comment by RobTrifiletti** [comment]
Thanks, adding /Library/TeX/texbin to the path in the small shell script that starts Ipe (inside the Ipe bundle in Ipe.app/Contents/MacOS/ipe) did the trick :)

**Comment by otfried** [comment]
Let's keep it open so people can find the fix more easily.

**Comment by sdmieu** [comment]
Hi, what is the command for adding the path?
Should I open ipe shell and add the command for the path?

**Comment by sdmieu** [comment]
I found it,
we need to open  Ipe (inside the Ipe bundle in Ipe.app/Contents/MacOS/ipe) by something like Xcode app. And then under PATH=$DIR:/usr/texbin:/usr/local/texbin:/usr/local/bin:$PATH, we need to add the following line:
PATH=$PATH:/Library/TeX/Distributions/.DefaultTeX/Contents/Programs/texbin
Then it would work.

**Comment by sghrunt** [comment]
Sorry, I've the same problem but I did't solved it. Following your suggestions I wrote something in  the terminal like  Ipe bundle in Ipe.app/Contents/MacOS/ipe. Now
1) It compiles  in pdflatex (only tex....I need to use insert text with $...$, insert formula gives me the same error) if I start ipe by clicking on the ipe file in the bundle (ipe starts as well as a terminal shell)
2) the terminal shell is no longer editable (it just give me a log file of the operations in ipe)
3) If I close the app and then I restart it, then all the old latex insertions appear as text on the drawing (not compiled)

Please help me to solve this issue step by step (as you see I/m not an expert at all on PATH, DEBUGS, and so on...). As a lazy user I just want to start the ipe app (from the application folder) and the app just working fine :)

Thanks a lot!

**Comment by RobTrifiletti** [comment]
1) Go to Ipe.app/Contents/MacOS/ipe and open this file by right-clicking->open with->text editor

2) Once you have the text file update the line with PATH=$DIR:/Library/TeX/texbin:/usr/texbin:/usr/local/texbin:/usr/local/bin:$PATH
Notice the /Library/TeX/texbin: that has been added to the front. That tells Ipe that it needs to look for pdflatex in that location, therefore you need to be sure that indeed pdflatex is present there on your system, if not it still won’t work.

3) Close and save the text file. Now when you run the ipe.app by simply double clicking it should work as before.

That’s what I did to make it work. Hope it helps.

**Comment by otfried** [comment]
This should be fixed on 7.1.10.

**Comment by sghrunt** [comment]
Thanks a lot RobTrifiletti, this solved my problem!
 :)

**Comment by zschmidt** [comment]
This didn't work for me (probably due to an incorrect setting in my own computer's TeX install)

Like other said, I had to modify the file:

Ipe.app/Contents/MacOS/ipe.sh

And I had to change my path to the following for it to work:

PATH=/Library/TeX/Distributions/.DefaultTeX/Contents/Programs/texbin:/usr/texbin:/usr/local/texbin:/usr/local/bin:$PATH

**Comment by otfried** [comment]
On my OS X 10.11.1 installation, /Library/TeX/texbin is a symbolic link:

```
$ ls -l /Library/TeX
total 32
drwxr-xr-x  7 root  wheel  238 22 Nov 02:41 Distributions
lrwxr-xr-x  1 root  wheel   38 22 Nov 02:41 Documentation -> Distributions/.DefaultTeX/Contents/Doc
lrwxr-xr-x  1 root  wheel   45 22 Nov 02:41 Local -> Distributions/.DefaultTeX/Contents/TexmfLocal
lrwxr-xr-x  1 root  wheel   39 22 Nov 02:41 Root -> Distributions/.DefaultTeX/Contents/Root
lrwxr-xr-x  1 root  wheel   29 22 Nov 02:41 texbin -> Distributions/Programs/texbin
$ ls -l /Library/TeX/Distributions/Programs/texbin
lrwxr-xr-x  1 root  wheel  39 22 Nov 02:41
/Library/TeX/Distributions/Programs/texbin -> ../.DefaultTeX/Contents/Programs/texbin
```

If you don't have that symbolic link, probably something went wrong during your TeX installation.  Did you install from https://www.tug.org/mactex/?

**Comment by zschmidt** [comment]
I wouldn't doubt that I did something incorrectly during my upgrade to El Capitan (when I was in a time crunch and needed to have LaTeX). If your fix works fine for most people that's totally awesome, I just figured that I'd post how I got mine to run for posterity.

BTW, I absolutely adore IPE and I use it all the time... there's nothing even remotely close to it (that I've found)

**Comment by spapadim** [comment]
Similar problem, but for using macports latex, which needs /opt/local/bin in the PATH.
In ipe 7.2.2, ipe is a binary executable (not a shell script, anymore).  However, adding the above binary dir in Ipe.app/Contents/Info.plist (just grep PATH) did the trick.

Perhaps /opt/local/bin should also be included in future versions.  BTW, ipe on macports seems to be a few versions behind, which is why I decided to install the app bundle separately.

**Comment by otfried** [comment]
Isn't that exactly what the instructions in the readme.txt in the app bundle say?

I'll add /opt/local/bin to the path.
