### ISSUE TITLE
iperender does not store png pixel density in metadata

### ISSUE THREAD

**Issue by antiskid56** [otfried/ipe#183]
The png files produced by iperender do not have a pixel density associated with them in their meta-data. This makes it difficult to import png files containing text with a font size that is consistent with expectations.

I have been using the convert program from the imagemagick package to add the dpi setting to the png metadata, like this:

$ `convert -units PixelsPerInch input.png -density 300 output.png`

but it would be very nice if this were not necessary.

**Comment by otfried** [comment]
Ipe relies on the CAIRO library to create the PNG file, and this does not offer the option of saving the pixel density.   So this would be hard to fix.
