### ISSUE TITLE
iperender does not accept -transparent with -resolution when rendering png

### ISSUE THREAD

**Issue by ryanberryhill** [otfried/ipe#184]
When rendering a png, iperender will accept -resolution or -transparent, but not both.

Expected Behavior
---
All of the following should render a.png

    $ iperender -png -transparent a.ipe a.png
    $ iperender -png -resolution 300 a.ipe a.png
    $ iperender -png -transparent -resolution 300 a.ipe a.png

Observed Behavior
---
In ipe-7.2.7 (tested with the AppImage) and ipe-7.1.10 (from ubuntu xenial repos) the first two commands render a.png. The third command prints a usage message.

**Comment by otfried** [comment]
Resolution must be specified before transparency.
