### ISSUE TITLE
Impossible to change option values (grid size and font size, etc.) from various menus

### ISSUE THREAD

**Issue by lmorel-insa** [otfried/ipe#186]
Dear ipe maintainers, 
I've recently installed ipe 7.2.7-3 through apt (debian 9/stretch). Installation went through perfectly.  

```apt-cache show ipe 
Package: ipe
Version: 7.2.7-3
Installed-Size: 6784
Maintainer: Debian Science Team <debian-science-maintainers@lists.alioth.debian.org>
Architecture: amd64
Depends: libc6 (>= 2.14), libcairo2 (>= 1.2.4), libgcc1 (>= 1:3.0), libipe7.2.7, liblua5.3-0, libqt5core5a (>= 5.9.0~beta), libqt5gui5 (>= 5.3.0), libqt5widgets5 (>= 5.7.0), libstdc++6 (>= 4.1.1), zlib1g (>= 1:1.1.4), texlive-latex-base, gsfonts, xdg-utils
```
 
When trying to use some of the drop menus, options appear to be missing. 
Most obvious examples are :  
- grid size (bug-ipe-1, bug-ipe-2)
- latex font size (bug-ipe-3) 
- color (bug-ipe-4)
- ...

I found no mention of a feature/bug resembling this behavior, but I might have missed it. If so, I apologize and will happily receive a link to such an answer in reply :)

In the meanwhile, the tool is still usable, doesn't show any other sign of misbehavior (no warning) but is rendered of course much less flexible.

 

bug-ipe-1: 
![bug-ipe-1](https://user-images.githubusercontent.com/6606156/40498343-15a91266-5f7f-11e8-8fbc-a04585cffad5.png)

bug-ipe-2: 
![bug-ipe-2](https://user-images.githubusercontent.com/6606156/40498342-1577500a-5f7f-11e8-944e-54c6b1fa1fb7.png)

bug-ipe-3:
![bug-ipe-3](https://user-images.githubusercontent.com/6606156/40498341-15438770-5f7f-11e8-9e7c-97621f50c3f1.png)

bug-ipe-4
![bug-ipe-4](https://user-images.githubusercontent.com/6606156/40498340-15110296-5f7f-11e8-89dd-b22b511fda24.png)

**Comment by otfried** [comment]
This is the effect you would get when your Ipe document does not contain a style sheet.  (The attributes offered in the UI come from the style sheet.)

Do you get the same problem when you start Ipe without an existing document?

Check under Edit -> Style sheets if it shows the "basic" style sheet.

**Comment by lmorel-insa** [comment]
First of all, I'm very sorry for letting your answer hang on for so long. 

I was unaware of this "feature" and I'm actually not very used to these stylesheets in IPE. 
When editing some of my documents, I found no "basic" style sheet in the Edit > Style sheets menu indeed. 
But I could add it from the default IPE style sheets location. On my system this is: 

`/usr/share/ipe/7.2.7/styles`

This solves my problem. 
Many thanks, both for your answer and for bringing IPE to us all!
Regards
