### ISSUE TITLE
Per-page commands

### ISSUE THREAD

**Issue by mrzv** [otfried/ipe#188]
It would be nice if it was possible to record Latex preamble commands for each page separately. It would make it much easier to copy-paste pages between presentations.

**Comment by otfried** [comment]
This looks very tricky.   I would need separate Latex runs for each page.

**Comment by mrzv** [comment]
I'm not sure I'm following. Why is that a bad/tricky thing?

**Comment by otfried** [comment]
I think I misunderstood this ticket.   You simply want each page to possibly carry preamble commands, and when Latex is run, Ipe would simply concatenate the commands from all pages to form the actual preamble?

**Comment by mrzv** [comment]
No, I think I want it the other way around. I want pages compiled individually, where the commands they have are the global preamble commands, plus their local commands. I imagine having the same command repeated on many pages.

The point is that I want to make it easy to copy pages between presentations, something that's quite painful right now. This would be a step towards that.

**Comment by otfried** [comment]
Compiling pages separately is not an option.   One issue is that it would be super-slow - so I would have to add logic to only recompile the pages that could possibly have changed after some action, and most likely compiling in the background so the first page of a document would appear fast, but the main issue is that combining PDF resources from different PDF files would be much harder than taking them from a single file. (For instance, you would have multiple copies of the same font but with different character subsets - how do you merge these?)

**Comment by mrzv** [comment]
I see. Then I suppose it's possible to make it work the way you suggest: concatenating all the commands. Actually, is it possible, instead of concatenated in the beginning, to paste commands before the page content? Then I'd use something like `\providecommand` to define the commands I care about locally. If there was something I could provide post-page, I could also undefine the commands, although it's probably more work than necessary. This would work well with sequences of slides. I'd `\providecommand`s on the first slide for the entire sequence, and I wouldn't have to worry about the preamble.

It would require the user to be more careful than what I had in mind, but I suppose that's the general spirit of Ipe.

**Comment by otfried** [comment]
Merged with #258
