### ISSUE TITLE
Can not export to an SVG file with iperender

### ISSUE THREAD

**Issue by GoBigorGoHome** [otfried/ipe#189]
The Ipe manual page about the command line utility [iperender](http://ipe.otfried.org/manual/manual_53.html) contains an example of how to convert a page of a .pdf  file into a .png file using iperender. Following this example, I tried to convert a .ipe file `level-graph.ipe` into `level-graph.svg` with 
`iperender -svg level-graph.ipe level-graph.svg`
and the output indicated that iperender does not identify the option `-svg` (it only knows `-png` and `-eps`), so I tried again with 
`iperender -eps level-graph.ipe level-graph.svg`
but the generated .svg file cannot be rendered properly in Chrome.

So, I am wondering the right way to do this.

**Comment by otfried** [comment]
If you use the -eps option, then of course the exported file will be in EPS format, no matter what file extension you give on the command line.

The Windows binaries provided for Ipe do not contain SVG support in the Cairo library.  I'll fix this in the next release.

**Comment by otfried** [comment]
See #130
