### ISSUE TITLE
Problem with HighSierra 

### ISSUE THREAD

**Issue by AntonioDEM** [otfried/ipe#190]
**when I try to insert a formula or a text : \alpha  or $\alpha$**

This is pdfTeX, Version 3.14159265-2.6-1.40.19 (TeX Live 2018) (preloaded format=pdflatex 2018.7.18)  24 JUL 2018 12:57
entering extended mode
 restricted \write18 enabled.
 %&-line parsing enabled.
**ipetemp.tex
(./ipetemp.tex
LaTeX2e <2018-04-01> patch level 2
Babel <3.18> and hyphenation patterns for 84 language(s) loaded.

(/usr/local/texlive/2018/texmf-dist/tex/latex/base/article.cls
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
(/usr/local/texlive/2018/texmf-dist/tex/latex/base/size10.clo
File: size10.clo 2014/09/29 v1.4h Standard LaTeX file (size option)
)
\c@part=\count80
\c@section=\count81
\c@subsection=\count82
\c@subsubsection=\count83
\c@paragraph=\count84
\c@subparagraph=\count85
\c@figure=\count86
\c@table=\count87
\abovecaptionskip=\skip41
\belowcaptionskip=\skip42
\bibindent=\dimen102
)
(/usr/local/texlive/2018/texmf-dist/tex/latex/xcolor/xcolor.sty
Package: xcolor 2016/05/11 v2.12 LaTeX color extensions (UK)

(/usr/local/texlive/2018/texmf-dist/tex/latex/graphics-cfg/color.cfg
File: color.cfg 2016/01/02 v1.6 sample color configuration
)
Package xcolor Info: Driver file: pdftex.def on input line 225.

(/usr/local/texlive/2018/texmf-dist/tex/latex/graphics-def/pdftex.def
File: pdftex.def 2018/01/08 v1.0l Graphics/color driver for pdftex
)
Package xcolor Info: Model `cmy' substituted by `cmy0' on input line 1348.
Package xcolor Info: Model `hsb' substituted by `rgb' on input line 1352.
Package xcolor Info: Model `RGB' extended on input line 1364.
Package xcolor Info: Model `HTML' substituted by `rgb' on input line 1366.
Package xcolor Info: Model `Hsb' substituted by `hsb' on input line 1367.
Package xcolor Info: Model `tHsb' substituted by `hsb' on input line 1368.
Package xcolor Info: Model `HSB' substituted by `hsb' on input line 1369.
Package xcolor Info: Model `Gray' substituted by `gray' on input line 1370.
Package xcolor Info: Model `wave' substituted by `hsb' on input line 1371.
)
\ipefs=\dimen103
\c@ipePage=\count88
\c@ipeView=\count89
\c@ipePages=\count90
\c@ipeViews=\count91
\bigpoint=\count92

(./ipetemp.aux)
\openout1 = `ipetemp.aux'.

LaTeX Font Info:    Checking defaults for OML/cmm/m/it on input line 47.
LaTeX Font Info:    ... okay on input line 47.
LaTeX Font Info:    Checking defaults for T1/cmr/m/n on input line 47.
LaTeX Font Info:    ... okay on input line 47.
LaTeX Font Info:    Checking defaults for OT1/cmr/m/n on input line 47.
LaTeX Font Info:    ... okay on input line 47.
LaTeX Font Info:    Checking defaults for OMS/cmsy/m/n on input line 47.
LaTeX Font Info:    ... okay on input line 47.
LaTeX Font Info:    Checking defaults for OMX/cmex/m/n on input line 47.
LaTeX Font Info:    ... okay on input line 47.
LaTeX Font Info:    Checking defaults for U/cmr/m/n on input line 47.
LaTeX Font Info:    ... okay on input line 47.

(/usr/local/texlive/2018/texmf-dist/tex/context/base/mkii/supp-pdf.mkii
[Loading MPS to PDF converter (version 2006.09.02).]
\scratchcounter=\count93
\scratchdimen=\dimen104
\scratchbox=\box26
\nofMPsegments=\count94
\nofMParguments=\count95
\everyMPshowfont=\toks14
\MPscratchCnt=\count96
\MPscratchDim=\dimen105
\MPnumerator=\count97
\makeMPintoPDFobject=\count98
\everyMPtoPDFconversion=\toks15
)
! Missing $ inserted.
<inserted text> 
                $
l.51 \alpha
           
I've inserted a begin-math/end-math symbol since I think
you left one out. Proceed, with fingers crossed.

LaTeX Font Info:    External font `cmex10' loaded for size
(Font)              <7> on input line 51.
LaTeX Font Info:    External font `cmex10' loaded for size
(Font)              <5> on input line 51.
! Extra }, or forgotten $.
l.53 \iperesetcolor}
                    
I've deleted a group-closing symbol because it seems to be
spurious, as in `$x}$'. But perhaps the } is legitimate and
you forgot something else, as in `\hbox{$x}'. In such cases
the way to recover is to insert both the forgotten and the
deleted material, e.g., by typing `I$}'.

! pdfTeX error (ext1): \pdfxform cannot be used with a void box.
<to be read again> 
                   \unskip 
l.55 ...unt0}0\put(0,0){\pdfrefxform\pdflastxform}
                                                  

 
Here is how much of TeX's memory you used:
 1165 strings out of 492649
 13948 string characters out of 6129622
 76496 words of memory out of 5000000
 5120 multiletter control sequences out of 15000+600000
 3640 words of font info for 14 fonts, out of 8000000 for 9000
 1141 hyphenation exceptions out of 8191
 23i,3n,35p,165b,115s stack positions out of 5000i,500n,10000p,200000b,80000s
!  ==> Fatal error occurred, no output PDF file produced!

**Comment by otfried** [comment]
Can you attach an Ipe document where this happens?

**Comment by otfried** [comment]
I have now installed Texlive 2018 on my Mac - it reports the exact same version that you are using.  
Could you attach an Ipe file that exposes the problem?
