### ISSUE TITLE
More trouble with joining paths

### ISSUE THREAD

**Issue by boris-aronov** [otfried/ipe#191]
Have a collection of paths that I am trying to join into one closed path, which I want to fill, assign some transparency too, etc etc... [one may dream...]  Worked in a simpler example, but for this collection I seem to be unable to join them, even in pairs.  Get the dreaded "Unable to join paths to a single curve" [I believe "into a single curve would have been more correct, but... :-) ]

Help! :-)  The attached is a stripped-down version, hopefully only with the curves I am interested in.  7.2.7 on MacOS 10.11.6.

[ipe-trouble.pdf](https://github.com/otfried/ipe-issues/files/2225045/ipe-trouble.pdf)

**Comment by otfried** [comment]
In your Ipe's Lua directory there is a file **editpath.lua**.   It contains this line:

```
local join_threshold = 1e-9
```

Apparently this is too much to ask for in many situations.   I will make it a preference, but for the moment you can join your paths by changing it to 1e-6.

**Comment by otfried** [comment]
Preference `prefs.join_threshold` added in 7.2.8.  The default value is now 1e-6.
