### ISSUE TITLE
Different grid types

### ISSUE THREAD

**Issue by jonasc** [otfried/ipe#198]
For some figures I want to have a hexagonal or triangular grid, e.g., for circle packings or similar. Since I did not find any possibility to have a different grid I helped myself by creating the grid out of triangles or lines on a locked layer.
However, I was wondering whether and how it would be possible to implement different grid into ipe itself or via ipelets. If it is possible I'd try to implement it.

Thanks in advance for the input.

**Comment by otfried** [comment]
No, it's not possible to add grids via ipelets, because snapping to the grid happens deep inside Ipe and needs to be very fast to be usable.

You could easily write an ipelet that creates a nice grid pattern and stores it in a layer like you do.  Perhaps this could be made more comfortable, see e.g. #112

**Comment by otfried** [comment]
Here is an ipelet that creates a triangular grid:

[gridmaker.lua.zip](https://github.com/otfried/ipe-issues/files/4536394/gridmaker.lua.zip)

With the new version Ipe 7.2.15, you can place this is a fresh layer, and turn on "always" snapping for that layer - then you can snap even when the grid is not visible.

![image](https://user-images.githubusercontent.com/9983417/80318592-7bb99880-880b-11ea-8241-79f38bbc56e6.png)

Would something like this satisfy your needs?

There are number of small things we could do to make this more comfortable.  For instance, when a layer named "GRID" exists, then grid snapping could mean to turn on intersection snapping for objects inside this layer (so we would snap to intersections between grid lines, but not for intersections between grid lines and other objects).

**Comment by jonasc** [comment]
This solution with 7.2.15 is already great and serves my purpose perfectly – thanks a lot for implementing it!

Your proposal for the GRID layer sounds really nice, too. One problem I see is whether the grid snapping then also still works for the "normal" grid or whether a GRID layer deactivates the normal grid. Or maybe it is only active for grid snapping if it is visible?
I think that sometimes you'd want to have both the normal and some special grid so I feel that there should be some kind of coexistence.

**Comment by otfried** [comment]
Good point - sometimes you may want to switch between the standard grid and your custom grid.

I think I'll just add one more snapping mode ("Custom grid") that will snap to intersections between objects in the "GRID" layer.

**Comment by otfried** [comment]
Custom grid snap mode implemented in 7.2.16.
