### ISSUE TITLE
Ending group edit also unlocks previously locked layers

### ISSUE THREAD

**Issue by jonasc** [otfried/ipe#199]
This happens with the current Ipe version 7.2.7.

How to reproduce:
1. Start with a new ipe file.
2. Create new layer "beta".
3. Lock beta.
4. Insert two objects to currently active layer alpha.
5. Group objects.
6. Go into the "Edit group" mode.
7. Exit "Edit group" mode.

Expected behaviour: Layer "beta" should still be locked.
Actual behaviour: Layer "beta" is unlocked.

**Comment by otfried** [comment]
Fixed in 7.2.16.
