### ISSUE TITLE
support for *.png files with 8bit colours

### ISSUE THREAD

**Issue by jenshenriknielsen** [otfried/ipe#20]
Hi,

When I try to include a PNG image with reduced no. of colors IPE chrashes. I've been able to du this in previous versions but not in the newest. I can import full color png images, however, the filesize seems to increase dramatically (including a 235kb png yields a 23.8MB ipe file (or 17.7MB pdf).

best regards,
Jens

**Comment by otfried** [comment]
Could you attach (or send me) such a PNG with reduced no of colors that causes Ipe to crash?

I see what the problem is with the full color image: Ipe no longer automatically compresses the bitmap.

**Comment by jenshenriknielsen** [comment]
![test_png](https://cloud.githubusercontent.com/assets/13219877/10638826/2ed5185e-780d-11e5-852a-7b20d5caf662.png)
Sure, I’ve tried to attach it.

**Comment by otfried** [comment]
Fixed in 7.1.9.

**Comment by otfried** [comment]
Transparency in this PNG now also works in 7.1.9.
