### ISSUE TITLE
Remove unused header

### ISSUE THREAD

**Issue by 0-wiz-0** [otfried/ipe#201]
ipelib/ipeplatform.cpp includes the `xlocale.h` header that does not exist on NetBSD.
Removing the header has no obvious sideeffects. Please either remove it or make it conditional on the systems that need it.

Suggested patch:
````
--- ipelib/ipeplatform.cpp.orig 2016-12-09 14:09:04.000000000 +0000
+++ ipelib/ipeplatform.cpp
@@ -38,7 +38,6 @@
 #include <gdiplus.h>
 #else
 #include <sys/wait.h>
-#include <xlocale.h>
 #include <dirent.h>
 #endif
 #ifdef __APPLE__
````

**Comment by otfried** [comment]
Implemented in 7.2.8.
