### ISSUE TITLE
documentation of minimum Mac OS version for Ipe 7.2.8

### ISSUE THREAD

**Issue by nathaniel** [otfried/ipe#202]
news.txt says for Ipe 7.2.8:
 * OSX binaries now require at least OSX 10.10 (Yosemite) and are
   built on Mojave.
readme.txt included in ipe-7.2.8-mac.dmg says:
   This is a binary distribution for Mac OS 10.8 or higher.

Looks like readme.txt needs to be updated.

**Comment by otfried** [comment]
Already fixed in git  - right after uploading the package :-(
