### ISSUE TITLE
allow relative drive path for environment variables and file/dir settings

### ISSUE THREAD

**Issue by nathaniel** [otfried/ipe#203]
When running Ipe from a USB drive on Windows, one does not choose the drive letter for the USB drive; rather, Windows does. Yet one might want to refer in the configuration (ipe.conf and customize.lua) to other directories and files located on the same USB drive, in settings like
prefs.save_as_directory
prefs.autosave_filename
IPELATEXPATH
IPELATEXDIR
IPESTYLES
IPELETPATH

However, I don't believe there is a way to specify the drive in relative fashion, such as "same drive letter that ipe.exe was launched from." I tried setting these without specifying directory, like
`prefs.autosave_filename = "\\ipe-settings\\autosave\\%s-autosave.ipe"`
and
`IPELATEXDIR=\ipe-settings\latexrun`

... but I find that Ipe is looking for the directory \ipe-settings\latexrun at the root of _whichever drive the currently-edited file was last saved to_. Thus, depending on the location of my Ipe file, I may get an error about not being able to find or create the directory for the Pdflatex file.

When viewing Help-->Show Configuration:
Unlike my custom directories, the default directory locations set automatically by Ipe do have the correct drive letter included, so I see for example:
* Ipelets:
  - \ipe-settings\ipelets
  - D:\ipe-7.2.8\ipelets

In order to really run Ipe in self-contained (portable) fashion from a USB drive, one needs to be able to refer to other files on the same drive.

**Comment by otfried** [comment]
In 7.2.9, you can use `config.ipedrive` to refer to the drive letter that Ipe is on in customization files, e.g. 
``` 
prefs.autosave_filename = config.ipedrive .. "\\ipe-settings\\autosave\\%s-autosave.ipe"
```
In environment variables, the string "ipe:" will be replaced by the same drive letter.
