### ISSUE TITLE
pdf table of contents incorrect when using ipetoipe -markedview

### ISSUE THREAD

**Issue by saschawolff** [otfried/ipe#205]
Dear Otfried,

thanks for putting your time into ipe!
I have the following small problem with ipetoipe. 

When I untick the little box "mark page" and then call ipetoipe -markedview I get (as expected) a pdf without the page that I unticked -- but the table of contents in the pdf still lists all pages, see the attached examples. It would be nice if the unticked pages would disappear from the table of contents.

Thanks.

Sascha

[ipe-test.pdf](https://github.com/otfried/ipe-issues/files/2751303/ipe-test.pdf)
[ipe-test-markedview.pdf](https://github.com/otfried/ipe-issues/files/2751304/ipe-test-markedview.pdf)

**Comment by otfried** [comment]
Fixed in 7.2.9.
