### ISSUE TITLE
Mouse wheel zoom not working in 7.2.8

### ISSUE THREAD

**Issue by christiankral** [otfried/ipe#206]
In version 7.2.7 one could zoom in/out using the mouse wheel. After upgrading to Ipe 7.2.8 I noticed that the mouse wheel is now used for panning. Even though I like this feature it were really greate to have zoom in/out by additionally pressing the CTRL key, as zooming is very practical during the creation of drawings.

Possibly this issue is related with the changes introduced by #91. 

I issue reporting refers to Linux Mint 19, 64bit.

**Comment by otfried** [comment]
As the release notes (and the announcement of the new version) say, you can switch back to the old behaviour by setting the preference prefs.scroll.pan = false

Control + scroll-wheel for zooming already works on Windows, I will add this also for Linux and OSX in the next version.

**Comment by otfried** [comment]
Implemented for Qt in 7.2.9.

**Comment by otfried** [comment]
Also for OSX in 7.2.9.
