### ISSUE TITLE
Dark mode on Mac

### ISSUE THREAD

**Issue by taxipomme** [otfried/ipe#207]
When Mac OS in on dark mode, then when one edits a math text then the original text appears written black on dark gray (almost impossible to read); however, when typing to edit, the new characters are written white, which is ok.
<img width="414" alt="capture d ecran 2019-01-15 a 10 51 37" src="https://user-images.githubusercontent.com/12033275/51172511-a81a0180-18b3-11e9-8088-15afea723bda.png">

**Comment by otfried** [comment]
I have fixed this and a few other similar issues in 7.2.9.

It's quite possible there are other problems in dark mode, please report them here.

One should also redo all the icons for dark mode - but that's a lot of work and will have to wait.
