### ISSUE TITLE
ipe is not implemented in Windows 10

### ISSUE THREAD

**Issue by DongJickMin** [otfried/ipe#209]
I upgraded the OS from Windows 7 to Windows 10
After OS upgrade is finished, the IPE is not implemented.
Any windows and error logs are not displayed.
I tried to implement both 7.2.7 & 7.2.9 
But both versions are not implemented.

What is the problem and how to resolve the problem?

**Comment by otfried** [comment]
What does "I tried to implement both 7.2.7 & 7.2.9" mean?

You need to download https://dl.bintray.com/otfried/generic/ipe/7.2/ipe-7.2.9-win32.zip
Store it on your desktop, and right click on it.   Select "Extract" and extract it somewhere (e.g. to your desktop).  

Then enter the ipe-7.2.9 folder, then the bin folder, then double-click on ipe.exe.

**Comment by DongJickMin** [comment]
I tried to download and run ipe7.2.9.
However, double clicking to run ipe does nothing.
No error log or window appears.
In Windows7, it works normally but it does not work in Windows10.
How can we solve it?

**Comment by DongJickMin** [comment]
> What does "I tried to implement both 7.2.7 & 7.2.9" mean?
> 
> You need to download https://dl.bintray.com/otfried/generic/ipe/7.2/ipe-7.2.9-win32.zip
> Store it on your desktop, and right click on it. Select "Extract" and extract it somewhere (e.g. to your desktop).
> 
> Then enter the ipe-7.2.9 folder, then the bin folder, then double-click on ipe.exe.
