### ISSUE TITLE
ipe hangs when opening saved file with text

### ISSUE THREAD

**Issue by anirudh-d** [otfried/ipe#21]
If I save a file with text in it and try to reopen it, it hangs and the CPU usage goes to 99%.
It started on Mac Yosemite OS and upgrading to El Capitan did not help.
ipe version - 7.1.7
I use MacTex - 2015
Other people in their systems can open the saved file I sent without any trouble.

**Comment by otfried** [comment]
Could you attach the file here?  Or does it happen with any file with text in it?

Try to turn off "Automatically run Latex" (in the File menu) before you reopen the file.

Have a look in your Latex directory (normally .ipe/latexrun, but check in Ipe -> Help -> Show configuration).  There should be a file "ipetemp.tex" there.  Try running pdlatex directly on this file - does it run through without error?

**Comment by anirudh-d** [comment]
Thanks for responding so fast.

It happens with any file with text in it.

I tried turning off "Automatically run Latex" before reopening the file but it did not help.

"ipetemp.tex" runs without error.

**Comment by otfried** [comment]
Can you attach a file that you saved from Ipe and that it cannot reopen?  I'd like to see if there is something strange.

Also, please try one  of the command line tools:  Save as "test.ipe" from Ipe, and then try running "ipetoipe -pdf test.ipe".  Does this also hang, or does it run through and produce a file "test.pdf" that you can open.

Finally, how did you install Ipe?  Did you compile yourself, with macports, or use the Mac binary version?  

Did you try the newest Mac binary (http://github.com/otfried/ipe/raw/master/releases/7.1/ipe-7.1.8-mac.dmg)?

**Comment by anirudh-d** [comment]
I installed the newest Mac binary right now and it did not help.

I used the Mac binary version.

I can not attach PDF files because it says I need write permission to this repository in order to do that.

> Also, please try one of the command line tools: Save as "test.ipe" from Ipe, and then try running >"ipetoipe -pdf test.ipe". Does this also hang, or does it run through and produce a file "test.pdf" that you >can open.

I get the error that 'ipetoipe' is not a valid command. Am I doing something wrong here?

**Comment by otfried** [comment]
You probably need to go into the directory that contains the Ipe binaries:

```
cd /Applications/Ipe.app/Contents/Resources/local/bin
ipetoipe -pdf path_to/test.ipe
```

You'd have to put the entire path to the test.ipe file that you just saved.

**Comment by anirudh-d** [comment]
Also, please try one of the command line tools: Save as "test.ipe" from Ipe, and then try running "ipetoipe -pdf test.ipe". Does this also hang, or does it run through and produce a file "test.pdf" that you can open.

It produces a file "test.pdf"

**Comment by otfried** [comment]
Please try running Ipe with debugging enabled, by setting the environment variable IPEDEBUG to 1.
From the command line, this might work (depending on your shell):

export IPEDEBUG=1
/Applications/Ipe.app/Contents/MacOS/ipe

Also try if ipeview can open the file (it's in the same bin directory as ipetoipe).

**Comment by anirudh-d** [comment]
> Please try running Ipe with debugging enabled, by setting the environment variable IPEDEBUG to 1.
> From the command line, this might work (depending on your shell):
> 
> export IPEDEBUG=1
> /Applications/Ipe.app/Contents/MacOS/ipe

The shell does not show any error logs, it just hangs when I try to open a file with text in it.

> Also try if ipeview can open the file (it's in the same bin directory as ipetoipe).

ipeview can open the file.

**Comment by otfried** [comment]
You get no output at all, not even "action open" when you press Ctrl+O to open the file?

Can you check whether running a Lua script works, for instance

```
ipescript update-styles test.ipe
```

**Comment by anirudh-d** [comment]
> You get no output at all, not even "action open" when you press Ctrl+O to open the file?

Not even "action open". I just get the following if I force quit ipe: /Applications/Ipe.app/Contents/MacOS/ipe: line 16: 19584 Terminated: 15          ./ipe

> Can you check whether running a Lua script works, for instance

Yes, Lua script works, I get the following output:

Updating styles in figure '/path_to/test.ipe'
- stylesheet 'basic'
   updating from '../../local/share/ipe/7.1.8/styles/basic.isy'
- standard stylesheet

**Comment by otfried** [comment]
Could you try the new release 7.1.10 and see if it changes anything?

**Comment by anirudh-d** [comment]
It is working now. Thank you very much!
