### ISSUE TITLE
Oposite direction scroll

### ISSUE THREAD

**Issue by hildogjr** [otfried/ipe#210]
On Ubuntu 16.04 Ipe is using the mouse scroll / pad scroll in the opposite direction.
When I scroll down (pulling the top part of the wheel to me) all the software makes the pages go up. But Ipe does the opposite.
This in version 7.2.9

**Comment by otfried** [comment]
Since Apple introduced "natural scrolling",  many systems changed the way the scroll direction works - or let the user decide.   On Mint 19, for instance, it's the setting "Reverse scrolling direction" in Settings -> Mouse and Touchpad.

Ipe also lets you decide: Set prefs.scroll.vertical_sign to 1 or -1 to achieve the effect you want.

**Comment by hildogjr** [comment]
@otfried where is this configuration on Ipe?
Ubuntu also have this configuration. I prefer not to change the OS preference since this has impact in the full system (the software that was non-opposite, in my vision, can became).
Yes, I release that this is because the "natural scrolling" of Mac, I reported the same issue on [KiCad software] (https://bugs.launchpad.net/kicad/). Since KiCad hasn't the option in it on-self the developers had to change on Linux compilation.

**Comment by otfried** [comment]
See http://ipe.otfried.org/manual/manual_39.html

**Comment by hildogjr** [comment]
I change the `prefs.scroll.vertical_sign = 1` to `prefs.scroll.vertical_sign = -1` and this fix the behavior on horizontal scroll. But \<Alt>+ \<Scroll> still opposite.

Is there some configuration to  `prefs.scroll.horizontal_sign`?

**Comment by otfried** [comment]
I didn't even know that Alt+Scroll wheel does a horizontal scroll.

I'll add a setting for the horizontal scroll direction in the next release.  It will be 
prefs.scroll.direction.x (and the vertical direction becomes prefs.scroll.direction.y).
