### ISSUE TITLE
Label style confusingly changes from normal to math

### ISSUE THREAD

**Issue by Willem3141** [otfried/ipe#211]
I made a label with text `$k$~blocks of size~$\epsilon$`. I then wanted to duplicate the label, so I copy-pasted it. The result was a label with style math, with text `k$~blocks of size~$\epsilon`. I think this is confusing.

Probably this normal-to-math conversion should either not happen at all on copy-pasting, or it should at least only happen when the entire content of the label is in math mode?

**Comment by otfried** [comment]
Fixed in 7.2.10.
