### ISSUE TITLE
producing a PDF without comments

### ISSUE THREAD

**Issue by pierreganty** [otfried/ipe#215]
I love the new feature exporting notes as pdf comments (it worked like a charm together with the Presentation.app on OSX).
However I am not sure how to distribute my slides without the comments.
Usually i use the "-export" switch of ipetoipe to generate a clean PDF but the resulting PDF includes the comments.
I've read about some solutions to remove the comments using pdftk but it seems overly complicated (https://stackoverflow.com/q/49598797/5486404).
On OSX it is not trivial to get pdftk installed (not part of homebrew AFAIK).

**Comment by pierreganty** [comment]
As a workaround you can delete the notes from the xml (.ipe) file before generating the PDF using xmlstarlet:
`xml ed --inplace -d /ipe/page/notes <file>.ipe`

**Comment by otfried** [comment]
I guess it makes sense that "-export" in ipetoipe does not include the page notes.

Should we have an extra option "-keep-notes" for the case where you want to export but still want to keep the notes?

**Comment by pierreganty** [comment]
Sounds like a good plan.

**Comment by otfried** [comment]
In 7.2.11.
