### ISSUE TITLE
Export as picture

### ISSUE THREAD

**Issue by DaLundi** [otfried/ipe#22]
Ipe is a very useful tool, but how about an export to our save to picture function? With formats like .png or similar

**Comment by otfried** [comment]
Have a look at iperender - it does exactly this, and is included in every Ipe installation:

http://ipe.otfried.org/manual/manual_48.html

**Comment by DaLundi** [comment]
But it would be nice, if that that tool gets an entry in the normal ipe Editor, in the "File" menu below "save as"

**Comment by otfried** [comment]
A function that has many options and needs no user interaction is much more efficiently used as a command line tool.

**Comment by otfried** [comment]
Added in 7.1.10.
