### ISSUE TITLE
Copied and pasted text between differente IPE instances is not rendered correctly 

### ISSUE THREAD

**Issue by christiankral** [otfried/ipe#224]
This issue may be related with #223. 

Consider the following example. Open two instances of IPE:

Instance 1
- Create new *Mathematical symbols* 
- Enter text `A_1` 
- The text is shown and rendered correctly 
![image](https://user-images.githubusercontent.com/4184218/53352306-d7944300-3922-11e9-84ab-fdea2dc7021d.png)
- Select text
- Hit CTRL+C to copy it the clipboard

Instance 2
- Hit CTRL+V to paste the mathematical symbols
- Select location and make a left mouse click
- The mathematical symbols are not rendered correctly; instead `A_1` is displayed 
![image](https://user-images.githubusercontent.com/4184218/53352398-fc88b600-3922-11e9-84c9-64fec31f0b6a.png)
- When saving and re-opening the mathematical symbols everything is rendered correctly

**Note 1:** I am using a LaTeX preamble in my style sheet 
```
<preamble>\usepackage{fourier,inconsolata}</preamble>
```

**Note 2:** The same happens with regular *Text labels* which are not rendered either

This issue applies to IPE 7.2.10 under Linux Mint 19, 64bit (based on Ubuntu 18.04).

**Comment by otfried** [comment]
See #223: Just press Ctrl+L.
