### ISSUE TITLE
Ipe 7.2.11 (preview): no Mac touch bar support?

### ISSUE THREAD

**Issue by nathaniel** [otfried/ipe#227]
Otfried, although you said the 7.2.11 preview has Touch Bar support, my touch bar Macbook Pro shows no app-specific buttons when Ipe is the active application. If I switch to TextEdit or Safari, I see the expected buttons for those apps.

**Comment by otfried** [comment]
Which OSX version are you running?

**Comment by nathaniel** [comment]
Good question -- I am a little behind the latest Mac OS. I am running
10.12.6

**Comment by otfried** [comment]
I have tested with the simulator on 10.14, so perhaps that is the difference.   That doesn't explain why it shouldn't work, though.   Perhaps I can insert a few NSLog statements to check if makeTouchBar is ever called.

**Comment by otfried** [comment]
If you have a chance to try `ipe-7.2.11b-mac.dmg` (on dropbox in the same folder), could you send me the output you get when starting Ipe from the command line?

**Comment by otfried** [comment]
Could you try `ipe-7.2.11c-mac.dmg` in the same dropbox folder?   

https://www.dropbox.com/sh/my4cj84i9a1tihr/AABEsk1dDaBaxrFWPt1kidLpa?dl=0

**Comment by nathaniel** [comment]
Otfried, the touchbar buttons are now visible! (7.2.11c)

One issue is that the black-on-dark-gray of the (unselected) snapping modes
buttons is hard to see on the touchbar, see attachment. (Sorry I didn't
ever try your earlier request.)

[image: 2019-03-06 08.01.29.jpg]

**Comment by otfried** [comment]
See #226 : we need improved icons anyway.

I'm a lousy graphics artist myself, so this will depend on someone else's contribution.
