### ISSUE TITLE
Page feed key in IpePresenter

### ISSUE THREAD

**Issue by MasahiroMae** [otfried/ipe#228]
We cannot feed page to next view or previous view with down or up key. In the common laser pointers with page feed function, the page feeding key is assigned to up and down key, not right and left key. Therefore, we cannot feed pages with these laser pointers in IpePresenter. Please add the down and up keys to next view and previous view commands.

Additionally, it is also a big issue that IpePresenter does not have a page jump function when the slide is too many. Please add a page jump function. (e.g. [g]+"number"->Go to page "number")

**Comment by otfried** [comment]
On my laser pointer, I use the left and right mouse button to move to the next and previous page.

I will also add the up/down key as alternatives for moving between views.

A page jump function and a page selector are already on my todo list.

**Comment by otfried** [comment]
Implemented in 7.2.11.
