### ISSUE TITLE
Update Mac .dmg background image to match icon

### ISSUE THREAD

**Issue by nathaniel** [otfried/ipe#232]
Hi Otfried,
Every time I open the .dmg disk image for a new version of Ipe, I realize I made the "I" in the Ipe logo backward in the .dmg background image, compared to the icon! Here is a screenshot showing the mismatch:
![mismatch](https://user-images.githubusercontent.com/68211/54060619-0f24aa00-41c3-11e9-9179-44ef3c05d075.png)

I made a corrected version of this image a few years ago, but I think I never sent that to you. here it is!
![ipe-dmg-background](https://user-images.githubusercontent.com/68211/54060654-282d5b00-41c3-11e9-9074-2d2109c7b1ba.png)

When you have a chance, consider swapping this fixed image in the .background folder of the disk image. Thanks!

**Comment by otfried** [comment]
Changed in 7.2.11.  Thanks!
