### ISSUE TITLE
Add Export to SVG option

### ISSUE THREAD

**Issue by Willem3141** [otfried/ipe#234]
It would be really useful to have an Export to SVG option in the File menu, as executing `iperender -svg` from the terminal every time is a bit inconvenient. (I export many images to SVG to be able to insert them into PowerPoint presentations.)

Note: I managed to get this working myself by copying and adapting the Lua code for `export_eps` to make a new action `export_svg` and adding this as a menu item. That seems to work fine, but may not be the cleanest way to do this (code duplication).

**Comment by otfried** [comment]
Added export_svg in 7.2.12.
