### ISSUE TITLE
Allow preferences to specify initial selection of attribute values in the UI

### ISSUE THREAD

**Issue by hildogjr** [otfried/ipe#235]
Pressing <Alt> we can use access (use) the horizontal scroll by the mouse wheel.
On Ubuntu 16 - Ipe 7.2.11 this direction is opposite of the other software. The vertical scroll and zooms have them direction just fine.

**Comment by otfried** [comment]
Just set
```
prefs.scroll.direction.x = -1
```
in your customization.

**Comment by hildogjr** [comment]
Perfect.
Should this be added by default after line 259?

**Comment by hildogjr** [comment]
I also can edit the default `prefs.grid_size` there. By can I edit the default "Pen width"?

**Comment by otfried** [comment]
No, because pen widths are defined in a style sheet.

Make your own style sheet where you define pen width "normal" to mean whatever you want, then make this the default style sheet by setting
```
prefs.style = { "basic", "mystyle" }
```
("basic" is the standard style sheet.  You could of course completely replace it with your own definitions.)

**Comment by otfried** [comment]
By the way, the available grid sizes are also defined in the style sheet.   The prefs setting only determines which setting is selected when Ipe starts.

**Comment by hildogjr** [comment]
Understood and thanks by tips.
So, is it possible:

    prefs.pen_width = "hevier"
    prefs.arrow_size = "small"

?
The default style is been nice for my documents, therefore I just want to change these 2 startup configurations.

**Comment by otfried** [comment]
It's not currently possible, but it's a good idea, I will implement something like this for the next version.

In the meantime, you can open the file `model.lua` and modify the definition of `self.attributes` (very close to the top of the file), e.g. like this:
```
  self.attributes = {
    pathmode = "stroked",
    stroke = "black",
    fill = "white",
    pen = "heavier",
    dashstyle = "normal",
    farrowshape = "arrow/normal(spx)",
    rarrowshape = "arrow/normal(spx)",
    farrowsize = "small",
    rarrowsize = "small",
    farrow = false,
    rarrow = false,
    symbolsize = "normal",
    textsize = "normal",
    textstyle = "normal",
    transformabletext = prefs.transformable_text,
    horizontalalignment = "left",
    verticalalignment = "baseline",
    pinned = "none",
    transformations = "affine",
    linejoin = "normal",
    linecap = "normal",
    fillrule = "normal",
    markshape = "mark/disk(sx)",
    tiling = "normal",
    gradient = "normal",
    opacity = "opaque", 
  }
```

**Comment by otfried** [comment]
Implemented in 7.2.12:

You can now set
```
prefs.initial_attributes.stroke = "darkblue"
prefs.initial_attributes.pen = "heavier"
```
in your preferences to determine Ipe's initial attribute settings in the UI.

**Comment by hildogjr** [comment]
It will be also possible to set the arrow default size? Or should I set this value at `farrowshape = "arrow/normal(spx)",` / `rarrowshape = "arrow/normal(spx)",` in `model.lua`.

**Comment by otfried** [comment]
```
prefs.initial_attributes.farrowsize = "large"
```
Just have a look at `prefs.lua` in the new version.

Here is a snapshot:
https://www.dropbox.com/sh/ct3bbdc6itjq659/AACyyTcVnt_0R7uOMn0IbJf7a?dl=0
