### ISSUE TITLE
Precisely select symbols

### ISSUE THREAD

**Issue by christiankral** [otfried/ipe#238]
Referring to the electrical engineering library in https://github.com/christiankral/ElectricalEngineering.isy I am asking the following question: Consider three symbols (two resistors, one disk marker) with the reference points show on the left in pic below; see https://gist.github.com/christiankral/134b9feb5603f159c6532039c7bcc0dd. 

![image](https://user-images.githubusercontent.com/4184218/55567406-e3331080-56fd-11e9-807f-78fc94b1eb53.png)

If I assemble the symbols to a circuit the three indicated reference points will end up on the very same place. My question is how a user can select one of the three symbols systematically, e.g., to move the vertical resistor...

Possibly the design of the components is wrong as all components shall rather have their reference points in the component center. So for the resistor the reference point could be moved from one line end to the center of the symbol -- this were a possible solution. @otfried Could you please comment on this.

**Comment by otfried** [comment]
Yes, trying to select a specific symbol among several at the same location will be difficult.

I suggest that you move this usability discussion to the Ipe discussion list, where other Ipe users can tell you how they do it and where we can come up with improvements to Ipe to make this easier.

**Comment by otfried** [comment]
- Snapping
- Selecting
- Display

Perhaps all triggered by the presence of a snap attribute in the symbol.

**Comment by otfried** [comment]
In Ipe 7.2.12, you can define snap positions for a symbol, like this:
```
<symbol name="Basic/Resistor horizontal" snap="0 0 32 0">
<group matrix="1 0 0 1 0 -16">
<path matrix="1 0 0 1 0 1.9" stroke="black">
8 16 m
8 12 l
24 12 l
24 16 l
h
</path>
<path stroke="black" cap="2">
0 16 m
8 16 l
</path>
<path stroke="black" cap="2">
24 16 m
32 16 l
</path>
</group>
</symbol>
```

When a symbol has the `snap` attribute, vertex snap will snap to those positions.  It will also be presented differently in selection mode (the entire symbol is outlined, like a group), and you can select it by clicking near any snap position (in this case, the two endpoints of the resistor).  Also, the drag-select mode works kind-of like for groups (it uses the bounding box of the snap points to detect if the object should be selected).

**Comment by otfried** [comment]
A snapshot for testing:

https://www.dropbox.com/sh/ct3bbdc6itjq659/AACyyTcVnt_0R7uOMn0IbJf7a?dl=0

**Comment by christiankral** [comment]
Thanks for implementing the snap attribute.

Is more than one snap also possible? For example, a transistor has three connectors. If yes, what is the syntax then?

**Comment by otfried** [comment]
If you look at the resistor example above, it has this line:
```
<symbol name="Basic/Resistor horizontal" snap="0 0 32 0">
```
This means there are *two* snap points, at (0,0) and at (32,0).   So you just list the x and y coordinates, one by one.  There is no limit on the number of snap points.

**Comment by christiankral** [comment]
Thanks for clarifying. Somehow I did not read the "0 0 ..." as the first snap point. I just could not see it. My fault.
