### ISSUE TITLE
IPE won't open on Ubuntu 18.04, 64 bit

### ISSUE THREAD

**Issue by InTheNight1** [otfried/ipe#239]
Hi,

I've used this software before on an older machine, but I cannot get it to work for the life of me on my new machine. I am running Ubuntu 18.04.2 LTS on a 64 bit machine. I tried downloading it from the software center, version 7.2.6 and it won't launch when I double click the icon. How do I fix this?

**Comment by otfried** [comment]
If you install Ipe through the Ubuntu package manager and it doesn't work, you really need to file an issue with Ubuntu - there is nothing we can do for you here.

Ipe 7.2.6 is ancient.  I recommend you use a recent version instead, by going to http://ipe.otfried.org, selecting "Download the current Ipe version", then "Linux binary packages", then downloading the two files for Ubuntu 18.04.   Make sure to complete erase the Ubuntu installation of Ipe using your package manager, then install the two files using `gdebi`.
