### ISSUE TITLE
Request for enhanced support for imperial sizes

### ISSUE THREAD

**Issue by ghali** [otfried/ipe#245]
Those in countries with imperial-sized paper have a difficulty. Even if the first few gridsize settings are from an additional stylesheet ("18 pts; 1/4 inch", etc), the file is loaded with a metric grid selected.

One possible solution is to save the selected gridsize, which would be a useful feature for those in countries using metric-sized paper as well. One way to do this is to add a property 'selected' in the relevant XML node (e.g.: <gridsize name="18 pts; 1/4 inch" value="18" selected/>).

Any other solution is good, provided that someone switching between multiple files does not have to reselect the grid that matches the drawing every time a file is loaded.

**Comment by otfried** [comment]
The default grid size set when Ipe starts is defined in `prefs.lua`, so you can simply change it.

The preset default is 16, which is actually not metric - it's 16/72 = 2/9 of an inch.

Adding support for true metric sizes has been on my to-do list forever.   It should be possible to write Ipe documents where the unit of measurement is not 1/72 of an inch.

There is currently no support for having the default depend on the style sheet - that's an interesting suggestion.

**Comment by ghali** [comment]
Right.. I forgot that we're all stuck in inch-based settings, whether for the paper size or for the 72 points/inch.

Thanks for the suggestion. Adjusting the values of <gridsize name="" value=""/> in /Applications/Ipe.app/Contents/Resources/styles/basic.isy (for macOS) and setting prefs.grid_size in /Applications/Ipe.app/Contents/Resources/lua/prefs.lua work well.

Is there also a way to write <layout paper="612 792" origin="0 0" frame="612 792"/> in "standard.isy" so that Ipe would always start with 8 1/2" x 11" paper?

**Comment by otfried** [comment]
You should avoid modifying any parts of the Ipe distribution directly - you will have to redo all your changes whenever you upgrade Ipe (which is hopefully often).    Especially changing the standard stylesheet `basic.isy` is problematic - if you share your documents with others and they run "Update stylesheets", everything will break.

The right procedure is:

1. Make your own stylesheet, e.g. `imperial.isy`, for instance like this:

```
<?xml version="1.0"?>
<!DOCTYPE ipestyle SYSTEM "ipe.dtd">
<ipestyle name="imperial">
<layout paper="612 792" origin="0 0" frame="612 792"/>
<gridsize name="1/8 in" value="9"/>
<gridsize name="1/4 in" value="18"/>
<gridsize name="1/2 in" value="36"/>
</ipestyle>
```

Store the style sheet in `$HOME/Library/Ipe/Styles/imperial.isy`.

2. Create a customization file in `$HOME/Library/Ipe/Ipelets/customization.lua`.   

Put your changes in this file:

```
-- my Ipe customizations
prefs.styles = { "basic", "imperial" }
prefs.grid_size = 18
```

See how we use an **additional** style sheet instead of modifying the standard `basic` style sheet.

Note that starting with Ipe 7.2.12, the second line needs to change to
```
prefs.initial.grid_size = 18
```

**Comment by ghali** [comment]
So to summarize:

----Option 1----

Define `letter-portrait.isy`, `letter-landscape.isy` and use them to define `initial-letter-portrait.ipe`, `initial-letter-landscape.ipe`.

Whenever one starts a new Ipe figure, copy one of these files first.

Problem: The gridsize still needs to be reset (to 1/4 inch, say) every time a file is opened.

----Option 2----

- Edit `/Applications/Ipe.app/Contents/Resources/styles/basic.isy`
- Adjust value of prefs.grid_size in `/Applications/Ipe.app/Contents/Resources/lua/prefs.lua`

Now Ipe uses both 8.5"x11"-paper and inch-based grid settings.

All is good, except that this is a heavy-handed solution, since it needs to be redone every time Ipe is upgraded.

----Option 3----

Create
 - `/Users/<username>/Library/Ipe/Ipelets/customization.lua`
 - `/Users/<username>/Library/Ipe/Styles/letter-portrait.isy` (etc)

I was using Option 1. I would be quite content with Option 2, even with the drawback.

You are suggesting Option 3. I see that Ipe (7.2.12) reads `~/Library/Ipe/Ipelets/customization.lua` and follows the line `prefs.initial.grid_size = 18`. Nice. But there are two issues:
- I think there is a bug though. The "18" option indeed appears selected, but another grid size is used until the "18" is explicitly selected. The file must first be saved and reloaded. This makes sense. Ipe reads `customization.lua` when it starts, but at that time no "18" setting is known. So it's a trivial issue, but still poses a small UI puzzle.
- Adding the stylesheet from `~/Library/Ipe/Styles/letter-portrait.isy` is no different than adding it from `/anywhere/else/letter-portrait.isy`. One possible enhancement is for Ipe to offer the styles in `~/Library/Ipe/Styles/`. It seems that right now Ipe reads `~/Library/Ipe/Ipelets/customization.lua` but ignores the contents of `~/Library/Ipe/Styles/`. That location is cached and ready for future edits.

Those using Ipe often would still find Option 2 easier if they're on 8.5"x11" paper all the time (or at least one of them would).

**Comment by otfried** [comment]
Point 2:

What is special about `~/Library/Ipe/Styles` is that Ipe knows that this is a style directory.   So "Update style sheets" will automatically find a style sheet here, and listing it in `prefs.styles` will find it without giving a full path.

So putting this in `customization.lua`:
```
prefs.styles = { "basic", "letter-portrait" }
```
can correctly load `letter-portrait.isy` from `~/Library/Ipe/Styles/letter-portrait.isy`.   If you put it somewhere else, you would have to write
```
prefs.styles = { "basic", "/anywhere/else/letter-portrait" }
```

**Comment by otfried** [comment]
Point 1:

This works correctly for me.   Are you loading your style sheet defining the 1/4 inch grid size automatically when you start Ipe, as explained above (setting `prefs.style` in a customization ipelet)?

Instead of forcing the style sheet in the customization, you can also select it when starting Ipe from the command line, like this:
```
ipe -sheet letter-landscape
```
 Of course this is only necessary the first time you create a document - the style sheet is then stored in the document and remains available when you open the document again.

**Comment by otfried** [comment]
To summarize:   If you do it correctly, your "Option 3" gives you all the advantages of "Option 2", but without the disadvantage that you have to redo it for every Ipe upgrade.

**Comment by ghali** [comment]
Ah! My mistake: when using Option 3 I was pointing to the name of the stylesheet in the `name` attribute of the XML file, not to the filename. Option 3 indeed flawlessly solves the paper-size and grid-size issue. Thanks for your help!
