### ISSUE TITLE
text object window:

### ISSUE THREAD

**Issue by AntonioDEM** [otfried/ipe#248]
Is it possible to insert the tab to increase the size of the text object 
[WINDOW](https://drive.google.com/file/d/1nUd5QD52Gh3vcZJzfDJOb9PdrjkunC6y/view?usp=sharing)??
use to insert graphics with the TIKZ library, but the TIKZ code being very extensive. with a small window it is inconvenient to be corrected. thanks

**Comment by otfried** [comment]
Set `prefs.editor_size` in your preferences.

**Comment by AntonioDEM** [comment]
and if i want confing, for example, EditPlus, as an external editor? C:\Program Files\EditPlus\editplus.exe
