### ISSUE TITLE
paste page - copy page

### ISSUE THREAD

**Issue by AntonioDEM** [otfried/ipe#249]
I noticed that when the copy and paste page is done, the [graph](https://drive.google.com/open?id=19_Fux5MfhH0EtR-3dnTkMXPU0H9RKrLP) is not automatically updated. you need to make a change to update. for example:
dash pattern = on 4pt -> [APPLY](https://drive.google.com/file/d/1jXCF7W1YahZGacaI6KEM8uaUfirZV1lz/view?usp=sharing) and then return the initial dash pattern = on 3pt.
Is it possible to insert an automatic update, as was done in previous versions of IPE?

**Comment by otfried** [comment]
Just press Ctrl+L to run Latex.
