### ISSUE TITLE
external editor

### ISSUE THREAD

**Issue by AntonioDEM** [otfried/ipe#250]
yesterday I was verifying the possibility of using a software with the name: Editplus as external editor.
how can i configure?
if I replace "notepad.exe" with editplus.exe, obviously nothing happens, I guess I'll have to direct the program. how can this be done ??

**Comment by otfried** [comment]
If editplus is in your path (so that you can call it from the command line), then it would be enough to set the preference
```
 prefs.external_editor = "editplus.exe %s"     
```
