### ISSUE TITLE
Adding the position in ipe

### ISSUE THREAD

**Issue by mateuspinheirodias** [otfried/ipe#251]
HI, guys. 

Would be possible to add this feature in ipe? it's a feature from Corel draw.
![image](https://user-images.githubusercontent.com/32579621/59533780-e64b3980-8ec2-11e9-817a-801315e5cd62.png)
With this, we can use new forms of align.

**Comment by otfried** [comment]
Please add some explanation what it exactly the tool does.    I wouldn't be able to tell from this screen shot.
