### ISSUE TITLE
Stroke opacity cannot be applied to multiple objects

### ISSUE THREAD

**Issue by Willem3141** [otfried/ipe#252]
Here's a small issue I noticed in Ipe 7.2.12: When selecting more than one path object, the stroke opacity option (from #134) option is not present in the right-click menu:

<img alt="The right-click menu for two objects, missing the stroke opacity option" src="https://user-images.githubusercontent.com/7533280/60016801-776e9d00-9687-11e9-96d3-4f5c7c41ff47.png">

Similarly, the stroke opacity cannot be copied between objects with Pick properties / Apply properties. Somehow Ipe does not seem to store the most-recently used stroke opacity in the Properties dock, like it stores other properties. Therefore it seems impossible to adjust the stroke opacity for several objects at once: you have to change all objects one by one.

It would be useful if stroke opacity would be treated like other properties (such as fill opacity) in this respect.

**Comment by otfried** [comment]
Fixed in 7.2.13.
