### ISSUE TITLE
Configure initial Ipe window size

### ISSUE THREAD

**Issue by ghali** [otfried/ipe#253]
[dot-emacs-for-ipe.txt](https://github.com/otfried/ipe-issues/files/3359107/dot-emacs-for-ipe.txt)

The attached .emacs makes it easy to use Ipe from within Emacs dired mode, with directory listings in that mode acting as a replacement for Windows Explorer or macOS Finder: point to an Ipe file and press 'o' to edit the file.

This would be seamless if one can configure, if not the location where the Ipe window will be located, at least the size of the window at launch, in addition to an initial choice between "Fit page" and "Fit objects".

On Macs one option might be to run the AppleScript lines:

tell application "Ipe"
	activate
	set the bounds of the first window to {10, 10, 1034, 778}
end tell

but Ipe declines being resized this way.

**Comment by otfried** [comment]
You can prescribe the Ipe window size by setting
```
prefs.window_size = { 1080, 600 } 
```

**Comment by ghali** [comment]
Cool.. thanks. (and I thought this was one of the tricky things to do in an OS-neutral program.)
