### ISSUE TITLE
How to rotate a label in Ipe?

### ISSUE THREAD

**Issue by vuongtrong2143** [otfried/ipe#254]
Maintainers can see this:

https://tex.stackexchange.com/questions/498804/how-to-rotate-the-label-in-ipe-software

I am happy if anyone can help me. Thanks.

**Comment by otfried** [comment]
By default, text objects can only be translated, not transformed or rotated.

You need to right-click the text object, and select "Transformations -> affine".      Once you have changed the setting, you can rotate and stretch the letter until it fits the perspective view.

**Comment by vuongtrong2143** [comment]
Best, thank for your answer. I have done this successfully.
