### ISSUE TITLE
Why the Ipe software is written by C++ and Lua but not the other?

### ISSUE THREAD

**Issue by vuongtrong2143** [otfried/ipe#255]
I see in http://ipe.otfried.org/ 

Ipe is written in standard C++ and Lua 5.

Can maintainer explain to me?

**Comment by otfried** [comment]
This issue tracker is meant to report problems are request features in Ipe.  

If you want to chat about Ipe, I recommend the Ipe discussion list (https://mailman.science.uu.nl/mailman/listinfo/ipe-discuss).

As an answer to your question, I can only point you to http://ipe.otfried.org/manual/manual_58.html.
