### ISSUE TITLE
Ipelets->symbols not loading style sheets after saving/re-opening

### ISSUE THREAD

**Issue by nhbaars** [otfried/ipe#257]
The UI window 'use symbols' (ipelets->symbols->use symbols) does not show the symbols in the loaded style sheet (see attachment .isy) after you save and close document.

[circuitsymbols.txt](https://github.com/otfried/ipe-issues/files/3482379/circuitsymbols.txt)

**Comment by otfried** [comment]
I don't understand the problem:  What do you mean by "close the document"?     If you close the Ipe window and open a new one, then obviously the symbols are not going to be there - they are in the style sheet of the first document.
