### ISSUE TITLE
Ipe crashes on Linux

### ISSUE THREAD

**Issue by zwang2** [otfried/ipe#259]
Ipe crashes on Linux when the page title has empty section or subsection headings. To reproduce, open a .ipe file with the following content:
```xml
<?xml version="1.0"?>
<!DOCTYPE ipe SYSTEM "ipe.dtd">
<ipe version="70212" creator="Ipe 7.2.12">
<info created="D:20170710160113" modified="D:20190828211329" numberpages="yes"/>
<page section="">
<layer name="alpha"/>
<view layers="alpha" active="alpha"/>
</page>
</ipe>
```
and press Ctrl+P for the title dialog.
The offending piece is `section=""`. If removed, the problem disappears.

A version of Ipe that has the problem is 7.2.12. Not sure if this is the earliest version having the problem though. But I am sure much early versions of Ipe did not have this problem. It seems to be an Qt issue related to opening dialogs. The version of Qt where the above test was performed was 5.13.0.

**Comment by otfried** [comment]
Fixed in 7.2.13.
