### ISSUE TITLE
Color of the selection

### ISSUE THREAD

**Issue by olcc** [otfried/ipe#26]
Hello,
In Ipe, the selected object is highlighted with a red line. Unfortunately I am color blind and I don't have red cones in my eyes (most common type of color blindness) => I can't notice red over black. I wish the color of the selection could be defined somewhere (in a config file for example).
Best regards,
Olivier

**Comment by otfried** [comment]
I've been planning to make this customizable for a looong time - you are giving me a good reason to finally implement it.

It will be an option in the prefs.lua file in the next version.

**Comment by otfried** [comment]
Which operating system are you on?

**Comment by olcc** [comment]
I'm with Linux (Debian)

**Comment by otfried** [comment]
If you are compiling Ipe yourself, you can already change the colors, in "src/ipecanvas/ipecanvas.cpp".

In the function  CanvasBase::drawTool, change

Color(1000, 0, 0)

to the primary selection color, and

Color(1000, 0, 1000)

to the secondary selection color.

The three components are red, green, blue, on a scale from 0 to 1000.

**Comment by otfried** [comment]
Implemented in 7.1.11.
