### ISSUE TITLE
tiling patterns do not render in Adobe Acrobat Pro

### ISSUE THREAD

**Issue by JulianKolm** [otfried/ipe#262]
Using tiling patterns in ipe results in a pdf that do not display the tiling in Adobe Acrobat Pro (see attachement). Acrobat simply renders a white rectangle. Unfortunately enough, the same problem occurs when the ipe figures are included in a Latex document (as pdf or eps) and then compiled via pdftex. 

[test.pdf](https://github.com/otfried/ipe-issues/files/3621864/test.pdf)

(I suspect that the problem is actually one specific to Adobe Acrobat.  But producing graphics that are shared as pdf's (after inclusion into scientific papers) seems to be a major use case of ipe and relies on good compatibility with the major pdf viewers)

**Comment by otfried** [comment]
The file works fine in Acrobat Reader Touch and in all PDF readers that I have access to (Android, Linux, Chrome and Firefox).   It's hard to fix a problem when I don't know what the problem is.

Have you tried if Acrobat Pro displays the tiling patterns produced by Tikz?

**Comment by otfried** [comment]
For instance, does Acrobat Pro display the tiling pattern on this picture?

http://www.texample.net/media/tikz/examples/PDF/supersonic-nozzle.pdf

**Comment by JulianKolm** [comment]
Thank you for your quick response and excuse my slow reply. It must have been some strange Adobe Acrobat error. Our IT dept. could not properly diagnsoe the error but finally managed to solve the issue with some reinstallations.
