### ISSUE TITLE
Is it possible to export an Ipe file with the grid reserved?

### ISSUE THREAD

**Issue by GoBigorGoHome** [otfried/ipe#264]
The grid does not appear on the exported image by default, which is quite reasonable.
But there are cases where I want the grid to be reserved, is there any option to achieve that?

**Comment by otfried** [comment]
No, the grid is only generated for the screen.   If you want one in the PDF, you would have to draw it in Ipe.

One very easy way to make grids is to use Tikz, that is, make a text object and put this inside:
```
\begin{tikzpicture}
\draw[step=.5cm,gray,thin] (0, 0) grid (10,10);
\end{tikzpicture}
```
(and, of course, `\usepackage{tikz}` in the preamble).
