### ISSUE TITLE
Clipping does not correctly set bounding box if objects in the group are outside the clipped area

### ISSUE THREAD

**Issue by jonasc** [otfried/ipe#265]
When clipping a group of objects where the objects are outside of the clipped path the bounding box is bigger than it should be, i.e., bigger than the bounding box.

See the attached file where the first page shows the drawing (all circles are in one group) together with the orange rectangle which will be the clipping path. The second picture than shows the same drawing but with the clipping applied to the group. For reference the clipped path is extracted and shown in green.

The third and fourth page show that this does not happen if the clipping contains all objects (partially).

The fifth and sixth page strengthen my intuition that somehow the bounding box extends until before the "left out" object starts, this can also be observed in the first two pages.

[ipe-clipping.pdf](https://github.com/otfried/ipe-issues/files/3707484/ipe-clipping.pdf)

**Comment by otfried** [comment]
Clipping a path did not work when the path lies completely outside the clipping rectangle.

Fixed in 7.2.14.
