### ISSUE TITLE
TEXINPUTS misses the old values

### ISSUE THREAD

**Issue by zwang2** [otfried/ipe#266]
With version 7.2.13, TEXINPUTS adds the document directory to TEXINPUTS environment variable. However, the old values of TEXINPUTS seem to be removed on the non-WIN32 versions. This causes the source files not in the Ipe document directory to be not available to TeX engine.

To fix this, the source file `ipelib/ipeplatform.cpp` should be modified such that line 589 reads 
```
s += "\":$TEXINPUTS; ";
```

**Comment by otfried** [comment]
Fixed in 7.2.14.
