### ISSUE TITLE
IpePresenter does not show notes on MacOS

### ISSUE THREAD

**Issue by pierreganty** [otfried/ipe#268]
I have tried several presentations of mine containing notes.
Notes are displayed fine with the presentation tool but I don't see them with IpePresenter.
I am running Ipe 7.2.13 on MacOS 10.14.6 (dark mode activated).

**Comment by otfried** [comment]
Could you attach an example file (or mail it directly to me)?

**Comment by pierreganty** [comment]
I just emailed you two files.

**Comment by otfried** [comment]
It works for me - but I see there are two problems:

* When I open Ipepresenter, the "notes" field is minimized.  You need to drag the splitter just below the clock downwards to see the notes.

* The text is black on dark-gray in dark mode.

**Comment by pierreganty** [comment]
I see, indeed I "found" the notes and I can see them in non dark mode.

Btw the same problem (black text on drak-gray) happens in Ipe when
returning from an external editor after editing a label.

Thank you for your very fast response.

Pierre.

PS: I am presenting on Monday so if you want me to try pre-release then let
me know.

**Comment by otfried** [comment]
I have fixed both problems and built new MacOS binaries:

https://www.dropbox.com/sh/fw6g11pct8265jz/AACQlr9BYzpiADj2cnKo8hUda?dl=0

Note that Ipe and IpePresenter are now two separate downloads (I want to market IpePresenter to beamer users who may not want to install Ipe).

**Comment by pierreganty** [comment]
Thanks Otfried. I could not hope for better application support!
