### ISSUE TITLE
Online LaTeX compilation broken on Mac

### ISSUE THREAD

**Issue by nathaniel** [otfried/ipe#269]
When I attempt to "Enable online compilation" on Mac, I get the following error:

```
Lua error

Data may have been corrupted. 
Save your file!

	Ipe.app/Contents/Resources/lua/actions.lua:933: bad argument #1 to 'close' (FILE* expected, got no value)
stack traceback:
	[C]: in field 'close'
	Ipe.app/Contents/Resources/lua/actions.lua:933: in local 'f'
	Ipe.app/Contents/Resources/lua/actions.lua:63: in method 'paction'
	Ipe.app/Contents/Resources/lua/actions.lua:11: in function <Ipe.app/Contents/Resources/lua/actions.lua:11>
	[C]: in function 'xpcall'
	Ipe.app/Contents/Resources/lua/actions.lua:11: in function <Ipe.app/Contents/Resources/lua/actions.lua:10>
```
Tried on 2 different Macs with same result. (Online compilation works fine in Windows.)
Nathaniel

**Comment by otfried** [comment]
I just fixed this yesterday, together with a few other OSX issues (#268).    

Since this is a serious bug, I'll upload the new packages to bintray (for the moment, you can get them through the dropbox link in #268).

**Comment by nathaniel** [comment]
Looks like the button "Enable" / "Disable" in the online compilation dialog on Mac is now backward. Clicking "Disable" makes LaTeX compilation work, and "Enable" causes further compilation attempts to give error:
`You either have no Latex installation on your computer, or the Latex executable is not on your command path.`

**Comment by otfried** [comment]
Strange.   It works correctly on Linux, and there's no Mac-specific code...

I'll look at it in a week when I have access to a Mac again.

**Comment by otfried** [comment]
It was a very simple issue:  to use the cloud service, Ipe calls a program called ipecurl (instead of pdflatex).   And it was assuming that this is on the path, which is of course not the case by default on OSX.

I have simply updated the binary on bintray, so please just download 7.2.13. again.

**Comment by nathaniel** [comment]
Thanks for the fix!
