### ISSUE TITLE
Change default resolution png export

### ISSUE THREAD

**Issue by pglira** [otfried/ipe#27]
It's great that png file can now be exported directly from IPE! Just one issue: the output resolution is to low. Is it possible to change somewhere the default dpi value? I couldn't find one.

Thanks.

**Comment by otfried** [comment]
The resolution is identical to the screen resolution, so just change the zoom factor.

**Comment by pglira** [comment]
Ok, I would prefer to set it manually, as this way it's very difficult to export different figures with the same resolution. Yes, I can use iperender for this, but doing it directly from IPE would be very nice. :-)

**Comment by otfried** [comment]
Make an ipelet that asks the user for the desired resolution and then calls

```
model.ui:setZoom(resolution / 72.0)
```

I might add this to the Zoom menu.

**Comment by pglira** [comment]
Thanks. I tried it, but something seems to be wrong in the following code:

``` lua
----------------------------------------------------------------------
-- set DPI ipelet
----------------------------------------------------------------------

label = "Set DPI"

about = [[
Set DPI
]]

function run(model)
  local str = model:getString("Enter DPI")
  if not str or str:match("^%s*$") then return end
  local resolution = tonumber(str)
  model.setZoom(resolution / 72.0)
end 

----------------------------------------------------------------------
```

Could you help me please?

**Comment by otfried** [comment]
model.setZoom(resolution / 72.0)

should be

model:setZoom(resolution / 72.0)

with a colon (it's a method call).

**Comment by pglira** [comment]
Oh, I can not explain how this happened. However, it is still not working:
![2015_11_25_09_34_56](https://cloud.githubusercontent.com/assets/14214284/11392140/f54d4a28-9357-11e5-9141-9fae7bd6581e.png)

**Comment by otfried** [comment]
Sorry, my mistake.  It should of course be:

```
  model.ui:setZoom(resolution / 72.0)
```

**Comment by pglira** [comment]
Thanks, now it's working:

``` lua
----------------------------------------------------------------------
-- set DPI ipelet
----------------------------------------------------------------------

label = "Set DPI"

about = [[
Set DPI
]]

function run(model)
  local str = model:getString("Enter DPI")
  if not str or str:match("^%s*$") then return end
  local resolution = tonumber(str)
  model.ui:setZoom(resolution / 72.0)
end 

---------------------------------------------------------------------- 
```
