### ISSUE TITLE
Can't disable Online LaTeX Compilation (Windows)

### ISSUE THREAD

**Issue by nathaniel** [otfried/ipe#270]
Ipe 7.2.13 in Windows 7:
The Online LaTeX Compilation works great, but it seems that the "Disable" choice subsequently doesn't do anything... LaTeX compilation still works (without local TeX), and the the Enable Online Compilation dialog still says, "You are currently using the following online service..." and offers a Disable button.

**Comment by otfried** [comment]
Strange.  I tested it under Wine and on Windows 10.

Could you try the following:   In actions.lua, find the line
```
  local urlFile = config.latexdir .. "/url.txt"
```
and replace it by 
```
  local urlFile = config.latexdir .. prefs.fsep .. "url.txt"
```
This is definitely better, but I'm not sure it is actually the reason for the bug.

**Comment by edyrol** [comment]
I have the same issue on Win 10 pro. Had to manually delete AppData\Local\ipe\url.txt.
The change you suggested in actions.lua did not fix the bug.

**Comment by otfried** [comment]
> I have the same issue on Win 10 pro. Had to manually delete AppData\Local\ipe\url.txt.
> The change you suggested in actions.lua did not fix the bug.

When you go to Help -> Show configuration, what exactly does it display for "Latex directory"?

**Comment by otfried** [comment]
It seems `config.latexdir` already contains the trailing path separator, so the line should really just be
```
  local urlFile = config.latexdir .. "url.txt"
```
I'm not convinced this is the actual problem, though, because on all my systems it works anyway.

**Comment by edyrol** [comment]
> When you go to Help -> Show configuration, what exactly does it display for "Latex directory"?
C:\Users\Edgardo\AppData\Local\ipe\

**Comment by otfried** [comment]
Could you try if it works when you make the change I suggest above: in actions.lua, find the line
```
  local urlFile = config.latexdir .. "/url.txt"
```
and replace it by
```
  local urlFile = config.latexdir .. "url.txt"
```

**Comment by edyrol** [comment]
It didn't work. I know next to nothing about Lua but I did some experiments.

After that last change, the value of urlFile is  C:\Users\Edgardo\AppData\Local\ipe\url.txt so it seems good. But apparently os.remove is returning a Permission denied error.
I tried running ipe as administrator but it didn't help.

I don't know why but if I remove
`local f = ipe.openFile(urlFile, "r")`
`local url = f:read("a")`
`url = url:match("^(%S+)%s*$")`
`f.close()`
and just give url any string value then the disable button works.

**Comment by edyrol** [comment]
Shouldn't it say `f:close()` instad of `f.close()`?

**Comment by otfried** [comment]
Ouch - does the current version still say `f.close`?    I fixed that in #269, but apparently I did not upload the fixed version except for MacOS....

That explains the problem - the file remains open and can therefore not be deleted.

Can you try changing it?

**Comment by edyrol** [comment]
I did it and it works ok now.

**Comment by otfried** [comment]
I have now uploaded fixed versions to bintray - anyone affected by the problem should download Ipe again.

I'll keep this issue open until I release a new version, so that people can find what causes the problem.
