### ISSUE TITLE
Ipe fails to parse valid path

### ISSUE THREAD

**Issue by tinloaf** [otfried/ipe#274]
If I understand [the documentation](http://ipe.otfried.org/manual/manual_48.html) correctly, this is a valid ipe file:

```xml
<?xml version="1.0"?>
<!DOCTYPE ipe SYSTEM "ipe.dtd">
<ipe version="70212" creator="Ipe 7.2.13">
<page>
<layer name="alpha"/>
<view layers="alpha" active="alpha"/>
<path layer="alpha" stroke="black">
64 480 m
192 480 l
h
0 0 m
</path>
</page>
</ipe>
```

However, ipe fails to parse the path. Sure, the starting of a new subpath as last operation in the path is nonsensical - however, such paths are created by `svgtoipe` if the respective SVG path does the same, i.e., starts a new nonsensical subpath as the last operation. Such SVGs seem to be generated by some tools (in this case: Inkscape) - and they are valid according to the SVG specs, I think.

**Comment by otfried** [comment]
It was on my to-do list to fix svgtoipe so that it no longer generates the trailing moveto - but you are right, it sounds much easier to let Ipe silently ignore them.

**Comment by tinloaf** [comment]
I just implemented that fix in my working copy of `svgtoipe`. I might submit a PR for `svgtoipe` some time soon anyways, that should include that fix.

**Comment by tinloaf** [comment]
Similar problem - this file with an empty path also crashes ipe, generated by `svgtoipe`:

```xml
<?xml version="1.0"?>
<!DOCTYPE ipe SYSTEM "ipe.dtd">
<ipe version="70212" creator="Ipe 7.2.13">
<page>
<layer name="alpha"/>
<view layers="alpha" active="alpha"/>
<path>
</path>
</page>
</ipe>
```

**Comment by otfried** [comment]
Both inputs are legal in 7.2.14.
