### ISSUE TITLE
Which version stays with lua-5.1?

### ISSUE THREAD

**Issue by hungshihhan** [otfried/ipe#277]
I am trying to install ipe with my gentoo machine. However, currently lua-5.3 is masked (https://packages.gentoo.org/packages/dev-lang/lua) and many packages still use lua-5.1. There does not seem an easy way to upgrade it to 5.3. Which version of ipe should I use to avoid heavy upgrades?

**Comment by otfried** [comment]
You'll have to go quite far back:  Ipe 7.1.3 from early 2013.   I really cannot recommend that.

Why don't you simply compile a private copy of Lua 5.3 and use that to compile Ipe yourself?

**Comment by hungshihhan** [comment]
How do I compile a private copy of Lua 5.3 and let Ipe see it?
