### ISSUE TITLE
Cannot use moving figures in Ipe

### ISSUE THREAD

**Issue by MasahiroMae** [otfried/ipe#278]
I want to use moving figures (e.g. mp4 video file or animated GIF file) in the Ipe slide presentation.

My environment is Windows 10 64bit and Ipe 7.2.13.

I already tried some LaTeX solusions, "animate.sty" and "media9.sty".
However, LaTeX compile error occurred with these packages.

I also tried the solution with group object and link action in Ipe, and start the presentation with pdfpc in "Bash on Ubuntu on Windows".
However, the linked video isn't played on the slide.

Are there any solutions to use moving figures (e.g. mp4 video file or animated GIF file) in the Ipe slide presentation?

**Comment by otfried** [comment]
If you set the URL of a group object using the `launch:` prefix, e.g. like this:
```
launch:apollo17.avi
```
then `pdfpc` on Linux will show the video inside the slide.    I've never tried installing pdfpc on Windows, so I don't know if it's working there.

See http://ipe.otfried.org/manual/manual_19.html.

The `animate` and `media9` packages seem to work by embedding Javascript in the PDF file, and this is not currently supported by Ipe.
