### ISSUE TITLE
Keyboard shortcut with cursor movement keys

### ISSUE THREAD

**Issue by MasahiroMae** [otfried/ipe#279]
I want to move views and pages with cursor movement keys (e.g. "←,↑,→,↓").
How to set a keyboard shortcut with cursor movement keys?

**Comment by otfried** [comment]
You can define shortcuts for all Ipe actions as described here:

http://ipe.otfried.org/manual/manual_40.html

Use "Left", "Right", "Up" and "Down" for the cursor keys.
