### ISSUE TITLE
Notes not displayed correctly in IpePresenter

### ISSUE THREAD

**Issue by pierreganty** [otfried/ipe#282]
As the enclosed screenshot shows non ASCII character ⚠ in Notes gets rendered correctly in Ipe but not in IpePresenter. (version 7.2.13)

<img width="1159" alt="image" src="https://user-images.githubusercontent.com/2111160/72445704-6d8ec180-37b2-11ea-93e6-b1334d9cfccd.png">

**Comment by otfried** [comment]
Fixed in 7.2.14.

Strange nobody else complained about this - it seems everybody writes their notes in English.  As soon as you used accented characters, or non-roman characters, it completely broke.
