### ISSUE TITLE
Mathscript in Ipe 7.2.13

### ISSUE THREAD

**Issue by tgrollec** [otfried/ipe#285]
I'm trying to use mathscript in the text box - either math mode with \mathscr{B} or text mode with $\mathscr{B}$ do not accept LaTeX command - but it is not working. Error message is below. Any advise/help would be great

Error message:
! Undefined control sequence.
<recently read> \mathscript 
                            
l.56 $\mathscript
                 {B}$%
The control sequence at the end of the top line
of your error message was never \def'ed. If you have
misspelled it (e.g., `\hobx'), type `I' and the correct
spelling (e.g., `I\hbox'). Otherwise just continue,
and I'll forget about whatever was undefined.

**Comment by otfried** [comment]
Did you put
```
\usepackage{mathrsfs}
```
in your preamble?

**Comment by tgrollec** [comment]
Thanks! I wasn't aware of the preamble function under "Document properties."  Works like a charm now.
