### ISSUE TITLE
textbullet becomes a square

### ISSUE THREAD

**Issue by zzjjzzgggg** [otfried/ipe#286]
Item in itemize shows a square instead of a dot. In addition, \textbullet is rendered as a square, while $\bullet$ renders correctly.

Tested on a laptop and a desktop running Linux Mint 19.3, respectively, and same issue is observed. 

IPE 2.7.13. 

Libraries:
 * Pdftex, Xetex, or Luatex
 * Lua 5.3 (1861 kB used)
 * The font rendering library Freetype 2.8.1 / 2.8.1
 * The rendering library Cairo 1.15.10 / 1.15.10
 * The GUI toolkit Qt 5.9.5 / 5.9.5
 * The compression library zlib 1.2.11

There is a workaround to this issue, i.e., `\def\labelitemi{$\bullet$}`.

**Comment by otfried** [comment]
I cannot reproduce this.   Can you attach an example file?

**Comment by zzjjzzgggg** [comment]
[example.zip](https://github.com/otfried/ipe-issues/files/4398862/example.zip)

The zipped attachment includes an example file and a screen shot. 

Thanks!

**Comment by otfried** [comment]
How did you create this file?   It doesn't contain the basic style sheet, which is automatically included in every newly created file - I don't know how that can actually happen.

How did you install Ipe?  Compiling yourself, or a package I provide, or something else?

I'm also running Mint 19.3, and on my system the file displays correctly.   The square looks like the system cannot find the right font.     What is your version of pdflatex?    If you save the document in PDF format, does it show the right bullet sign?

**Comment by zzjjzzgggg** [comment]
It is created by just running `ipe` in terminal. I didn't use any style sheet. 

Ipe is installed by installing the two debs you provided. I tested on two LM 19.3 computers, and both have this issue.

pdflatex:  Version 3.14159265-2.6-1.40.20 (TeX Live 2019/Debian)

The PDF renders correctly.

BTW, I also use lyx. The textbullet renders correctly.

**Comment by otfried** [comment]
Even when you don't explicitly use any style sheet, Ipe would add the "basic" style sheet to any newly created document.

Can you attach the output of running `ipe -show-configuration` from the command line?

Also, can you attach the output of the following commands?
```
$ cd ~/.ipe/latexrun/
$ pdflatex ipetemp.tex 
```

How did you install Latex?   I have an up-to-date Mint 19.3 system, but I still have texlive 2017.  You seem to have Texlive 2019 - did you install that manually?

**Comment by zzjjzzgggg** [comment]
➜  ~ ipe -show-configuration
Ipe 7.2.13
Lua code: /usr/local/share/ipe/7.2.13/lua/?.lua
Style directories: /home/jzzhao/.ipe/styles, /usr/local/share/ipe/7.2.13/styles
Styles for new documents: basic
Autosave file: /tmp/%s.autosave
Save-as directory: .
Documentation: /usr/local/share/ipe/7.2.13/doc
Ipelets: /usr/local/lib/ipe/7.2.13/ipelets, /home/jzzhao/.ipe/ipelets
Latex program path: 
Latex directory: /home/jzzhao/.ipe/latexrun/
Icons: /usr/local/share/ipe/7.2.13/icons/
External editor: gvim -f %s

[latexrun.zip](https://github.com/otfried/ipe-issues/files/4398944/latexrun.zip)

I am using this texlive 2019 ppa.
ppa:jonathonf/texlive

Thanks a lot. I need to leave for a while.

**Comment by otfried** [comment]
Ah, so here we have the problem:
```
</home/jzzhao/.texlive2019/texmf-var/fonts/pk/ljfour/jknappen/ec/tcrm1000.600pk>
</usr/share/texlive/texmf-dist/fonts/type1/public/amsfonts/cm/cmr10.pfb>
```
For some reason, your pdflatex uses a bitmapped font (ec) for the bullet symbol, while it uses the normal cmr font for the text.   You can check that easily as follows:
```
$ cd ~/.ipe/latexrun/
$ pdffonts ipetemp.pdf
```
On your system, you get:
```
$ pdffonts ipetemp.pdf 
name                                 type              encoding         emb sub uni object ID
------------------------------------ ----------------- ---------------- --- --- --- ---------
[none]                               Type 3            Custom           yes no  no       7  0
QGJCBO+CMR10                         Type 1            Builtin          yes yes no       8  0
```
On my system, I get
```
$ pdffonts ipetemp.pdf 
name                                 type              encoding         emb sub uni object ID
------------------------------------ ----------------- ---------------- --- --- --- ---------
GFAWRG+CMSY10                        Type 1            Builtin          yes yes no       7  0
QGJCBO+CMR10                         Type 1            Builtin          yes yes no       8  0
```

Ipe wants to generate high-quality vector graphics that can be scaled arbitrarily, so it refuses to work with bitmapped (Type 3) fonts.

You can probably solve the issue by installing the `cm-super` package.

This doesn't seem to be an Ipe problem - if you run pdflatex on a tiny latex file, e.g.:
```
\documentclass{article}
\begin{document}
\textbullet
\end{document}
```
you should see the same issue (check with `pdffonts`).

**Comment by zzjjzzgggg** [comment]
Wow, installing the `cm-super` package indeed solves the issue on both of my machines. I am really appreciate for your efforts to dig out the root cause of this problem. Ipe is great, and I have been using Ipe for years!
