### ISSUE TITLE
iperender ignores the page title line

### ISSUE THREAD

**Issue by guenterrote** [otfried/ipe#287]
Example: [Titel.pdf](https://github.com/otfried/ipe-issues/files/4489945/Titel.pdf)
`iperender -svg -nocrop Titel.pdf a.svg`
everything will be in the output but not the title line. This holds in all 4 modes  -png | -eps | -pdf | -svg

**Comment by otfried** [comment]
It seems this was once a deliberate decision (typical use of iperender does not need the title), but I don't remember the reason.

**Comment by guenterrote** [comment]
Typical use of iperender would not use the -nocrop option, and even so, it would not include the logo and the footer lines. (But this is not important; there are other tools to turn pdf into a picture, e.g. screenshot.)

**Comment by otfried** [comment]
I still think it's a good idea to fix it.   It'll be in 7.2.14 (planned for next week).
