### ISSUE TITLE
Parentheses disappear with lmodern and bm packages and \dot{}

### ISSUE THREAD

**Issue by MasahiroMae** [otfried/ipe#290]
When I use the XeTeX engine and LaTeX packages as follows,
```
\usepackage{lmodern}
\usepackage{bm}
```
and, insert math text as follows,
`\dot{\bm{x}}(t)=\bm{y}(t)`.
Then, `()` and `=` disappear in the Ipe preview.
(However, they appear in the saved PDF.)

My guess is that the command `\dot` is bad.

**Comment by otfried** [comment]
The problem seems to be the `lmodern` package.   If you remove it, the math displays well.

I suggest you remove the `lmodern` from the preamble, and install the `cm-super` package instead.

**Comment by MasahiroMae** [comment]
Thanks for an early reply.
Now I use `\usepackage{fix-cm}`.
As you say, `\usepackage{cm-super}` is also a good solution.

**Comment by otfried** [comment]
On my texlive installation, you do not need to include any package - it is enough to **install** `cm-super` to get the fonts.
