### ISSUE TITLE
Items outside the paper also appear in IpePresenter

### ISSUE THREAD

**Issue by MasahiroMae** [otfried/ipe#291]
I usually use the Ipe presentation slide with the aspect ratio 4:3.
I sometimes move items outside the paper for like "comment-out".
When I do a presentation with IpePresenter in the widescreen whose aspect ratio is 16:9, the items outside the paper also appear on the screen.

I also would like to say that the margin color of the IpePresenter "Show Presentation" window prefers to Black compared with Gray in the dark presentation room.

**Comment by otfried** [comment]
Ipe does not clip to the paper (as you noticed), so when you want to "comment out" something, the best would be to make a new layer, move the object there, and turn off the layer.

I'll fix the background color.

**Comment by MasahiroMae** [comment]
Thanks. I will comment out with a new layer.

**Comment by otfried** [comment]
Background color changed to black in 7.2.15.
