### ISSUE TITLE
Blackout function for IpePresenter

### ISSUE THREAD

**Issue by MasahiroMae** [otfried/ipe#293]
Blackout function for hide presentation window and it's shortcut key "B" are needed for IpePresenter.
This function is useful when he/she is wating for presentation.

**Comment by otfried** [comment]
Do you want to hide the presentation window?   Or turn it completely black?

**Comment by MasahiroMae** [comment]
For the preparation of the slide presentation, I want to show the presentation in fullscreen and wait with turning it completely black.

**Comment by otfried** [comment]
Implemented in 7.2.15.
