### ISSUE TITLE
Double click should be treated as two single clicks

### ISSUE THREAD

**Issue by ghost** [otfried/ipe#3]
When Qt passes a double click event, the event should be treated as two single clicks if Ipe is not expecting a double click. For example, when using the Ink tool with a tablet input device, if two successive strokes have only a small time interval, they will be pass through by Qt as a double click, whereas it should be treated as two single clicks (strokes)

**Comment by otfried** [comment]
Have you tried mapping 129 to 1 in INKTOOL:mouseButton?

Qt already reports two events for a double-click:  The first one is a normal mouse click, the second one is reported as a double-click. By mapping this back to a normal click it should work (unless Qt does something else?)

**Comment by ghost** [comment]
I tried to map 129 to 1 in MODEL:mouseButtonAction() and it works. It does
not work by mapping 129 to 1 in INKTOOL:mouseButton. The reason is that the
MODEL:mouseButtonAction() function will block 129. So actually, I think 129
is not used any where in the Ipe program. Therefore it is probably safe to
map 129 to 1 inside MODEL:MouseButtonAction(). It is also a good design if
double clicks are not used at all.

My point here is that this may also need to be corrected in Ipe in the
released official version. The reason is that when writing using Inktool,
and writing quickly (at normal writing speed), the second stroke in two
consecutive strokes is reported (correctly) by Qt as a double click, but
Ipe should really accept 129 the second click as a normal click. I cannot
see any side effect of doing this, inside INKTOOL at least.

**Comment by otfried** [comment]
There are Ipe users that insist on having double-clicks as an alternative to the right mouse button, because their tablet pen does not have a right button.  Double-clicks can be used to terminate paths, for instance.

So yes, 129 is used in some tools (see tools.lua and search for 0x81).

So I cannot simply get rid of the double-click events, and instead Ipe needs to handle them.  It seems mapping it to 1 in MODEL:mouseButtonAction should be enough.

**Comment by otfried** [comment]
And yes, I've already included this in the official version for the next release.

**Comment by ghost** [comment]
Thanks.
