### ISSUE TITLE
Ipe 7.1.7. with presentation ipelet

### ISSUE THREAD

**Issue by Jurgenvz2** [otfried/ipe#3]
In previous versions I successfully used the presentation ipelet (https://algohub.iti.kit.edu/algo1/ipe/files/master/ipelets/presentation).

However, since I moved to version 7.1.7, the bezier type seems to be classified as invalid. But it seems it stills exists?

Any ideas on how to fix this?

**Comment by otfried** [comment]
Just change "bezier" to "spline" everywhere in the ipelet.
