### ISSUE TITLE
Voronoi diagram ipelet incorrect for vertical infinite lines

### ISSUE THREAD

**Issue by alexprand** [otfried/ipe#301]
The Voronoi ipelet fails to draw infinite vertical lines and instead shows horizontal ones.

![VoronoiIssue](https://user-images.githubusercontent.com/7891261/80862980-ab6b0500-8c3e-11ea-87dd-eecf025c7603.png)

Here is the .ipe file containing the issue: [VoronoiIssue.zip](https://github.com/otfried/ipe-issues/files/4567591/VoronoiIssue.zip)

To reproduce the issue on that file, delete the existing Voronoi lines, select all the vertices and the run Iplets>Voronoi diagrams>Voronoi diagram.

I see this problem using ipe on windows in the version 7.2.16.

**Comment by otfried** [comment]
This bug must have existed forever.   It was a simple typo and is fixed in 7.2.17.

I've also updated the win64 binary on the website with a fixed version.

**Comment by alexprand** [comment]
Thanks for such a quick fix.
