### ISSUE TITLE
Setting different IPELATEXDIR for each ipe files

### ISSUE THREAD

**Issue by MasahiroMae** [otfried/ipe#306]
I usually using LaTeX command \includegraphics for insert image files to Ipe.
And setting IPELATEXDIR as the relative path from ipe files in ipe.conf as follows.
`IPELATEXDIR=./`
However, when I share the Ipe file and figure files to other people, the IPELATEXDIR setting is different depending on their environments, and sometimes compiling error occurs.
So, is it possible to set different IPELATEXDIR for each ipe file?

Additionally, is it possible to delete temporary LaTeX files (e.g. aux, log, pdf, tex, bat files) automatically when the Ipe application is closed?

**Comment by otfried** [comment]
When using \includegraphics, Ipe will automatically search the directory where the current Ipe file is. This has been available since 7.2.13.

So I think what you are asking for is no longer necessary.

**Comment by MasahiroMae** [comment]
This is what I am looking for!
I have used Ipe for a long time before Ipe 7.2.13 is released, therefore, I misunderstood I cannot do that!
Thank a lot!

**Comment by MasahiroMae** [comment]
Is the latter problem possible?

> Additionally, is it possible to delete temporary LaTeX files made in IPELATEXDIR (e.g. aux, log, pdf, tex, bat files) automatically when the Ipe application is closed?

**Comment by otfried** [comment]
It is often important to keep those files to debug problems with the Latex conversion.   I don't see a good reason to delete them.

**Comment by MasahiroMae** [comment]
I understand your idea. I agree with you. Thanks.
Would you tell me the default IPELATEXDIR directory path of each OS?

**Comment by otfried** [comment]
On Unix, it is `~/.ipe/latexrun`.

On Windows, it is given by the operating system for CSIDL_LOCAL_APPDATA + "\Ipe".
(https://docs.microsoft.com/en-us/windows/win32/shell/csidl).
A typical path is C:\Documents and Settings\username\Local Settings\Application Data\Ipe, but it really depends on what Windows gives back.

**Comment by MasahiroMae** [comment]
Thank you!
