### ISSUE TITLE
'Move graph nodes' tool moves hidden edges

### ISSUE THREAD

**Issue by jonasc** [otfried/ipe#307]
I guess that this behavior is not expected:

### How to reproduce
1. Place marker at position A
2. Draw edge 1 from somewhere to position A
3. "New layer, new view"
4. On the new layer draw edge 2 from somewhere to position A
5. Go to the first view (hence hiding edge 2 on the new layer)
6. Use 'Move graph nodes' to move marker at position A

**Expected behaviour:** Marker moves together with edge 1

**Actual behaviour:** Marker moves together with edge 1 and edge 2

This is especially obstructive if one is working on multiple copies of some graph on different layers and wants to move a node on one layer while having the other copy hidden on some other layer.

**Comment by jonasc** [comment]
Thinking about it a bit further, the behavior is actually desirable, sometimes. So maybe an option to toggle between the two behaviors is the best solution.

**Comment by otfried** [comment]
Indeed, the mode doesn't seem to check at all if the edges are visible.

What about changing it so by default it will only move visible edges, but with the shift-key it will also move currently invisible ones?

**Comment by jonasc** [comment]
Yes, this sounds really good to me.

**Comment by otfried** [comment]
Fixed in 7.2.17.
