### ISSUE TITLE
Problem with xepersian package from Ipe 7.2.8

### ISSUE THREAD

**Issue by mfarshi** [otfried/ipe#308]
Starting from Ipe 7.2.2, the xetex engine is added to ipe and it makes the ability to use other languages in Ipe, especially right-to-left languages.  To use this with Persian, we load the xepersian package in the preamble. 
Starting from Ipe-7.2.8, this does not work and gives the following error:

! Package bidi Error: Oops! you have loaded package color after bidi package. Please load package color before bidi package, and then try to run xelatex on your document again.

A minimal example generated by Ipe 7.2.7 is attached.
[Ipe-7.2.7-xepersian.pdf](https://github.com/otfried/ipe-issues/files/4592012/Ipe-7.2.7-xepersian.pdf)
If you open it with Ipe-7.2.8 and later, you will see the problem.

**Comment by otfried** [comment]
Please upgrade to an up-to-date version of Ipe.

Instructions for using xepersian are here: http://ipe.otfried.org/manual/manual_38.html
What you need since 7.2.8 is a call to \ipedefinecolors{} *before* including bidi.sty.

**Comment by mfarshi** [comment]
Thanks. It solves the problem.
Would you please add the command in the Manual too? It has to be change from

\usepackage[documentdirection=lefttoright]{xepersian}
\settextfont{FreeFarsi}

to
\ipedefinecolors{}
\usepackage[documentdirection=lefttoright]{xepersian}
\settextfont{FreeFarsi}

Thanks Otfried.

**Comment by otfried** [comment]
Actually, if you follow the instructions in the manual, it is not necessary:  The stylesheet `right-to-left.isy` already contains that command.

It seems you are not using the stylesheet?   I noticed that for labels, Persian seems to work fine even without using the `\hboxR{...}` command.  But for minipages, I noticed the typesetting is different.

This is what I get when using the `rtl` style:
![image](https://user-images.githubusercontent.com/9983417/81287844-c3d68780-9063-11ea-8003-6fa40de11d88.png)

And this is for normal style:
![image](https://user-images.githubusercontent.com/9983417/81287892-dc46a200-9063-11ea-8f01-1a9dd0eb9830.png)

I guess the first one is correct, right?

Do you not use minipages?  Or do you manually write `\RTL ... \endRTL` in each minipage?

**Comment by mfarshi** [comment]
I could not find the style sheet, even on the internet!  It was not with previous versions. I found the style sheet with the new version and it works perfectly. Thanks. 
The first one is right. I use \rl{} for Persian texts. It is almost the same as the command you mentioned.
