### ISSUE TITLE
Error: BadDrawable (invalid Pixmap or Window parameter) 9

### ISSUE THREAD

**Issue by VincentRouvreau** [otfried/ipe#31]
Hello,
ipe was working good for me on my Ubuntu. After updates, I can still launch it, but I have the following error every time I move the mouse:
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x0
I can see just one button on the interface.
I am on Ubuntu 14.04-x86_64, Qt version 4.8.7.
It seems to be a issue with Qt, ldd /usr/bin/ipe have no missing link.

Do you think I have to compile it in order to install it properly ?
I installed it with sudo apt-get install ipe

Regards,
Vincent Rouvreau

**Comment by otfried** [comment]
Which version of Ipe is this?

You'll have to report this to the maintainer of the Debian package.

I suggest you try to compile yourself.

**Comment by VincentRouvreau** [comment]
Sorry about that. Ipe 7.1.4.
Ok I will try when I will have more time.

Thanks for your quick answer.

Vincent Rouvreau

**Comment by otfried** [comment]
That version is ancient anyway.
