### ISSUE TITLE
Degenerate bounding box when nothing is selected

### ISSUE THREAD

**Issue by ghali** [otfried/ipe#312]
- Start Ipe 7.2.17 (or any recent Ipe).
- Insert two circles.
- Select nothing (click on empty space in Selection mode).
- Ipelets \ Goodies \ Insert bounding box.
- Edit \ Select all.
- Ipelets \ Goodies \ Insert bounding box.

Even when nothing was selected, Ipe inserted a degenerate (-1,0) to (1,0) bounding box.

Circle: 18 0 0 18 216 720 e
Circle: 18 0 0 18 288 612 e
Box: 1 0 m 1 0 l -1 0 l -1 0 l h
Box: -1 0 m -1 738 l 306 738 l 306 0 l h

I'd rather if this is declared a bug, not a feature.

Two better actions for "Insert bounding box" when nothing is selected are:

- Open a dialog box saying "can't do it; nothing is selected".
- Insert a bounding box on the assumption that everything is selected.

**Comment by otfried** [comment]
Fixed in 7.2.18.
