### ISSUE TITLE
Ipe 7.2.17 crashes on "Edit path"

### ISSUE THREAD

**Issue by marszw** [otfried/ipe#315]
Ipe 7.2.17 on Windows crashes when "Edit path" is invoked after the path was tweaked with the use of "Simplify path" Iplet.
Here is the MWE:
1. Open Ipe in the Windows 10 environment.
2. Draw any spline.
3. Apply "Iplets>Simplify path">"Simplify to spline" with any tolerance.
4. Select the spline tweaked in point 4.
5. Right-click - and the crash follows.

**Comment by otfried** [comment]
It's a bug in the ipelet:  it leaves the page with only secondary selections and no primary selections. Unfortunately I cannot transfer this issue to https://github.com/PhKindermann/ipe-simplify/issues ...

The code 
```
      for _, i in ipairs(t.selection) do
        p:setSelect(i, 2)
      end
```
should just be deleted from each of the functions, it does only harm and no good.

I've added a check to Ipe so that after an ipelet returns it makes sure a primary selection exists again.

For the moment,  all you need to do is to deselect the object and select it again, and the right-click menu will work correctly.

**Comment by marszw** [comment]
OK, thank you very much.

I kind of felt that the Iplet was to blame, but preferred to send it to the experts instead of 
meddling myself in the code.

Incidentally, since I have you on the line - these are no bugs, but rather questions/wishes.

1. On my system the toolbars "grid" and "angle"  are unnecessarily wide. The result is that all 
toolbars fill two lines in the window, whereas they would fit in just one. I can't figure out which 
setting and in which file controles these widths. Is it hard-coded in Qt/Cairo or whatever you 
use?

2. Can you separate the private user settings from application-wide by adding a path to the 
environment that would contain user's files and settings, something like "localtemf" in LaTeX 
installations. Over the years of using Ipe I have accumulated qiute a number of my own 
snippets. Any time you upgrade Ipe to the new version I need to move these files between 
the folders.



On 11 May 2020 at 2:54, Otfried Cheong wrote:

> 
> It's a bug in the ipelet: it leaves the page with only secondary selections and no primary selections. 
> Unfortunately I cannot transfer this issue to https://github.com/PhKindermann/ipe-simplify/issues 
> ...
> The code
> 
>       for _, i in ipairs(t.selection) do
>         p:setSelect(i, 2)
>       end
> 
> 
> should just be deleted from each of the functions, it does only harm and no good.
> I've added a check to Ipe so that after an ipelet returns it makes sure a primary selection exists 
> again.
> For the moment, all you need to do is to deselect the object and select it again, and the right-click 
> menu will work correctly.
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.


Yours sincerely
Marek L. Szwabowicz
_________________________________________________
E-mail: m.szwabowicz@wm.umg.edu.pl
_________________________________________________
MARITIME ACADEMY
Faculty of Marine Engineering
ul. Morska 83
81 - 225 Gdynia, POLAND

Tel. 0 58 55 86 452
Fax  0 58 55 86 399
_________________________________________________


---
Niniejsza korespondencja przeznaczona jest tylko dla osoby lub podmiotu, do ktorego jest zaadresowana. Wykorzystanie, przekazanie, rozpowszechnianie lub innego rodzaju przetwarzanie otrzymanej korespondencji - gdy nie jest Pani/Pan jej adresatem - jest zabronione. W takiej sytuacji konieczne jest natychmiastowe skasowanie korespondencji i zawiadomienie o tym nadawcy.
Administratorem Pani/Pana danych osobowych jest Uniwersytet Morski w Gdyni. Administrator wyznaczyl Inspektora Ochrony Danych (email: iod@umg.edu.pl).
Zasady przetwarzania danych osobowych zawarto na stronie https://www.umg.edu.pl/prywatnosc/
---

**Comment by otfried** [comment]
1. If you are on Windows:  the toolbar is laid out by the system, and it makes those selectors wider to fill the space.   It would not do that if they really fit on one line.    If it does, then that's a but, you should file a report with some screenshots.

Note that you an play with the ordering by changing the settings:
```
prefs.win_toolbar_order = { "snap", "grid", "angle", "edit", "mode" }
prefs.win_mini_edit = false
```

**Comment by otfried** [comment]
2.  This is already possible.   On Unix, user settings are in `~/.ipe`.   On Windows, you should make folders for your customization, and then tell Ipe about them by setting an environment variable.

See http://ipe.otfried.org/manual/manual_52.html

**Comment by marszw** [comment]
Here is the screen dump of raw settings without my intervention:



And this is the result of my reordering of the toolbars:


I see now that after you added the additional "Snap to custom grid" button the stuff does not 
fit into one line, but it actually did in 7.2.15 version of Ipe, although the layout resembled the 
one from the first picture.

But if all that is controled by the OS not much can be done I gather.




On 11 May 2020 at 4:33, Otfried Cheong wrote:

> 
> *   If you are on Windows: the toolbar is laid out by the system, and it makes those selectors 
>     wider to fill the space. It would not do that if they really fit on one line. If it does, then that's a 
>     but, you should file a report with some screenshots.
> Note that you an play with the ordering by changing the settings:
> 
> prefs.win_toolbar_order = { "snap", "grid", "angle", "edit", "mode" }
> prefs.win_mini_edit = false
> 
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.


Yours sincerely
Marek L. Szwabowicz
_________________________________________________
E-mail: m.szwabowicz@wm.umg.edu.pl
_________________________________________________
MARITIME ACADEMY
Faculty of Marine Engineering
ul. Morska 83
81 - 225 Gdynia, POLAND

Tel. 0 58 55 86 452
Fax  0 58 55 86 399
_________________________________________________


---
Niniejsza korespondencja przeznaczona jest tylko dla osoby lub podmiotu, do ktorego jest zaadresowana. Wykorzystanie, przekazanie, rozpowszechnianie lub innego rodzaju przetwarzanie otrzymanej korespondencji - gdy nie jest Pani/Pan jej adresatem - jest zabronione. W takiej sytuacji konieczne jest natychmiastowe skasowanie korespondencji i zawiadomienie o tym nadawcy.
Administratorem Pani/Pana danych osobowych jest Uniwersytet Morski w Gdyni. Administrator wyznaczyl Inspektora Ochrony Danych (email: iod@umg.edu.pl).
Zasady przetwarzania danych osobowych zawarto na stronie https://www.umg.edu.pl/prywatnosc/
---

The following section of this message contains a file attachment
prepared for transmission using the Internet MIME message format.
If you are using Pegasus Mail, or any other MIME-compliant system,
you should be able to save it or view it from within your mailer.
If you cannot, please ask your system administrator for assistance.

   ---- File information -----------
     File:  hts_1.PNG
     Date:  11 May 2020, 16:58
     Size:  344140 bytes.
     Type:  Unknown

The following section of this message contains a file attachment
prepared for transmission using the Internet MIME message format.
If you are using Pegasus Mail, or any other MIME-compliant system,
you should be able to save it or view it from within your mailer.
If you cannot, please ask your system administrator for assistance.

   ---- File information -----------
     File:  hts_2.PNG
     Date:  11 May 2020, 16:58
     Size:  358518 bytes.
     Type:  Unknown

**Comment by otfried** [comment]
If you want to include screen shots, you have to do it on the webpage (https://github.com/otfried/ipe-issues/issues/315).  It doesn't work if you just reply to the email.

I suspect that when you got it to fit on one line, you rearranged the bars slightly - so you can definitely try to play around with the prefs settings.   
If you set `prefs.win_mini_edit` to `true`, then the edit toolbar will be much shorter (I personally never use those buttons).
