### ISSUE TITLE
href does not work in Ipe 7.2.13

### ISSUE THREAD

**Issue by CsatiZoltan** [otfried/ipe#316]
`\href{https://google.com}{text}` throws the error
```
{/usr/local/texlive/2020/texmf-var/fonts/map/pdftex/updmap/pdftex.map}
! pdfTeX error (ext4): link annotations cannot be inside an XForm.
```
even though *hyperref* is added to the preamble.

**Comment by otfried** [comment]
`\href` cannot be supported by Ipe because of the way link annotations work in PDF.

You will need to use a group object and add the link destination to that.

**Comment by CsatiZoltan** [comment]
OK, [found it](http://ipe.otfried.org/manual/manual_19.html). Thanks.
