### ISSUE TITLE
Trying to modify a path caused ipe to crash repeatedly

### ISSUE THREAD

**Issue by nonamedotc** [otfried/ipe#318]
The following crash happens on Fedora 32, Ipe 7.2.17.

Steps to reproduce: 
1) open the attached pdf in ipe
2) enable "snap to intersection" (F6)
3) move the mouse somewhere around w_i (approximately -- it is very easy to trigger)

**Result:**
ipe crashes.

PDF with problem is attached.

Downstream bug report: https://bugzilla.redhat.com/show_bug.cgi?id=1836143

[odd-even-path.pdf](https://github.com/otfried/ipe-issues/files/4654235/odd-even-path.pdf)

**Comment by otfried** [comment]
Which version of libgsl is this with?

It seems there was a change in libgsl - the newer version returns an error code, the older version aborts.   Ipe should better not rely on the error code then.

**Comment by otfried** [comment]
Ah, it turns out you need to explicitly turn off the GSL internal error handling to even get the error codes returned.

**Comment by otfried** [comment]
Fixed in 7.2.18.

**Comment by nonamedotc** [comment]
Thank you for fixing this! 

Do you have a patch I can apply downstream until 7.2.18 is released?

**Comment by otfried** [comment]
Here you are.

[gsl-patch.txt](https://github.com/otfried/ipe-issues/files/4657536/gsl-patch.txt)
