### ISSUE TITLE
Opacity for layers

### ISSUE THREAD

**Issue by jonaprieto** [otfried/ipe#319]
Hi,

Is there any way I can have a layer with certain opacity? At the moment, I have to select the objects in the layer I want, and then make every object have such an opacity. 

However, it would be nice to have that option but for the whole layer. 

Thanks

**Comment by otfried** [comment]
Ipe does not (yet) support transparency groups, so having opacity on layers isn't as useful as it might sound (when two objects in that layer overlap, the effect wouldn't be what it should be for a semi-transparent layer).

Also, layers in Ipe really are not "layers" - they have nothing to do with the back-to-front ordering of the objects.   That makes the whole concept of layer opacity somewhat questionable.

You can already group the objects, set transparency on the group, and edit the contents of the group as a layer.

**Comment by jonaprieto** [comment]
> You can already group the objects, set transparency on the group, and edit the contents of the group as a layer.

I see. This is good enough to me. ;)
