### ISSUE TITLE
Snapping with splines is incorrect

### ISSUE THREAD

**Issue by Willem3141** [otfried/ipe#32]
It seems that there is a precision issue / bug with the snap-to-intersection mode if splines are involved.

To reproduce, draw two splines, or a line segment and a spline, that intersect each other. Enter the snap-to-intersection mode and hover above the intersection point. In many cases, the intersection point indicated by Fifi will be displaced slightly from the actual intersection.

A test case is [here](http://wimiso.nl/random/spline-intersection-test-case.ipe); I placed orange marks on the intersection points that Ipe indicates. Here is a screenshot of the worst case I could find:
![schermafdruk3](https://cloud.githubusercontent.com/assets/7533280/11557054/e636a6ac-99aa-11e5-9da1-4ce40c761fd0.png)

I'm using Ipe 7.1.10 on Kubuntu (Linux).

**Comment by Willem3141** [comment]
This is also reproducible with Ipe 7.1.10 on Windows 8, and Ipe 7.1.4 on Kubuntu. Unfortunately, I can't find older versions to test with.

**Comment by otfried** [comment]
This has always been the case in Ipe.  The spline intersection code was contributed years ago, it just approximates the splines by polygonal curves and then computes the intersections points.  

I need to look at this again some time.

**Comment by derekwolfson** [comment]
This is extremely annoying behavior.  I'd like to spline to respect the intersections at the grid points that I tell it to.  

This makes it next to impossible to draw horizontal and vertical lines to the axes at various points (unless I'm just a noob and there is some way to force lines to be horizontal and vertical!).

**Comment by otfried** [comment]
@derekwolfson I'm sorry, but I have no idea what you are trying to say.   What does "I'd like to spline to respect the intersections at the grid points that I tell it to." mean?

To force horizontal and vertical lines, set the angular grid to 90 degrees, and turn on angular snapping (F8) or automatic snapping (F9), depending on your needs.

I don't understand what horizontal/vertical lines have to do with intersections of splines.

**Comment by derekwolfson** [comment]
Otfied – I won’t even try and explain myself since it isn’t well defined.

 

The Angular + Automatic snapping you told is the correct and well-functioning workflow to get what I want accomplished.  

 

I could explain more – but it will just distract from this issue.

**Comment by derekwolfson** [comment]
@otfried -- it is the same behavior that is mentioned above.  Using this picture

![Image of Yaktocat](https://cloud.githubusercontent.com/assets/7533280/11557054/e636a6ac-99aa-11e5-9da1-4ce40c761fd0.png)

I want the spline to respect that I **want** it to intersect at the grid point underneath the orange circle, even as I add more points to the spline.

However, the work-around you gave re: the horizontal and vertical lines allows me to have intersections of a spline and a line with webbing back to the axes, even when the intersection of the spline and the line are **not** on a grid-point:

![capture](https://cloud.githubusercontent.com/assets/6483319/19292091/6dda288a-8fce-11e6-97bf-f8dcfcc5e900.PNG)

Thanks for dealing with my n00bness.

**Comment by otfried** [comment]
Let's merge this with #116
