### ISSUE TITLE
Saved file cannot open

### ISSUE THREAD

**Issue by MasahiroMae** [otfried/ipe#320]
When I saved Ipe or pdf, and try to open again, the message "The document was created by a newer version of Ipe" is appeared and cannot open.

My environment is Windows 10 64 bit, and Ipe 7.2.18.

**Comment by otfried** [comment]
My apologies.   It seems I edited some files on a virtual machine where the clock was wrong, and they were not recompiled when I built the Windows packages.

I've now done a full rebuild and uploaded the packages again (just download 7.2.18 again).

**Comment by MasahiroMae** [comment]
Thanks for your quick fixing!
