### ISSUE TITLE
Can't donate

### ISSUE THREAD

**Issue by dpaleka** [otfried/ipe#323]
(This is probably off-topic, but I couldn't find where else to put it.)

After Ipe saved me several hours for like fourth time this year, I decided to finally start supporting the project by a small amount every now and then. However, options for donating are:
a) make a Patreon account - it's too much of a commitment for one project, and it asks for information I am not comfortable giving
b) make a PayPal account - I wanted to, but it crashes on me? The UI is terrible.

If the author feels like it, I would suggest setting up a Ko-fi or buymeacoffee.com, or anything that allows people to donate a small amount every now and then using only a credit card. If it's too much of a nuisance, I'm sorry for bothering you.

**Comment by otfried** [comment]
Thanks for your support, and thanks for pointing out the issues with the existing options!  They are all based on what users suggested.

I've created a Ko-if page, it's here:

https://ko-fi.com/ipe7author
