### ISSUE TITLE
Saving/opening files in ipe 7.2.18 on Mac OS 10.15.4

### ISSUE THREAD

**Issue by mnoellenburg** [otfried/ipe#324]
I have issues with file handling and Latex compilation in ipe since upgrading to ipe 7.2.18 (binary package from ipe.otfried.org) on my MacBook running Mac OS Catalina 10.15.4. 

If I start ipe, create a new drawing with, say, a rectangle and no Latex text, and then want to save this, ipe stalls with a message "Compiling Latex". If I create the same empty figure, but with at least one piece of text, it works fine. 

Similarly, if I open a .ipe file that contains no Latex code, I get the "Compiling Latex" message, ipe stalls and I have to kill the process.

Any idea how to fix this?

**Comment by otfried** [comment]
I just fixed this two days ago - you'll need to download the `ipe-7.2.18-mac.dmg` package again.

I really shouldn't be uploading fixes under the same name, but doing it right is so much hassle ...

**Comment by mnoellenburg** [comment]
Thanks, that fixed it :)
