### ISSUE TITLE
Fix description of spline modes in manual

### ISSUE THREAD

**Issue by weidmrbh** [otfried/ipe#325]
following the below instructions to create a bezier curve does not work for me in the latest Windows version:

To add a quadratic Bézier spline (that is, a parabola), click twice in polyline mode for the first two control points. Then press the q key and click on the third (last) control point.

Circular arcs do work, so I am probably doing it the right way.

Circular arcs can be added as follows: Click twice in polyline mode, once on the starting point of the arc, then on a point in the correct tangent direction. Press the a key, and click on the endpoint of the arc.

**Comment by otfried** [comment]
This part of the manual is completely outdated.   There are no longer separate modes to draw cubic and quadratic splines:   Simply draw a spline with three control points, and you will get a quadratic Bezier spline (a parabola).

There is one other way to create a parabola:   Draw a line segment and a marker, then select both (with the segment as the primary selection) and choose "Ipelets -> Goodies -> Make parabolas".  This will create the parabola that is equidistant from the point and the segment.

**Comment by weidmrbh** [comment]
thank you for the quick reply.

**Comment by otfried** [comment]
Let me keep this issue open to remind me that I need to correct the manual.
