### ISSUE TITLE
Crash when text label -> symbolic text size

### ISSUE THREAD

**Issue by StefPillaert** [otfried/ipe#327]
I open a blank file. I put in a "Text Label" by clicking on the "A" button. I type in some text "test", I see a message "compiling LaTeX", and the label appears. All fine!
Then immediately after that (label is still red="selected"?), I click on button to change text size (see screenshot). Then again a message appears with "compiling LaTeX", and then, after a pause.... a crash.

![screenshot](https://user-images.githubusercontent.com/34961219/84033393-0f4cc000-a999-11ea-937f-a486459a567f.png)

**Comment by otfried** [comment]
You are amazing - already the second serious crash that nobody else seems to have noticed yet!

Here is a fixed version:

[ipe-7.2.18-win64.zip](https://github.com/otfried/ipe-issues/files/4748225/ipe-7.2.18-win64.zip)
