### ISSUE TITLE
ipe tool, latex text not able to run

### ISSUE THREAD

**Issue by pramodachar** [otfried/ipe#329]
I was trying to add latex text/symbols in ipe tools, but it's popping out error shown in the image.
I tried to add the path as an environment variable as C:\Users\Pramod\AppData\Local\ipe where "runlatex" file located , still got the same error. Please could you please help?

![Capture2](https://user-images.githubusercontent.com/43794641/84111215-17ae0500-aa44-11ea-88b2-1c68b52cf10b.PNG)

**Comment by otfried** [comment]
Well, did you install Latex on your computer?   If you open a command window (press Windows+R and type "cmd"), and type "pdflatex" into the command window, does it find the pdflatex program?

Please remove the environment variable - of course Ipe already knows where "runlatex.bat" is located - Ipe created this file itself.

If you did not install Latex and do not wish to do so, then you can still use Ipe by using online Latex compilation (Help menu -> Enable online Latex-compilation.

**Comment by pramodachar** [comment]
> 
> 
> Well, did you install Latex on your computer? If you open a command window (press Windows+R and type "cmd"), and type "pdflatex" into the command window, does it find the pdflatex program?
> 
> Please remove the environment variable - of course Ipe already knows where "runlatex.bat" is located - Ipe created this file itself.
> 
> If you did not install Latex and do not wish to do so, then you can still use Ipe by using online Latex compilation (Help menu -> Enable online Latex-compilation.

Thank you , the problem was with cmd prompt was not opening, fixed the registry , now ipe is working fine.
