### ISSUE TITLE
copy-paste text label with equation ($...$): no equation anymore

### ISSUE THREAD

**Issue by StefPillaert** [otfried/ipe#330]
Rather "strange behaviour" than a bug, maybe?
Create text label with LaTeX equation in it. (e.g. $2\mathrm{m}$).
Immediately after that (so label still "selected") type ctrl-C.
Then ctrl-V seems to give a text label without "running" LaTeX, you see the source.
But also: the two $ signs have disappeared in the copying proces.

When adding a new text label, the other (copied) labels seem to get interpreted suddenly. 

But $-signs gone "for ever" in copied label, so is it still an equation or not? Not clear to me...
![screenshot](https://user-images.githubusercontent.com/34961219/84145358-040d9900-aa5a-11ea-9f09-0ca0b125d5ff.png)

Stef

**Comment by otfried** [comment]
You'll need to run latex (Ctrl+L, in the file menu) to update your text objects.    Ipe does this automatically when it knows that it's necessary, but that doesn't apply to copy & paste.

Check the "mode" of your text objects: you'll find the new ones have mode "math", so they don't need the dollar signs.

**Comment by StefPillaert** [comment]
OK, thanks!
