### ISSUE TITLE
Bookmark links not working with "ipetoipe -markedview"

### ISSUE THREAD

**Issue by joklawitter** [otfried/ipe#331]
When using `ipetoipe -pdf -markedview ...` for slides, the bookmarks for sections and subsections appeard but the links don't work if the marked view was the first (only) view.

**Comment by otfried** [comment]
Thanks so much for getting me to look at this!

Countless times I was annoyed that this didn't work when I made handouts for students - but always was too busy to fix it right away.

It turned out the fix was entirely trivial...   Bookmarks will now always point to the first view of the page.
