### ISSUE TITLE
On MacOS, ipe 7.2.18 stalls saying "latexing..." whenever I save a picture without text in pdf format

### ISSUE THREAD

**Issue by saschawolff** [otfried/ipe#332]
I haven't had this problem with any other recent version of ipe, so it's unlikely that the problem is due to my LaTeX setup (which hasn't changed recently).

**Comment by otfried** [comment]
Can you check if the "solution" in #324 works for you?

**Comment by saschawolff** [comment]
It does. Thanks, Otfried and sorry for not seeing the list of closed issues.
The other issue I just described (which is much easier to live with) persists.
Sascha
