### ISSUE TITLE
Stability issue IPE 7.2.18

### ISSUE THREAD

**Issue by brianjoubert** [otfried/ipe#334]
Hello,

I have stability issues with IPE 7.2.18 on Windows 10. Basically when I enter a text in latex it works correctly until the moment I want to change the textsize using the left toolbar. The software starts compiling latex and then crashes all the time. If I do a right click on the text and change it there it works fine.

**Comment by otfried** [comment]
I've just fixed this and will release a new version shortly.  In the meantime, you can use this one:

https://github.com/otfried/ipe-issues/files/4758721/ipe-7.2.18-win64.zip
