### ISSUE TITLE
URI too large error on Ipe file

### ISSUE THREAD

**Issue by rjanar** [otfried/ipe#335]
I started creating an Ipe figure by typing some text labels at various places in the canvas (and nothing else like shapes etc. so far) Each label is a single alphanumeric character. The first 16 labels work fine. Upon typing the 17th label I get the following error. I am running Ipe 7.2.13 on Windows 10 and have the "Automatically run Latex" option (under File) checked. I am able to replicate the issue reliably across several days and different files, so it does not appear to be a transient issue at the server.  Here is a screenshot. Quite puzzling...any help would be appreciated. Thanks.

![screenshot](https://user-images.githubusercontent.com/67062343/84917688-41d77680-b085-11ea-9b73-df99c53b06b1.png)

**Comment by otfried** [comment]
Apparently the latex-online service changed, and can now handle only quite small URLs, so it no longer works to send the Latex file through the URL.

I'll have to rewrite how the online service is accessed.  On Linux/OSX this is easy, I'll have to figure out what to do on Windows...

**Comment by rjanar** [comment]
Thank you for the quick reply. 

Is the URL dependent on the file contents somehow (as the problem seems to occur on only certain files, as far as I can tell)? Or can the user specify a small URL somehow?  As recently as 6 weeks ago I was generating fairly complex IPE files (with a mix of shapes, text, and layers) and this problem did not occur.

Is there a way to avoid using the online service and compile the file locally (and automatically)?

**Comment by otfried** [comment]
In the current version, the Latex file is encoded in the URL.  There has been a recent change in latexonline.cc, and apparently now there is a much smaller limit on the length of the URL that it accepts.

If you install Latex on your computer (Miktex or texlive are popular on Windows), then you don't need to use the online service.

But I think I'll be able to solve the issue quickly (hopefully tomorrow), by using a different method for transferring the file.

**Comment by rjanar** [comment]
Thank you very much. In the meantime I have a local installation of MiKTeX now and it seems to have solved the problem (though some commands like \dfrac and \binom are not being recognized in Ipe, even though the relevant packages are installed in MiKTeX).

**Comment by otfried** [comment]
Did you declare the relevant packages in the preamble?

If you still want to use the online Latex service, here is a version where it will work:

[ipe-7.2.19-win64.zip](https://github.com/otfried/ipe-issues/files/4795114/ipe-7.2.19-win64.zip)

**Comment by rjanar** [comment]
Ah, I  did not even know about this option to declare packages in Ipe (so used to declaring packages in Latex source files only). Thanks.
