### ISSUE TITLE
Error on building at Ubuntu 16

### ISSUE THREAD

**Issue by hildogjr** [otfried/ipe#336]
I am building Ipe 7.2.19 from source in a Ubuntu 16.04. I already used past version and have all needed libraries installed.

I am getting the follow error:

```
In file included from /usr/include/c++/5/unordered_map:35:0,
                 from ../include/ipepdfparser.h:38,
                 from ipepdfparser.cpp:31:
/usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support \
  ^
In file included from /usr/include/c++/5/unordered_map:35:0,
                 from ../include/ipepdfwriter.h:42,
                 from ipepdfwriter.cpp:38:
/usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support \
  ^
In file included from /usr/include/c++/5/unordered_map:35:0,
                 from ../include/ipepdfparser.h:38,
                 from ../include/iperesources.h:37,
                 from iperesources.cpp:31:
/usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support \
  ^
In file included from /usr/include/c++/5/unordered_map:35:0,
                 from ../include/ipepdfparser.h:38,
                 from ../include/ipelatex.h:39,
                 from ipelatex.cpp:35:
/usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support \
  ^
In file included from /usr/include/c++/5/unordered_map:35:0,
                 from ../include/ipepdfparser.h:38,
                 from ipedoc.cpp:37:
/usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support \

...


ipeplatform.cpp:54:27: fatal error: gsl/gsl_errno.h: No such file or directory
compilation terminated.
../common.mak:252: recipe for target '../../build/obj/ipelib/ipeplatform.o' failed
```

**Comment by otfried** [comment]
Well, apparently you did not install the `libgsl-dev` package (it was not used in earlier versions).

What command is used to compile `ipepdfparser.cpp`?   (make should output this just before you see the first error message.)

**Comment by hildogjr** [comment]
I have this follow dependencies installed:

```
sudo apt -y install checkinstall zlib1g-dev libgsl-dev
sudo apt -y install qtbase5-dev qtbase5-dev-tools
sudo apt -y install libfreetype6-dev libcairo2-dev libjpeg-dev
sudo apt -y install libpng16-dev liblua5.3-dev
```
Just `libcurl-openssl-dev` that is not available on Ubuntu 16.04. I had installed `libcurl4-openssl-dev` instead.

I try to compile by:
```
export QT_SELECT=5       
    make IPEPREFIX=/usr/local
    sudo checkinstall --pkgname=ipe --pkgversion=7.x.y --backup=no \
    	 --fstrans=no --default make install IPEPREFIX=/usr/local
    sudo ldconfig
```
Attached the build log.
[Build.log](https://github.com/otfried/ipe-issues/files/4794583/Build.log)

**Comment by otfried** [comment]
Apparently the "make depend" fails because it doesn't set `-std=c++14` - but that's not a serious error, the dependencies are created anyway.

However, you did not correctly install freetype2 and cairo.  Also, you did not install libgsl-dev (the list you mention above is not complete, please look in `install.txt` for up-to-date instructions).

Why don't you use the Ubuntu 16.04 package that I provide?

**Comment by hildogjr** [comment]
I using this script mine for build since before the package were available (and it does some extra configurations as shortcut, copy my templates, ...).

Yes, I had ran `sudo apt -y install libfreetype6-dev libcairo2-dev`.


I can build the 7.2.14 version. On 7.2.15 that this error start to appear.

**Comment by hildogjr** [comment]
I using this script mine for build since before the package were available (and it does some extra configurations as shortcut, copy my templates, ...).

Yes, I had ran sudo apt -y install libfreetype6-dev libcairo2-dev.

I can build the 7.2.14 version. On 7.2.15 that this error start to appear.

**Comment by otfried** [comment]
Well, as you can see from the build log, the settings for freetype and cairo are not correct:
```
Package cairo was not found in the pkg-config search path.
Perhaps you should add the directory containing `cairo.pc'
to the PKG_CONFIG_PATH environment variable
No package 'cairo' found
Package freetype2 was not found in the pkg-config search path.
Perhaps you should add the directory containing `freetype2.pc'
to the PKG_CONFIG_PATH environment variable
No package 'freetype2' found
```

You should check that running `pkg-config` will find the packages.  The output should look like this:
```
~/Devel/ipe$ pkg-config --cflags --libs freetype2
-I/usr/include/freetype2 -I/usr/include/libpng16 -lfreetype
~/Devel/ipe$ pkg-config --cflags --libs cairo
-I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/libpng16 -lcairo
```

I know that Ipe compiles without problem on Ubuntu 16.04: 

https://build.opensuse.org/package/live_build_log/home:otfried13/Ipe/xUbuntu_16.04/i586

You can see in that build log that it also has the warnings about C++11 - those are harmless, they only happen during dependency creation, not during the actual compilation.

**Comment by hildogjr** [comment]
Thanks, already fix.

Nice new icons.
