### ISSUE TITLE
layers from third column onwards can't be activated

### ISSUE THREAD

**Issue by IPEfluencer** [otfried/ipe#337]
When you have many layers and need to click on a layer e.g. at the third column of the "Layers" list (left-hand side of IPE window), the displayed layer list jumps back to the very first column - making it impossible to activate such a layer by double-clicking, tested on Win 10 x64.

**Comment by otfried** [comment]
Can you attach a screen shot and an example file?   I didn't know Windows would show layers in more than one column.

**Comment by IPEfluencer** [comment]
Sure (columns 2 and 3 are visible here):
![IPE_layer_columns](https://user-images.githubusercontent.com/67276300/85298725-bb67ce00-b4a4-11ea-9cd5-e40ac222cf5c.PNG)

An example file can be easily created by adding dozens of empty layers: 
[example_many_layers.ipe.txt](https://github.com/otfried/ipe-issues/files/4815148/example_many_layers.ipe.txt)

**Comment by otfried** [comment]
Can you try this version?

[ipe-7.2.19-win64.zip](https://github.com/otfried/ipe-issues/files/4821938/ipe-7.2.19-win64.zip)

**Comment by IPEfluencer** [comment]
It works and looks like this:

![layers_new](https://user-images.githubusercontent.com/67276300/85606035-0a536600-b653-11ea-8829-99ba251d21af.PNG)

Now the layer becomes active after a single click[*] is performed (before: double-click). Was it intended? Anyway, I like it.

[*] = after a short delay of about one second (but I don't mind)

**Comment by otfried** [comment]
Yes, that was an intended change.  On Linux and MacOS, you select the active layer with a single click.  When I originally implemented the layer list on Windows, I didn't find the option that enabled this behaviour - I discovered it while figuring out how to solve the bug you reported.
