### ISSUE TITLE
online LaTeX-compilation fails when IPE path contains a space (Windows)

### ISSUE THREAD

**Issue by IPEfluencer** [otfried/ipe#339]
I get the following error on Windows 10 (x64), when IPE is located at a path that contains spaces, e.g. C:\Program Files\ipe-7.2.19:

![ipe_latex_online](https://user-images.githubusercontent.com/67276300/85433320-8df25180-b584-11ea-804c-60a14b3123cb.PNG)

I'm not sure whether this is related to #297, which is, however, marked as closed and fixed. Anyway, I found the root cause for my issue: It would work if the last line of _runlatex.bat_ created at C:\Users\\%Username%\AppData\Local\ipe\ was (for my example) changed from

`C:\Program Files\ipe-7.2.19\bin\ipecurl.exe pdflatex`

to

`"C:\Program Files\ipe-7.2.19\bin\ipecurl.exe" pdflatex`
(path was put in quotation marks)

Since _runlatex.bat_ is rewritten dynamically this needs to be adapted in the implementation.

**Comment by otfried** [comment]
Thanks for diagnosing the problem - will be fixed in 7.2.20.
