### ISSUE TITLE
ipe crashes when changing width of text field to negative value

### ISSUE THREAD

**Issue by J-0e** [otfried/ipe#340]
Changing the width of a minipage text field, I was able to set the end of the text field to the left hand side of its beginning. Then, however, ipe crashes. A behaviour similar to initializing the text field would be an option but avoiding the crash would be sufficient, in my opinion. On this occasion: thanks for the autosave feature ;)

**Comment by otfried** [comment]
Which Ipe version are you using?   I cannot reproduce this on 7.2.19, it only says "The width of a text object should be positive".

**Comment by J-0e** [comment]
I missed to check this beforehand, sorry. It's 7.2.12 (there was no need for an update). It's working in 7.2.19 as you described.
