### ISSUE TITLE
online LaTeX-compilation fails for unknown reason

### ISSUE THREAD

**Issue by IPEfluencer** [otfried/ipe#343]
When I try to use online Latex-compilation of the current IPE version 7.2.20 at work, I get this error message (Windows 10, x64):
![](https://user-images.githubusercontent.com/67276300/85433320-8df25180-b584-11ea-804c-60a14b3123cb.PNG)
I certainly have an internet connection at work, but maybe there is some network problem though (everything works well on my PC at home).

For investigation purposes I tested _runlatex.bat_ at cmd and get the following screen:
```
...
C:\Users\IPEfluencer\AppData\Local\ipe>H:\Software\ipe-7.2.20\bin\ipecurl.exe pdflatex
Error 12005 in WinHttpConnect.
```
I won't get any support from the company's IT - do you have any solution for that issue?

**Comment by otfried** [comment]
What is the contents of the file `C:\Users\IPEfluencer\AppData\Local\ipe\url.txt`?

**Comment by IPEfluencer** [comment]
This is the original file:

[url.txt](https://github.com/otfried/ipe-issues/files/4879277/url.txt)

**Comment by otfried** [comment]
Ah, that explains it.

Can you just disable online Latex-compilation (from the Help menu in Ipe), and enable it again?   That should fix the problem.

**Comment by IPEfluencer** [comment]
Now the error messages changes to:
`Error 12175 in WinHttpSendRequest or WinHttpReceiveResponse.`
The new url file is:
[url.txt](https://github.com/otfried/ipe-issues/files/4898808/url.txt)

**Comment by otfried** [comment]
Error 12175 is an error with SSL encryption - perhaps there is something in your company network that stops this from working.

You could try changing the preference:
```
prefs.latex_service_url = "http://latexonline.cc"
```
(So change `https` to `http`.)

**Comment by IPEfluencer** [comment]
It works! Can this modified URL become the standard one? Otherwise, an entry in the FAQ would be good.

**Comment by otfried** [comment]
I don't want to switch everybody to the insecure channel, so I've added an entry to the FAQ.
