### ISSUE TITLE
Deleting default grid sizes from stylesheet breaks the selection

### ISSUE THREAD

**Issue by thobl** [otfried/ipe#344]
Way to reproduce:
Edit the "basic" style sheet and remove the line `<gridsize name="4 pts" value="4"/>`

Issue:
The combobox for the grid sizes still shows the default grid sizes (including 4 pts) and additionally has all non-deleted grid sizes a second time. Selecting one of the additional copies seems to actually select the correct grid size but then shows the wrong size in the combobox.
The correct list of grid sizes is shown in the menu Snap -> Grid size

**Comment by otfried** [comment]
Fixed in 7.2.21.
