### ISSUE TITLE
You can only snap to the midpoint of 3 out of 4 sides of a rectangle

### ISSUE THREAD

**Issue by DirkGerrits** [otfried/ipe#346]
**Reproduction scenario:** 

- Draw an axis-parallel rectangle [B].
- Enable control point snapping [shift+F4]. 
- Move the mouse cursor along the boundary of the rectangle. 

**Expectation:** Snapping will occur at the midpoints of the 4 sides, and nowhere else.

**Reality:** Snapping occurs at the starting vertex ("m" command in the underlying XML), and the midpoint of 3 of the 4 sides (the ones with the "l" command in the XML, not the one with the "h" command).

Polygons [shift+P] seem to behave similarly.

The problem seems to occur at least in Ipe versions 7.2.18 - 7.2.20, possibly more.

**Comment by otfried** [comment]
Fixed in 7.2.21.
