### ISSUE TITLE
Vertex-snap to image corners

### ISSUE THREAD

**Issue by ghali** [otfried/ipe#348]
- Write the following lines in a file checkerboard.pgm:

P2
3 3
1
0 1 0
1 0 1
0 1 0

- Convert the file to PNG (`convert checkerboard.pgm checkerboard.png`).

- Using Ipe 7.2.20, File \ Insert Image.. and choose checkerboard.png.

- Enable "Snap to Vertex (F4)".

- The cursor should now snap to the four corners of the image.

Even if the image is a photograph with no sharp features, the four corners are well-defined, and hence the cursor should snap to the corners if vertex snapping is enabled.

This of course opens more issues (edge and intersection snapping), but it would be nice to be able to position images without building (then hiding or deleting) bounding boxes.

**Comment by otfried** [comment]
The corners of images are not considered vertices, but control points (like centers of circles and midpoints of segments).

So you need to switch on "Snap to control point"  (Shift-F4).
