### ISSUE TITLE
Pen on MacOS -- questions

### ISSUE THREAD

**Issue by boris-aronov** [otfried/ipe#350]
Context: I am trying to use Ipe with an [ancient] Intuos graphics tablet plugged into a [not very new] Macbook Pro.

This is probably silly, but: I am trying to use the pen to "write" in Ipe, i.e., produce scribbles resembling handwriting.  By just clicking on the "Ink" icon on the top and using the pen.  My question is: What are the objects produced by this?  Are they paths?  What controls their properties?   On Wednesday I tried this in class and for some reason the paths had "fill" property set, which made them act very weirdly when I tried to circle something (as you might imagine...). 

*Also:* any hints on what properties to set to have the result look more like actual handwriting?  Not sure if I know how to formulate it precisely.

**Comment by otfried** [comment]
Yes, the ink tool produces normal path objects, so you'll need to make sure to have it set to "stroke only".

There are quite a few people who use this to annotate their slides during a lecture, and Ipe has recently added some better support for this: http://ipe.otfried.org/manual/filming.html

These quickstyles https://github.com/andreschulz/ipe_quickstyles were explicitly created for this purpose.

As for making ink look more like handwriting:  My experience is that different pens/tablets give very different results, and so I have no general answer to this.   If you search in `prefs.lua` for `prefs.ink_`, you'll find several settings that you can tweak to get a nicer result with your hardware.

**Comment by boris-aronov** [comment]
Thank you.  Another question: Is it possible to have the "Properties" panel on the left disappear or pop up on request only?  I saw that the menu bar (if that's what it's called) and the snapping thing can be disappeared as per the instructions in <http://ipe.otfried.org/manual/filming.html>.

What does "pretty display" do?  There's no mention of it in the manual.

About tuning to accommodate my digitizer: I have not quite figured out what it is that makes the result less than perfect.  I will try paying attention next time.  I was so thrilled that it worked at all. :-)

**Comment by otfried** [comment]
"Pretty display" makes the canvas look like in a presentation - it removes all auxiliary stuff like the dotted rectangle around a text object.

There is currently no way to hide the properties panel on macOS, because the users who film from the Ipe canvas seem to simply set up their camera software to only record the canvas area of the screen.   But that would be easy to add if it is useful.

**Comment by boris-aronov** [comment]
_Pretty_: Thanks.  Understood.

_Panel/camera:_ My use case is Zoom, which allows to pick which window to share (and on Android it seems to only want to share the entire screen), but I _do not think_ it allows to pick the canvas only.  Would be happy to find out that I am wrong.

**Comment by otfried** [comment]
Here is a new MacOS version of Ipe where you can hide the properties panel and layer list on the left side ("Hide Properties Panel" in the Zoom-menu, Option-Command-P).

https://www.dropbox.com/s/q1skqecgdorz269/ipe-7.2.20-mac.dmg?dl=0

I could also try to make a version where the canvas is simply in a different window, so that one could use the canvas window as input for Zoom and still have all the controls in another window elsewhere on the screen.    But that'll have to wait until another day.

**Comment by boris-aronov** [comment]
Thanks, Otrfried!  Tried it extra quickly and it seems to work fine.   I guess the quickstyles mentioned above can be used for quickly switching, say, colors, so perhaps having the panel constantly available (even if in another window) is not so important.  Or at least that's what I say now. :-)

**Comment by pierreganty** [comment]
> Yes, the ink tool produces normal path objects, so you'll need to make sure to have it set to "stroke only".
> 
> There are quite a few people who use this to annotate their slides during a lecture, and Ipe has recently added some better support for this: http://ipe.otfried.org/manual/filming.html
> 
> These quickstyles https://github.com/andreschulz/ipe_quickstyles were explicitly created for this purpose.
> 
> As for making ink look more like handwriting: My experience is that different pens/tablets give very different results, and so I have no general answer to this. If you search in `prefs.lua` for `prefs.ink_`, you'll find several settings that you can tweak to get a nicer result with your hardware.

I have not tried it but there was an applet to simplify the paths you draw by hand:
https://github.com/phkindermann/ipe-simplify

**Comment by otfried** [comment]
If I remember right, the functionality of that ipelet was included in Ipe in 7.2.5:

> Improvements for ink mode to make it more responsive, less  memory-consuming, and display smoother strokes (thanks to Zhengdao  Wang and Philipp Kindermann for contributing code).

The relevant settings are `prefs.ink_smoothing` and `prefs.ink_tolerance`.
