### ISSUE TITLE
Crashes frequently when inserting text label after changing symbolic pen width and or symbolic text size

### ISSUE THREAD

**Issue by StefPillaert** [otfried/ipe#351]
I use latest version, and make use of active stylus all the time, Windows10.
See the subject of this issue for a description. I can not give an exact procedure to reproduce the bug, since sometimes there seems to be no problem, but sometimes IPE either crashes, or (more often) hangs at the message "compiling LaTeX". When it happens, it seems to be always triggered by changing symbolic pen width or symbolic text size (I use the buttons in the GUI to do this), and then clicking on the "A"-button to insert a text label.
The crash (or hanging) is always after closing the window where I have to enter the text.

**Comment by otfried** [comment]
Have you tried the workaround mentioned in #338 ?

**Comment by StefPillaert** [comment]
OK, I made the change in model.lua, until now I didn't have the problem yet.
Thanks,
Stef

**Comment by otfried** [comment]
Could you try the version I attached to #338 ?  I'm hoping that your problem is the same and that this version fixes it.

**Comment by StefPillaert** [comment]
OK, I've been trying very hard to create the problem, without succes!!! So it seems OK now, many thanks!
Stef
