### ISSUE TITLE
Prefs option to start ipe in full screen

### ISSUE THREAD

**Issue by joklawitter** [otfried/ipe#353]
Afaik there is only the option to set the initial windows size, but neither to set the initial position nor to start in full screen mode. Could this be added?

**Comment by otfried** [comment]
Which platform do you want this on?

**Comment by joklawitter** [comment]
Win10

**Comment by otfried** [comment]
Implemented in 7.2.21.   Here's a preview to try it:

[ipe-7.2.20-win64.zip](https://github.com/otfried/ipe-issues/files/5333004/ipe-7.2.20-win64.zip)

**Comment by joklawitter** [comment]
Thanks Otfried, for the fast implementation. This is a great view for when recording a lecture with ipe. :)
However, I have to apologize for my imprecise wording! What I actually meant was just a maximized window, like you can select in the top right.  (You can tell Windows to open an application maximized, but that setting is ingored when opening a file.)

**Comment by otfried** [comment]
Can't you get a maximized window by simply setting the dimensions of your screen, e.g.
```
prefs.window_size = { 3440, 1440, 0, 0 }
```
?

**Comment by joklawitter** [comment]
It is not maximized, but the new `x` and `y` coordinates are great. So this works for me. Thanks! :)

**Comment by otfried** [comment]
I've now added support for maximizing as well.   You'll need to set
```
prefs.start_screen = "maximized"
```

[ipe-7.2.20-win64.zip](https://github.com/otfried/ipe-issues/files/5378227/ipe-7.2.20-win64.zip)

**Comment by joklawitter** [comment]
:) Thanks! :)
