### ISSUE TITLE
UI elements broken on QT5.15.1 and MacOS Big Sur

### ISSUE THREAD

**Issue by jferlez** [otfried/ipe#357]
When built against QT5.15.1 on MacOS Big Sur, various UI elements either display incorrectly (e.g. toolbar buttons appear as text only) or don't function as expected (e.g. drop-down menus such as color chooser, grid-snap chooser, etc). See attachment.

As far as I know, QT5.14.x does not (yet?) build on Big Sur, which is why I am using QT5.15.1. There are some (pre-5.15.1) QT bugs filed that relate to UI elements on Big Sur (e.g. https://forum.qt.io/topic/117552/button-clicked-not-working-on-big-sur ), but I couldn't find any that obviously pertain to these IPE issues (from my inexpert assessment, anyway).

Finally, in the interest of full disclosure, I am using a modified version of the current Macports IPE port (to get IPE 7.2.21), and building against Macports installs of the prerequisites, including a modified QT port (to get QT5.15.1). But I didn't notice anything that suggests there was a build problem, either with QT or with IPE.

![Screen Shot 2020-11-16 at 3 07 13 PM](https://user-images.githubusercontent.com/28321792/99440283-2e963480-28cb-11eb-91e3-bec42128b049.jpg)

**Comment by otfried** [comment]
Why do you use Qt on MacOS instead of the native Cocoa UI?

**Comment by jferlez** [comment]
Honestly, I've always installed via Macports, which always builds using qt5. I didn't even realize that there was a native Cocoa UI!

**Comment by otfried** [comment]
The problems you see are purely that Ipe does not find the right resources (icons and style files), so something is broken with your configuration.

I recommend compiling from the original Ipe sources, following the instructions in `macos.txt`.  If you have macports, that's really trivial.

**Comment by jferlez** [comment]
Ok, I will do as you suggest. Thanks for your help! And I'm sorry for the misspecified bug report. (I will close the issue, so it doesn't create any other confusion.)
