### ISSUE TITLE
ending lines

### ISSUE THREAD

**Issue by fulvioforni** [otfried/ipe#36]
I cannot end a line with a final vtx, on mac.
- Double click does not work
- I am not sure I have a right-click on mac
- In the old versions of Ipe I was used to do a click while holding CTRL. This combination does not work anymore.

Thank you,
Fulvio

**Comment by otfried** [comment]
On a Mac trackpad, clicking with two fingers should work.

But I will also enable Ctrl+Click again.

**Comment by fulvioforni** [comment]
Thank you.

I just tried. On a Mac trackpad, clicking with two fingers works. It does not with a mouse.

I am looking forward to have the old CTRL + click re-enabled

Thank you,
Fulvio

**Comment by m7thon** [comment]
> On a Mac trackpad, clicking with two fingers should work.

No, this is a special setting that can be enabled or not. Alternative settings are clicking in lower left or right. The default is Ctrl+Click.

**Comment by otfried** [comment]
So Ipe never contained code for Ctrl+Left to act like a right click.  This must either have been a Qt "feature", or you had this setting enabled in your mouse preferences, as Michael says.

By the way, in my Trackpad preferences, Ctrl+Click does not exist.  The default seems to be clicking with two fingers.

And - as far as I know, even Apple mice had at least two buttons for many years.  Doesn't the right button work?

**Comment by fulvioforni** [comment]
Thank you for the detailed answer.

I do not aim to get CTRL+Click restored, as in the old version. But I would
like to have a way to "end" a line with an end point. I do not get that
whatever I try with my mouse (standard mac mouse, 2012): click with two
fingers together (like with trackpad), click right, click left for a long
time, double and triple left click... nothing work.

I guess ending a line should be an easy operation. It is indeed easy in the
old version, by Ctrl+Click, but there is no need to replicate that.
Whatever works would be great.

Thank you,
Fulvio

**Comment by otfried** [comment]
I've already implemented Ctrl-click as a right click in all tools.  You can try it in this version:

https://www.dropbox.com/s/nwnbhgjku87ueao/ipe-7.2.2-mac-a.dmg?dl=0

**Comment by fulvioforni** [comment]
Excellent. It works very well. Now I can use the new version. Thank you
very much.

Please let me know if you would like to be bothered about further possible
issues.

Thank you,
Fulvio

**Comment by otfried** [comment]
Certainly, please report any issues you find.

**Comment by gingerlong** [comment]
@otfried I am in Mac and I do not know how to change style of a line, by Ctrl+click it does not seem to work, could you please instruct me? Thanks!
