### ISSUE TITLE
Feature request: allow pages to be hidden from the final PDF

### ISSUE THREAD

**Issue by Steven--** [otfried/ipe#362]
Sometimes when working with presentation it is useful to hide a page from the final PDF.
Some use cases include keeping a fancy slide that ultimately did not make it into the final presentation, or shortening an existing talk.

Currently the only options are:
1) Moving the pages past the intended end of the presentation.
2) Making a copy of the presentation and deleting the unwanted slides.
3) Always marking every view in all pages and then using ipetoipe to export only marked pages.
4) Post-processing the output file to remove the extra pages (this destroys the additional ipe data embedded in the PDF).

It would be great if ipe allowed to include/exclude pages from the output pdf.
Perhaps this could be integrated with the existing page marks by adding a "Export only marked pages" option?

**Comment by otfried** [comment]
Implemented in 7.2.22.
