### ISSUE TITLE
\usepackage{amsmath} support?

### ISSUE THREAD

**Issue by EEsanity** [otfried/ipe#363]
Does IPE drawing support any features that is available in \usepackage{amsmath}?

I am very interested in aligning of multiple equations 

https://www.overleaf.com/learn/latex/Aligning%20equations%20with%20amsmath

Thanks a lot.

YZ

**Comment by otfried** [comment]
Yes, of course you can do this - there is nothing special about amsmath.

Just put `\usepackage{amsmath}` in your Latex preamble (Edit -> Document properties):
![image](https://user-images.githubusercontent.com/9983417/102688346-8be91280-41f6-11eb-982b-1762d43fe9d9.png)

And now you can use the commands in a paragraph object:
![image](https://user-images.githubusercontent.com/9983417/102688370-a02d0f80-41f6-11eb-8e0c-76b9ceb20865.png)

It just works:

![image](https://user-images.githubusercontent.com/9983417/102688381-af13c200-41f6-11eb-94c9-c1cc6f3e06f5.png)

**Comment by EEsanity** [comment]
You made my day! Thank you
Ye Z

**Comment by gujinwh** [comment]
The align environment (like many other environments) cannot be used
inside a Latex box.    You have to use it in a minipage.   In Ipe, use
"Paragraphs (G)", not "Text labels (L)".
