### ISSUE TITLE
Ipe crashes when  working with ipestyles

### ISSUE THREAD

**Issue by angiolo** [otfried/ipe#364]
Hi.
I recently installed Ipe7.2.23 on Ubuntu 20.04 and I realised that it closes unexpectedly, at least when updating stylesheets.

**Comment by otfried** [comment]
I cannot reproduce the problem.  Can you attach (or send me) an Ipe document that exposes the problem?

**Comment by otfried** [comment]
Did you install using my binary package?

**Comment by angiolo** [comment]
Hi.
I had the problem using the Ubuntu .deb package.
However, I desinstalled the application and this time I compiled the source (luckily without problems),
nad now the problems disappeard (up to now), so probably the problem is in the binary.
Greetings.
