### ISSUE TITLE
Pointing Ipe 7.2.23 to TeX Live 2020 on macOS 10.15.7

### ISSUE THREAD

**Issue by ghali** [otfried/ipe#366]
Ipe's connection to latex works in two of three scenarios.

My TeX installation on Catalina is at:

    > ls -l /usr/local/texlive/2020/bin/x86_64-darwin/{pdf,xe}latex
    lrwxr-xr-x  1 root  wheel  6 25 Jun  2020 /usr/local/texlive/2020/bin/x86_64-darwin/pdflatex -> pdftex
    lrwxr-xr-x  1 root  wheel  5 25 Jun  2020 /usr/local/texlive/2020/bin/x86_64-darwin/xelatex -> xetex

I edit /Applications/Ipe.app/Contents/Info.plist and modify the path:

     ...
    (key)LSEnvironment(/key)
    (dict)
      (key)PATH(/key)
      (string)/usr/local/texlive/2020/bin/x86_64-darwin:/Library/TeX/texbin:/usr/texbin:/usr/local/texbin:/usr/local/bin:/opt/local/bin:/usr/bin:/bin(/string)
    </dict)
    ...

When I run Ipe from the Terminal (with a path that includes /Applications/Ipe.app/Contents/MacOS/), Ipe calls {pdf,xe}latex fine, presumably because I have /usr/local/texlive/2020/bin/x86_64-darwin/pdflatex in IPEPDFLATEX and in PATH (not sure which one is used). Compiling in the cloud also works.

But when I launch Ipe by double-clicking in /Applications or in the Dock, I get

    Ipe did not succeed to run Latex to process your text objects.
    You either have no Latex installation on your computer, or the Latex executable is not on your command path.

**Comment by otfried** [comment]
Is your Info.plist correct?  The excerpt above shows round parentheses where angular brackets should be.

Note that editing `info.plist` is tricky.  On newer MacOS versions, system integrity protection doesn't allow you to make any changes, so you need to temporarily turn that off.  Another problem is that MacOS *cashes* the Info.plist file, so editing has no immediate effect, and you somehow need to get it to reload the new file.

It might be easier to set the environment variable IPELATEXPATH.  (Note that IPEPDFLATEX is not used anymore - since long ago, see http://ipe.otfried.org/manual/manual_53.html.)

If you create the file `~/.ipe/ipe.conf` with this contents:
```
IPELATEXPATH=/usr/local/texlive/2020/bin/x86_64-darwin
```
then this should be picked up when Ipe is started in any way (including from the dock).

**Comment by ghali** [comment]
Sorry, I omitted to mention that I was replacing the angle brackets with parentheses so that they show up in some way on github. Github's rich-text format interprets angle brackets as XML tags, making them disappear—and using HTML's &lt; and &gt; didn't work.

In the actual info.plist I did use angle brackets. Also, when I read (in the readme.txt in the macOS distribution) that I may have to log out and back in, I rebooted the machine for good measure.

But setting IPELATEXPATH in ~/.ipe/ipe.conf is much nicer, since it survives upgrading Ipe.

It's all good then, and so I won't go through disabling SIP (https://developer.apple.com/documentation/security/disabling_and_enabling_system_integrity_protection) at this time. By the way, on up to and including Catalina, the system will initially refuse to run a downloaded program, until one insists through "security & privacy" in the system settings. This seems to be distinct from disabling SIP.

Something else stopped working for me recently. It's a separate issue, but since it's rather minor, let me mention it here.

Until recently on macOS I was able to define keyboard shortcuts by adding in ~/Library/Ipe/Ipelets/customization.lua the lines

shortcuts = {
    ipelet_12_goodies = "Control+B", -- Insert bounding box
}

Now this shortcut no longer works. Has the format changed?

**Comment by otfried** [comment]
You can show verbatim text by marking it using the "Insert code" button (or writing triple back-quotes before and after).

The correct format for setting the shortcut is:
```
shortcuts.ipelet_12_goodies = "Control+B"   -- Insert bounding box
```
The other format cannot work, because it overwrites all shortcut settings.

**Comment by ghali** [comment]
All is well then. Thank you!
