### ISSUE TITLE
Files open in Ipe's launch window on macOS

### ISSUE THREAD

**Issue by ghali** [otfried/ipe#367]
Opening a file (File - Open) used to work correctly until Ipe 7.2.21.

After updating to 7.2.23 whether I open a file through the file menu or through the (new feature) recent files, the file does not open in a separate window, but in Ipe's launch window, replacing what was there.

**Comment by otfried** [comment]
I cannot reproduce this.   For me, both File->Open and File->Recent files create a new Ipe window in addition to the existing Ipe windows for the new Ipe document.

The new window is created at the exact same location as the original launch window, but if you drag it elsewhere you see that the launch window is still there.

**Comment by ghali** [comment]
That's odd. I had observed it multiple times, but I've now reinstalled 7.2.23 and all seems well.
