### ISSUE TITLE
Saving EPS files outside the intial frame

### ISSUE THREAD

**Issue by lauwwarmemagnetronmaaltijd** [otfried/ipe#369]
Right now, the versions later than 7.2.14 do no longer support compiling eps files when (some of) the design is outside the reference document. However all versions up to 7.2.14 do support this. Note that when compiling png files, drawing "ouside the lines" is actually allowed. It seems to be a problem only for eps.

**Comment by otfried** [comment]
By "outside the reference document" you mean "outside the paper", right?

I made a change that caused this behaviour when I fixed #275 in 7.2.15.   The intention was to keep the original coordinates of the Ipe objects preserved inside the EPS file.    At that time, it seemed to me that was important, and didn't think anybody would want to export objects outside the paper.

I will change it for the next version.
