### ISSUE TITLE
Line attributes

### ISSUE THREAD

**Issue by fulvioforni** [otfried/ipe#37]
I cannot change the dash style of a line.

The old procedure:
- draw a line
- Ctrl+click on the left column, on the yellow rectangle (the one to add arrows)
- select the attributes of the line from the selection menu that appears

In the actual version the selection menu does not appear. Is there a new way to change line attributes (thickness, dash style, arrows style, opacity, etc).

Thank you,
Fulvio

**Comment by otfried** [comment]
Fixed here (Ctrl+Click works again):

https://www.dropbox.com/s/7667apvav92yzu7/ipe-7.2.2-mac-c.dmg?dl=0

**Comment by fulvioforni** [comment]
Excellent. It works. (this Ctrl+click feature seems quite relevant to me).

Thank you,
Fulvio
