### ISSUE TITLE
IPE crases after rendering LaTeX in an Ipelet

### ISSUE THREAD

**Issue by lluisalemanypuig** [otfried/ipe#373]
Hello.

I'm developing an Ipelet that has to render LaTeX at some point. However, the Ipelet makes IPE crash if I render LaTeX on the interface (by pressing `CTRL+L`) before running the Ipelet. I'm running the latest version of IPE `7.2.23` on Ubuntu 20.04. Before installing the version `7.2.23` I removed the previous packages of ipe, including Ipelib.

The minimal example is the following piece of code

```
label = "MWE Crashing IPE"
about = [[
Ipelet to make IPE crash
]]
function run(model)
	success, what, result_code, logfile = model.doc:runLatex()
	if not success then
		print("Something went wrong...")
		print(what)
	end
	print("Finished!")
end
```

In order to reproduce the crash follow these steps:
1. Launch IPE and add a label with the contents $b_2$.
2. Press `CTRL+L`.
3. Now launch the `MWE Crashing IPE`. You should see on your command-line terminal the message `Finished!`, indicating that IPE executed the ipelet successfully.
4. IPE (version `7.2.23`) crashes.

It goes without saying that I expected IPE not to crash and simply nothing to change.

Changing line `6`:
```
success, what, result_code, logfile = model.doc:runLatex()
```
with 
```
success, what, result_code, logfile = model.doc:runLatex(model.file_name)
```
does not fix the problem.

Tell me if I can provide more useful information.

Thanks a lot for creating and maintaining ipe! :)

**Comment by otfried** [comment]
Before you give back control to Ipe, you must make sure that the resources in the UI match the ones from the document. 

This will work:
```
label = "MWE Crashing IPE"
about = [[
Ipelet to make IPE crash
]]
function run(model)
	success, what, result_code, logfile = model.doc:runLatex()
	if not success then
		print("Something went wrong...")
		print(what)
	else
	  model.ui:setResources(model.doc)
	end
	print("Finished!")
end
```

**Comment by lluisalemanypuig** [comment]
This did the trick. Thank you for your support :)
