### ISSUE TITLE
Parsing Error at position 77825

### ISSUE THREAD

**Issue by DiogoCardao** [otfried/ipe#377]
I get this error when opening a file, up till now the file was working fine.

Thanks in advance

![parsing error](https://user-images.githubusercontent.com/80316084/110633655-51659500-81a9-11eb-9eaa-b4633074ae89.PNG)

**Comment by otfried** [comment]
Can you attach the file here, or send it to me by email?

If it contains secret information, you need to open it in an editor and look at character position 77825 to see what is wrong.

**Comment by DiogoCardao** [comment]
> Can you attach the file here, or send it to me by email?
> 
> If it contains secret information, you need to open it in an editor and look at character position 77825 to see what is wrong.

Hello, Can you share your email?

**Comment by otfried** [comment]
It's in the readme file that came with Ipe.

**Comment by DiogoCardao** [comment]
Hello, sent.

Thanks for the support.

**Comment by MarieSchmidtWuerzburg2** [comment]
I think that I have the same issue here
![image](https://user-images.githubusercontent.com/131957765/234810376-be1bb572-b534-4aa7-a0a4-9471ff3da7c2.png)
- is there any advice what I can do? 
I have emailed the document to the address in the readme, and I would really really appreciate any help
Best regards, Marie

**Comment by MarieSchmidtWuerzburg2** [comment]
Update: The problem appeared to be that I had used the " sign in a layer name.
Thank you so much for your help!
