### ISSUE TITLE
Truncated arrows

### ISSUE THREAD

**Issue by griff-sean-t** [otfried/ipe#378]
The bounding box around a LaTeX arrow seems to be truncated when added using the Mathematical Symbols or the Text Label tool. The problem goes away when you include a taller character in the text object.

The symbols I tested were \leftrightarrow, \rightarrow, and \Rightarrow, and the same problem occurred with all three.

I am using Ipe version 7.2.23 on MacOS Catalina.

[leftrightarrow_test.pdf](https://github.com/otfried/ipe-issues/files/6174489/leftrightarrow_test.pdf)

By the way, thanks for creating such an amazing program! It has been incredibly useful to me for creating presentations and figures.

**Comment by otfried** [comment]
Ipe uses the dimensions that Latex reports for the text, and those are simply wrong for the arrows.

If you try this Latex document, it will show the same problem.
```
\documentclass{article}
\fboxsep0pt
\begin{document}
\fbox{$\leftrightarrow$}
\end{document}
```

Except for manually enlarging those objects, you can use the `<textpad>` setting in the style sheet: https://mailman.science.uu.nl/pipermail/ipe-discuss/2014-March/001568.html

**Comment by griff-sean-t** [comment]
That makes sense, thank you!
