### ISSUE TITLE
Grid maker selection modification

### ISSUE THREAD

**Issue by pta-janssen** [otfried/ipe#379]
The example of grid maker that was implemented last year is great! I copied and modified the code such that I can create a grid useful for axonometric drawings which works great. 

However, one downside to the grid made by a grid maker ipelet: the grid remains selectable. Consequently, the entire grid is selected after each operation or modification on the workpiece (such that the entire artboard lits up red (for small grid sizes)). I've tried ungrouping the grid which makes the issue less dramatic but still there. 

Would it be possible to implement a function to toggle the ability to select anything in a layer, whilst still allowing to snap to custom grid?
Any suggestions on how to implement it on my personal Ipe would be great as well!

**Comment by otfried** [comment]
That function is called "locking" the layer:  Right-click the layer name and choose "Lock".

This is independent of snapping - you can still snap to features in a locked layer.

In addition, you can call your grid layer `GRID`: then you can use the  "custom snap" mode to snap to it - this is independent of the normal snap operations, and will work even if the layer is not visible.  (See http://ipe.otfried.org/manual/manual_24.html)

**Comment by pta-janssen** [comment]
That's exactly what I've been looking for thanks! I didn't notice beforehand that the layer locking feature imposed the unclickable functionality.
Thanks for the fast and helpful response.
