### ISSUE TITLE
Select by custom stroke color doesn't select anything

### ISSUE THREAD

**Issue by anusser** [otfried/ipe#380]
Ipe Version: 7.2.23
OS: Linux Manjaro

The (somewhat) new "select by type/attribute" ipelet is awesome. Unfortunately it fails when trying to select by a stroke color that was manually created, i.e., that one selects from the HSV color square.

Steps to reproduce:
- Click the stroke color button (left of the drop down list of the predefined colors) 
- Create some custom color using the HSV color square and select "Ok" (the color drop down menu should now show "\<absolute\>")
- Create an object, e.g., a marker
- Got to "Ipelets -> select by type/attribute" and choose only "Stroke color" and click "Ok"

Expected result:
The marker should now be selected as it has the stroke color which we wanted to select.

Actual result:
Nothing is selected.

Note that the selection by stroke color works flawlessly if one selects by a predefined color.

Tell me if you need more information. I had a look at the ipelet but it is very simple and the issue seems to be on a deeper layer I suppose.

Thanks! :)

**Comment by otfried** [comment]
Fixed in 7.2.24.

Here is the updated ipelet in case you want to test it.
[selectby.zip](https://github.com/otfried/ipe-issues/files/6238885/selectby.zip)

**Comment by anusser** [comment]
The fix works. Thank you so much for reacting that fast! :+1:
