### ISSUE TITLE
Customizing the latex preamble

### ISSUE THREAD

**Issue by ghali** [otfried/ipe#382]
I start every Ipe file by inserting `\usepackage{times}` in the latex preamble.

But rather than copying a starting template file, it would be nice if this can be done through `~/Library/Ipe/Ipelets/customization.lua`.

Looking at `ipe-7.2.23/src/ipe/lua/prefs.lua`, this preference customization seems not to be available.

Could you add a feature to parse customizations such as `prefs.latex_preamble = "\usepackage{times}"`?

**Comment by otfried** [comment]
The way this is meant to be done is as follows:
Create a file `times.isy` and put it in an Ipe style directory, with contents:
```
<ipestyle name="times">
<preamble>
\usepackage{times}
</preamble>
</ipestyle>
```
Then change your configuration to automatically include this style sheet with a new document:
```
prefs.styles = { "basic", "times" }
```

**Comment by ghali** [comment]
Neat.. That's a tidier solution, especially for more elaborate preambles.
