### ISSUE TITLE
UI: dropdowns inconsistent behavior

### ISSUE THREAD

**Issue by d1nuc0m** [otfried/ipe#383]
Hello, 
I noticed that dropdowns in the UI behave in two different ways when Ipe is run "normally" through CLI/DE and when is run on an existing file with "Open this file with".

**Normal behavior (?)**
When Ipe is launched through CLI or application menu, the dropdowns are ordered in this way:
**_Grid size_**
- 4 pts
- 8 pts
- 16 pts
- 32 pts
- 10 pts
- 20 pts
- 14 pts
- 28 pts
- 56 pts

**_Angle for angular snap_**
- 90 deg
- 60 deg
- 45 deg
- 30 deg
- 22.5 deg

**_Text size_** in Text labels tool
- normal
- large
- Large
- LARGE
- huge
- Huge
- small
- footnote
- tiny

**Wrong order in dropdowns**
At the same time, if in the file manager I select an Ipe file and use "Open With", the dropdowns are ordered in this way:
**_Grid size_**
- 10 pts
- 14 pts
- 16 pts
- 20 pts
- 28 pts
- 32 pts
- 4 pts
- 56 pts
- 8 pts

**_Angle for angular snap_**
- 22.5 deg
- 30 deg
- 45 deg
- 60 deg
- 90 deg

**_Text size_** in Text labels tool
- normal
- large
- small
- tiny
- Huge
- LARGE
- Large
- footnote
- huge

**Environment**
- OS: Artix Linux (Plasma Runit)
- Kernel: 5.10.26-1-lts
- DE: Plasma 5.21.3
- WM: Kwin
- Ipe version: 7.2.23, installed from [AUR](https://aur.archlinux.org/packages/ipe/) with yay

**Comment by otfried** [comment]
There is no predefined order for the symbolic names - it's on my todo-list, but it's not clear what the right behaviour is.

See #65 and #241.

**Comment by d1nuc0m** [comment]
Ok, thank you, I thought that there was a predefined order
