### ISSUE TITLE
Ipe website and HTTPS

### ISSUE THREAD

**Issue by d1nuc0m** [otfried/ipe#384]
I know that probably this is not the best place, but I noticed that now the official Ipe website does not support HTTPS.
When trying to connect to [https://ipe.otfried.org](https://ipe.otfried.org), browsers show a safety warning, because the certificate is only valid for the subdomain presentations.otfried.org.
Plain HTTP is regarded by major browser as more or less deprecated, so at least they show the website http://ipe.otfried.org as "not safe".
Also, because on the website there are sources and binaries, HTTPS wouldn't be bad as a security layer to avoid tampering.

**Comment by otfried** [comment]
Fixed.

**Comment by d1nuc0m** [comment]
Could you also set the website to use HTTPS by default and then switch to HTTP if the client does not support it?
So that ipe.otfried.org by default redirects to https://ipe.otfried.org and not to http://ipe.otfried.org

**Comment by otfried** [comment]
Isn't that already what happens?

**Comment by d1nuc0m** [comment]
No, if the browser is not in HTTPS-only mode the default protocol is plain HTTP
EDIT: now it works
