### ISSUE TITLE
Default presentation aspect ratio 

### ISSUE THREAD

**Issue by anusser** [otfried/ipe#385]
When creating a presentation in ipe, the default way to do it is to use the command `ipe -sheet presentation` as far as I understand. This still uses a style sheet with 4:3 aspect ratio. Especially, many sets of slides that are created with ipe still seem to use this aspect ratio -- at least I often notice this in talks. I think it is better nowadays to use a 16:9 aspect ratio as default for slides.

So, I would suggest to change the presentation style sheet such that it uses a 16:9 aspect ratio instead of 4:3.

_Small note:_ I do use my own style sheet for presentations anyway, but I think that changing the default encourages creating better slides.

**Comment by otfried** [comment]
In 7.2.25.
