### ISSUE TITLE
Full Documentation Source Code File

### ISSUE THREAD

**Issue by mkohlhaas** [otfried/ipe#389]
First of all: **awesome project, awesome software**!!!

Void Linux has an [ipe package](https://github.com/void-linux/void-packages/blob/master/srcpkgs/ipe/template) for installation which it made from the [ipe sources](https://github.com/otfried/ipe/releases/download/v7.2.24/ipe-7.2.24-src.tar.gz). Unfortunately the documentation is not complete, e.g. the link to the ipelets docs is not working because it is missing. The Debian packages contain the whole documentation.

Could you make the complete documentation also available in the ipe sources?

Kind regards!

**Comment by otfried** [comment]
The template file is missing the `make documentation` call, which is needed since 7.2.23.
