### ISSUE TITLE
Feature Request: Reorder Layers via Drag & Drop

### ISSUE THREAD

**Issue by anusser** [otfried/ipe#390]
Currently it is only possible to reorder layers using right click on a layer and then choosing where to move it in "move \<layer\>". This seems much more complicated than just using drag & drop on the layers.

Can drag & drop in the layers list be added? If there is any good reason that I am missing for the current design, feel free to close this issue of course.

**Comment by otfried** [comment]
In 7.3.1.

**Comment by anusser** [comment]
Thank you! :) Very much appreciated!
