### ISSUE TITLE
Assertion failure on arch linux

### ISSUE THREAD

**Issue by PaulDetterer** [otfried/ipe#392]
I get this when I try to start:
```
/usr/include/c++/10.2.0/bits/stl_vector.h:1045: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = ipe::String; _Alloc = std::allocator<ipe::String>; std::vector<_Tp, _Alloc>::reference = ipe::String&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__builtin_expect(__n < this->size(), true)' failed.
Aborted (core dumped)
```
[CoreDumpHere](https://github.com/otfried/ipe-issues/files/6533784/tmp.txt)

**Comment by otfried** [comment]
This is already fixed in my sources: #387 

You either have to compile without the `D_GLIBCXX_ASSERTIONS` flag, or you have to change the line
```
(*ui)->setBookmarks(no, &bm[0]);
```
to
```
(*ui)->setBookmarks(no, bm.data());
```
in `src/ipe/uilua.cpp`.

**Comment by PaulDetterer** [comment]
I see. Appologies! I did not look into fixed issues because the comment about same mistake in AUR package was new. I guess the update did not reach the AUR package yet. Thank you for very helpful reply.

**Comment by otfried** [comment]
The fix is not yet in the latest Ipe release - so until that happens the AUR package specification file should really apply the patch (since they seem to insist on the `-D_GLIBCXX_ASSERTIONS` flag now).

Let's leave this issue open so future Arch users can find it more easily.
