### ISSUE TITLE
Feature request: make save dialog for new file default to last used directory

### ISSUE THREAD

**Issue by ThomasChaffey** [otfried/ipe#394]
I'm using 7.2.24 on OSX.

As the title says, it would be wonderful if the "save/save as" dialogs for a new drawing defaulted to the last used directory, rather than the home directory.

This would be a big time saver when doing a lot of figures for one project.

My current workaround is to open an existing figure and "save as", which is quicker than navigating down my (admittedly large) directory tree.

Thank you!

PS love IPE, it has changed my life after transitioning from tikz.

**Comment by otfried** [comment]
It would be rather easy to add this for when you have already looked at a file, and now you create a new file and want to save it.

However, this would not save the directory across Ipe runs.  If you completely quit Ipe and start again, it would again start at the directory you have set in the preferences (which is another tip: set the save_as directory to somewhere in your directory tree where you can quickly get to the figures of interest).

Ipe currently stores no information at all across runs, with enabling online latex conversion as the only exception.   I would have to come up with a nice mechanism to support this first.

**Comment by otfried** [comment]
I had completely forgotten that I implemented the "recent files" feature, so adding this was actually trivial.  In 7.2.25.
