### ISSUE TITLE
Another assertion failure on arch linux

### ISSUE THREAD

**Issue by thobl** [otfried/ipe#396]
When using labels with fractions (e.g., $\frac{1}{2}$), I get the following assertion error:

```
/usr/include/c++/11.1.0/bits/stl_vector.h:1045: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = double; _Alloc = std::allocator<double>; std::vector<_Tp, _Alloc>::reference = double&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__n < this->size()' failed.
```

This happens when I create a new label with a fraction or if I try to navigate to a view that already contains such a label. Also, if the ipe file contains a fraction somewhere and I use the "Page" button it crashes and if the current page contains a fraction and I use the "View" button, it also crashes.

I already use the patched version as suggested in [issue 392](https://github.com/otfried/ipe-issues/issues/392) (without this patch it already crashes on startup with the same assertion failing but with ipe::String instead of double).

I believe this issue did not appear with 7.2.23.

ipetoipe converts to pdf properly.

**Comment by otfried** [comment]
I've now changed the syntax `&vector[0]` everywhere in Ipe to `vector.data()`, this should fix all those "issues".

I wonder who makes these decisions to require flags that have so many false positives.

Here is the patch, in case you want to apply it yourself:

[patch.txt](https://github.com/otfried/ipe-issues/files/6661987/patch.txt)

**Comment by mrzv** [comment]
What is this patch made against? It fails to apply on top of 7.2.24.

**Comment by otfried** [comment]
Strange.  It applies cleanly with the `-l` flag:
```
$ tar xzf ipe-7.2.24-src.tar.gz 
$ cd ipe-7.2.24/
$ patch -i ~/Downloads/patch.txt -p 1 -l
patching file src/ipe/appui_qt.cpp
Hunk #1 succeeded at 920 (offset 26 lines).
Hunk #2 succeeded at 929 (offset 26 lines).
patching file src/ipe/appui_win.cpp
Hunk #1 succeeded at 1360 (offset 26 lines).
patching file src/ipe/main_win.cpp
Hunk #1 succeeded at 124 (offset 26 lines).
patching file src/ipe/pagesorter_win.cpp
Hunk #1 succeeded at 386 (offset 26 lines).
patching file src/ipecairo/ipecairopainter.cpp
Hunk #1 succeeded at 573 (offset 26 lines).
Hunk #2 succeeded at 962 (offset 26 lines).
Hunk #3 succeeded at 1446 (offset 26 lines).
Hunk #4 succeeded at 1468 (offset 26 lines).
patching file src/ipecanvas/ipeselector_win.cpp
Hunk #1 succeeded at 171 (offset 26 lines).
patching file src/ipelib/ipeplatform.cpp
Hunk #1 succeeded at 642 (offset 26 lines).
patching file src/ipelua/ipelib.cpp
Hunk #1 succeeded at 543 (offset 26 lines).
Hunk #2 succeeded at 555 (offset 26 lines).
patching file src/ipepresenter/ipepresenter_qt.cpp
Hunk #1 succeeded at 432 (offset 26 lines).
patching file src/ipepresenter/ipepresenter_win.cpp
Hunk #1 succeeded at 53 (offset 26 lines).
Hunk #2 succeeded at 63 (offset 26 lines).
Hunk #3 succeeded at 546 (offset 26 lines).
patching file src/ipeui/ipeui_win.cpp
Hunk #1 succeeded at 64 (offset 26 lines).
Hunk #2 succeeded at 77 (offset 26 lines).
Hunk #3 succeeded at 275 (offset 26 lines).
Hunk #4 succeeded at 535 (offset 26 lines).
Hunk #5 succeeded at 1040 (offset 26 lines).
Hunk #6 succeeded at 1268 (offset 26 lines).
Hunk #7 succeeded at 1289 (offset 26 lines).
```
There must have been some whitespace changes in my sources.

There is really no reason at all to apply this  patch, though, if you compile Ipe yourself - just remove the `-D_GLIBCXX_ASSERTIONS` flag from the compilation.

Frankly, I think it is a mistake by Arch Linux to require this flag for package compilation.  It's not like a flag that turns on additional compile time warnings (of which I am a big fan - I turn on all warnings and treat them as errors during development) - rather, it introduces subtle run time crashes in perfectly correct code.

None of the changes I made to accommodate this policy was an actual bug - the code was correct, but written in pre-C++11 style.  I agree that the new style is prettier and I'm happy I made the change, but forcing the new style into Ipe by making Ipe users experience crashes with possible data loss is extremely questionable behaviour of Arch Linux.

I used to have a good opinion of Arch Linux, but in the future I will probably treat bug reports by Arch Linux users with a grain of salt.

**Comment by mrzv** [comment]
Ah, thanks for the `-l` flag suggestion; it indeed works. I am trying to fix the Arch Ipe package, which is why it's not enough to just fix my local compilation.

I agree that the decision to force `-D_GLIBCXX_ASSERTIONS` is annoying. (I was in no way involved; I only maintain a couple of packages in the AUR.) On the other hand, in the grand scheme of things it's a minor decision — much more extreme changes have been made in the past. And I can understand the desire for greater safety, given how much infrastructure relies on the packaging, without thinking about it. For Ipe, it's a vacuous assertion, but you can imagine how this could uncover broken code in other places.

**Comment by otfried** [comment]
> For Ipe, it's a vacuous assertion, but you can imagine how this could uncover broken code in other places.

Obviously, but there are ways to introduce such checks without causing users to lose their data.   One obvious approach would be to have a version of the assertion that prints a warning only, and turn it into a crash in the next release, or after a year, or something like that.

If I was an Arch user and I lost an Ipe document because of this silliness, I would be quite annoyed.  I had been thinking of switching to Arch myself, but now I'm not sure I like this unpredictability.

**Comment by mrzv** [comment]
I agree with you there.

FWIW, I've been an Arch user for 15 years, and it's been a delight. This situation is not representative of its general MO.

**Comment by thobl** [comment]
Thank you very much for the quick solution!
