### ISSUE TITLE
Developer cannot be verified on macOS

### ISSUE THREAD

**Issue by JuliaKatheder** [otfried/ipe#398]
When trying to launch both Ipe and IpePresenter on macOS Big Sur 11.2.3, there is an error stating the program cannot be opened because the developer cannot be verified.

<img width="365" alt="Bildschirmfoto 2021-07-16 um 10 28 17" src="https://user-images.githubusercontent.com/15217783/125917581-9656c35f-6dae-4342-9bc0-a1b6386044e3.png">

**Comment by otfried** [comment]
This is the normal behaviour of macOS when you install an app from elsewhere.  You need to go to your security settings and allow that the program can be opened.

As far as I know, we could only avoid this warning for Ipe if I publish Ipe on the macOS app store.  That is simply too expensive and too much work for a single developer of a free program.

**Comment by otfried** [comment]
For future consideration:

https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution

Apparently it is possible to sign apps with a developer id and still distribute them outside the app store.  This does not seem to be too complicated, it just requires being an Apple developer ($99 per year).
