### ISSUE TITLE
iperender --all-pages-output-by-name

### ISSUE THREAD

**Issue by ghali** [otfried/ipe#399]
To output either PNG or SVG images from a multi-page Ipe file, I have been iterating then renaming the filenames

    for num in $(seq 1 2)
    do
        set -x
        zero_leading_num=$(printf "%02d" $num)
        ${IPERENDER} ${PREFIX} -page ${num} ${SUFFIX} ${IPESOURCE} "png/d"${zero_leading_num}${FILEEXT}
        set +x
    done

    mv png/d01.png png/name_of_first.png
    mv png/d02.png png/name_of_second.png
    ...

Inclusion in a document by name is clearer and also makes it a simple matter to insert a new page and displace the numbers.

Since `iperender` now has a great new feature

    <page> can be a page number or a page name.

and page names are allowed, I'm encouraged to request the following feature.

Could you add an option in `iperender` to generate all PNG/SVG images into files with filenames exactly matching those that are already defined in the Ipe file?

By the way, I know how to set the page title, the page notes, and the page mark, but it's not clear how to set the page name. Is the name the same as the title?

**Comment by ghali** [comment]
I see (https://github.com/otfried/ipe-issues/issues/136) that name is synonymous to title. The feature might work like this: If a page has a title/name, the page is saved (as PNG/SVG/PDF). Pages that do not have a title are considered draft pages and are not converted.

Converting to a PDF file and inserting page names then referring to pages by name from a Latex document (if/when that is possible) would be ideal, but that doesn't generalize to PNG or SVG. Those who use a Makefile to assemble documents can still `touch drawing.txt` at the same time `iperender drawing.ipe` is run.

**Comment by ghali** [comment]
I spoke too soon. It seems that views have names (https://mailman.science.uu.nl/pipermail/ipe-announce/2019-October/000084.html) and those are the names used by iperender by name.

The names used by iperender are again unclear. Also, I know how to change layer names, but it's unclear how to set/chage view names.

**Comment by otfried** [comment]
Both pages and views can now have names.

The page name is set as the page title - if it satisfies the rules for PDF identifiers (letters and digits would be okay).

The view name is set using "Edit view" (in the Views menu).

iperender uses page names for the -page argument and view names for the -view argument.

**Comment by ghali** [comment]
I see. In that case may I suggest adding either or both of the following flags?

    iperender --output-all-named-pages
    iperender --output-all-named-views

**Comment by otfried** [comment]
Oops - I made a mistake above:  the page label is set as the "Section" name of the page.

**Comment by otfried** [comment]
Have a look at the script `page-labels`.   It can output a list of all the page names and view names in the document.

You can modify this script to output, for instance, a shell script that does what you want.

**Comment by ghali** [comment]
Nice! Thanks.

> You can modify this script to output, for instance, a shell script that does what you want.

No need. It's cleaner if all figures remain in one file.

I think the documentation at
https://otfried.github.io/ipe/80_advanced.html#multiple
has a typo though. Instead of
"Enter the name in the Section field, using only letters."
it should say
"Enter the name in the Page Title field, using only letters."
as that is what is currently used, regardless of whether the "Use title" checkbox is marked.
