### ISSUE TITLE
Crash under Windows with pdf2ipe file

### ISSUE THREAD

**Issue by mkraska** [otfried/ipe#4]
Hi.

With version 7.1.7 I experience a crash under Windows 7 under the following circumstances:
- create an ipe file from an existing pdf (TpX-generated) using 

>D:\Programme\IPE\ipe-7.1.7\bin\pdftoipe.exe Sandwich.pdf

When I then open this pdf in IPE, the contents of the grid space selector and of the snap angle selector gets lost and when accessing these selectors, IPE crashes. I get a system message dialog: ipe.exe does not work any more (or so, it is in german).
Sorry, no idea, how to attach files to the issue.

Best regards, Martin Kraska

**Comment by otfried** [comment]
Try inserting the standard stylesheet (basic.isy) manually into the file generated by *pdftoipe*.

That file should be called *Sandwich.xml*, and you need to insert the style sheet in front of the existing *ipestyle* tag.

**Comment by otfried** [comment]
At the bottom of the *Comment* field there is an option to attach images by selecting them.  Can you check if this works for the Sandwich.pdf file?

**Comment by mkraska** [comment]
It seems that neither pdf nor ipe files are supported for attachment. But I guess that you don't need the file anyway, because your proposal on how to fix the problem works. Thanks a lot. 

----- Am 21. Jun 2015 um 15:34 schrieb otfried <notifications@github.com>:

**Comment by mkraska** [comment]
The workaround works for me in two ways: 
- Inserting the contents of basic.isy (everything inside the <ipestyle> tag into the corresponding tag of Sandwich.pdf)
- adding basic.isy as a style sheet via edit> style sheets.

The latter, however, did not take immediate effect, even update style sheets did not help. I had to close and re-open the file in order to get the styles populated.

**Comment by mkraska** [comment]
This might be a separate feature request:

How about having a menu entry File> Import> PDF or even better, doing the import silently when  trying to open a non-IPE pdf.

**Comment by otfried** [comment]
Fixed in 7.1.8
