### ISSUE TITLE
Getting the wrong information from Tablet when Ipe is started after Tablet is plugged in

### ISSUE THREAD

**Issue by zwang2** [otfried/ipe#4]
I am not sure if this is a bug/problem with Ipe or with Qt or something else. But the problem is as follows: If I start Ipe and then plug in my tablet input device, then I can use the tablet with no problem. But if the tablet is already plugged in when Ipe is started, then Ipe does not get the correct inputs from the tablet. For example, when using the INKTOOL, the set of positions obtained by Ipe using model.ui:pos() are as follows:

One Instance: 

-1031.7204362801, 994.55109070034
65.068541905855, 622.53332353617
65.255030998852, 622.53332353617
BUTTON: 1 PRESS: false 

Another Instance:

-1031.7204362801, 994.55109070034
189.31690011481, 580.69915774971
188.80405510907, 580.06975706085
188.33783237658, 579.56623650976
188.01147646383, 579.10467600459
187.73174282434, 578.81095568312
187.49863145809, 578.55919540758
187.3121423651, 578.47527531573
187.2188978186, 578.39135522388
BUTTON: 1 PRESS: false 

Abnormalities: 1) The first position is definitely way off. 2) The two initial positions are identical. 3) A button release event is reported shortly after the pen is pressed, and after the pen has barely moved, even though the pen is still depressed. As a result of all these, it is impossible to use the INKTOOL with the tablet.

Workaround: The problem only happens when Ipe is started after the tablet is plugged. So it is possible to unbind the USB tablet device before starting Ipe, and then bind it again -- the software equivalent of unplugging the tablet, starting Ipe, and then plugging in the tablet.

**Comment by otfried** [comment]
Which platform?  Windows, Linux, Mac?

**Comment by zwang2** [comment]
It is Linux, with the kernel 4.1.3.

**Comment by otfried** [comment]
I guess you should first check if Qt is actually reporting tablet events or only mouse events.  (See src/ipecanvas/ipecanvas_qt.cpp - the interesting method is Canvas::tabletEvent).

If the first coordinates are wrong, that would be the "press" event, while the "move" events are fine.  Perhaps there is a mismatch to how Ipe calculates the high resolution position (hiPos in tabletEvent).

**Comment by zwang2** [comment]
I did two tests, as follows:

TEST 1: starting Ipe, and then plug in tablet.
Result 1: the tablet input are reported as mouse events, not as tabletEvent. A sample output as a result of moving tablet pen, using the following code

Canvas::mouseMoveEvent(QMouseEvent *ev)
qDebug() << ev->x() <<","<<ev->y();

is as follows:
562 , 548
564 , 549
566 , 550
569 , 550
573 , 551
576 , 552
579 , 553
583 , 553
586 , 553
588 , 553
590 , 553
591 , 553
592 , 554
593 , 554

TEST2: plug the tablet, and then run Ipe. 
RESULT2: The tablet events are reported through tabletEvent(). However, the coordinates are eratic. A sample of the output, using the code:

Canvas::tabletEvent(QTabletEvent *ev)
qDebug() << "HiPos=" << hiPos.x() <<", "<< hiPos.y();

is as follows:

HiPos= 456.928 ,  404.789
HiPos= 268.528 ,  -141
HiPos= 456.832 ,  -141
HiPos= 456.832 ,  -141
HiPos= 456.736 ,  404.962
HiPos= 456.64 ,  405.091
HiPos= 456.544 ,  405.178
HiPos= 456.448 ,  -141
HiPos= 456.4 ,  -141
HiPos= 456.352 ,  -141
HiPos= 456.304 ,  -141
HiPos= 456.208 ,  -141
HiPos= 456.16 ,  -141
HiPos= 268.768 ,  -141
HiPos= 268.672 ,  -141
HiPos= 268.576 ,  -141
HiPos= 268.624 ,  -141
HiPos= 268.672 ,  -141
HiPos= 268.576 ,  -141
HiPos= 268.432 ,  -141
HiPos= 456.064 ,  404.702
HiPos= -338 ,  -141
Mouse button  1 false false
HiPos= 455.968 ,  404.702
HiPos= 455.92 ,  404.573
HiPos= 268.144 ,  -127.219
HiPos= 455.872 ,  404.53
HiPos= 455.824 ,  404.4
HiPos= 455.776 ,  404.4
HiPos= 455.728 ,  404.314
HiPos= 455.68 ,  404.227
HiPos= 455.584 ,  404.227
HiPos= 267.664 ,  -102.034
HiPos= -289.808 ,  -141
HiPos= 267.52 ,  -93.5664
HiPos= -281.408 ,  -141
HiPos= 267.424 ,  -86.7408
HiPos= 267.328 ,  -83.76
HiPos= -270.944 ,  -141
HiPos= -267.008 ,  -141
HiPos= 267.232 ,  -73.6512
HiPos= 267.088 ,  -70.1088

Not sure what is going on in the TEST2. But the results in TEST1 is consistent with the previous observed result that the coordinates of the drawn line appear to be quantized to integers.

**Comment by zwang2** [comment]
By monitoring the TabletEvent function, it does seem that Qt is sending the wrong events:

TABLET PRESSED
Mouse button    1   false   false
TABLET MOVED 
TABLET RELEASED 
TABLET MOVED 
TABLET RELEASED 
TABLET MOVED 
TABLET MOVED 
TABLET RELEASED 
TABLET MOVED 
TABLET RELEASED 
TABLET MOVED 
TABLET MOVED 
TABLET MOVED 
TABLET RELEASED 
TABLET RELEASED 
TABLET MOVED 
TABLET RELEASED 
TABLET MOVED 
TABLET RELEASED 
TABLET MOVED 
TABLET RELEASED 
TABLET MOVED 
TABLET RELEASED 
TABLET MOVED 
TABLET RELEASED 
TABLET MOVED 

It seems that QEvent::TabletMove is almost always followed by an QEvent::TabletRelease event, which caused the premature ending of the drawing.

**Comment by otfried** [comment]
One simple thing you could do is to simply disable the tablet events (that is, entirely take out the Canvas::tabletEvent method).  In this case you would always get mouse events, which seem to work - but you lose the higher precision.

Instead of printing out hiPos, maybe you could print the globalPos (and the ev->type()).  Perhaps something is going wrong in Ipe's computation of hiPos.

**Comment by zwang2** [comment]
I tried to print the globalPos. Many of the (X,Y) coordinates from globalPos have the Y component exactly equal to 0, and the X coordinate seems to be within the range (1, 1024). And the X coordinate is correlated with the pressure -- high pressure causes larger X value. So I think somewhere along the event pipe (likely Qt), the pressure value passed by the tablet gets interpreted as a Move event. A google search also reveals the following

https://bugs.launchpad.net/ubuntu/+source/qt4-x11/+bug/721471

So I think it is not Ipe's fault and for now I will just use the low-resolution mouse events.

Thanks for the great suggestions.
