### ISSUE TITLE
Icons on the menu buttons are not visible

### ISSUE THREAD

**Issue by ritesh-777** [otfried/ipe#401]
Hi there !! I have just installed Fedora 34 and then installed IPE from official repo of fedora. Installed without any error or worning. Opened IPE but can not see the icons on the menu buttons but the buttons are working properly while using. In the terminal there no log available to identify the problem. I tried it in few instances like -

1) Install IPE after fresh install of Fedora
2) Install IPE after updating Fedora
3) Removing "adwaita-qt5" package
4) Switching between "Wayland" and "Xorg"

All results the same issue. I have used IPE on different linux distributions for last 2 years but never faced any problem. Any suggestion? I don't want to move on from Fedora but IPE is necessary for my work.

My hardware confg is - 
Processor - Intel i5 6th gen
GPU -  Intel HD 520 (Integrated)
RAM - 8 GB

![Screenshot from 2021-09-03 13-10-08](https://user-images.githubusercontent.com/45590358/131973125-b30ac262-0daf-498b-a18b-10a9483ca2a5.png)

**Comment by otfried** [comment]
The icons are now in SVG format.  I could imagine that you are perhaps missing the Qt5 SVG package.   It's a plugin without which SVG files simply wouldn't be displayed.

On my system the package is called `libqt5svg5`, you would have to search for the Fedora equivalent.

**Comment by ritesh-777** [comment]
> The icons are now in SVG format. I could imagine that you are perhaps missing the Qt5 SVG package. It's a plugin without which SVG files simply wouldn't be displayed.
> 
> On my system the package is called `libqt5svg5`, you would have to search for the Fedora equivalent.

Thanks mate !!  I just installed "qt5-qtsvg" and that solved the issue !!
