### ISSUE TITLE
Not all corners are the same in a rectangle

### ISSUE THREAD

**Issue by pierreganty** [otfried/ipe#402]
As shown in the screenshot of Ipe 7.2.24, every `rectangle` button returns a rectangle with 3 rounded corners and 1 straight one (NW corner). 

<img width="1150" alt="image" src="https://user-images.githubusercontent.com/2111160/132011354-c76a7d0b-192a-4722-b3b1-05fed1929377.png">

**Comment by otfried** [comment]
I cannot reproduce this - can you explain what you are doing precisely to get the incorrect rectangle?  I assume by `rectangle` button you mean the three modes for drawing rectangles (axis-parallel, axis-parallel by center, general rectangle)?

**Comment by pierreganty** [comment]
The issue happens for me using any of the three mode for drawing
rectangles. Maybe I have some config somewhere ( in a lua file or
stylesheet) that triggers the problem. Is there a way to start ipe with no
configs or stylesheet?

**Comment by otfried** [comment]
Assuming your customization is in `~/.ipe/ipelets`, the easiest would be to rename that directory.

**Comment by pierreganty** [comment]
I could reproduce the issue on windows with Ipe 7.2.23 and no customization. I also reproduced the problem after renaming `~/.ipe/ipelets` on MacOS with Ipe 7.2.24. Finally I reproduced it on Fedora 34 with Ipe 7.2.24 after a fresh install. It is barely noticeable, you have to zoom in very close to see that one corner is not the same.

**Comment by otfried** [comment]
Ah - now I see what you mean.

I had set the line width to a larger value to make it more obvious - but the problem only occurs when the line width is small.   
For line width 0.685 I see the problem, for line width 0.69 it goes away.

Mysterious.

**Comment by otfried** [comment]
So this is weird:

If I save the file in PDF and open it in xreader, the corner is also broken.

When I open the PDF file in Firefox or in Acrobat, the corner is correct.

I suspect this is a bug in Cairo (which is presumably what xreader uses to display the PDF).

Does the corner display correctly in the OSX PDF viewer?

**Comment by pierreganty** [comment]
Using Skim and Preview on MacOS all the corners are the same.
