### ISSUE TITLE
IPE crashes and disappears immediately upon startup

### ISSUE THREAD

**Issue by AlexisWartelle** [otfried/ipe#405]
I seem to have "broken" IPE (v. 7.2.24 on Windows 10) just with a change in the stylesheet I was using, and of which I'm attaching the present version.
[upgr_basic_new_v2.txt](https://github.com/otfried/ipe-issues/files/7399623/upgr_basic_new_v2.txt)

I had been using *almost* exactly that stylesheet for several months without any issue, all colours, pen thicknesses etc. were working nicely. In the version that caused no problems, the last few lines looked like this:

`(...)`

`</gradient>`

`<opacity name="test" value="0.90"/>`

`<opacity name="threeq" value="0.75"/>`

`<opacity name="half" value="0.5"/>`

`<opacity name="oneq" value="0.25"/>`

`<opacity name="min" value="0.00101"/>`

`</ipestyle>`

And then I replaced the line `<opacity name="test" value="0.90"/>` with the following two:

`<opacity name="90percent" value="0.90"/>`

`<opacity name="10percent" value="0.10"/>`

which then caused IPE to crash and immediately close itself upon launch since then. I changed to the attached stylesheet as it was set to be taken by default for new documents, but to no avail.

I hope I didn't forget anything important but if I did so I'll be happy to try and complete this description. I guess I can try to re-install IPE but it seemed to me that such an issue deserved to be mentioned, just in case.

At any rate, I'll take the opportunity to write a huge **THANK YOU!** I've used IPE for ~5 years now and I advertise it whenever I have the chance, it's really a great tool! Best regards,

Alexis

**Comment by otfried** [comment]
I cannot reproduce this problem.

I can add the style sheet to an Ipe document without problem (by the way, there is no "test" opacity inside - I guess you meant the "ninetypercent" one?)   I can also start Ipe with the `-sheet upgr_basic.isy` option and it works fine.

You say Ipe crashes immediately on startup.  Does this happen when starting it without file?   But then it wouldn't load that style sheet either.   Do you perhaps have some customization that could be the problem?

By the way, you seem to have defined **lots** of various line widths etc.  Do you know that when you really need so many different values, you can just use absolute values for the width (click on the icon to the left of the pen width selector).

**Comment by AlexisWartelle** [comment]
Thank you! I wrote things in a confusing way: the "test" was only temporarily there and not in the stylesheet I attached indeed.

Actually, I meant that IPE crashes when I start it to create a new document. However, your message gave me an idea: I actually could start IPE by opening an already existing .pdf document that I created with it. From there, if I click on "New Window" I get the attached error message:

![IPE_lua_error](https://user-images.githubusercontent.com/84846711/138589882-0bb19b36-0451-4d8b-980f-b269b929b126.png)

Does this help?
I'm confused because as far as I remember I shouldn't have tinkered with the model.lua file; I don't know the language and have had no need to change stuff there so far, therefore I can't imagine to have played with this file's contents...

Also, thanks for the tip, I'd never tried clicking there...!

**Comment by otfried** [comment]
Aha, so you set up Ipe to automatically add a specific style sheet to newly created documents, and that style sheet has an error at position 10708.

Before you set up a style sheet as a default, you should always check that it actually can be added to new documents using "Add" from the style sheets dialog (Edit->Style sheets).

To find out what style sheets are added to new documents, use Help->Show configuration (under "Styles for new documents").

**Comment by AlexisWartelle** [comment]
Hm, well it seems I added the error when I added opacities in a rush: I just found it that there was a simple syntax error - forgot a ' " ' in an opacity definition - which I corrected, and thereafter I could start IPE again without problems. Seems to me that was the gist of the issue.

Sorry for the silly mistake and thank you very much for your time and reactivity!

**Comment by otfried** [comment]
It's of course unfortunate that Ipe crashes in such a case without a useful error message.    Let me see if there is some reasonable fix for that.

In general - always test your style sheet before you set them as the default.
