### ISSUE TITLE
When saving as PDF, .ipe stops updating on save

### ISSUE THREAD

**Issue by francesco-riz** [otfried/ipe#408]
Hello,

I get the issue whenever I follow this sequence of commands:

- Launch IPE
- Save .ipe with a random name ('try.ipe')
- Sketch some lines
- Save as PDF ('try.pdf')
- Close IPE

When I open the PDF file, it contains the lines I have sketched, while when I open the .ipe file, it is completely empty.

This is problem for me since I export as PDF, see how the figure fits the presentation (or the latex file), then modify the (still open) .ipe file, and keep looping this way. By doing so, I end up with the most updated version on a PDF I cannot modify and an older version on the .ipe file.

Hope I have explained the issue, I can I fix it without having to save both as PDF and as .ipe every time?

**Comment by otfried** [comment]
When you "save as PDF", of course the file is only saved as PDF.   Why would it update the .ipe file?

What you can do is to set the preference
```
prefs.auto_export = { "pdf" }
```
Then every time you save the .ipe file, Ipe also exports a PDF file with the same contents.
