### ISSUE TITLE
Feature request: Implement links

### ISSUE THREAD

**Issue by pglira** [otfried/ipe#41]
Hi,

I'm using IPE predominantly to create presentations and it's working perfectly, except for one thing: I cannot include any movies / video files. Since the output is a pdf file, this seems quite logical to me. But I'm wondering if it is possible (as some kind of workaround) to insert a hyperlink into a presentation that calls a local(!) video file (placed in the same folder as the presentation). I tried many things, but wasn't able to find a solution. Can somebody help me please?

Regards

**Comment by otfried** [comment]
Creating links in the PDF document is not currently possible.  It cannot be done by tricks with pdf/xe/latex, since Ipe creates a PDF XForm for each text object and PDF link annotations cannot be inside an XForm...   I would have to add direct support for links in Ipe itself.

**Comment by otfried** [comment]
In 7.2.4.

**Comment by pglira** [comment]
Great, thank you so much!!!
