### ISSUE TITLE
Black screen when using calligraphic fonts

### ISSUE THREAD

**Issue by davidstalfa** [otfried/ipe#411]
I've been using several of the Auriocus Kalligraphicus fonts (https://tug.org/FontCatalogue/auriocuskalligraphicus/) but have run into a weird problem where the display goes completely black when I try to make them bold. The problem arises in a very simple setting -- I add \usepackage{aurical} to the latex preamble in Document Settings and then create a paragraph using any of the fonts, e.g. Fontauri. The text compiles fine as long as it's not bold. However, if you bold the text using \bfseries of \textbf it causes the whole display to go black unless the text is very short. It seems like you can still interact with things on the page (at least you can still edit the text using Ctrl+E) but if I remove the bold command the screen stays black. I've included a couple screenshots before and after hitting Apply to show what happens. 

Thanks for the help! 
 
![Screenshot 2021-11-28 220138](https://user-images.githubusercontent.com/57416116/143802108-79b5ff53-fd9f-4192-abba-ee4a11e75d88.jpg)

![Screenshot 2021-11-28 220633](https://user-images.githubusercontent.com/57416116/143802463-d58c5176-eff6-46f6-8195-6dadaf707413.jpg)

**Comment by otfried** [comment]
The problem happens for me on Windows with Freetype 2.9.1, but not on Linux with Freetype 2.10.1.  Let me try to upgrade Freetype on Windows to see if that fixes it.

**Comment by otfried** [comment]
Good news - upgrading Freetype fixes the problem.  I'll include a newer Freetype in 7.2.25.
