### ISSUE TITLE
Temporary files in "/home/pengdlzn/.ipe/latexrun" are not updated

### ISSUE THREAD

**Issue by pengdlzn** [otfried/ipe#413]
On the first page, I made a label and in it use the filecontents environment to save data, where the data is saved in a virtual file named RunningTime.txt. On the second page, I drew a figure according to the data (see the attached file).

When I changed the data in the filecontents environment, the data in the figure is not updated. I observed that file RunningTime.txt in folder "/home/pengdlzn/.ipe/latexrun" is not updated either.

Would it be possible to fix the problem?

[running_time.pdf](https://github.com/otfried/ipe-issues/files/7867578/running_time.pdf)

**Comment by otfried** [comment]
If you add the option `overwrite` to the `filecontents*` environment, it will work.

Also, `filecontents` is now part of Latex, so you can remove the `\usepackage{filecontents}` from the preamble.

**Comment by pengdlzn** [comment]
It works to add option `overwrite`.
Thank you very much!
