### ISSUE TITLE
All the views of a page have the same clipping rectangle

### ISSUE THREAD

**Issue by pengdlzn** [otfried/ipe#414]
I have a page of several views (see the attached file). In the pdf format, it seems that all the output pages have the same size, which means that each view of the ipe page is cropped with the same rectangle.

Would it be possible that each view of the ipe page has its own clipping rectangle or each view of the ipe page is cropped tightly?

[create_graph_test.pdf](https://github.com/otfried/ipe-issues/files/7874376/create_graph_test.pdf)

**Comment by otfried** [comment]
Check Section 8.2.5 in the manual:

https://ipe.otfried.org/manual/manual_views.html

**Comment by pengdlzn** [comment]
I have learned how to do it.
Thanks a lot!
