### ISSUE TITLE
Ipe 7.2.24 can't compile latex text 

### ISSUE THREAD

**Issue by Lorenzo-code-art** [otfried/ipe#415]
Good afternoon,
in the last few days IPE can't produce any drawing with LaTeX text inside. Every time I try to save a file, even with only one letter written in LaTeX, IPE shows an error in which it is reported:

 "_an error occured during the Pdflatex run. Error writing LaTeX source_."

I don't really have a clue about how to solve it. 
My PC runs windows 10.

Thank you in advance for your reply.

**Comment by otfried** [comment]
In the Help menu, open "Show configuration" and look for "Latex directory".   Does this folder exist?

**Comment by Lorenzo-code-art** [comment]
No, actually not

**Comment by otfried** [comment]
So there is your problem - Ipe is trying to create a file there, but cannot, because the folder does not exist.   What exactly does it display?   Did your user name change or something like that?

**Comment by Lorenzo-code-art** [comment]
Here you have the screenshot of the error:
![Capture](https://user-images.githubusercontent.com/68990199/151212688-a591971e-6f7a-455a-a26e-8831f09c4f1b.PNG)

No, nothing has changed, at least nothing that I personally changed. There isn't the entire _Local_ folder in AppData by the way

**Comment by otfried** [comment]
I meant - what exactly does it display for the Latex directory in the "Show configuration"?

It worked before on the same computer?   Perhaps an update to Windows 10 changed how these directories are organized.

**Comment by Lorenzo-code-art** [comment]
Oh, sorry, here it is

![Capture_2](https://user-images.githubusercontent.com/68990199/151214270-fe00930b-3eb8-41fb-b842-3289b0f798dd.PNG)

**Comment by Lorenzo-code-art** [comment]
Sorry, here it is
![Capture_2](https://user-images.githubusercontent.com/68990199/151214876-55f5eb71-6a79-40da-843b-537252bc4e36.PNG)

Yes it worked on the same PC, I've searched for recent updates, but I haven't seen anything that were installed the day or the day before IPE started not working

**Comment by otfried** [comment]
Do you instead have the folder "\users\...\Local Settings\Application Data" ?   That's what Ipe uses on my Windows 10 computer.

**Comment by otfried** [comment]
So the easiest would be that you simply create the folder that Ipe wants to use.

**Comment by Lorenzo-code-art** [comment]
> 

No, there is not.

**Comment by Lorenzo-code-art** [comment]
> 

Okay, I'll try to make it

**Comment by Lorenzo-code-art** [comment]
Okay, so here is the problem. The folder actually does exist. But for some reasons, it is not shown, even though the hidden files should be displayed by folder properties.

**Comment by otfried** [comment]
There seems to be something weird going on with the permissions on your computer.

The easiest would be to make another folder for Ipe to use - it could be as simple as `C:\ipelatexrun`.

Then make a text file `ipe.conf` inside your Ipe folder (the directory that has the bin, styles, lua subdirectories) with the single line
```
IPELATEXDIR=c:\ipelatexrun
```

**Comment by Lorenzo-code-art** [comment]
Yes, that worked, even though it requires a lot of time to compile, about 10 seconds

**Comment by Lorenzo-code-art** [comment]
Thank you very much for your help
