### ISSUE TITLE
Engine xetex doesn't work with filecontents environment

### ISSUE THREAD

**Issue by pengdlzn** [otfried/ipe#416]
I made a label and in it use the filecontents environment to save data, where the data is saved in a virtual file named RunningTime.txt. When I use pdftex as the engine, Ipe complies correctly. However, if I change the engine to xetex, Ipe returns an error.

Would it be possible to fix the problem?

Please find below the screenshot of the error and the minimal working example.

![error_message](https://user-images.githubusercontent.com/12211925/152665266-d322e90c-0c73-4563-ac45-0d457d34f33f.png)

[case_study_test.pdf](https://github.com/otfried/ipe-issues/files/8009268/case_study_test.pdf)

**Comment by otfried** [comment]
The problem is simply that text objects that produce no PDF output do not work correctly in the Ipe-xetex interface.  If you change the object to look like this, it will work:
```
X
\begin{filecontents*}[overwrite]{RunningTime.txt}
some text
\end{filecontents*}
```
You can put this object in a layer that is not visible to avoid having the X in the figure.  Or simply make it white.

**Comment by pengdlzn** [comment]
Hi Otfried, your solution works. Thank you very much!
