### ISSUE TITLE
7.2.24 is not running LaTeX

### ISSUE THREAD

**Issue by kwads123** [otfried/ipe#417]
No matter what I try, LaTeX will not run on ipe. I have checked to make sure pdflatex is on the path. I have also made sure that the latex dir exists. Please could you advise on how to fix this?

![image](https://user-images.githubusercontent.com/56446814/153015093-c6cec474-8e5f-48fc-b55d-4f97a7691317.png)

**Comment by otfried** [comment]
If you open a command line and type "pdflatex", do you get any output?

**Comment by kwads123** [comment]
Yes, it runs as expected. I tried running the same command that is defined in the runlatex.bat using command line and it worked fine.

**Comment by otfried** [comment]
Can you attach a screen shot of "Show configuration" (in the Help menu)?   And paste the exact contents of `runlatex.bat` here?

**Comment by kwads123** [comment]
Here is the output of Show configuration:
![image](https://user-images.githubusercontent.com/56446814/153017786-1ea2a220-8656-4ca0-b906-d25c18dd1813.png)

Here is the contents of runlatex.bat:
![image](https://user-images.githubusercontent.com/56446814/153018200-210ff2aa-5a6a-48be-9a1d-10bed14425b8.png)

**Comment by kwads123** [comment]
Here is the output of Show Contents:
![image](https://user-images.githubusercontent.com/56446814/153019257-8a0c4559-0aa4-4b9f-8754-e54757c62106.png)

Here is the contents of runlatex.bat:
![image](https://user-images.githubusercontent.com/56446814/153018306-d497d07b-cd39-4c49-9d39-75c30cf2a9bb.png)

**Comment by otfried** [comment]
In a command line, can you cd to that directory, and try to run runlatex.bat, like this:
```
c:
cd \Users\...\AppData\Local\ipe
call runlatex.bat
```

**Comment by kwads123** [comment]
I think you have found the source of the problem. It says that it is blocked by my administrator group policy. I may be able to get around that.

**Comment by kwads123** [comment]
Running ipe as administrator solved the problem.

**Comment by otfried** [comment]
If that is the issue, you can simply use any other directory and set the IPELATEXDIR variable.

See here: https://github.com/otfried/ipe-issues/issues/415#issuecomment-1022449466

**Comment by kwads123** [comment]
Running IPE as administrator solved the problem. Thanks for your help. Unbelievable response times!
