### ISSUE TITLE
ipe crashes very frequently when saving 

### ISSUE THREAD

**Issue by deadalps** [otfried/ipe#419]
Hello, I am using Fedora 35 with KDE and ipe 7.2.24 crashes very frequently after saving (about every 15 minutes). Can someone help me out? Here is the log (I started ipe from console):

$ ipe BD.pdf 
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 25182, resource id: 17755760, major code: 40 (TranslateCoords), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 61109, resource id: 17759628, major code: 40 (TranslateCoords), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 21474, resource id: 17763184, major code: 40 (TranslateCoords), minor code: 0
Segmentation fault (core dumped)

Best regards,
Manfred

**Comment by otfried** [comment]
How did you install Ipe?

That output may not have anything to do with the problem - apparently it simply means that a window disappeared, which may be a consequence of the crash, not the other way round.

You could try running
```
gdb --args ipe BD.pdf
```
and then `run` to start Ipe.  You should be more useful information about where it crashed.

**Comment by deadalps** [comment]
I installed ipe using the fedora package manager dnf.
i ran gdb and ipe crashed with an additional window showing "Compiling Latex". 
the last line of gdb shows
```
Thread 1 "ipe" received signal SIGSEGV, Segmentation fault.
0x00007ffff6df852b in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) () from /lib64/libQt5Core.so.5

```
you can find the full log here and a screenshot of the crash (gdb keeps the ipe windows open after the crash)
[log.txt](https://github.com/otfried/ipe-issues/files/8222109/log.txt)
![Screenshot_20220310_103353](https://user-images.githubusercontent.com/67948783/157634495-973adcc2-dbd1-496b-b5a7-209eafeab45a.png)

**Comment by deadalps** [comment]
sorry, i attached an empty log file. here is the correct on
[log.txt](https://github.com/otfried/ipe-issues/files/8222154/log.txt)
e

**Comment by otfried** [comment]
Unfortunately that log has very little information. 

So the problem is not specific to this Ipe file, it happens also with other documents?

My guess would be that there is some problem with the KDE integration.  I wonder if Fedora is making any changes to Qt for that.

Since you are using the official Fedora release, you might have more luck reporting it on the Fedora bug tracker.
