### ISSUE TITLE
Two-point perspective grid fails to detect quadrilateral

### ISSUE THREAD

**Issue by phdoerfler** [otfried/ipe#420]
Ipelets -> Gridmaker -> Two-point perspective grid fails to identify quadrilateral.

I tried with multiple tools, lastly with the polygon tool <kbd>Shift</kbd>+<kbd>P</kbd> but to no avail:
![image](https://user-images.githubusercontent.com/163428/159482740-d4185bf7-725e-4de2-9166-838bff91e03b.png)

I'm very new to Ipe, please excuse if I'm missing something obvious here.

Related: #256

Ipe version: Ipe 7.2.24, installed via `homebrew install --cask Ipe` on macOS 12.2.1 (21D62)

**Comment by otfried** [comment]
Can you attach the Ipe document you made with the quadrilateral?

**Comment by otfried** [comment]
My guess is that you have accidentally created a polygon that is not really a quadrilateral, perhaps by clicking the last vertex first with the left and then with the right mouse key.  If you right-click on the polygon and select "Edit as XML", you should see exactly 4 coordinate pairs.
