### ISSUE TITLE
Move graph nodes does not update the center of circular segments

### ISSUE THREAD

**Issue by loizuf** [otfried/ipe#424]
When creating a circular arc segment (through points A, B and C) and then placing marks on either end, one can use the "Move graph nodes" tool to move the ends. The endpoint of the circular segment is updated, but the center of the circular segment is not. If one enters edit mode end simply moves one endpoint slightly (and, for example, just drops it back where it already is), the center is then correctly updated.
However the behaviour seems to be slightly off and depends on which end (A or C) you move.

(i) If you move the starting point (A) of the circular segment (the one which was defined first), the geometry of the circular segment is updated to still start at that endpoint, but the center stays where it was, distorting the line away from a circular arc. But it is still rendered as a circular arc starting at the crossing point of the supporting circle of the original arc and the straight line between the center of the arc and the new position of A
(ii) If you move the endpoint (C), the geometry is the same as what is rendered. The circular arc now ends at the crossing point between supporting circle of the original arc and the straight line between the center and the new position

Since the update of the arc center does happen when you move one endpoint in edit mode, I assume, that would be expected behaviour.

I attached a screenshot showcasing this and the ipe file.
![move_bug](https://user-images.githubusercontent.com/6917005/161719667-f190ecb8-a197-4e81-aff4-67c491571bec.png)
[move_bug.pdf](https://github.com/otfried/ipe-issues/files/8416617/move_bug.pdf)

Best wishes,
Soeren

**Comment by otfried** [comment]
Fixed in 7.2.26.
