### ISSUE TITLE
Invisible Icons on Fedora 36 / GNOME 42.2

### ISSUE THREAD

**Issue by Nacknime** [otfried/ipe#427]
Both with the Fedora 33 .rpm as well as when compiled from source, most of Ipe's icons are not showing up. All other functionality is working, including LaTeX compilation and viewing existing figures.

I use Fedora 36, GNOME 42.2, the issue happens in both Light and Dark Mode and seems to not be affected by the theme. There are no warnings or errors on the Terminal where ipe is launched from.

Screenshot attached.
![Screenshot from 2022-06-09 16-40-43](https://user-images.githubusercontent.com/34569965/172874959-cd1f12ed-e555-446b-a515-761ecf7f33da.png)

**Comment by otfried** [comment]
Perhaps the solution in #401 solves this?

Otfried

**Comment by Nacknime** [comment]
Thank you so much for your quick answer, this solved it! I'm sorry, for some reason I only searched among the currently open issues.
