### ISSUE TITLE
Ipe suddenly crashing on opening (Fedora Linux 36 / Gnome 42.1)

### ISSUE THREAD

**Issue by neuroshock1** [otfried/ipe#428]
Hi,

Long time fan of Ipe! I just upgraded Fedora Linux to 36, and now Ipe won't open. If I run it at a command prompt, it crashes with the following message:

/usr/include/c++/12/bits/stl_vector.h:1122: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = double; _Alloc = std::allocator<double>; reference = double&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.
Aborted (core dumped)

Please let me know if you need more information. Thanks!

**Comment by otfried** [comment]
Fedora apparently added a new option during compilation that breaks Ipe, see https://github.com/otfried/ipe-issues/issues/392 (and the linked one) for an explanation.

I reported the problem, the newest Fedora package (apparently released yesterday) fixes it:
https://packages.fedoraproject.org/pkgs/ipe/ipe/fedora-rawhide.html
You would need the 7.2.24-5 package (I'm not sure how easy it is to get that onto Fedora 36).

I will also release the current Ipe version soon so the corrections get onto all distributions...

**Comment by otfried** [comment]
You can download a package of Ipe 7.2.25 that should work on FC36 from ipe.otfried.org.

**Comment by neuroshock1** [comment]
It didn't work after doing a full dnf update in Fedora – but it did work after using the latest Ipe RPM package from your website. Everything is great now. Thanks so much!
