### ISSUE TITLE
Text with underscore causes latex error

### ISSUE THREAD

**Issue by SHuang-Broad** [otfried/ipe#43]
Hi Otfried, 

I've found that inputing text having underscore would cause latex errors.
The error message from trying to type in "underscore_causesError" is attached.
Looking at the output, it seems that underscore in text is messing with latex, and a temporary fix would be writing "underscore\_notToCauseError".

Machine: Retina MBP Mid-2015 with OS X 10.10.5.
Latex info is in the file.

Thanks.
[Ipe_error_running_latex.txt](https://github.com/otfried/ipe-issues/files/128436/Ipe_error_running_latex.txt)

Steve

**Comment by otfried** [comment]
This seems to be a misunderstanding.  Ipe requires you to enter text in Latex format - Latex does not allow underscores in text (it's an active character that has a function only in math mode).

**Comment by SHuang-Broad** [comment]
Hmm, sorry for the false alarm and not reading the manual!
Refugee from xfig.
