### ISSUE TITLE
Key-Binding for macOS Monterey 

### ISSUE THREAD

**Issue by RickFreemanCui** [otfried/ipe#431]
The default key shortcut for selection is control+left on Windows, which works just fine for me. However, on macOS the control key is a bit too far and instead I want to change it to command+left. The documentation guides me to creating a customization file ~/.ipe/ipelets/customize.lua. However, the following line does not work

>mouse.left_command = "select"

I tested that binding the right-key (which is simulated by pressing the touchpad with two fingers) works perfectly, using the following line:

> mouse.right_command = "select"

Does anyone know why binding command+left would fail? Or is there any mistake in my configuration?

Here is my system information:

Hardware: MacBook Pro (13-inch, M1, 2020)

Software: 

* Lua code: /Applications/Ipe.app/Contents/Resources/lua/?.lua
* Style directories:
- /Users/name/.ipe/styles
- /Users/name/Library/Ipe/Styles
- /Applications/Ipe.app/Contents/Resources/styles
* Styles for new documents: basic
* Autosave file: /Users/name/%s.autosave
* Save-as directory: .
* Documentation: /Applications/Ipe.app/Contents/SharedSupport/doc
* Ipelets:
- /Applications/Ipe.app/Contents/Resources/ipelets
- /Users/name/.ipe/ipelets
- /Users/name/Library/Ipe/Ipelets
* Latex program path: 
* Latex directory: /Users/name/.ipe/latexrun/
* Icons: /Applications/Ipe.app/Contents/Resources/icons/
* Screen geometry: 1440 x 900
* External editor: open -W -n -e %s

**Comment by otfried** [comment]
Fixed in 7.2.26. 
Also defining left|right_command to be equivalent to left|right_control by default.

**Comment by RickFreemanCui** [comment]
thanks mate, I updated my software and it works like a charm now.
