### ISSUE TITLE
error running Latex: 'xcolor.sty' not found

### ISSUE THREAD

**Issue by deividvillamil** [otfried/ipe#432]
hello
I just installed ipe. I want to place text on the figure I am creating, I open the [Create text object] popup window, enter the desired text and the error occurs:
  ! LaTeX Error: File `xcolor.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: style)

Enter file name:
! Emergency stop.

--
can you help me please.

**Comment by otfried** [comment]
Your Latex installation is missing the `xcolor` style file.  You should use its package manager to install this style (it's something very basic, I'm surprised any Latex setup would miss it).
