### ISSUE TITLE
absolute autosave paths do not work anymore

### ISSUE THREAD

**Issue by MerlindlH** [otfried/ipe#433]
Hello :)

A while ago, I set my autosave path to be "/tmp/%s.autosave~" in order to not clutter every directory with autosave files.
Lately (using 7.2.26 here) this seemed to have stopped working, as it now simply appends the absolute autosave path (for testing purposes set to `prefs.autosave_filename = "/home/merlin/%s.autosave~"`) to the file directory (in my test `/home/merlin/` for the file `/home/merlin/test.ipe`). 
See also the image below for the error popup I get:
![image](https://user-images.githubusercontent.com/8302493/182349164-6bfbcceb-0dc1-4ea5-8a85-045f1957524c.png)
I added this preference mentioned above in a custom ipelet in `~/.ipe/ipelets/customize.lua` which gets picked up normally.

Would be great if you can have a look at this. Please let me know if you need more details :)

**Comment by otfried** [comment]
What a stupid bug, it seems I hadn't programmed in Lua for too long.

It'll be fixed in the next release.   You can fix it yourself by finding the file `model.lua`, inside it the function `MODEL:autosave`, and changing it as follows:
```
function MODEL:autosave()
  -- only autosave if document has been modified
  if not self:isModified() then return end
  local f
  if self.file_name then 
    if prefs.autosave_filename:find("%%s") then
      f = self.file_name:match(prefs.basename_pattern) or self.file_name
      f = string.format(prefs.autosave_filename, f)
    else
      f = prefs.autosave_filename
    end
    if f:sub(1, 1) ~= prefs.fsep then -- relative filename
      local d = self.file_name:match(prefs.dir_pattern)
      if d then
        f = d .. prefs.fsep .. f
      end
    end
  else
    f = prefs.autosave_unnamed
  end
  self.ui:explain("Autosaving to " .. f .. "...")
  if not self.doc:save(f, "xml") then
    messageBox(self.ui:win(), "critical", 
	       "Autosaving failed!\nFilename: " .. f)
  end
end
```
(Only the line with the comment "relative filename" has changed.)

**Comment by MerlindlH** [comment]
Your fix works splendidly, thank you very much for providing it in such a timely manner!

One remark for future consideration: in the current implementation, `~` cannot be used as shorthand for `/home/<current user>` and there are probably some other things (e.g. absolute paths with drive letters on Windows) that may not work as well (have only tested `~` though). Handling all these things manually seems cumbersome to me, and I'm more than happy with the current fix, I just wanted to mention that these things may be problematic for others. 

Cheers,
Merlin :)
