### ISSUE TITLE
Pen width heavier is not displaying correctly

### ISSUE THREAD

**Issue by EEsanity** [otfried/ipe#434]
IPE drawing is such as wonderful tool to use.

I found a minor problem displaying the Pen width at Heavier.
It looks still as normal to me.

Could you fix this bug in the next version?

Thanks

Ye

![image](https://user-images.githubusercontent.com/45189878/189183083-add69910-20b0-4665-af68-11dfdebdc2bc.png)

**Comment by otfried** [comment]
This seems to be a misunderstanding.  "heavier" is heavier than "normal", but thinner than "fat".  If you zoom in, you'll be able to see the difference.

In the standard "basic" stylesheet, normal is 0.4, heavier is 0.8. and fat is 1.2, but you can of course change this any way you like in your own stylesheet.

The ordering of the attributes in the popup has nothing to do with the thickness, it's somewhat arbitrary.
