### ISSUE TITLE
Latex font

### ISSUE THREAD

**Issue by Juleszlsk** [otfried/ipe#438]
Good afternoon,

It's been a while that the font used to compile latex in ipe isn't the default one (I prefer). I'm using the online compiler and sometimes miktex. I've tried several times to reinstall miktex and delete the ipe's  latex directory in vain.
I've also tried to change the latex preambule with : 
\usepackage[utf8]{inputenc}
\usepackage[TS1,T1]{fontenc}
\usepackage{lmodern}

but the '=' and other symbols disapear and the font isn't the cmodern (default).

Thanks

**Comment by otfried** [comment]
I'm sorry, I cannot understand what the problem is.   Can you clarify:
1. what you expect to happen,
2. what is happening instead,
3. and attach an Ipe file the shows the problem?

**Comment by Juleszlsk** [comment]
Sorry and thank you, 
Things have changed:
With the first image, it's now working and I have the latex font I want. The latex preambule is empty and I'm using the online compiler.

![Good](https://user-images.githubusercontent.com/116444765/198206312-8c71a91b-0117-49fa-9c67-bad738ea90bd.PNG)


But, the file created while having font troubles isn't still compilling with the font i want (see second image). 
![Wrong](https://user-images.githubusercontent.com/116444765/198207428-f706400d-10af-45a5-a8e3-59f08c252016.PNG)

As seen on the first picture, the equation is working on the default font. (Except the \bolsymbol{} where I still have an issue).
I think it's more a latex problem than a ipe one, it's nearly solved I think. I've recovered for the basic use the font I want. You don't to spend time on this.

Thanks

**Comment by otfried** [comment]
To debug this kind of Latex problem, it is convenient to find out where Ipe's latex directory is (Help -> Show configuration).  You can go to that directory and run `pdflatex ipetemp.tex` from the command line to see what is happening.  (Assuming you are using your local Latex installation, of course.)
