### ISSUE TITLE
Broken mirror

### ISSUE THREAD

**Issue by urgrueA** [otfried/ipe#439]
Using ipe 7.2.26, the mirroring under Ipelets > Goodies appears to be whacked. With axes set and object selected, choosing any of the four mirroring options leads to the object vanishing. However, a work around at this point is to use Ctrl+E. The ready-for-editing object reappears at the required position, and you must then Accept the "edit" to restore normality. This does not work with multiply selected objects nor with grouped objects, however. 

I'm sure this used to work properly before.

I tried this earlier today with a plotted curve. Strangely, the curve appeared unreflected somewhere else on the page and promptly disappeared when the aforementioned "edit" was accepted.

**Comment by otfried** [comment]
Could you attach an Ipe file where mirroring doesn't work?   I cannot reproduce the issue.

**Comment by urgrueA** [comment]
Running Windows 7 x64

[mirror_test.zip](https://github.com/otfried/ipe-issues/files/10048215/mirror_test.zip)

**Comment by otfried** [comment]
You have set all the objects to have transformation mode 'rigid motion'.   In Ipe, that does not include reflections, so what happens is that Ipe calculates a new position and a rotation, and then translates and rotates the object there.   I agree that the new location is not very logical, I will look at what exactly happens there, but in any case, you can fix your problem by selecting the objects and setting the transformation to "affine transformation".

**Comment by urgrueA** [comment]
My mistake. Great software, BTW.

Thank you
