### ISSUE TITLE
Compilation on OSX

### ISSUE THREAD

**Issue by m7thon** [otfried/ipe#44]
Following the instructions for compilation of ipe (7.2.2) on OSX runs into the following error:

`make[1]: *** No rule to make target `mainmenu.xib', needed by `../../build/Ipe.app/Contents/Resources/mainmenu.nib'.  Stop.`

I guess the file `mainmenu.xib` is missing from the sources?

**Comment by otfried** [comment]
Indeed, it seems to be excluded from packaging.  Here it is:

[mainmenu.xib.txt](https://github.com/otfried/ipe-issues/files/136676/mainmenu.xib.txt)

**Comment by m7thon** [comment]
Thanks, that does it.
