### ISSUE TITLE
Feature request: Add /opt/homebrew/bin path to Info.plist

### ISSUE THREAD

**Issue by tsuruken29** [otfried/ipe#440]
Hi, I'm currently using Ipe 7.2.26 on OSX.

I use vscode as my external editor for Ipe by setting `prefs.external_editor = "code --wait %s"` in `customize.lua`.
However, I install vscode via homebrew, so the `code` command is located in `/opt/homebrew/bin`.
Therefore, right now I need to 
1. Add `/opt/homebrew/bin` path to `/Applications/Ipe.app/Contents/Info.plist`.
2. Clear cache of `Ipe.app`

and it is a bit of a hassle.

Would it be possible to add `/opt/homebrew/bin` path to Info.plist for future versions?

**Comment by otfried** [comment]
Wouldn't it be easier if you simply set
```
prefs.external_editor = "/opt/homebrew/bin/code --wait %s"
```
?

**Comment by tsuruken29** [comment]
Yes, this will perfectly work if I would only want to modify the settings of `prefs.external_editor`.

However, I also use several custom ipelets files using `pdftoipe`. (which I also install using homebrew.)
The custom ipelets files are created for cross platform support, so changing all of the code to `/opt/homebrew/bin/pdftoipe` would be more mess for me.

Otherwise, I thought that `/opt/homebrew/bin` is a somewhat important directory to add to the default list of path, but are there technical issues to simply add it?

**Comment by otfried** [comment]
Sure, I was just wondering.  It seems weird that MacOS does not provide a better way to add something to the path for everybody.

I guess I can delete `/opt/local/bin` from the path, then?   Does `/opt/homebrew/bin` replace that?

**Comment by tsuruken29** [comment]
True, wish it was more easier and intuitive.

Was `/opt/local/bin` a path for MacPorts support? Currently for homebrew users who do not use MacPorts, it seems the existence of `/opt/local/bin` does not matter. Simply adding `opt/homebrew/bin` to the end worked  for me.

If there is not much of a reason, I think `opt/local/bin` should be kept just in case there is a MacPorts user.

**Comment by otfried** [comment]
Ah yes, it's possible we once added that for MacPorts.  Are MacPorts and Homebrew still both actively maintained?  

In any case, I've added `/opt/homebrew/bin` now.

**Comment by tsuruken29** [comment]
Thank you!

On the current state of 2022 MacOS package manager, both MacPorts and Homebrew are actively maintained.
However, currently Homebrew seems to be by far the most popular option.
