### ISSUE TITLE
escaping < in stylesheets

### ISSUE THREAD

**Issue by noinia** [otfried/ipe#443]
I just wanted to define some symbol in the preamble of my ipe stylesheet; in particular something like:

```xml
<?xml version="1.0"?>
<!DOCTYPE ipestyle SYSTEM "ipe.dtd">
<ipestyle name="bug">
  <preamble>
    \newcommand{\pred}{\ensuremath{\pi^{<}}}
  </preamble>
</ipestyle>
```

however when I try to load it in ipe I get an "Parsing error at 136" error. It seems ipe doesn't like the '<' in my piece of latex definition. I tried escaping it with a backslash, but ipe also does not seem to like that. Is there a way to escape <'s appropriately? I couldn't really find this in the manual.

ipe version: Ipe 7.2.24

**Comment by otfried** [comment]
This is XML, so `&lt;` should work.

**Comment by noinia** [comment]
ah, it seems I should have used the html/xml code for < instead. (which I discovered by looking at the xml file after inserting some < in a text field in ipe). So this does seem to work:

```
 \newcommand{\pred}{\ensuremath{\pi^{&lt;}}}
```

It might be nice to remind the reader about this somewhere in the ipe docs. (But feel free to otherwise close this).

edit: ah, just too late :)
