### ISSUE TITLE
[Feature request] Curve trim

### ISSUE THREAD

**Issue by brunolnetto** [otfried/ipe#444]
I have no intent to exhaustively research a curve trim on Ipe pallet. Hence, I post here to request help:

A curve trim requires a continuous curve and two non-coincidental points on this curve. Based on these requirements, the command "trim" operates like a scissor, cutting the curve between these two points. 

This may become very complicated since there are closed and self-intercepting curves.

**Comment by otfried** [comment]
You are right that someone needs to write a tutorial on editing paths.  Until then,  I suggest you ask for help on the Ipe discussion list (https://mailman.science.uu.nl/mailman/listinfo/ipe-discuss).

Cutting paths into pieces is already fully supported in Ipe, but one needs to learn how to use it correctly...
