### ISSUE TITLE
feature request: lock all layers and add a scratchpad layer for presentation

### ISSUE THREAD

**Issue by pierreganty** [otfried/ipe#445]
When using Ipe as described in the Section 8.7 of the manual "Filming from the canvas" one would like
a "live on stage" configuration to prevent accidental deletions (it happened to me) while allowing annotations.
It can already be achieved by setting all the layers on all the views as locked and adding, as the active yet unlocked layer on each view, an extra "scratchpad" layer that you can use as you please (e.g. with the `Ink` mode). 
In the current version of Ipe it can be done manually but it is kind of tedious if you have many pages.
`ipetoipe` could have a flag that takes a presentation lock all layers on all the views of all pages and add a scratchpad (and therefore active) layer for annotation.

**Comment by otfried** [comment]
This would be a typical application of an Ipe script.   Here is one that does what you ask for - just save it as `~/.ipe/scripts/scratchpad.lua` and then run as
```
ipescript scratchpad <input> <output>
```

```
#!/usr/bin/env ipescript 
-- -*- lua -*-
----------------------------------------------------------------------
-- Create a copy of an Ipe presentation for presentation inside Ipe
----------------------------------------------------------------------
--
-- Running this script as "ipescript scratchpad <input> <output>" will
-- create <output> as a copy of the Ipe document <input>,
-- but adding a new layer "scratchpad" to all pages of the input,
-- making this layer the active layer of every view,
-- and locking all input layers.
--
----------------------------------------------------------------------

if #argv ~= 2 then
  io.stderr:write("Usage: ipescript scratchpad <input> <output>\n")
  return
end

local inname = argv[1]
local outname = argv[2]

local doc = assert(ipe.Document(inname))

for pno = 1,#doc do
  print("Page: ", pno)
  local p = doc[pno]
  p:addLayer("scratchpad")
  for vno = 1,p:countViews() do
    p:setActive(vno, "scratchpad")
    p:setVisible(vno, "scratchpad", true)
  end
  for i, l in ipairs(p:layers()) do
    if l ~= "scratchpad" then
      p:setLocked(l, true)
    end
  end
end

doc:save(outname)
```
