### ISSUE TITLE
IPE not parsing input in canonical XML form

### ISSUE THREAD

**Issue by pierreganty** [otfried/ipe#446]
In an attempt to solve #445 leveraging XML tools I bumped into the following which might or not be an issue (I let you decide).

Take this mwe
```xml
<?xml version="1.0"?>
<!DOCTYPE ipe SYSTEM "ipe.dtd">
<ipe version="70218" creator="Ipe 7.2.26">
<info created="D:20230122134457" modified="D:20230122134538"/>
<page>
<layer name="alpha"/>
<view layers="alpha" active="alpha"/>
</page>
</ipe>
```
and produce a [canonical](https://en.wikipedia.org/wiki/Canonical_XML) version of the XML document. This can be accomplished, for instance, by running:
```
xmllint --c14n mwe.ipe
```
The result is
```xml
<ipe creator="Ipe 7.2.26" version="70218">
<info created="D:20230122134457" modified="D:20230122134538" pagemode="fullscreen" tex="pdftex"></info>
<page marked="yes">
<layer edit="yes" name="alpha" snap="visible"></layer>
<view active="alpha" effect="normal" layers="alpha" marked="yes" name=""></view>
</page>
</ipe>
```
Ipe does not open the canonical XML document and returns parsing errors. The ones I investigated are of the following form.
Before putting the XML in canonical form:
```xml
<info created="D:20230122134457" modified="D:20230122134538"/>
```
After:
```xml
<info created="D:20230122134457" modified="D:20230122134538" pagemode="fullscreen" tex="pdftex"></info>
```
In particular going from `<info />` to `<info></info>` seems the problem.
In larger examples it happens with others fields including `<anglesize>`, `<arrowsize>`, ...

Given that the Ipe manual states that:
> The second Ipe file format is a pure XML implementation. Files stored in this format can be parsed with any XML-aware application, and you can create XML files for Ipe from your own applications.

The described issue either ought to be fixed or the manual should make more precise what Ipe is capable of.

**Comment by otfried** [comment]
I should probably drop the homegrown XML-parser I wrote in 2003 and use a library.  On the other hand, that adds yet another dependency I need to worry about for the Windows build...

**Comment by pierreganty** [comment]
I completely understand the dilemma here. I have no experience with XML libraries hence no help to offer. I did however see a [SO thread](https://stackoverflow.com/questions/3966548/c-xml-library-for-use-under-windows) where [pugixml](https://pugixml.org/) appears as a reasonable option.

**Comment by otfried** [comment]
Let me not fix this now.   We can always revisit it later if a compelling use case arises.
