### ISSUE TITLE
Infinite edges in Voronoi diagrams behaving strangely

### ISSUE THREAD

**Issue by Nacknime** [otfried/ipe#447]
[bug.pdf](https://github.com/otfried/ipe-issues/files/10570888/bug.pdf)
When creating a Voronoi diagram of all the points in the attached picture, some edges are extended into infinity, and cause visual bugs as shown in the following picture:

![image](https://user-images.githubusercontent.com/34569965/216376885-83212836-0045-41d7-b775-0e07552f8f44.png)

I think this might be related to closed issue #301 , but I am using Ipe 7.2.26 (on Fedora Wayland), in which this should be fixed already.

**Comment by otfried** [comment]
The Voronoi code using qhull uses floating point arithmetic, it has issues with very degenerate situations like this one.

I have added some slack so this example will work correctly in 7.2.27.  In general, however, you may be better off with the CGAL ipelet which is meant to handle arbitrary inputs.
