### ISSUE TITLE
OSX: Resizing window distorts canvas (minor cosmetic issue)

### ISSUE THREAD

**Issue by m7thon** [otfried/ipe#45]
On OSX (7.2.2) using the cocoa interface, during the resizing of the ipe application window by dragging a corner of the window with the mouse, the canvas gets distorted (scaled). When releasing the mouse, the canvas updates correctly again.

Here is what it looks like (only during the actual resizing of the window):

![ipe_resizing_window](https://cloud.githubusercontent.com/assets/5876537/13164047/a0ba89c8-d6b2-11e5-8b4c-942068fcdaa4.jpg)

There is nothing really wrong with this, but it does look weird and unexpected. I am almost sure there is some simple property of the canvas that can be changed to get a more natural behavior (as it was before with Qt).

**Comment by otfried** [comment]
The Qt-way is very resource-wasting and prone to flickering:  every time the size of the canvas changes (even if it's only a few pixels), it discards the old backing surface and draws everything again on a new backing surface.

Cocoa let's me detect easily that we are inside a live-resize operation, so we can draw an approximation cheaply.    Yes,  I could do something better by first rendering the entire page to a surface and scaling that properly, but it doesn't seem worth the effort.
