### ISSUE TITLE
Ipe does not show page number when there is no text

### ISSUE THREAD

**Issue by us91** [otfried/ipe#450]
When there is no text on the page, and "number pages" is set, Ipe does not show page numbers, because LaTeX is not run (as it thinks it is unnecessary). This usually is not a problem, because there is almost always some text on the page. However, in some cases, e.g., when the page has only lines, or when the page is fresh, not showing page number even when the user requests can be confusing.

So LaTeX running logic should be changed so that it is run when there is text, or, when "number pages" option is set.

This also affects "ipetoipe -pdf -export".

**Comment by otfried** [comment]
Fixed in 7.2.27.
