### ISSUE TITLE
Switching spell checking language by other means than environment variables

### ISSUE THREAD

**Issue by jonasc** [otfried/ipe#451]
Maybe I've missed it, but I looked through the manual, wiki, and issues here, but couldn't find any more details about the spell checking mechanism.

The spell checking, which is done by Ipe in text fields, seems to depend on the currently set locale. On my Linux system (which is set to English) I can thus force German spell checking (for German slides) by launching Ipe as `LANG=de_DE.UTF-8 ipe`. However, it would be nice to have an option to set the document language in the file options and having the spell checking respect the setting.
I think a good place, if considered, would be the document properties.

If one wanted to go further, it might even be possible to set a document wide language in the document properties and still have the option to locally change the language for specific text boxes.

However, I guess that this really is not an urgent problem, as I can easily work around it. I just thought I might leave these thoughts here, even for other people who have wondered about changing the spell checker language.

**Comment by otfried** [comment]
That would be quite easy to add, but it's a bit problematic to put it in the document properties, since this would only work on Linux.

**Comment by wang2357** [comment]
I thought it might be worth mention that one can do spell checking of any Ipe presentations using aspell:
```
aspell \
    --add-sgml-skip=bitmap \
    --add-sgml-check=title \
    --add-filter=sgml --add-filter=tex -c file.ipe
```
This will check the text part of the document, assuming it is written in TeX. There should be a way to config aspell to use the dictionary from a language, say English or German.

**Comment by otfried** [comment]
I'll have to drop spell checking on Linux for the time being, as QtSpell is not yet available for Qt6.

**Comment by otfried** [comment]
In 7.2.28 you can set the language in the document properties, and that will be handed through to the spell checker.
