### ISSUE TITLE
ipe v 7.2.26 crashes on mac

### ISSUE THREAD

**Issue by dinesh-krishnamoorthy** [otfried/ipe#455]
I am using ipe v7.2.26, from a macbook running OS Monterey. 

I was using ipe just fine for a few months in my macbook, until suddenly it crashed yesterday, and now ipe crashes everytime i try to open it. This happens directly after starting ipe. 

I tried to uninstall and reinstall, still the same.
------------------------------------------------------------
Process: ipe [66904]
Path: /Applications/Ipe.app/Contents/MacOS/ipe
Identifier: org.otfried.ipe.Ipe
Version: 7.2.26 (7.2.26)
Code Type: X86-64 (Translated)
Parent Process: launchd [1]
User ID: 503

Date/Time: 2023-03-27 00:39:51.8725 +0200
OS Version: macOS 12.6 (21G115)
Report Version: 12
------------------------------------------------------------

When I run ipe.exec I get the following message with "bad argument.... "

------------------------------------------------------------
(base) ***@***.*** ~ % /Applications/Ipe.app/Contents/MacOS/ipe ; exit;
/Applications/Ipe.app/Contents/Resources/lua/model.lua:685: bad argument [#1](https://github.com/otfried/ipe-issues/issues/1) to 'setRecentFiles' (argument is not a table)
stack traceback:
	[C]: in method 'setRecentFiles'
	/Applications/Ipe.app/Contents/Resources/lua/model.lua:685: in method 'updateRecentFiles'
	/Applications/Ipe.app/Contents/Resources/lua/model.lua:83: in method 'init'
	/Applications/Ipe.app/Contents/Resources/lua/model.lua:14: in method 'new'
	/Applications/Ipe.app/Contents/Resources/lua/main.lua:489: in main chunk
	[C]: in function 'require'
	[string "require "main""]:1: in main chunk

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

**Comment by otfried** [comment]
Aha, so this sounds very different from what you reported before (which was an issue about Ipe not running on new Mac OS versions).

Could you check the contents of the file `~/.ipe/latexrun/recent_files.lua` ?

**Comment by dinesh-krishnamoorthy** [comment]
recent_files.lua  is completely empty. :/

In the same folder ~/.ipe/latexrun, there is an ipetemp.tex and a corresponding pdf, where I can see some latex text boxes that I was using in ipe just when it crashed.

**Comment by otfried** [comment]
Aha, so that is the problem.  Can you delete the file `recent_files.lua` and restart Ipe?

**Comment by dinesh-krishnamoorthy** [comment]
Great! That resolved it. 

Thank you very much for your help and for developing such a great tool. :)

**Comment by otfried** [comment]
It'll be fixed in the next version that if this file ends up in an invalid state it doesn't crash Ipe.
