### ISSUE TITLE
Title is off to the right in `presentation.isy` style

### ISSUE THREAD

**Issue by pierreganty** [otfried/ipe#464]
In `presentation.isy` I think the title should be a positioned at 608 (=640-32) rather than 640.

```diff
 <layout paper="1280 720" origin="32 0" frame="1216 648" skip="3
2" crop="no"/>
-<titlestyle pos="608 674" size="large" color="title"
+<titlestyle pos="640 674" size="large" color="title"
            halign="center" valign="baseline"/>
 </ipestyle>
```

**Comment by otfried** [comment]
You are entirely right.   The error must have been in the stylesheet since I changed it to be 16:9 in 7.2.25, a year ago.  Funny that nobody noticed. 

Fixed in 7.2.28.
