### ISSUE TITLE
Cannot use on MacOs BigSur 11.5.1

### ISSUE THREAD

**Issue by varshadani** [otfried/ipe#466]
I downloaded ipe-7.2.27-mac.dmg but I cannot open it, because the OS says the developer cannot be verified
<img width="263" alt="Screen Shot 2023-05-14 at 9 54 35 PM" src="https://github.com/otfried/ipe/assets/23050621/e881a906-279f-4961-9b91-f17c29f7db46">

Any advice?

Thanks in advance,
Varsha

**Comment by otfried** [comment]
https://support.apple.com/en-au/guide/mac-help/mh40616/mac

**Comment by varshadani** [comment]
Thanks!
