### ISSUE TITLE
HiDPI monitors are not detected and do not work

### ISSUE THREAD

**Issue by GoBigorGoHome** [otfried/ipe#470]
I installed ipe 7.2.27 on my linux machine, and the monitor resolution is 3840x2160. But the screen geometry of ipe is 1920 x 1053, and the displayed graphics in ipe is a little bit blur.

How screen geometry is determined? Is there any settings option for it?

```
 * Lua code: /usr/share/ipe/7.2.27/lua/?.lua
 * Style directories:
  - /home/zjs/.ipe/styles
  - /usr/share/ipe/7.2.27/styles
 * Styles for new documents: basic
 * Autosave file: %s.autosave.ipe
 * Save-as directory: .
 * Documentation: /usr/share/ipe/7.2.27/doc
 * Ipelets:
   - /usr/lib/ipe/7.2.27/ipelets
   - /home/zjs/.ipe/ipelets
 * Latex program path: 
 * Latex directory: /home/zjs/.ipe/latexrun/
 * Icons: /usr/share/ipe/7.2.27/icons/
 * Screen geometry: 1920 x 1053
 * External editor: /usr/bin/nano %s
```

**Comment by otfried** [comment]
Apparently how Qt handles HiDPI-displays has changed between Qt5 and Q6.  I will have to investigate how to handle this.

I've just checked that I if you set `export QT_USE_PHYSICAL_DPI=1`, then the UI becomes crisp (but half the size) again.  However, it still doesn't give the correct Screen geometry, and drawings on the canvas are still blurry.

Unfortunately, HiDPI handling on Linux does not seem to be standardized at all...

https://doc.qt.io/qt-6/highdpi.html

**Comment by MiuKaShi** [comment]
try   `QT_ENABLE_HIGHDPI_SCALING=0 ipe`  maybe help for your case

**Comment by otfried** [comment]
I think I've fixed it.  I'll release 7.2.28 soon, hopefully next week.
