### ISSUE TITLE
drawings are too pixelated in editor

### ISSUE THREAD

**Issue by Aneeqasif** [otfried/ipe#476]
i am on x11 in linux and arch linux plasma 5.27 and Qt versin 5.15.10. I am on a hi-dpi laptop screen and using scalling. i am new to ipe and i dont know what how to fix the pixelated editor problem. asking here for support bellow is a screenshot to show the behavior 
![image](https://github.com/otfried/ipe/assets/78728701/b68c9807-930f-40fc-b28e-a00df1435302)

**Comment by otfried** [comment]
Which Ipe version are you running?  The current Ipe version uses Qt6 - what does Help -> Show libraries say?

For Qt6, see https://github.com/otfried/ipe/issues/470 for some tips.   For Qt5 similar environment variables existed.

**Comment by Aneeqasif** [comment]
> 

i am on following versions of libraries sir
```
Ipe relies on the following fine pieces of software:

 * Pdftex, Xetex, or Luatex
 * Lua 5.4 (823 kB used)
 * The font rendering library Freetype 2.13.0 / 2.13.1
 * The rendering library Cairo 1.17.8 / 1.17.8
 * The clothoid spline library libspiro 1.3
 * The GNU scientific library gsl 2.7.1 / 2.7.1
 * The GUI toolkit Qt 6.5.1 / 6.5.2
 * The compression library zlib 1.2.13
 ```
 i have tried `export QT_USE_PHYSICAL_DPI=1` and `QT_ENABLE_HIGHDPI_SCALING=0 ipe` but this didn't worked for me

**Comment by Aneeqasif** [comment]
any thing u might wanna suggest?

**Comment by otfried** [comment]
This is really the same issue as #470
