### ISSUE TITLE
Gridsize and angle dropdowns cut off option text (Mac)

### ISSUE THREAD

**Issue by nathaniel** [otfried/ipe#48]
In Ipe 7.2.2 on Mac, width of the the Grid and Angle dropdowns menus adjust to the width of their currently-selected option.  When the menu is activated (dropped), only menu items _narrower than_
the currently-selected option are show in their entirety; others are abbreviated (cut off).
See the attached screenshots.

Is there a way to fix the widths of these menus, to accommodate the longest members, so that no abbreviation occurs?  The changing size of the dropdown doesn't serve a useful purpose, here.

![grid_menu_cutoff](https://cloud.githubusercontent.com/assets/68211/13611925/92d19c9e-e52a-11e5-9728-54924d30172f.png)
![angle_menu_cutoff](https://cloud.githubusercontent.com/assets/68211/13611926/92d325dc-e52a-11e5-8527-188a586f74d5.png)

**Comment by otfried** [comment]
Fixed in 7.2.4.

**Comment by nathaniel** [comment]
new NSPopUpButton works great here.  Problem solved!
