### ISSUE TITLE
Crashes many times on arch linux

### ISSUE THREAD

**Issue by MiuKaShi** [otfried/ipe#482]
Recently, I started using ipe plotting a lot, but found that it often crashed suddenly. 

Several times I lost my plots that I've spent hours plotting and can't be recovered. It makes me crazy.

Since there is no history backup feature, I think the autosave function should be added.

(ps: I am using arch linux)

**Comment by otfried** [comment]
Ipe autosaves your file every 10 minutes.   The interval and the name of the autosave file are configured in the preferences.

Can you explain how you managed to crash Ipe?   What exactly do you mean by "ipe plotting"?   Are you using an ipelet to plot functions?

**Comment by MiuKaShi** [comment]
Thank you for your response, and sorry for late reply.

Yes, when I use my lua iplet, it crashes.
Now, I solved the problem by rewriting the script.

However, I still notice that when I try to adjust the font size or the size of the input figures.
IPE crashes more easily.

In addition, I found that when I import a png figure with a white background (create by OriginPro, 600 dpi), a gray border seems to be appear around the imported figure after export (also 600 dpi for export). How do I move this border?

Thank you

**Comment by aweinstein** [comment]
I'm using IPE 7.2.28 in Manjaro Linux. I'm also observing several crashes (about three in half an hour of use). 

Unfortunately, I can't find a correlation between the action and the crush. 

I've been using Ipe for many years, and I've never observed such instability. Since I am also using an Arch based Linux distribution, I wonder if it is a particular combination of libraries that generates the problem.

**Comment by otfried** [comment]
Perhaps you should bring this up on the bugtracker for arch packages?  (I assume there is such a thing?)

Arch is always very much ahead in terms of library versions, so if there has been a change in a dependency, the problem very often problems show first on arch linux.

**Comment by aweinstein** [comment]
I just commented about this issue here: https://aur.archlinux.org/packages/ipe#comment-945602

Also, I noticed that crashes happen when editing text. So maybe is related to https://github.com/otfried/ipe/issues/359.

**Comment by otfried** [comment]
I think this is the same issue as #495.  I've made some changes in 7.2.29, and I'm hoping they will eliminate the problem.
