### ISSUE TITLE
Export all slides to svg

### ISSUE THREAD

**Issue by dominikscheder** [otfried/ipe#483]
For my Html lecture notes I often create "carousels", for example illustrating an algorithm. Here is an [example](https://web1.hszg.de/scheder-lehre/AuK/lecture-notes/carousel-example.html)

To create this, I first create a presentation in Ipe with several slides/views. Then I export every page to an svg file. By hand. I go on every slide/view, and hit the key for "export to svg". This becomes tedious / repetitive / time consuming because sometimes I have over 30, sometimes even 50 pages. 

Question: is there a way to export *all* slides to svg, like creating fifty contiguously numbered svg files? If not, can I write some ipelet / lua script to accomplish this? What would be a good point to start learning this?

**Comment by otfried** [comment]
One way to do this would be to make a shell script that calls `iperender` on each view.  The only problem with doing that is that you would need to know the number of pages and the number of views per page, and getting those is not as easy as it should be.

Here is an ipelet that does what you want:

[splitviews.zip](https://github.com/otfried/ipe/files/12904225/splitviews.zip)

**Comment by dominikscheder** [comment]
Awesome! Thank you so much, Otfried!
