### ISSUE TITLE
Join paths shortcut not working

### ISSUE THREAD

**Issue by LenAgain** [otfried/ipe#485]
The default shortcut for joining paths (ctrl+j) isn't working for me.

I'm using Ipe 7.2.28 on Windows 11, with only the default ipelets loaded.

The feature works fine from the context menu, and I've checked that other shortcuts work fine.

**Comment by otfried** [comment]
Apparently the entry for `join_paths` in `shortcuts.lua` is a remnant of a historic version where this action was in the Edit menu.  It's simply not possible to have shortcuts for the context menu right now.

**Comment by LenAgain** [comment]
Thanks for clearing that up.

Are there any plans to change this behaviour? Having a shortcut for this action would be incredibly helpful.
