### ISSUE TITLE
affine scaling of line and arrow

### ISSUE THREAD

**Issue by MasahiroMae** [otfried/ipe#488]
Is it possible to affine scale line and arrow?
When I scale the line and arrow smaller by "stretch objects [E]", the line width doesn't change and the arrow size is still large.
Is there any solution other than just manually changing the line width and arrow size by option?

**Comment by otfried** [comment]
No, this is a design decision of Ipe.

Why do you want to do this?  Can you explain your use case?

**Comment by MasahiroMae** [comment]
I understand the design decision of Ipe.
The use case when I need the affine scale of the arrow is for smaller size than tiny.

**Comment by otfried** [comment]
So again what you really want is your own style sheet.  The standard one defines three arrow sizes:
```
<arrowsize name="small" value="5"/>
<arrowsize name="tiny" value="3"/>
<arrowsize name="large" value="10"/>
```

You can add as many as you want.
