### ISSUE TITLE
1pt and 2pt grid size option as a default

### ISSUE THREAD

**Issue by MasahiroMae** [otfried/ipe#489]
Is there any plan to restore the 1pt and 2pt grid size as a default for Ipe distribution?

**Comment by otfried** [comment]
Grid sizes are defined in the style sheet, so you can define any size you want yourself.

**Comment by MasahiroMae** [comment]
I also added 1pt and 2pt grid sizes to my stylesheet manually.
Is the reason that 1pt and 2pt are not as default for too small?
I wondered how many users do the same thing.

**Comment by otfried** [comment]
I don't remember hearing this request before, actually. 

In any case, advanced Ipe users are comfortable with creating their own style sheets - without that you are really very limited.

Note that 1pt is only about 1/3mm, is that really the grid you want?
