### ISSUE TITLE
Save As not pre-populated (7.2.2 on Mac)

### ISSUE THREAD

**Issue by nathaniel** [otfried/ipe#49]
On Mac, the "Save As" dialog does not pre-populate the filename with the current filename (not even the base name without suffix.)  Also, there are no file type options (.pdf, .ipe, .eps) to choose from.  See attached screenshot.
![saveas](https://cloud.githubusercontent.com/assets/68211/13612305/69703eda-e52c-11e5-906e-d9699d600c40.png)

While manually typing the desired filename and desired extension works fine, this is rather time consuming for the common workflow of "publishing" the current .ipe file to .pdf, with the same filename (just different extension).  It requires either retyping the entire filename, or finding the current .ipe file in the file browser and then changing the extension.  Ideally, "Save As" would propose the current filename, extension and all, rather than a blank filename.  A dropdown to select .pdf/.ipe/.eps would then be a quick way to simply save a different file type.

[Come to think of it, an option to _automatically_ save the same filename as _both_ .ipe and .pdf each time file is saved, would be delightful.  While I love Ipe's ability to edit the PDF files it generates, it occasionally happens that when viewing the PDF with another program, I inadvertently save over it, destroying the Ipe content.  Thus I like to keep the Ipe files for editing in Ipe, and the PDF versions for quicklook or for using in documents.]

**Comment by otfried** [comment]
Ipe had the ability to automatically save (or rather, export) into the other file formats for many years.  I finally removed it in 7.2.1 since nobody seemed to use it.

**Comment by otfried** [comment]
Implemented in 7.2.3.
