### ISSUE TITLE
Ipe 7.2.28 crashes (and the file is not readable anymore)

### ISSUE THREAD

**Issue by Pedro-RamosA** [otfried/ipe#490]
I'm working with Windows 10. Ipe crashes and the most serious thing is that the file cannot be read.
Pdf viewers also say that the pdf is corrupt (not using another pdf viewers).

**Comment by otfried** [comment]
Ipe automatically saves the document you are working on every 10 minutes.  Have you looked at the autosave file?

Otherwise you can attach the document here, or send it to me by email and I'll have a look if we can save it.

**Comment by Pedro-RamosA** [comment]
I could restore the file using dropbox, so it was not a serious problem, but I think I've lost the corrupted file. I will send it to you if this happens again. 
Thank you very much por your help!

**Comment by Pedro-RamosA** [comment]
I can't find new autosave files. It seems that the autosave option is not working (and I can't find where to switch it on again)

**Comment by otfried** [comment]
When you go to Help -> Show configuration, what does it display as the Autosave file?

**Comment by Pedro-RamosA** [comment]
![autosave](https://github.com/otfried/ipe/assets/153722568/98ba78ba-b9a5-4690-b3b9-cfd176093402)

I hope you can see the screen capture

**Comment by otfried** [comment]
So that means that autosaving is enabled.  The autosave file should be in the same folder as your original document.  If the original file is called "abc.pdf", the autosaved file would be called "abc.pdf.autosave.ipe".

**Comment by Pedro-RamosA** [comment]
Yes, that was my understanding... and now it is working! (It was not working this morning). 
Anyway, thank you very much for your help!
