### ISSUE TITLE
LaTeX in labels is not auto compiled when copied objects are pasted

### ISSUE THREAD

**Issue by GoBigorGoHome** [otfried/ipe#497]
![Peek 2024-02-28 18-48](https://github.com/otfried/ipe/assets/9896288/2cc31a1f-59fa-4841-8a6b-4bf997dd80d8)

The final frame of the GIF is after I pressed CTRL+L to compile latex.

I am using Ipe 7.2.28 on Manjaro Linux, kernel version 6.1.77.

Automatically run Latex is enabled in the File menu.

I am not sure if this is a bug or a feature.

**Comment by otfried** [comment]
Fixed in 7.2.29.

**Comment by GoBigorGoHome** [comment]
Just want to say Thank You @otfried. I should have reported earlier since I noticed this issue about half a year ago.
