### ISSUE TITLE
Exported SVG is truncated

### ISSUE THREAD

**Issue by GoBigorGoHome** [otfried/ipe#498]
![ipe-editor](https://github.com/otfried/ipe/assets/9896288/ffdcd8a2-526a-42b4-a98e-8ee0bd961ce1)

In the exported SVG of the drawing above, the arrow heads at the bottom are truncated.

Below is the exported SVG opened in the Edge browser

![svg-in-edge](https://github.com/otfried/ipe/assets/9896288/5f8fa600-1ade-4492-bedf-58ba8c8af849)

Below is the exported SVG opened in Inkscape, it is more obvious the that the drawing goes outside of the "canvas" at bottom

![svg-in-inkscape](https://github.com/otfried/ipe/assets/9896288/ec48533f-2798-4e77-b9d4-d2d74a864672)

The exported svg file:
![cycle-to-cycle-4-2](https://github.com/otfried/ipe/assets/9896288/bcca952e-2932-4eaf-98a6-5e600e1de4ee)

**Comment by otfried** [comment]
Fixed in 7.2.29.
