### ISSUE TITLE
Voronoi problem under Windows 

### ISSUE THREAD

**Issue by mkraska** [otfried/ipe#5]
When selecting a set of marks and calling ipelets>Voronoi diagrams, then any of the options leads to an error message (IPE 7.1.7, Win7)
![voronoi](https://cloud.githubusercontent.com/assets/12987918/8284547/a52ff218-18fd-11e5-93b5-bc706c62ef3f.PNG)

**Comment by otfried** [comment]
I finally found a fix.  For some reason qhull crashes when reporting the statistics of the convex hull found on Windows, but the problem does not happen when started under cygwin.  Mysterious, but fixed by removing the statistics output in 7.1.8.

**Comment by mkraska** [comment]
Thanks a lot.

**Comment by mkraska** [comment]
Can't confirm that the fix works.
![voronoi718](https://cloud.githubusercontent.com/assets/12987918/8635279/df8c4ba4-281c-11e5-9bee-7211a2b5b1fa.PNG)

**Comment by otfried** [comment]
Oops.  Sorry about this.  A patch is now available at 

https://github.com/otfried/ipe/tree/master/releases/7.1

**Comment by mkraska** [comment]
Sorry, the patch did not solve the problem. 
![voronoi718p](https://cloud.githubusercontent.com/assets/12987918/8636564/e59063e4-2869-11e5-8f2a-bac202f74538.PNG)

**Comment by otfried** [comment]
If you try Ipelets -> Voronoi Diagrams -> Set length of infinite edges,  do you get the small dialog where you can enter the edge length in points?

Also, can you attach the output of Help -> Show Configuration?

Which Windows version are you on exactly?

It seems your's may be a different problem from the one I have fixed...

**Comment by mkraska** [comment]
No, I don't get the dialog, just the same error message as for all other voronoi items. 

I don't know how to copy the text from the configuration window, therefore I attach a screenshot 

I am using Win7 pro 

----- Am 12. Jul 2015 um 8:23 schrieb otfried <notifications@github.com>:

**Comment by otfried** [comment]
If you don't get this dialog, then you indeed have a completely different problem from what I have been fixing...

I don't see an attachment.  Did you reply by email?  It seems you need to attach it through the github web interface.

**Comment by mkraska** [comment]
I attached the image to the previous comment. Seems that replying by mail does not convey attachments to the system.
Let me know if I can do something to support debugging.

**Comment by otfried** [comment]
If you can attach the screen shot of the "Show configuration" output to a new comment, that would be helpful.

**Comment by mkraska** [comment]
![config](https://cloud.githubusercontent.com/assets/12987918/8636903/249d522c-2879-11e5-84de-e9abce96135c.PNG)

**Comment by otfried** [comment]
Could you try this version:

https://www.dropbox.com/s/zn3ptfxhkwdg5rz/ipe-7.1.8-win.zip?dl=0

**Comment by mkraska** [comment]
Problem persists. error message slightly different.
![voronoi718p2](https://cloud.githubusercontent.com/assets/12987918/8637198/f543b874-2885-11e5-9a98-8825784b19aa.PNG)

**Comment by otfried** [comment]
The error message was the point: I wanted to know why it fails to call the Ipelet.

The error code 998 is "Invalid access to memory location" - which is unfortunately not very enlightening.

**Comment by otfried** [comment]
Could you try again?  Same link as before, the file was updated.

**Comment by otfried** [comment]
You could also right-click on the file d:\Programme\IPE\ipe-7.1.8\ipelets\qvoronoi.dll and look in the "Security" tab.   Do you have permission to "Read and Execute"?   The same may be necessary for d:\Programme\IPE\ipe-7.1.8\bin\qhull.dll.

**Comment by mkraska** [comment]
Same error as before (slightly different message formatting). 

I checked the security setting. All dlls have the warning message that they originate from the web and execution might be blocked. I allowed the access and even extended the access rights to full access for all users. This did not solve the problem. 

----- Am 12. Jul 2015 um 11:59 schrieb otfried <notifications@github.com>:

**Comment by otfried** [comment]
Did it say "Error 998 loading Ipelet DLL" or "Error 998 finding DLL entry point"?

**Comment by mkraska** [comment]
"Error 998 loading Ipelet DLL"

**Comment by otfried** [comment]
Are you running 64-bit Windows?

**Comment by mkraska** [comment]
This is the system information from SMath Studio, a freeware but closed source Mathcad clone:

SMath Studio: SMath Studio Desktop 0.97.5346.24640, x64
OS: Microsoft Windows NT 6.1.7601 Service Pack 1 (Microsoft Windows 7 Professional , x64)
Screen: 1920x1080 px, 96x96 dpi
Localization: separator=<semicolon>; decimal symbol=<comma>; system decimal symbol=<comma>; language=GER
Frameworks: CLR 2.0.50727.5485

	installed versions:
	v2.0.50727	2.0.50727.5420 SP2
	v3.0	3.0.30729.5420 SP2
	v3.5	3.5.30729.5420 SP1
	v4	
		Client	4.0.30319
		Full	4.0.30319
	v4.0

**Comment by otfried** [comment]
Maybe that's the problem.  I'll try to get my hands on 64-bits Windows 7.

**Comment by otfried** [comment]
If you are not tired of trying out things:  You could run http://www.dependencywalker.com/ on qvoronoi.dll and see whether it reports a missing dependency or a CPU mismatch.

**Comment by otfried** [comment]
One more simple test:  If you have Ipe running and open the Task Manager, does it show Ipe as a 32-bit process?  (32 bit processes have *32 appended to the process name).

**Comment by mkraska** [comment]
Ipe is a 32-bit process. 

----- Am 12. Jul 2015 um 12:56 schrieb otfried <notifications@github.com>:

**Comment by otfried** [comment]
One more attempt (same link as before).

This time there should be a new Ipelet in the Ipelets list, called "Regular k-gon".  Please check if you can call this or if you get the same error.  (This one is also implemented as a DLL in C++.)   To fully use it, select a circle before calling it.

Then try the Voronoi ipelet again.  There should now be a message box saying "QVoronoi DLL is loaded" popping up when the DLL is being loaded.  I want to see if we get this far.

**Comment by mkraska** [comment]
I ran the dependency walker. I am not sure how to read the output. How to attach non-image files to this discussion?
The Regular k-gon Ipelet works. The voronoi-problem remains,
![voronoi718p3](https://cloud.githubusercontent.com/assets/12987918/8637826/4ef54ba2-28a5-11e5-8849-04da866cebf5.PNG)

**Comment by otfried** [comment]
So you didn't see the little MessageBox saying "QVoronoi DLL is loaded".

So the DLL entry point is not even called.  Since kgon works and qvoronoi doesn't, the problem must be with qhull.dll.   Apparently Windows fails to load the dependency for qvoronoi.dll, and therefore reports that loading the DLL fails.    

You cannot attach non-image attachments here.  Can you just email it to me?   My first name at ipe.airpost.net.

**Comment by otfried** [comment]
Last attempt for today.  I've succeeded to recompile qhull myself and make a static library, so we don't need qhull.dll anymore.  Maybe this will work.

Same link as before.

**Comment by mkraska** [comment]
Finally it works! Great, thank you!
![voronoi718p4](https://cloud.githubusercontent.com/assets/12987918/8638079/cf63924a-28ae-11e5-9ca2-b53ddaaf2303.PNG)

**Comment by otfried** [comment]
Excellent!

**Comment by mkraska** [comment]
Now I confused with the result of Delaunay - I expected all triangles. But that is already a different piece of cake. The triangulation is not unique here, because all four points in the quadrangle are on a circle. But I am not an expert in this.
![delauny](https://cloud.githubusercontent.com/assets/12987918/8638142/12ddc53e-28b1-11e5-90f0-f1df8a52f8b5.PNG)

**Comment by otfried** [comment]
Yes, this is the intended behaviour.  Strictly speaking, the ipelet computes the Delaunay graph, the dual of the Voronoi diagram.   When sites are co-circular, the faces may not be triangles.
