### ISSUE TITLE
Problems with eps

### ISSUE THREAD

**Issue by miccal** [otfried/ipe#5]
Hello

I use Maple (www.maplesoft.com) to create plots of mathematical functions, which I export to eps format. I then use epstopdf followed by pdftoipe so I can open the plot in Ipe to add things like Latex-style equations, arrows, etc. However, when I do this most of the options regarding line thickness, text size, etc cannot be changed. For example, when I right-click on an equation there is only one size option available, namely "normal". Or if a draw a line, the only pen width option available is "normal" and the only stroke colors available are "Black" and "White" and the only dash style available is "normal". Is there a way to allow all the options?

Any advice on this would be greatly appreciated.

Thanks!

**Comment by otfried** [comment]
Pdftoipe doesn't add a style sheet to the document, so there are no symbolic attributes.  You either need to set absolute attributes, or add a stylesheet (e.g. "basic.sty").

**Comment by miccal** [comment]
Thanks for the advice, and thanks for maintaining this great program.
