### ISSUE TITLE
Save As: redundant "overwrite" dialogs on Mac

### ISSUE THREAD

**Issue by nathaniel** [otfried/ipe#50]
Ipe 7.2.2 on Mac:
When "saving as" an existing filename, the Save As dialog pops up its own
"___ already exists.  Do you want to replace it?"
dialog.  If one selects "Replace", then Ipe launches another
"File already exists.  Do you wish to overwrite?"
dialog.

Secondary bug: this second dialog has a `<br>` tag that appears verbatim, instead of producing a line break.

**Comment by esromneb** [comment]
I do not have this issue, however the overwritten file gets  permanently deleted!!!! This should send to the trash bin!!

**Comment by otfried** [comment]
What does "I do not have this issue" mean?  You get only one confirmation dialog?  Or none?  Which version of Mac OSX are you running?

Do other apps send the old version to the trash bin when you allow to overwrite?  OSX certainly doesn't seem to make this easy (http://apple.stackexchange.com/questions/50844/how-to-move-files-to-trash-from-command-line).

**Comment by m7thon** [comment]
On Mac OSX 10.11.4, with ipe 7.2.2 **compiled with Cocoa interface**, I get 2 confirmation dialogs. The first seems to be system generated, the second seems to be ipe generated. See images:

![save1](https://cloud.githubusercontent.com/assets/5876537/15174548/721b93aa-1762-11e6-8660-cd56e0e5cf6b.png)
<img width="420" alt="save2" src="https://cloud.githubusercontent.com/assets/5876537/15174549/72480606-1762-11e6-85cd-c128dd4bb576.png">
<img width="420" alt="save3" src="https://cloud.githubusercontent.com/assets/5876537/15174550/724a295e-1762-11e6-906a-2b35397421b0.png">

Regarding trash: Preview.app ("Export...") overwrites with warning, as Ipe does, and saves a versioned file when simply saving. Photos.app ("Export...") does not overwrite, but appends " (1)" or " (2)" etc. to the file name (at least with default file naming). Safari.app overwrites with warning when saving a page ("Save as...") or exporting ("Export as PDF..."). When downloading, numbers get appended to the file name. I don't think any OSX app moves older file versions to the trash.

EDIT:
With ipe 7.2.2 compiled **with Qt4 interface**, I do not get an extra confirmation dialog:
![save4](https://cloud.githubusercontent.com/assets/5876537/15175176/767c9838-1765-11e6-9ab6-c66eef1a5741.png)
<img width="282" alt="save5" src="https://cloud.githubusercontent.com/assets/5876537/15175177/76a4b8fe-1765-11e6-9380-4ff0794f60cf.png">

So the extra system generated confirmation dialog seems to be a Cocoa feature.

**Comment by otfried** [comment]
Extra dialog removed in 7.2.3.
