### ISSUE TITLE
Feature request: command line file creation

### ISSUE THREAD

**Issue by dereckpiche** [otfried/ipe#500]
I can open files with 
`ipe file.pdf'
I would really appreciate it if it created a blank canvas `file.pdf` if it does not exist (preferably in the folder from which ipe is called from). This is for a https://castel.dev/post/lecture-notes-2/ inspired set up.

**Comment by otfried** [comment]
I'm confused.  Isn't this exactly how Ipe already works?

If I start Ipe with `ipe file.pdf`, it opens an empty document, but in the title line it already displays the filename.  As soon as I save, the file is created.
