### ISSUE TITLE
Mouse click release does not work properly on drop-down menu

### ISSUE THREAD

**Issue by mdelia17** [otfried/ipe#502]
Hello,

I'm encountering issues with the stroke and fill color drop-down menu. When the menu becomes scrollable due to a sufficient number of colors (I am using these colors [KITcolor.zip](https://github.com/otfried/ipe/files/15274557/KITcolor.zip)), it unexpectedly closes as soon as I release the click. This forces me to select a color randomly based on the mouse's position.

While it's possible to use a workaround with the mouse wheel without releasing the click, it's not as straightforward when using a touchpad.

I'm currently using Ubuntu 23.10 (Wayland), and this problem persists across previous releases. Interestingly, switching to XOrg instead of Wayland seems to resolve the issue.

**Comment by otfried** [comment]
This sounds very much like a Qt bug.   Which version of Qt are you using?

**Comment by mdelia17** [comment]
qmake --version returns "Using Qt version 5.15.2"

**Comment by otfried** [comment]
Please open Ipe, go to the Help menu und select "Show libraries".   Ipe has not been using Qt 5 for a long time...

**Comment by mdelia17** [comment]
I removed all the old Qt releases, reinstalled Ipe, and checked its dependencies. It now appears to use Qt 6. However, the problem persists on Wayland.

**Comment by otfried** [comment]
So which Qt version exactly is it using?

**Comment by mdelia17** [comment]
6.4.2

**Comment by otfried** [comment]
There is really nothing I can do for you - the problem is in Qt, and it's quite likely it's already been fixed in a newer Qt version (the current one is 6.7).     You could double check that by running Ipe on a Manjaro Linux live image.  Even if it's not fixed in 6.7, you would have to report the problem to the Qt maintainers.

**Comment by mdelia17** [comment]
Thank you very much anyway!
