### ISSUE TITLE
Change of symbolic value inside a view ignored in the PDF version

### ISSUE THREAD

**Issue by pierreganty** [otfried/ipe#503]
Hi there,

I am preparing a presentation, and I am using the feature documented here:

https://otfried.github.io/ipe/70_presentations.html#changing-symbolic-values-inside-a-view

However, the change of mark shape is not reflected into the PDF, as the enclosed screenshot shows:
![Screenshot 2024-05-13 at 11 30 15](https://github.com/otfried/ipe/assets/2111160/24f1c233-00ff-4f14-b551-57dfa486ce26)

Indeed, the mark pointed by the "yellow box" is a disk in the `ipe` interface, but at the corresponding place in the PDF it has remained a square.

**Comment by pierreganty** [comment]
Hi @otfried, do you need more info like a MWE?

**Comment by otfried** [comment]
An example exhibiting the problem would be great.

**Comment by pierreganty** [comment]
If you open the PDF file in `ipe` its two views display different marks while any PDF viewer you get twice the same page
[mwe-values.pdf](https://github.com/otfried/ipe/files/15374795/mwe-values.pdf)

**Comment by otfried** [comment]
Fixed in 7.2.29.
