### ISSUE TITLE
Ipe 7.2.29 fails to start on Windows

### ISSUE THREAD

**Issue by ThexXTURBOXx** [otfried/ipe#505]
Today I updated my ipe installation to 7.2.29 on Windows 11, but directly upon start the following error is shown:

![grafik](https://github.com/otfried/ipe/assets/12763829/df127cb7-221b-497a-b43b-4c2134b6814b)

Translated from German: `libssp-0.dll` cannot be found

Is it needed for the new version? If yes, it is indeed missing in the distribution zip for Windows.

**Comment by otfried** [comment]
My apologies.  It seems the compiler upgraded itself since last year and now we need this additional file as part of the package.

I've simply replaced the Windows packages by new ones that contain the file, so please just download it again.

**Comment by ThexXTURBOXx** [comment]
It's no problem, really! Thank you very much for your quick fix!
ipe 7.2.29 works perfectly fine now! :)
