### ISSUE TITLE
View sorter wipes out changes of symbolic values

### ISSUE THREAD

**Issue by pierreganty** [otfried/ipe#507]
The changes of symbolic values as described [here](https://otfried.github.io/ipe/70_presentations.html?highlight=symbolic#changing-symbolic-values-inside-a-view) are wiped out when moving views with the view sorter.

To reproduce, open [mwe-values.pdf](https://github.com/otfried/ipe/files/15464930/mwe-values.pdf), go to `Views` → `View Sorter` and swap the 2 views of the document. 
Then you can check with `Edit View` that all the info has been removed.

**Comment by otfried** [comment]
Fixed in 7.2.30.
