### ISSUE TITLE
Undo runs LaTeX compilation unconditionally

### ISSUE THREAD

**Issue by pierreganty** [otfried/ipe#508]
When undoing actions like moving objects around, LaTeX recompilation is launched after every undo actions.
This becomes sluggish in large documents, for which LaTeX compilation can take several seconds.

I am aware a workaround is to disable `Automatically run LaTeX` when undoing a long series of actions but it quickly becomes inconvenient.
Perhaps there is an "easy" fix to this that would skip LaTeX recompilation if the action to undo has no LaTeX editing involved (e.g. moving an object).

**Comment by otfried** [comment]
I fully agree, I think we went overboard accommodating complaints that Ipe did not always update the text representation.  Even if the undo contains text, sometimes you quickly want to go back and forward in the undo history to find the right spot, and then it's much better not to have to run Latex for each small step.

I'll change it in 7.2.30.
