### ISSUE TITLE
Mark shapes not treated like other properties

### ISSUE THREAD

**Issue by pierreganty** [otfried/ipe#509]
This one is not completely clear to me.
I am not sure why mark shapes (cross, disk, …) are not treated similarly to other properties like color or size.
In particular, when picking and applying properties to marks I'd expect that picking the property of a mark that is a cross would 
then turn other marks to cross when using applying properties.

**Comment by otfried** [comment]
It's not quite that simple.

Marks are just a special case of references, which is an object that makes use of a predefined symbol from the style sheet.
For users who use other types of symbols (not marks, but e.g. circuit symbols), your proposed semantic could have very undesirable  consequences - turning resistors into capacitors, for instance.

I also know that many users consider crosses, disks, and squares as different kinds of objects.  While they are fine with applying colors, they would be wary of objects changing type.

So it seems to me that what you suggest would create more problems than it would solve.  After all, it's very easy to apply a mark shape to a group of selected objects.

**Comment by pierreganty** [comment]
Fair enough. Thank you.
