### ISSUE TITLE
"Close" and "Quit" behavior (Mac)

### ISSUE THREAD

**Issue by nathaniel** [otfried/ipe#51]
Typical behavior for Mac programs (though not quite universal):
Close (Cmd-W) closes the current document, but leaves the application running, regardless of whether any open documents remain open.
Quit (Cmd-Q) closes all documents and quits the program.

Current behavior in Ipe 7.2.2 (Cocoa) does not match this Mac paradigm.  Currently, "Close" closes the current document, **and** quits the program if no documents remain open after closing the current one.  There is no "Quit" option in the Cocoa implementation of Ipe 7.2.2, which is a change from the Qt implementation ("Quit Ipe" was provided in the Ipe menu, as usual for Mac programs).

Request: add a Quit Ipe command (shortcut Cmd-Q), and prevent the Close command from quitting Ipe, in the Mac build.

**Comment by otfried** [comment]
Why would it ever be advantageous to keep Ipe running after the last window was closed?   I noticed that many OSX apps have this behaviour, I personally find it just annoying.

Cocoa actually has a flag that determines this, so apps can opt in or out of this behaviour.

**Comment by otfried** [comment]
I removed the Quit-Ipe action because it unconditionally closed all windows - even if there were unsaved changes.  How do OSX programs implement that if they rely on explicit saving?
(I know that Cocoa is now encouraging a smartphone style of apps where any change is immediately saved, and no more explicit saves are used - in that case the problem does not arise.)

**Comment by nathaniel** [comment]
On Tue, Mar 8, 2016 at 1:12 PM, Otfried Cheong notifications@github.com
wrote:

> Why would it ever be advantageous to keep Ipe running after the last
> window was closed?
> 
> It took me a while to adapt to this behavior when I was new to Macs.  But
> it actually makes good sense: _because being done with the currently-open
> Ipe documents doesn't mean I'm done with Ipe_.  What if I finish and save
> (or discard) Diagram 1, and want to start new Diagram 2?  There is no
> logical reason that I should be forced to create a the new document _first_,
> _before_ closing the old.  Besides, this way I don't have to count my open
> documents in order to know what the outcome of "Close" will be -- will Ipe
> be left running after the Close, or not?

The strongest reason to implement this in Ipe for Mac is simply that it's
the Mac way; Ipe playing along makes it a good Mac OS X citizen.  It
doesn't have to feel natural to a Windows or Linux user, it's just for
consistency for the Mac user.  It will seem normal for Mac users, since
almost all apps act this way.

**Comment by nathaniel** [comment]
> I removed the Quit-Ipe action because it unconditionally closed all
> windows - even if there were unsaved changes. How do OSX programs implement
> that if they rely on explicit saving?
> 
> I can tell you about the behavior, but not how to implement it. :)

Many non-Apple programs just treat "Quitting," when there are open
documents with unsaved changes, as "closing all documents then quitting" --
with each document with unsaved changes launching its own, ordinary "do you
want to save?" dialog in turn.

Apple programs (I just tested TextEdit, Pages, and Preview) launch a single
"You have XX Pages documents with unconfirmed changes.  Do you want to
review these documents before quitting?" (or "You have XX untitled Pages
documents.  Do you want...").  Choices are "Delete and Quit", "Cancel",
"Review Changes..."  If one selects "Review Changes...", then each of the
documents in question launches its own Save/Don't Save/Cancel dialog, and
ultimately (unless Cancel is clicked along the way) the program quits.

**Comment by otfried** [comment]
> Besides, this way I don't have to count my open
> documents in order to know what the outcome of "Close" will be -- will Ipe
> be left running after the Close, or not?

But what's the point?  I mean, what's the difference between the window closing and Ipe terminating, and Ipe remaining in memory, sleeping?  Isn't the only user-observable effect that there is a dot displayed underneath the Ipe icon in the launch bar?  To create a new document or to edit another document, you would have to open a new Ipe window in either case.  Why is it relevant that this window is created by a new instance of Ipe rather than an existing instance?

**Comment by nathaniel** [comment]
> Isn't the only user-observable effect that there is a dot displayed underneath the Ipe icon in the launch bar? To create a new document or to edit another document, you would have to open a new Ipe window in either case. Why is it relevant that this window is created by a new instance of Ipe rather than an existing instance?

In my case, very few applications live in my Dock, so the difference between Ipe running and Ipe _not_ running is the Ipe icon present there at all--not just the dot.

With Ipe running, all that's needed to create a new document is Cmd-N (or for the mouse inclined, File --> New).  It is impossible to create a new Ipe document in this fashion if Ipe is not running.  (And re-launching Ipe [or any other program] takes longer than simply opening a new document in an already-running instance.)

This is how I operate, in TextEdit, Word, Aquamacs Emacs, and other programs from Apple and 3rd parties alike.  Even if you don't like this Mac OS X design choice, isn't it preferable to make Ipe behave consistently in the OS?

**Comment by otfried** [comment]
Certainly, I have no problem providing this behaviour - I just wanted to understand why it's done this way.  I guess I haven't gotten used to the fact yet that apps can have menus and shortcuts even when no window is open at all.

**Comment by m7thon** [comment]
For some applications, it makes a lot of sense to have them remain running without open windows. I currently use in this state: Mail, Calendar, iTunes, Skype. Messages, too, but this actually does seem to quit. For browsers it makes a real difference if the program quits or not, something about sessions / cookies or whatever.

For other applications, including Ipe, I don't really see the point for this behavior. However, there is nothing wrong with it either, especially if one is used to it on a Mac.

Concerning what "quit" should do, I vote for "closing all documents then quitting".

**Comment by otfried** [comment]
I've changed the flag in 7.2.3 so that Ipe keeps running after the last Window has been closed.

Adding a Quit action will have to wait until I have time to figure out how to reliably make sure no unsaved changes are lost.

**Comment by m7thon** [comment]
Hang on, does this mean one can no longer quit ipe 7.2.3 at all (except for actually killing it)? That would be considerably worse than quitting when the last windows is closed, as is currently the case.

**Comment by otfried** [comment]
You can still close it by right-clicking on Ipe in the docker and selecting quit.

But there is a second, very annoying consequence of this change: I **always** start Ipe from the command line. When closing Ipe, i expect the command line to return to the prompt - but now it doesn't!

**Comment by otfried** [comment]
I find this "do not terminate" behavior so annoying, I made it a preference (terminate_on_close).

**Comment by otfried** [comment]
Implemented in 7.2.3

**Comment by nathaniel** [comment]
Thanks for implementing this in 7.2.3.  I set
prefs.terminate_on_close = false
and gave it a try in OS 10.10.5
- Launched Ipe
- Closed the only Ipe window, leave Ipe running.
  There are some problems when all Ipe windows are closed:
  1) No menu items are available, except Quit.  The following items should be available:
  About Ipe; File --> New Window; File --> Open; the entire Help menu.
  2) Opening a file in Ipe, by double clicking a .ipe file, or by drag-and-drop onto Ipe dock icon, fails (sometimes does nothing, sometimes crashes Ipe)

**Comment by otfried** [comment]
Fixed in 7.2.4.

A snapshot with todays fixes is here:

https://dl.dropboxusercontent.com/u/1840678/ipe-snapshot-0615.dmg
