### ISSUE TITLE
[7.2.29] Ipe keeps "Waiting for external editor" after it closed

### ISSUE THREAD

**Issue by thobl** [otfried/ipe#510]
After finishing editing with an external editor (`prefs.external_editor = "emacsclient -a emacs %s -c"`), the window showing "Waiting for external editor" does not close and Ipe does no longer respond to input.

In the terminal, I get the following error message, when closing my external editor after finishing editing:
`QObject::installEventFilter(): Cannot filter events for objects in a different thread.`

I am pretty sure that this worked in 7.2.28.

**Comment by otfried** [comment]
Let me guess: you run a very new Qt version like 6.6 or 6.7, most likely on Arch Linux?   Then the solution is in #506

**Comment by thobl** [comment]
Yes, tank you!
