### ISSUE TITLE
Ipe 7.2.30 fails to run on Ubuntu 24.04 LTS

### ISSUE THREAD

**Issue by rezaAdinepour** [otfried/ipe#511]

**Comment by hildogjr** [comment]
How did you install it?  Did you compile from source? (Could you indicate the procedure to follow?)

By `sudo snap install ipe --edge` I got version 7.2.6 and the `Segmentation fault (core dumped)` error on start.

**Comment by rezaAdinepour** [comment]
I install directly as bellow:

`sudo apt install ipe`

I have an error same as you. I solve this error with with run `sudo apt update` and `sudo apt upgrade` and then restart my PC :))
I hope you can fix this issue as my way.

**Comment by hildogjr** [comment]
The PPA Ubuntu repository have just old Ipe version, probably not compatible with last Ubuntu and Wayland display controls.

To get the most recent compiled version:
- Download the last compiled version from https://ipe.otfried.org/ (actual 7.2.29);
- Install it by `dpkg -i file.deb`;
- Some problem may occur due missing libraries;
- Run `apt install --fix-missing` or `apt install EACH_MISSING_LIBRARY_LISTED`;
- Redo `dpkg -i file.deb`;
- If you want, do https://github.com/otfried/ipe/issues/527.

**Comment by otfried** [comment]
If you use `gdebi` instead of `dpkg -i`, it will install all the libraries needed by the package, you don't have to do it manually.
