### ISSUE TITLE
UI errors from moving graph nodes, sometimes seems to lead to crashes

### ISSUE THREAD

**Issue by DaGeggo** [otfried/ipe#512]
I typically draw and use graphs in ipe, for which there is this useful tool called "move graph nodes". But it breaks the UI consistently. When i move the nodes a few times, i cannot click on the edges as i would expect. 

![image](https://github.com/otfried/ipe/assets/79143476/57c65451-47b3-4ea0-866e-e6b052e5a9aa)
![image](https://github.com/otfried/ipe/assets/79143476/d7461382-bd07-4702-96a2-4725fd0f0fd6)

Reproduction steps: 
Open a new document, add a few vertices (does not matter if i use labels, marks or circles), and a few edges (simple lines, no polylines). Then i move the vertices using "move graph nodes" and some of the edges become unclickable (or hard to click). Sometimes i can click on them on specific regions, or using the rectangle selection in both include or cut mode (left or right drag). Here is a recording starting from a new document. After the first moves it still works, but after doing some more, some edges cannot be clicked:

https://github.com/otfried/ipe/assets/79143476/d6d945d6-0b46-4b1e-b425-1e9f75975bfa

Furthermore, i sometimes end up with documents crashing (mostly when saving) when using "move graph nodes", especially when i additionally group vertices to their labels (e.g. a circle with small radius with a label inside). I suspect that these bugs are related, and i might test it again when this first issue is resolved.

**Comment by otfried** [comment]
Which version of Ipe and which operating system are you using?

**Comment by DaGeggo** [comment]
Fedora 38 and Ipe 7.2.26. I remember having this issue in older versions and other operating systems, too.

**Comment by otfried** [comment]
Fixed in 7.2.31.

You can fix it for yourself by replacing your copy of `tools.lua` with the newest one: https://raw.githubusercontent.com/otfried/ipe/master/src/ipe/lua/tools.lua
