### ISSUE TITLE
Crashing during compile

### ISSUE THREAD

**Issue by maowa-uleth** [otfried/ipe#515]
entering extended mode: using latexonline at 'https://latexonline.cc/data?target=ipetemp.tex&command=pdflatex'
! A network error occurred using the Latex cloud service
Code:   -1001
Domain: NSURLErrorDomain
Error:  The request timed out.

**Comment by otfried** [comment]
` A network error occurred` means that had difficulty accessing the Latex compilation service at https://latexonline.cc.

Either your network connection did not work, or that service had downtime.

This is not an Ipe problem.
