### ISSUE TITLE
Shift + scroll: opposite direction than other applications

### ISSUE THREAD

**Issue by fakub** [otfried/ipe#516]
The usual direction of horizontal scrolling towards the right is with Shift + scroll down (and vice versa; tested with Gimp, Firefox, ...), however, in IPE 7.2.27, it's the opposite.

**Comment by hildogjr** [comment]
I think it was been opposite always or at least several releases a go.

To "fix" search your `/usr/local/share/ipe/$last_version/lua/prefs.lua` file and add the line `prefs.scroll.direction.x = -1`.

**Comment by otfried** [comment]
Fixed in 7.3.1.
