### ISSUE TITLE
Bad equation cutting when using Steinmetz package

### ISSUE THREAD

**Issue by gabriel-torreao** [otfried/ipe#519]
When using the steinmetz inside a "Mathematical Symbol" box, IPE cuts off the bottom of the wedge reserved for stating the phase in this convention, typical in electrical circuits. This issue is illustrated in the figure attached.

The left hand side of the figure was obtained with
`127\phase{60^{\circ}}`
and the right hand side with
```
\begin{array}{c}127\phase{60^{\circ}}\\
\phantom{x}\end{array}
```
so that I could forcibly create space bellow the desired expression and be able to see the full wedge.

![steinmetzInIPE](https://github.com/user-attachments/assets/cf4877e0-0817-41b2-9c36-3c757878ea46)

**Comment by otfried** [comment]
Unfortunately when constructing a PDF XForm, pdflatex uses the "TeX box dimensions" for the XForm bounding box, and ignores parts that are outside the TeX hbox.  You can see this by running this test file in pdflatex:
```
\documentclass{article}
\usepackage{steinmetz}
\begin{document}
\setbox0=\hbox{$127\phase{60^{\circ}}$}
\pdfxform0

Here we use the box: {\pdfrefxform\pdflastxform}

And now with a frame: \fbox{\pdfrefxform\pdflastxform}
\end{document}
```

Ipe therefore offers the `<textpad>` element in its style sheet, which adds some safety buffer around the boxes.   The default setting is
```
<textpad left="1" right="1" top="1" bottom="1"/>
```
but this is not big enough for the Steinmetz package - you'll have to increase at least the bottom.

In 7.3.1 you will be able to see the effect also on the screen (until then only in the produced PDF file).
