### ISSUE TITLE
gtk backend: no image display, some menus do not work

### ISSUE THREAD

**Issue by barracuda156** [otfried/ipe#523]
I have finally got this building with GTK, but when I launch the binary, there is no image displayed (I can see cursor moving, and it changes depending on the mode, but nothing gets reflected on canvas). Importing an image places it on canvas, but it remains invisible. Many menus say that it is unimplemented, some just crash the program.

Has this been tested? How to get it working?

![ipe](https://github.com/user-attachments/assets/0548479b-024a-4290-a281-a3bdc0bd03c8)

**Comment by otfried** [comment]
Have you looked at `install.txt`?   It lists all the supported modes of compiling Ipe.

The GTK port is incomplete, and since the existing code was made for GTK 2, it's stale.

**Comment by barracuda156** [comment]
> Have you looked at `install.txt`?   It lists all the supported modes of compiling Ipe.
> 
> The GTK port is incomplete, and since the existing code was made for GTK 2, it's stale.

This is sad. Is GTK3 or GTK4 support planned?

**Comment by otfried** [comment]
I'd like to add GTK4 at some point - but I cannot give you any estimate when this will happen.
