### ISSUE TITLE
Update the snap version

### ISSUE THREAD

**Issue by hildogjr** [otfried/ipe#525]
The Linux distro repository doesn't have the most recent Ipe version, although create a repository for Linux Ipe (PPA) fix this, it will able to new platform issues.

A workaround is to release Ipe as Snap/flatplack, which is already done (https://snapcraft.io/ipe by `snap install ipe`) but the package is dated from 2017.

I propose to we include the Snap release as "Github Action".

**Comment by otfried** [comment]
You can find an up-to-date flatpak for Ipe at https://flathub.org/apps/org.otfried.Ipe (this link is on the website).

The snap is outdated and unmaintained.  I'll have a look if I can remove it from snapcraft.io.

**Comment by hildogjr** [comment]
Could we add the Snap release procedure to `/.github/workflows/compile.yml` or will this create more work than benefits?

IMHO, Snap could track user to Ipe.

**Comment by otfried** [comment]
Since snap is Ubuntu-specific, I think we should stick with flatpak, which is maintained.

But both flatpak and snap are not really attractive for Ipe users, since Ipe packaged this way cannot use the latex installed on your system.   You would either have to install latex as a flatpak as well, or rely solely on online latex compilation.

**Comment by hildogjr** [comment]
This last fact (not recognize local Latex) is a strong point! I just recent migrated my Ubuntu but I was familiar to Ipe complication for some time.

About the .DEB version available at https://ipe.otfried.org/, it still on 7.2.29. Will the pre-compiled release package be updated to 7.2.30 at the website?

**Comment by otfried** [comment]
Ipe 7.2.30 was a very small release, only really important for ArchLinux users.   There will be binaries again for the next version, 7.2.31.
