### ISSUE TITLE
Add Ipe launch shortcut

### ISSUE THREAD

**Issue by hildogjr** [otfried/ipe#527]
For sack of user experience I usually add a shortcut to Ipe in Ubuntu/Debian. I think it could be added to the DEB package on compilation. I just do:

```bash

last_version=VERSION_HERE

APPLICATIONS='/usr/share/applications'
IPE_DIR_INSTALL=/usr/local
IPE_LIB_FOLDER=/usr/share/ipe/$last_version
shortcutIcon=`find $IPE_LIB_FOLDER/icons/*.png`

sudo bash -c "cat >$APPLICATIONS/ipe.desktop <<EOF
[Desktop Entry]
Type=Application
Name=Ipe
Comment=Ipe extensible drawing editor
Categories=Graphics;2DGraphics;
Keywords=latex;tex;pdf;
Exec=ipe %F
Path=$IPE_DIR_INSTALL/bin/
Icon=$shortcutIcon
EOF"
```

This configuration also allow to open a PDF on Ipe by mouse right-click. Could we add this `ipe.desktop` to the DEB package?

![image](https://github.com/user-attachments/assets/f817b3f0-f1d9-4c71-b021-884898c0a027)

**Comment by otfried** [comment]
This is not really possible for the prebuilt packages because each desktop environment uses slightly different conventions for the contents and location of the `ipe.desktop` file.  And it's *very* easy for users to do this themselves.
