### ISSUE TITLE
Rendering performance with Cairo > 1.12

### ISSUE THREAD

**Issue by nzeh** [otfried/ipe#53]
Finally upgraded from Debian Wheezy (cairo 1.12) to Jessie (cairo 1.14).  Some of my ipe slides have a pretty massive jpg as background image.  They nevertheless rendered unbelievably fast with cairo 1.12 but render really slow with cairo 1.14.  A quick Google search led me to the following explanation and fix:

Up to cairo 1.12, there was no real difference between the BEST and FAST filters.  Both were fast and yielded reasonable results.  Starting with cairo 1.13, the BEST filter really tries to do a better job in terms of quality but is slow enough that the official cairo documentation says "may not be suitable for interactive use".  So I patched the ipe source code on my machine replacing BEST with FAST and I now have my fast rendering back.  I think in Ipe, rendering performance trumps ultimate quality (if the latter comes at a lag of 1s+ when flipping through pages or views).  Thus, I suggest switching to the FAST cairo filter or maybe one of the trade-offs between speed and quality in between.

**Comment by otfried** [comment]
Thanks for the tip, I will change it in the next version.

**Comment by nzeh** [comment]
Excellent!

**Comment by gasagna** [comment]
Has this been fixed? I am on a mac os and rendering seems pretty slow when I insert png images.

These are my details:

<img width="495" alt="screen shot 2017-01-05 at 17 13 23" src="https://cloud.githubusercontent.com/assets/744738/21690003/627fd676-d36a-11e6-8d75-549424b07d9b.png">

**Comment by otfried** [comment]
Yes, this has been fixed. Please upgrade to a recent version of Ipe.

**Comment by otfried** [comment]
For the record: the change was implemented in 7.2.3.

**Comment by gasagna** [comment]
Thanks! I can confirm this now works on mac os as well
