### ISSUE TITLE
[Bug] Text is clipped by its bounding box

### ISSUE THREAD

**Issue by LRBaalmann** [otfried/ipe#531]
It appears that all text is currently clipped by its bounding box. In previous versions text also often exceeded its bounding box but was not clipped. Now it is clipped; especially for numbers quite a bit is cut off. I have not managed to draw non-clipped numbers in my figures, which is rather annoying. 

The below image has been generated with 7.2.24 (left) and 7.2.29 (right) with a fresh download of IPE, no ipelets, no stylesheets except the default, tested on both Windows 10 and Windows 11. I have not used the versions in-between, so I can't say for sure when the bug appeared, but from the changelog I'd think that 7.2.29 is the likely culprit. 
![ipe-clip-bug](https://github.com/user-attachments/assets/eb458799-6955-4c34-a3c1-9695ad531b1e)

Thanks! :)

**Comment by otfried** [comment]
Does the problem also appear on the generated PDF output?

**Comment by LRBaalmann** [comment]
No, but it appears in the svg/png/eps export.

**Comment by makamto** [comment]
I can confirmed that, and tried to use `pad.isy` to fix. However, unsuccessful.

**Comment by otfried** [comment]
Fixed in 7.3.1.

**Comment by ahttraga** [comment]
Perhaps useful to others: using [pdf2svg](https://cityinthesky.co.uk/opensource/pdf2svg/) to convert the ipe pdf to svg, instead of the native SVG export in 7.2.29, preserves the text.
