### ISSUE TITLE
Ipe 7.2.29 keep compiling....

### ISSUE THREAD

**Issue by hildogjr** [otfried/ipe#534]
Ipe v7.2.29 on Ubuntu 24.04 keep compiling file forever, the error appear intermittent: happens most of time and freeze all Ipe instances but, sometimes I can make the file to compile. I am using local Latex installation.

```bash
ipe

# Open and edit some file here. Try to save it and the follow error message came up.

QObject::installEventFilter(): Cannot filter events for objects in a different thread.
```

Should this possible related with https://github.com/otfried/ipe/issues/508? I didn't test 7.2.30 yet.

**Comment by otfried** [comment]
Which version of Qt are you using? (Check under Ipe ➤ Help ➤ Show libraries)

This looks more related to #495.  

Can you try adding `prefs.freeze_in_latex = true` to your preferences and see if this removes the problem?

**Comment by hildogjr** [comment]
Check under Ipe ➤ Help ➤ Show libraries:

```
Ipe relies on the following fine pieces of software:

 * Pdftex, Xetex, or Luatex
 * Lua 5.4 (1811 kB used)
 * The font rendering library Freetype 2.13.2 / 2.13.2
 * The rendering library Cairo 1.18.0 / 1.18.0
 * The clothoid spline library libspiro 1.3
 * The GNU scientific library gsl 2.7.1 / 2.7.1
 * The GUI toolkit Qt 6.4.2 / 6.4.2
 * The compression library zlib 1.3
```

Apparently `prefs.freeze_in_latex = true`  got a better behavior until now.

**Comment by hildogjr** [comment]
Yes, `prefs.freeze_in_latex = true` have better behavior local or online LaTEX compiler.

What does this option do?

**Comment by otfried** [comment]
Let's treat this together with #495. 
The code in question has been completely rewritten for 7.3.1, I hope that will fix this problem.
