### ISSUE TITLE
Can Pretty Display be customized as default?

### ISSUE THREAD

**Issue by makamto** [otfried/ipe#538]
<img width="520" alt="image" src="https://github.com/user-attachments/assets/7b42819b-51d6-4c15-8527-9eec839acb12">

I tried to find any variable related to "Pretty Display" in `prefs.lua`, however I cannot find. Is it possible to customize it in my `personal.lua`?

**Comment by makamto** [comment]
Moreover, I created a shortcuts in `personal.lua` that conflicts with `shortcuts.lua`, and I supposed that my shortcut configuration will overwrite the default one. However, when I tried to "Ctrl+P", it starts `edit_title`.

<img width="327" alt="image" src="https://github.com/user-attachments/assets/1b18a122-8630-4963-aeb1-8d39861a8e04">

**Comment by otfried** [comment]
I'll add it to the next version that you can customize the initial setting of `pretty_display`.  Currently it's not possible.

Ipe does not like it when the same shortcut is assigned to more than one action, so the right way to do it is to remove the other shortcut:
```
shortcuts.edit_title = nil
shortcuts.export_svg = "Ctrl+P"
```
