### ISSUE TITLE
Math text gets top and bottom trimmed

### ISSUE THREAD

**Issue by Marshhall** [otfried/ipe#539]
Hello! I am having a very simple yet annoying problem. When I add a math text, the text gets trimmed slightly on top and bottom. I have attached a screenshot of the issue. Does anyone know how to solve this?

Thank you very much in advance!
<img width="974" alt="Trouble with math text" src="https://github.com/user-attachments/assets/00dd5037-7584-4ba4-b7eb-2a16f8cb8460">

**Comment by otfried** [comment]
#531
