### ISSUE TITLE
Move to layer throws a Lua error

### ISSUE THREAD

**Issue by Willem3141** [otfried/ipe#54]
I get a Lua error when trying to move objects to another layer.

To reproduce:
- Make a new file
- Add a second layer _beta_
- Add an arbitrary object (polyline, text, ...) on the layer _alpha_
- With the object selected, click _Layers > Move to layer > beta_

This throws the following error:

```
/usr/local/share/ipe/7.2.2/lua/actions.lua:1002: bad argument #2 to 'setLayerOf' (layer does not exist)
stack traceback:
    [C]: in function 'setLayerOf'
    /usr/local/share/ipe/7.2.2/lua/actions.lua:1002: in function 'redo'
    /usr/local/share/ipe/7.2.2/lua/model.lua:668: in function 'register'
    /usr/local/share/ipe/7.2.2/lua/actions.lua:1004: in function 'action_move_to_layer'
    /usr/local/share/ipe/7.2.2/lua/actions.lua:85: in function 'paction'
    /usr/local/share/ipe/7.2.2/lua/actions.lua:37: in function </usr/local/share/ipe/7.2.2/lua/actions.lua:37>
    [C]: in function 'xpcall'
    /usr/local/share/ipe/7.2.2/lua/actions.lua:37: in function </usr/local/share/ipe/7.2.2/lua/actions.lua:36>
    [C]: in function 'mainloop'
    /usr/local/share/ipe/7.2.2/lua/main.lua:466: in main chunk
    [C]: in function 'require'
    [string "require "main""]:1: in main chunk
```

A workaround for me is to right-click on the element and to set the layer there; this works normally.

I'm using Ipe 7.2.2 on Kubuntu (Linux).

**Comment by otfried** [comment]
I cannot reproduce this.  How exactly are you adding the layer beta?

**Comment by Willem3141** [comment]
I added the layer by the _Layers > New Layer_ menu option. It does not matter how I add it though, even if I open an existing file with several layers I get this error.

If it helps, [here](http://wimiso.nl/random/ipe-move-to-layer-error-3.mp4) is a screencast demonstrating the problem.

**Comment by otfried** [comment]
Can you set the environment variable IPEDEBUG (e.g. say "export IPEDEBUG=1") and check what output you get?  I just tried it, it works and I get this output:

```
$ ipe
Debug messages enabled
size has changed to 937 x 487 (937 x 487)
action new_layer
action mode_rectangles
action movetolayer-beta
```

**Comment by Willem3141** [comment]
Thanks for the suggestion. Unfortunately, there doesn't seem to be anything related to the error:

```
wsonke@nbwin1339:~$ export IPEDEBUG=1
wsonke@nbwin1339:~$ ipe
Debug messages enabled
size has changed to 887 x 467 (887 x 467)
```

I don't get any line starting with `action`. It seems that those are not emitted in the Qt version (in the source code, I can only find the corresponding `ipeDebug` statements in `appui_cocoa.cpp` and `appui_win.cpp`).

**Edit:** I copied the debug statement from `appui_cocoa.cpp` into `appui_qt.cpp` and recompiled. Now I get the following output:

```
wsonke@nbwin1339:~/Downloads/ipe-7.2.2/src$ ipe
Debug messages enabled
size has changed to 887 x 467 (887 x 467)
action mode_lines
action new_layer
action movetolayer-&beta
```

That `&` sign seems to be the culprit... maybe it is a focus marker?

**Comment by otfried** [comment]
Ah, very good.  Which Qt version are you using?

**Comment by Willem3141** [comment]
I'm using Qt 5.5.1.

**Comment by otfried** [comment]
Does the same problem occur with the other generated menus, e.g. Properties -> Text Style or Snap -> Grid size?

**Comment by Willem3141** [comment]
You're right, indeed those menus exhibit similar symptoms, although none of them causes error messages like the layers menu:
- _Properties -> Text style_: does not influence the text style of the label, but produces `style="&itemize"` in the XML
- _Snap -> Grid size_: whatever option you click, it always sets the grid size to _8 pts (~3 mm)_
- _Snap -> Radial angle_: menu refuses to open at all:  
  ![ipe-radial-angle](https://cloud.githubusercontent.com/assets/7533280/15898916/45f4d77a-2d9a-11e6-872d-0cecdc820a43.png)

(I didn't notice this before, as I normally use the popup menus to set those, and there is no problem with those.)

**Comment by otfried** [comment]
As a temporary solution, you could edit "actions.lua", and change the beginning of `MODEL:paction` from 

```
function MODEL:paction(a)
  -- print("MODEL:paction(" .. a .. ")")
```

to

```
function MODEL:paction(a1)
  local a = a1:gsub("&", "")
  -- print("MODEL:paction(" .. a .. ")")
```

This is not a full solution, because now layer names containing an ampersand will not work anymore (not sure if that was ever supported), and similar for ampersands in property names (but there are none in the standard style sheets).

**Comment by otfried** [comment]
I hope this works as I can't check it - I'm still on Qt 5.2, where the problem doesn't occur.  Another silent Qt behaviour change that bites us :-(

**Comment by Willem3141** [comment]
This patch indeed fixes the issue with the layer menu for me. Thanks!
