### ISSUE TITLE
Feature Request: Colored text box with round corner

### ISSUE THREAD

**Issue by JunmingDuan** [otfried/ipe#547]
I want to sketch a workflow, by connecting different text boxes with lines. The text box is preferred to be a colored round-cornered rectangle with text inside. For example, the box can be obtained by using Tikz:
\tikzstyle{proc_green} = [rectangle, rounded corners, minimum width = 2cm, minimum height=0.5cm, text centered, draw = green!80!black, top color = white, bottom color = green!50!black!20]
This feature would be very nice for creating beautiful workflow figures.

**Comment by otfried** [comment]
Do you mean what Ipe calls a "decoration"?

![image](https://github.com/user-attachments/assets/2d0db461-809b-4454-a31c-e261a6649a68)

See https://otfried.github.io/ipe/60_stylesheets.html#decorations

**Comment by JunmingDuan** [comment]
Thank you for pointing to the decorations. I tried to draw a rounded box with filled color and it worked.
But how to make the filled color of the textbox gradient? Can I draw a tikzpicture with a text box and then save it as a decoration?
<img width="107" alt="image" src="https://github.com/user-attachments/assets/a5b4d73a-b403-4e17-b5f8-39f67bf7b6f6">

**Comment by otfried** [comment]
If you want to use tikz, just do it:

![image](https://github.com/user-attachments/assets/39cc4c87-9c81-4221-924f-3a9308acb093)

![image](https://github.com/user-attachments/assets/c405a3fe-682a-4c0d-a1c5-ab295ddd1b6f)

![image](https://github.com/user-attachments/assets/fcbd34fa-7304-485c-9554-8333d97daa6b)

**Comment by otfried** [comment]
Ipe also supports gradients itself, and in principle it should work to make a decoration that uses a gradient:

https://otfried.github.io/ipe/70_presentations.html#gradient-patterns

**Comment by JunmingDuan** [comment]
Thank you! I can define a decoration with a gradient, attached below.

```xml
<gradient name="linear" type="axial" extend="yes" coords="0 92 0 208">
  <stop offset="0.00" color="0.75 0.90 0.75"/>
  <stop offset="1.00" color="1.0 1.0 1.0"/>
</gradient>

<symbol name="decoration/green_gradient_rbox">
<path stroke="0 1 0" fill="1" pen="2" gradient="linear">
300 208 m
8 0 0 -8 300 200 308 200 a
308 100 l
0 -8 -8 0 300 100 300 92 a
100 92 l
0 -8 -8 0 100 100 92 100 a
92 200 l
-8 0 0 8 100 200 100 208 a
h
</path>
</symbol>
```
