### ISSUE TITLE
Latex not working in IPE with flatpak

### ISSUE THREAD

**Issue by hlucian** [otfried/ipe#562]
Hi 

I have installed IPE using flatpak on my Rocky Linux. However, I do not manage to 
make latex work. Everytime I try to add some text I get the message that "... Latex executable is not in your command path.

In the shell where flatpak is running i get the prompt
`sh: line 1: /home/hanimann/Software/Texlive/bin/x86_64-linux/pdflatex: No such file or director`

This is after I have added the following line in my .bashrc
`export IPELATEXPATH=/home/hanimann/Software/Texlive/bin/x86_64-linux`

pdflatex is surely in this path. What else do I miss in this context?

Kindly
Lucian

**Comment by otfried** [comment]
Flatpak isolates each application - so flatpak Ipe simply has no access to your Latex installation.

Apparently there is an extension that makes it possible - I have not tried this.  See

https://github.com/flathub/org.otfried.Ipe
