### ISSUE TITLE
Labels are cropped by bounding boxes

### ISSUE THREAD

**Issue by GoBigorGoHome** [otfried/ipe#565]
I have Ipe 7.2.30 and TeX Live 2024 installed on my Manjaro Linux.

I found that Labels are cropped by bounding boxes both as displayed on screen and in exported png/svg/eps.

With latex engine set to pdftex (which is also the default), following is how text label `sa`, math label `$sa$`, and "mixed" label `s$sa$a` are cropped 
on screen:
![image](https://github.com/user-attachments/assets/33924375-1fad-4636-9201-9c6cb08be18b)
exported png:
![cropped](https://github.com/user-attachments/assets/83a00858-3a38-4961-9f22-563dd5574070)

However, in saved pdf, they are NOT cropped
![image](https://github.com/user-attachments/assets/43ea9040-7145-44a4-b63b-ab4ab44ed836)

Here comes the mysterious part, with latex engine set to xetex or luatex, the text label (and also the mixed label) are NOT cropped.
on screen:
![image](https://github.com/user-attachments/assets/e08b466e-b953-487e-a869-83714dde9323)
exported png:
![cropped](https://github.com/user-attachments/assets/aa80bda7-b269-4908-a623-71622da76ccd)

**Comment by otfried** [comment]
This is already fixed for the next release, see #531
