### ISSUE TITLE
Cannot open settings

### ISSUE THREAD

**Issue by taxipomme** [otfried/ipe#566]
The Settings... in the Ipe menu is grayed and cannot be clicked.
Ipe version  7.2.29 on Macbook Pro M1 Max (ARM) running Sequoia 15.2

**Comment by otfried** [comment]
Can you include a screenshot?    Ipe does not have a "Settings..." item in the menu.

Or do you mean "Preferences" in the "Help" menu?

**Comment by taxipomme** [comment]
Here you are.

Best,

Patrice

￼

**Comment by otfried** [comment]
There is no screen shot.   You cannot attach it when you reply to the email, you have to go the issue page in the issue tracker (https://github.com/otfried/ipe/issues/566).

**Comment by taxipomme** [comment]
<img width="442" alt="Capture d’écran 2024-12-18 à 09 52 04" src="https://github.com/user-attachments/assets/380b0b39-96c5-4bbd-aecd-f3546d6e95a7" />

**Comment by otfried** [comment]
The menu you are showing here is not created by Ipe, but by MacOS.   I do not know what the "Settings" item would normally be for, and I do not know why MacOS shows you a grayed-out one here - but I do know that it's not Ipe that is doing this.   You find all Ipe functionality in the remaining menus, from `File` to `Help`.
