### ISSUE TITLE
Page numbers not working 

### ISSUE THREAD

**Issue by ko56** [otfried/ipe#57]
I have an Ipe document with just one word "stuff" in it, and a "presentation" and a "standard" stylesheet.  When I load into 7.1.10, the page number "1" shows.  When I load it into 7.2.2, it does not.  By "shows", I mean using common Linux/BSD viewers such as "atril", "epdfview", "qpdfview", or  "okular".

Further, when I run "gs" on the pdf file made by 7.2.2, see what happens in the attached file.
I don't know if this is related to the page number problem.
[bug.txt](https://github.com/otfried/ipe-issues/files/190675/bug.txt)

**Comment by pglira** [comment]
I have the same problem. Page numbers don't appear in the pdf compiled with IPE 7.2.2 (Windows). However, in IPE 7.1.10 everything works fine. Fortunately, I could open my presentation made in 7.2.2. in 7.1.10 to add the page numbers.

**Comment by otfried** [comment]
Fixed in 7.2.4.
