### ISSUE TITLE
Resize bookmark sidebar

### ISSUE THREAD

**Issue by pglira** [otfried/ipe#58]
It seems that it is not possible to resize the sidebar with the bookmarks. Of course, that's a minor problem, but it would be nice to make it a little bit wider.

![2016_04_04_21_12_06](https://cloud.githubusercontent.com/assets/14214284/14260047/e75a06f4-faa9-11e5-87cc-c155405220d8.png)

**Comment by otfried** [comment]
Implemented in 7.2.3: Use prefs.width_notes_bookmarks
