### ISSUE TITLE
Ipe crashes if clipboard too large

### ISSUE THREAD

**Issue by pglira** [otfried/ipe#59]
IPE crashes if the content of the clipboard is too large, see this video:
https://www.dropbox.com/s/qxs95fr64t7ffr6/ipe_crashes.flv?dl=0
(a single image has approx 1MB in size)

I found two workarounds:
1) copy/paste element by element (very annoying and sometimes even 1 single image is already too large for the clipboard)
2) if i want to just move a page within a presentation, I can edit the .ipe file in a text editor directly (so cut and paste `<page>` ... `</page>`)

The reason seems to be that the IPE selection doesn't fit to the windows clipboard. If I paste the selection to a text editor like notepad it begins with:
iBucHt2djbvT/IoIlGMSLQiEq2IRDEi0YpIFOPd8CjeT7j9v
instead of
`<ipeselection>`....

Thanks for your help.

**Comment by otfried** [comment]
The documentation says there is no size limit on the clipboard.   Could you send me a file that exhibits the problem so that I can debug it?

**Comment by pglira** [comment]
You can find the Ipe file (generated as in the video above) here:
https://www.dropbox.com/s/uwvwli89ab6huum/clipboard_error.pdf?dl=0

**Comment by otfried** [comment]
Fixed in 7.2.3.
