### ISSUE TITLE
Enter closes paragraph window

### ISSUE THREAD

**Issue by pglira** [otfried/ipe#6]
When editing a paragraph, pressing the enter key closes the window instead of jumping to a new line (IPE 7.1.8 / win).
![2015-09-11 14_11_33](https://cloud.githubusercontent.com/assets/14214284/9814509/093c05e6-588f-11e5-8e99-950dea07ed4a.png)

**Comment by otfried** [comment]
Fixed in 7.1.10.

**Comment by michitux** [comment]
Is the code with the fix (or even better: compiled versions of 7.1.10) available somewhere? I couldn't find any source code for anything newer than version 7.1.9.

**Comment by otfried** [comment]
I normally don't publish sources in between release, but if you need this fix, here is the current snapshot:

https://www.dropbox.com/s/upx0ooflzis51w7/ipe-7.1.10-win.zip?dl=0
