### ISSUE TITLE
Problem while using the decorator ipelet

### ISSUE THREAD

**Issue by pierreganty** [otfried/ipe#66]
Steps to reproduce:
- use the decorator ipelet `decorator.lua` (with the companion decorator ipestyle if you want).
- navigate to Help->Ipelets Information

<img width="534" alt="screen shot 2016-04-27 at 6 29 52 pm" src="https://cloud.githubusercontent.com/assets/2111160/14859834/36d5d61e-0ca6-11e6-80f6-40e9488a3fdf.png">

**Comment by otfried** [comment]
Fixed in 7.2.3.
