### ISSUE TITLE
Notes hiding even if told not to

### ISSUE THREAD

**Issue by pierreganty** [otfried/ipe#68]
On OSX 10.9.5.

Even though "notes" was removed form hidden in prefs.lua as shown below:

`/opt/homebrew-cask/Caskroom/ipe/7.2.2 $ grep -e 'hidden' ./Ipe.app/Contents/Resources/lua/prefs.lua
  hidden = { "bookmarks" }`

The notes pane keeps hiding.

**Comment by pierreganty** [comment]
confirmed on OSX 10.11.5

**Comment by otfried** [comment]
Fixed in 7.2.3.
