### ISSUE TITLE
annoying feature interfering with the XML editor

### ISSUE THREAD

**Issue by pierreganty** [otfried/ipe#69]
On OSX 10.9.5 when running "Edit XML" of an object the editor
replaces automatically quotes like this "foo" into “foo”.
With the new quotes, the XML is not valid anymore.
See the quotes for path stroke in the screenshot.
<img width="298" alt="screen shot 2016-04-29 at 11 30 37 am" src="https://cloud.githubusercontent.com/assets/2111160/14912759/92085f44-0dfe-11e6-9bcb-e32cfcfd4480.png">

**Comment by pierreganty** [comment]
This applies to the LaTeX editor as well. Because of the automatic conversion into quotes the LaTeX compiler complains when writing variables with double primes in math mode. 
Workaround: use the `\prime` command.

**Comment by pierreganty** [comment]
Confirmed on OSX 10.11.4

**Comment by otfried** [comment]
Fixed in 7.2.3.
