### ISSUE TITLE
Ipe crashes after right click on symbol

### ISSUE THREAD

**Issue by pglira** [otfried/ipe#7]
Clicking on any symbol with the right mouse button leads to a crash (IPE 7.1.8 / win).

![2015-09-11 14_13_52](https://cloud.githubusercontent.com/assets/14214284/9814576/6e09d6f6-588f-11e5-8d94-72c1aa892ffd.png)

**Comment by otfried** [comment]
I cannot reproduce this.  Did you define your own symbols?

Can you attach a link to the file that causes the problem (or just mail it to me), and tell me exactly where to right-click?

**Comment by pglira** [comment]
Sorry, maybe I should write 'icon' instead of 'symbol'. See here a short video:
https://www.dropbox.com/s/iny8xfdrt2gqfbv/ipe.mp4?dl=0

**Comment by otfried** [comment]
Got it.  Amazing that nobody reported this before.

**Comment by otfried** [comment]
Fixed in 7.1.9.
