### ISSUE TITLE
CTRL + KeyPad not working

### ISSUE THREAD

**Issue by ben-strasser** [otfried/ipe#70]
Hi,

I have ipe version 7.2.2 and am running ubuntu 14.04 with Gnome classic and compiz.

None of the movement key-binding such as ctrl + 4 or alt + 4 work if I use the 4 from the keypad. The 4 above the letters work.  This used to work.

If I run xev and press CTRL + KP_4 then I see a message. From this I conclude that it is not some ubuntu/gnome/compiz bug/misconfiguration that prevents the key message from being delivered to IPE. It might be a QT thing though.

Is it possible that in earlier versions CTRL + 4 and CTRL + KP_4 were mapped onto the same command whereas in newer versions only CTRL + 4 is mapped? 

Best Regards
Ben Strasser

**Comment by otfried** [comment]
Several people reported problems with keyboard shortcuts on ubuntu 14.04 if not running Unity, see e.g.  issue #42.
This is a bug in the Ubuntu modifications to Qt. One solution seems to be to remove the `appmenu-qt5` package, that is, do

```
sudo apt-get remove appmenu-qt5
```

Another solution is to recompile Ipe with Qt4 instead of Qt5.

**Comment by ben-strasser** [comment]
Hi,

I already uninstalled appmenu-qt5 to get the menu bar working. This does
not fix the issue for me.

From the xev experiment I am confident that the xserver events reach the
ipe binary. However, I believe that the key events do not pass through
QT to the actual program code. As the bindings work for my college with
Arch Linux and ipe 7.2.2 I do not believe that it is a breaking change
in the interface from QT4 to QT5.

The only explanation for the behavior that I have is that the QT5
package of Ubuntu is broken... Ubuntu seems to have passed the point
where it was a good distro. :/

Best Regards
Ben Strasser

**Comment by otfried** [comment]
My suspicion is rather that Qt made a subtle, probably undocumented change in some minor version - this has happened many times over the years.   Could you check the precise Qt versions that you and your colleague are using? (Ipe -> Help -> About Ipe)?

**Comment by ben-strasser** [comment]
Hi,

on my Ubuntu system with the problem I have:

Lua 5.2.3 (927 kB used)
The font rendering library Freetype 2.5.2 / 2.5.2
The rendering library Cairo 1.13.1 / 1.13.1
The GUI toolkit Qt 5.2.1 / 5.2.1
The compression library zlib 1.2.8

On my colleagues system where everything works there is

Lua 5.2.4 (...)
The font rendering library Freetype 2.6.3 / 2.6.3
The rendering library Cairo 1.14.6 / 1.14.6
The GUI toolkit Qt 5.6.0 / 5.6.0
The compression library zlib 1.2.8

Best Regards
Ben Strasser

**Comment by otfried** [comment]
I'm actually running the exact same version (ubuntu 14.04 with Qt 5.2.1), and I have the same problem.  My guess is that Qt didn't handle keypad shortcuts in this early Qt5 version, and it was fixed later - which is why it works on Qt 5.6.

There doesn't seem to be an easy way to fix it, so you'll have to upgrade to a new Qt version if it's important to you.

**Comment by ben-strasser** [comment]
Hi,

thank you for debugging the problem. Too bad that there is no easy fix. :/

Best Regards
Ben Strasser

**Comment by otfried** [comment]
Actually there is a reasonably easy fix: recompile Ipe with Qt 4...

**Comment by otfried** [comment]
Link for compiling with Qt4:

https://github.com/otfried/ipe-wiki/wiki/Downloading,%20Compiling,%20and%20Installing%20Ipe#debian-ubuntu-mint-with-qt-4
