### ISSUE TITLE
Launching apps from Ipe

### ISSUE THREAD

**Issue by pierreganty** [otfried/ipe#71]
I am running Ipe 7.2.2 on OSX 10.9.5
- Help -> Onscreen Keyboard has no effect
- the command `prefs.keyboard = "open -a KeyboardViewer -n"` extracted from `prefs.lua` works fine when run form the Terminal

The same problem occurs with if I set
`prefs.external_editor = "open -a macvim %s"`:
Clicking the Editor XML -> Editor button has no effect

**Comment by m7thon** [comment]
You need to add `/usr/bin` to the `PATH` in `/Applications/Ipe.app/Contents/Info.plist`, since the `open` command resides in `/usr/bin`.

**Comment by pierreganty** [comment]
I updated to: `<key>PATH</key>
    <string>/Library/TeX/texbin:/usr/texbin:/usr/local/texbin:/usr/local/bin:/usr/bin</string>`
as suggested but it does not solve my problem.  Onscreen Keyboard or Macvim do not launch.

**Comment by m7thon** [comment]
Ah, I think you need to move the whole `Ipe.app` somewhere else (e.g. Desktop) and then back to `/Applications` for changes in `Info.plist` to take effect, since there is some caching going on.

**Comment by otfried** [comment]
Thanks for pointing this out - I didn't realize the PATH setting in Info.plist was **overriding** any default paths (rather than adding to them).  I'll add at least /usr/bin and /bin to the list then.
