### ISSUE TITLE
Altered color after choosing a color with the color picker

### ISSUE THREAD

**Issue by marcelrad** [otfried/ipe#74]
I've noticed the following behaviour in Ipe Version 7.2.2 regarding the color picker.

1) draw a mark with in red color (#FE0000)
2) open the color dialog
3) use the color picker to select the color of the red mark

Now the color is #B20000 and not #FE0000, as expected. This probably is due to the grey overlay over the canvas. It would be nice to select the true color value in future ipe versions.  Thanks :)

**Comment by otfried** [comment]
1. Please indicate your platform: Windows, OSX, Linux?
2. Ipe doesn't use HTML-format for colors - where did you find the color #FE0000?  In fact, "red" in Ipe is (1.0, 0, 0), which translates to #FF0000.
3. Ipe does not have a grey overlay over the canvas - I have no idea what you are referring to.
4. Are you aware that on OSX the color dialog works a bit different? (#38)

I've just tried changing the color of a mark using the color dialog - it works just fine.

**Comment by marcelrad** [comment]
1) Ubuntu 14.04 with Gnome 3.8
2) The HTML-code is displayed in the "color name" field which actually is not consistent with the rgb values displayed above.
3) See Attachment
![ipe_color](https://cloud.githubusercontent.com/assets/458451/15735838/f43fa098-289b-11e6-8dff-c65ed6201a6c.png)

**Comment by otfried** [comment]
Ah, now I understand the question.

The color picker is a feature of the system color dialog.  It allows you to copy colors from _other_ applications, _exactly_ as they are shown on the screen.   It accesses the display directly and has no access to the internal values of applications, so while the modal dialog shadow is over the Ipe display, it cannot give you anything else.

This feature isn't meant to pick colors from Ipe objects.

**Comment by otfried** [comment]
I can't reproduce this - on my system (Ubuntu 14.04) the Ipe window isn't grayed out when the color dialog is shown.  

It seems support for Gnome is really poor on Ubuntu.
