### ISSUE TITLE
Ipe 7.2.2: "could not read image" Error when inserting a jpg image

### ISSUE THREAD

**Issue by mfarshi** [otfried/ipe#75]
I try to insert images using File->insert Image menu but on some figures it gives a "could not read image" error. A sample figure with this problem is attached. I change the photo to bmp format using paint and no problem with inserting bmp file.
![kowsar-small3](https://cloud.githubusercontent.com/assets/19818593/15893444/05a99ad4-2d95-11e6-827b-817e264e43a3.jpeg)
Also the same one with jpg does not work
![kowsar-small2](https://cloud.githubusercontent.com/assets/19818593/15893513/6cee6b52-2d95-11e6-80b4-ff54de7e3ab6.JPG)

**Comment by otfried** [comment]
Fixed in 7.2.3.
