### ISSUE TITLE
Zooming is too sensitive

### ISSUE THREAD

**Issue by Steven--** [otfried/ipe#76]
Hello,
I have a problem with Ipe 7.1.10 (from the Debian stretch repositories). When scrolling with an high precision touchpad the zoom changes extremely quickly making almost impossible to get the desired zoom level.

In my understanding these touchpads report scrolling events much more frequently and probably ipe is zooming in/out at each event without checking the amount of scrolled pixels.

This bug report and the corresponding patch might be somewhat related:
https://bugs.kde.org/show_bug.cgi?id=339671

Thank you and keep up the great work!

**Comment by otfried** [comment]
The setting of `prefs.wheel_zoom_factor` allows you to control this.  At least on recent Ipe versions, it should take the scrolled amount into account.

**Comment by Steven--** [comment]
Thank you and sorry for the noise.

**Comment by otfried** [comment]
Did it solve your problem?  I just checked, and on 7.1.10 the scroll action doesn't take the scroll amount reported by the scroll wheel into account.  Upgrade to 7.2.3 if you need that.

**Comment by Steven--** [comment]
It solved my problem, thanks!
I'll just wait for 7.2.3 to become available in the Debian repositories. For now 7.1.10 with the tweaked `prefs.wheel_zoom_factor` setting is working fine!
