### ISSUE TITLE
"Save As" file type filter text is cut off on OS X

### ISSUE THREAD

**Issue by nathaniel** [otfried/ipe#77]
In 7.2.3 on OS X (10.10.5), in the Save As dialog, the file type/extension filter text is partially cut off.  See attached screenshots.
![screen1](https://cloud.githubusercontent.com/assets/68211/16054424/b28b08cc-3232-11e6-8c2f-2c11d3aa1882.png)
![screen2](https://cloud.githubusercontent.com/assets/68211/16054430/b44808ea-3232-11e6-836a-727ee8740b9e.png)

**Comment by otfried** [comment]
This is very strange.  I cannot even reproduce it if I set the height of the combobox to a very small value - it automatically enlarges itself to contain the text.  Are you using larger than normal fonts or some other non-standard setting?

**Comment by nathaniel** [comment]
I am not doing anything non-standard that I am aware of.  So far I've only
tried this on one mac; I'll try it on two others when I get a chance.
Thanks for looking into it.

**Comment by nathaniel** [comment]
In the preview build you posted today at https://dl.dropboxusercontent.com/u/1840678/ipe-snapshot-0615.dmg , this issue is nearly non-existent.  (The dropped stems of the letter "p" are still cut off a little.) On the same machine, version 7.2.3 still shows the same issue.  Two new screenshots, and a comparison shot from another program that doesn't cut off the letter "p", are attached.
![ipe1](https://cloud.githubusercontent.com/assets/68211/16086341/d197ecbe-32e4-11e6-9d7b-222417dfea6b.png)
![ipe2](https://cloud.githubusercontent.com/assets/68211/16086343/d361bb92-32e4-11e6-99eb-ef7974df251d.png)
![ppt](https://cloud.githubusercontent.com/assets/68211/16086348/d7030f4e-32e4-11e6-8d1f-6f6897410b3a.png)

**Comment by otfried** [comment]
I did increase the height of the NSComboBox slightly.   What I don't understand is why I cannot reproduce any problem if I _decrease_ the height - on my system the dialog enforces that the box is large enough for the contents.

On the screen shot it seems as if the Powerpoint saving dialog uses much smaller fonts than Ipe's save dialog.  Is this indeed the case?  Considering that these are standard system dialogs, I find that surprising. (I wouldn't even know how to modify the font of the panel.)

**Comment by nathaniel** [comment]
Actually, after a closer look at my screenshots, the fonts in the Powerpoint dialog are slightly _larger_ than Ipe's.  (The image is wider, so it's scaled differently here in Github.) I do notice that the file type dropdown in Powerpoint has a different form -- rounded corners, different pulldown button -- than the one in Ipe; the Powerpoint one matches what I see in Textedit as well.

**Comment by otfried** [comment]
That's a good tip - they are actually using a different control, an NSPopupButton.

I will try that out, perhaps it can solve all our issues with NSComboBox (see #47).

**Comment by otfried** [comment]
I think the problem goes away after the switch to NSPopUpButton.

**Comment by nathaniel** [comment]
New NSPopUpButton works great, thanks for tracking down that fix.
