### ISSUE TITLE
Filename/path issue in OS X

### ISSUE THREAD

**Issue by nathaniel** [otfried/ipe#78]
File can end up with a filename that contains path-like content _just in the filename_, without the path.  For example, I just (inadvertently) saved a file called "/Users/ncunning/Desktop/Untitled.ipe" to my desktop.  When I open this file in Ipe, the title bar of the Ipe window reads:
Ipe "/Users/ncunning/Desktop/:Users:ncunning:Desktop:Untitled.ipe"

Steps to reproduce (tested in Ipe 7.2.3, on Mac OS 10.10.5):
- Launch Ipe, edit blank document.
- "Save", using default name of Untitled.ipe, to Desktop
- Quit Ipe, then double-click Untitled.ipe on the Desktop, to launch Ipe again.
- "Save As", and accept default filename (in my case, /Users/ncunning/Desktop/Untitled.ipe)
  This creates a **second** file, whose name appears in Finder as /Users/ncunning/Desktop/Untitled.ipe, and in Terminal (after "ls" command) as ":Users:ncunning:Desktop:Untitled.ipe"
  Title bar of Ipe now reads as stated above.

**Comment by otfried** [comment]
Fixed in 7.2.4.
