### ISSUE TITLE
Stylesheet update

### ISSUE THREAD

**Issue by pglira** [otfried/ipe#8]
Stylesheets are only updated if they are within the "styles" folder of IPE (IPE 7.1.8 / win). For example, the stylesheet "egu" is not updated in the following image.

![2015-09-11 14_18_55](https://cloud.githubusercontent.com/assets/14214284/9814670/21af9498-5890-11e5-8418-f58dbe8de41d.png)

**Comment by otfried** [comment]
Another simple problem:
In actions.lua, change 

```
if self.file_name then dir = string.gsub(self.file_name, "[^/]+$", "") end
```

to

```
if self.file_name then dir = string.gsub(self.file_name, "[^/\\]+$", "") end
```

The problem is the different path separator on Windows...

**Comment by pglira** [comment]
It's working now. Thanks!
