### ISSUE TITLE
prefs.editable_textfile for editing stylesheets

### ISSUE THREAD

**Issue by thobl** [otfried/ipe#80]
In tools.lua in the function externalEditor, the name of the temporary file is determined as follows (which allows to manually set the name via the preferences):

``` lua
local fname = os.tmpname()
if prefs.editable_textfile then
  fname = prefs.editable_textfile
end
```

In actions.lua in the function sheets_edit, the variable prefs.editable_textfile is not considered (it always uses os.tmpname). It would be nice to have the same behavior for both cases of using the external editor.

**Comment by otfried** [comment]
Done in 7.2.4.
