### ISSUE TITLE
Save Edit->DocumentProperties values

### ISSUE THREAD

**Issue by egorpugin** [otfried/ipe#81]
Hi!

Is it possible to create a setting of saving Edit->DocumentProperties? Or maybe the contents of that windows will be saved for the next documents?

I'm using xetex as LaTeX engine and custom preamble, so I should set this every time on each small document. And it's not very productive.

**Comment by otfried** [comment]
This is the bug reporting system for Ipe. It's not meant for asking questions, use the mailing list or Facebook for that.

You should create a style sheet with your custom preamble, then add it to the default styles in prefs.lua. xetex can also be set there. See the manual under customising Ipe.
