### ISSUE TITLE
rounding coordinates to integers due to European locale (comma decimal point)

### ISSUE THREAD

**Issue by marklundeberg** [otfried/ipe#83]
I'm running Ipe 7.1.4 on Ubuntu 14.04. I was having problems in Ipe with the following actions:
- "Edit as XML": all coordinates in a path were cast to an integer.
- Saving and loading: While the coordinates were saved properly with many significant figures (as could be seen in the text file), they were loaded as integers.

I solved it by changing my locale settings (output of `locale`) from `es_ES` to `en_US`, via the Ubuntu Settings|Language Support menu. But I thought it would be useful to fix the bug in Ipe itself. My guess is the LC_NUMERIC was making Ipe try to read numbers expecting a comma (,) for decimal point, however they were saved with period (.).

**Comment by otfried** [comment]
Please upgrade to a recent version of Ipe.
