### ISSUE TITLE
Joining more than two paths doesn't always work

### ISSUE THREAD

**Issue by AndrewMartchenko** [otfried/ipe#85]
When joining more than two paths involving curves (as in the example below), I get the error message "Unable to join paths to a single curve". However, I can usually get around this problem by successively joining adjacent paths. I have attached the ipe file for you to reproduce the error.
[join_paths.ipe.zip](https://github.com/otfried/ipe-issues/files/329261/join_paths.ipe.zip)

![join_paths](https://cloud.githubusercontent.com/assets/18596661/16292863/9ca4c0a2-3958-11e6-9973-52f825b62f60.png)

**Comment by otfried** [comment]
Fixed in 7.2.4.

**Comment by otfried** [comment]
Thanks for the example - it really helped me nail down this problem.
