### ISSUE TITLE
Export to EPS doesn't work if there are some text or mathematical formula.

### ISSUE THREAD

**Issue by jtarrasso** [otfried/ipe#86]
Hello,
I use Ipe 7.1.10 on Ubunto 16.04 if I export to EPS a pdf figure with no text, it works fine but if there is a text or formula it doesn't work. Have you any solution?
Thanks.

**Comment by otfried** [comment]
This is a bug in pdflatex - Ipe has a workaround since version 7.2.2, so please upgrade Ipe.

**Comment by jtarrasso** [comment]
Thank you very much! And for your beautiful work!
