### ISSUE TITLE
Feature request: don't snap to objects that don't appear in this view

### ISSUE THREAD

**Issue by Markvy** [otfried/ipe#88]
If a layer doesn't appear in the current view, then its objects should (probably??) not be snap targets.  It's just clutter.  (On the other hand, this seems like exactly the sort of change that would trigger https://xkcd.com/1172/)

**Comment by otfried** [comment]
I don't understand this.   There is no snapping to objects in a layer that is not in the current view.

If you see such an effect, it is a bug - please attach a file that demonstrates the problem.

**Comment by otfried** [comment]
Oops - you are right.  This is definitely a bug (and it was most certainly not there at some point).

**Comment by Markvy** [comment]
Perhaps so, but it's been there for some time.  I'm too lazy to install old
ipe versions right now, but it's been there since at least 7.1.10.

I would have reported this long ago, but I assumed it was "by design" so I
didn't bother.

**Comment by otfried** [comment]
Fixed in 7.2.5.

**Comment by Markvy** [comment]
Sweet!  No word yet on roughly when the next release is?
That is, are we talking a few days, or a few months, or...?

**Comment by otfried** [comment]
You can try a snapshot:
https://dl.dropboxusercontent.com/u/1840678/ipe-snapshot-0707-mac.dmg
https://dl.dropboxusercontent.com/u/1840678/ipe-snapshot-0707-win.zip

**Comment by Markvy** [comment]
Thanks!  I think I phrased my question poorly though.  I was asking out of
curiosity, not out of any urgency :)
