### ISSUE TITLE
Annotate PDF files gives "File not found" error

### ISSUE THREAD

**Issue by AndrewMartchenko** [otfried/ipe#90]
Hi Otfied,
When I open up the IPE that was generated by annotate.py, I get the following error
File `myfile.pdf' not found  

Any ideas?

**Comment by otfried** [comment]
You need to set TEXINPUTS, or copy myfile.pdf into the directory where Ipe runs Latex (.ipe/latexrun on Unix, see Help->Show configuration -> Latex directory).
