### ISSUE TITLE
Adding elements to invisible layers

### ISSUE THREAD

**Issue by bwinkler** [otfried/ipe#92]
It's possible (and easy) to add elements to invisible layers. That is, it's possible to have an active, invisible layer and so, when adding elements, it appears as if nothing is happening. In fact, though, these elements are being added unintentionally to the invisible layer. 

If this is the intended behavior, it would be great to have an option to either:
- Disable making invisible layers active
- Throw an error when you try to add to an invisible layer

**Comment by otfried** [comment]
Warning implemented in 7.2.15.
