### ISSUE TITLE
textsc in 7.2.5

### ISSUE THREAD

**Issue by RichardSieg** [otfried/ipe#93]
Hi! 

With using 7.2.5 I noticed a weird behavior: If I use textsc in a label environment (which I use regularly) some letters are cut on top (like the top cap of the capital S or G).

Best,

Richard

**Comment by otfried** [comment]
Are you on OSX?    Do you see the cutoff in the PDF output, but not on the Ipe screen?

**Comment by RichardSieg** [comment]
I'm working on Ubuntu 16.04 and I only see it in the PDF output. Actually, you can see how the bounding box is cutting of the letters on top. I have not seen this behavior before.

**Comment by otfried** [comment]
Fixed in 7.2.6.
