### ISSUE TITLE
Eps files created with Ipe are not recognised by Ipe

### ISSUE THREAD

**Issue by fernandosuarezguerra** [otfried/ipe#94]
Hello,
First of all, thank you for the amazing tool that Ipe is, I have been using it for about two years now and I find it extremely useful.
I have upgraded to version 7.2.5 and I have observed that if I open an *.eps file and try to save it again, Ipe tells me I can only save it as *.xml, *.ipe or *.pdf. Then, I have tried exporting it as *.eps and all seems to be fine, but when I try to open the *.eps file again, Ipe says that "The document was not created by Ipe".
I guess it is a bug, but I am not very sure.
I know I could save my file as an .ipe file, but it is quite convenient for me to work only with .eps files, since I don't need duplicates and can use the same file with Ipe and Latex.
Thanks again for your help and for developing such a useful tool.

Fernando

**Comment by otfried** [comment]
See news.txt:

```
Ipe 7.1.10 (2015-11-21)

 * "Export to EPS" replaces saving in EPS format.  Ipe can still load
   Ipe figures in EPS format, but will not save in this format
   anymore.  Use "Export to EPS" if you need EPS figures for your
   publisher.
```

**Comment by fernandosuarezguerra** [comment]
Dear otfried,
Thanks for your answer, but I can open a .eps file created with an older version of Ipe, but if I try opening a .eps file created with the new version (7.2.5) Ipe says that it was not created by Ipe", which is not correct... any clue about why this happens?
Thank you,

Fernando

**Comment by otfried** [comment]
Because "export" means something different from saving.  

Old eps files were **saved** with Ipe, they contain Ipe markup and can be read.

New eps files are **exported** from Ipe.  They contain no Ipe markup and cannot be read.

**Comment by fernandosuarezguerra** [comment]
Understood, thank you!
