### ISSUE TITLE
Implement per-monitor High-DPI support on Windows

### ISSUE THREAD

**Issue by nesteruk** [otfried/ipe#96]
I have a 4K laptop screen. The editor window and menus are ok, but all of the toolbars look terrible. Would be nice if high-DPI supporting code was added so that UI elements are scaled to OS settings. Thanks!

**Comment by otfried** [comment]
In `prefs.lua`, set

```
prefs.ui_scale = 200
prefs.toolbar_scale = 200
```

**Comment by alanrunner** [comment]
I also have a 4K monitor. I made the suggested changes to these setting in prefs.lua in version 7.2.7, and they had no effect.  The icons on the toolbar were the same size after restarting IPE and are still too small for me to see clearly.

**Comment by otfried** [comment]
How are you modifying the settings?   Editing the prefs.lua file in the Ipe distribution directly?

In 7.2.7, Ipe will actually pick up the DPI from the system if the settings are left at 100, but not on a per-monitor basis.    What is the resolution setting in your Windows control panel?

**Comment by alanrunner** [comment]
Otfried,

First of all, thank you for releasing Ipe to the general public.  I use it
quite often to create figure for my LaTeX documents.  You've done a really
nice job with Ipe and have made a very positive contribution to the
community of LaTeX users.

I'm using Windows 10 Build 17723.  I'm only using a single 4K monitor for
each computer.  On the laptop it is the home version. On the desktop it is
the enterprise version. I get exactly the same results on both computers.
Each computer is set at its native screen resolution of 3840 by 2160. Ipe
is running in an arbitrary directory where it was unzipped.  I edited the
prefs.lua file in the Ipe distribution directly.  I have not made any
"Compatibility" setting changes such as Windows 7 compatible. Here is what
I see at settings 100 and 200.

The small icon size isn't a big issue on my 27" desktop 4K monitor, but it
becomes a problem for me on my smaller laptop computer with a 4K monitor.





With the settings:
prefs.ui_scale = 100
prefs.toolbar_scale = 100
Ipe's toolbar icons are extremely small relative to the screensize, as
follows:



With the settings:
prefs.ui_scale = 200
prefs.toolbar_scale = 200
Ipe's toolbar icons are extremely small relative to the screensize, as
follows:





The size of various icons does not change when I change those settings.
It's not too bad on my 27" desktop monitor, but on the laptop the icons are
quite difficult to see.

**Comment by otfried** [comment]
I have now finally implemented per-monitor dpi support for Windows.

Here is a beta version that supports this: 

https://bintray.com/otfried/generic/download_file?file_path=ipe%2F7.2%2Fipe-7.2.15-beta1-win64.zip

It would be great if you could try if this works well on your computers.   It should show a reasonable size UI when you initially start Ipe, both on low-res and 4K monitors, and the UI should resize itself correctly when you drag Ipe from one monitor to the other.

**Comment by alanrunner** [comment]
The new beta still doesn't show in proper resolution on my 4K monitor.  The
toolbar icons are about 1/4th the correct size.

**Comment by otfried** [comment]
That is strange.  Which Windows 10 build are you running?

Here is a new beta version, which displays the resolution it detects in Help->Show Configuration:

https://bintray.com/otfried/generic/download_file?file_path=ipe%2F7.2%2Fipe-7.2.15-beta2-win64.zip

Can you check what it displays as "Monitor resolution" on your computer?

The UI should change size when you go into Windows Settings -> System -> Display and change the "Scale and layout" setting (on my laptop, it offers 100%, 125%, 150%, and 175%).
