### ISSUE TITLE
Ipe 7.2.5 can not display Chinese correctly

### ISSUE THREAD

**Issue by angeugdong** [otfried/ipe#97]
![capture](https://cloud.githubusercontent.com/assets/22285559/18621980/19839a5c-7e65-11e6-8e64-0a0dce4d15cb.PNG)

Please refer to the above picture. The pdf file is created by Ipe 7.2.5. When opened by Adobe Reader, it displays Chinese without problems. But when the same file is opened using Ipe, the characters are displayed as square blocks. There is no such problem in Ipe 7.1.\* versions.

**Comment by otfried** [comment]
Please attach or send me the PDF file.

**Comment by angeugdong** [comment]
Dear Professor Cheong, thank you for your quick reply! I really like your software. Please refer to the attached file.
[test.pdf](https://github.com/otfried/ipe-issues/files/479703/test.pdf)

**Comment by otfried** [comment]
Mysterious - the problem was that the code said "Truetype" instead of "TrueType".  Apparently you are the first one to use a TTF/TTC font since I changed the rendering code.  Thanks for reporting the problem!
