### ISSUE TITLE
Esc and Cmd+Return doesn't work while editing text labels on Mac

### ISSUE THREAD

**Issue by unruhschuh** [otfried/ipe#98]
In the older versions with Qt-Interface, if one pressed Esc while editing a text label canceled the operation. Pressing Cmd+Return was equivalent to pressing the ok button. This doesn't work in 7.2.6.

Edit: The part about Esc is not true, though it should, I think.

**Comment by otfried** [comment]
The Esc button was disabled for most dialogs in Ipe a long time ago, because people found it extremely annoying that if they mistakenly pressed Esc while writing a long piece of text, all the work was lost.

If you feel that Esc _should_ terminate the edit-text dialog, you can find the function `action_edit_text` in `tools.lua` and change the line

```
  d:set("ignore-escape", true)
```

by replacing `true` by `false`.

**Comment by otfried** [comment]
When I wrote the Cocoa interface, I noted that Ctrl+Enter or Command+Enter did not close the dialog, but I didn't think this was a problem because Fn+Enter worked for me.

In the meantime I realized that the big Mac keyboard does not have a `Fn` key, so we'll have to do something about this...

**Comment by unruhschuh** [comment]
Note that Fn+Return = Enter on the small Mac keyboard.
Return is the big key with the arrow pointing down and left. Enter is the small key at the lower right of the num pad on big keyboards.

This is a historical artifact. (Carriage) Return stems from the old typewriters, where hitting the return button caused the carriage to move to the right, so that the next line can be written.

https://en.wikipedia.org/wiki/Enter_key

**Comment by otfried** [comment]
So does it work to accept and close the edit dialogs by pressing the Enter key on the num pad?

**Comment by unruhschuh** [comment]
I don't know. I'm using a small keyboard by Lenovo on a Mac and Fn+Return doesn't work. Probably because that particular keyboard doesn't send Enter when pressing Fn+Return.

**Comment by otfried** [comment]
So on my big Mac keyboard Cmd+Keypad_Enter works to close dialogs, where Keypad_Enter is the key at the bottom right of the numeric keyboard.

**Comment by otfried** [comment]
Have you tried Fn+Cmd+Return?

**Comment by unruhschuh** [comment]
That doesn't work either. I used [1] to find the keycode of fn+Return, but apparently my keyboard doesn't send anything on fn+Return.

[1] https://itunes.apple.com/us/app/key-codes/id414568915?mt=12

**Comment by mrzv** [comment]
Fn+Return works for me, but Cmd+Return would be much more natural (it would match the interface in every other application).

**Comment by otfried** [comment]
Fixed in 7.2.8
