### ISSUE TITLE
\ipesymbol TeX command broken in 7.2

### ISSUE THREAD

**Issue by tinloaf** [otfried/ipe#99]
Hi,

I'm using ipe-7.2.6-x86_64.AppImage on a recent Ubuntu. I'm using a template that relies on \ipesymbol, and the template has broken when migrating from 7.1 to 7.2. It looks like Ipe 7.2 replaces all \ipesymbols with circles.

A minimal example can be found at http://i11www.iti.uni-karlsruhe.de/~barth/symbol.ipe : When opening this file with ipe 7.1, the label (correctly) displays a square. When opening the file with ipe 7.2, it (incorrectly) displays a circle.

Kind regards,
Lukas

**Comment by otfried** [comment]
Support for \ipesymbol had to be removed in 7.2.5 because Ipe now supports Tikz and \includegraphics.

You will have to find another solution - in the minimal example you could replace the symbol by a Latex or Tikz symbol.

What will always work is to save the symbol in a separate Ipe file and to redefine \ipesymbol to use \includegraphics to load that.

**Comment by tinloaf** [comment]
Oh okay - being able to use PGF and includegraphics should work, too. However, since \includegraphics has not made it into the documentation yet: Is there any documentation on which path will be searched for images when using \includegraphics? It seems like I cannot make it work...

**Comment by otfried** [comment]
Currently Ipe doesn't do anything special with the Latex path, so you either have to put the file into Ipe's latex directory (.ipe/latexrun on Unix, check Help -> Show configuration -> Latex directory), or set the TEXINPUTS environment variable.

In the future I'll try to add the directory that contains the current document to the Latex path automatically.

**Comment by tinloaf** [comment]
Great, that worked! Thanks for the support.
